// Smart contracts — the C call-bytes codec (shared/dnac/evm_call_wire.c) and
// the EVM envelope builder (crypto/nodus-send-wasm.c "SMART CONTRACTS")
// through the module.
//
// Always run (the committed src/nodus/send.wasm): the shipped module exports
// every smart-contract entry point send-module.js calls and none of the
// test-only ones.
//
// With NODUS_SEND_PARITY_OUT (`scripts/build-nodus-send-wasm.sh parity`;
// otherwise these SKIP — a skip is not a pass), on the TEST wasm:
//   - every EVM op's call bytes equal a layout assembled HERE from design
//     docs/plans/2026-10-04-nodus-evm-chain-integration-design.md rev 3 §2 (the
//     same shapes as the node test's own encoder, nodus/tests/test_v2_evm.c
//     enc_call / enc_create / enc_deposit / enc_withdraw / enc_redeem), and
//     decode -> re-encode returns them unchanged;
//   - the decoder refuses what the node's rtevm_decode refuses: a trailing
//     byte, a short call, a wrong version, an access-list key count past the
//     data, a CREATE initcode over 49 152 bytes;
//   - the EVMFUND call (the node's layout since Nodus EVM Faz 4 — the node decodes
//     it with the same codec, evm_call_wire.h) round-trips and its refusals
//     (role, input order, change count 0..16, owner case, zero amount,
//     non-native token);
//   - an offline DEPOSIT build: two legs CORE op 9 (role DEPOSIT) then EVM op
//     3, the deposit call bytes, Σinputs = amount + fee + change, fee =
//     max(floor, units × gas price); built twice from the same fixed
//     randomness it is the same envelope; without a meter weight for CORE op
//     9 (generation 2's pinned policy has none) the build refuses; a
//     declared ceiling below the minimum refuses;
//   - red-team 1 F11: the shared CREATE-address rule
//     (nodus/src/client/nodus_v2_evm.c nodus_v2_evm_create_address) equals
//     the engine's INDEPENDENT oracle vectors (shared/evm/tests/
//     addr32_vectors.h, generated by addr32_oracle.py — read from that file
//     here, nonces 0, 0x7f, 0x80, 0x100), and an offline CREATE build's
//     nsw_evm_built_created is that rule on the signed sender and nonce
//     (also re-derived here with @noble/hashes keccak_256 over the RLP);
//     every other op gives "";
//   - red-team 1 F9: an offline CALL build refuses an estimate whose `ue` is
//     below the reference shape's units or whose read units exceed
//     EVM_READS_BASE (16 334) × w_read (1, nodus_ruleset_pins.h
//     NODUS_PIN_G2_SYS_METER_W_READ), and takes one at exactly the bound;
//   - red-team 1 F4: the §18 query argument text's `U` tag (`c=U:h,x,li`,
//     the evm_logs cursor) encodes to a CBOR array of 1..3 uints (bytes
//     assembled HERE from RFC 8949 major types), and an empty element,
//     more than 3 elements, a leading zero, 2^64 refuse.
// Inputs are SYNTHETIC (fixed seed, made-up coins, chain id and EVM ruleset
// hash, op weight 9 = 1 on top of generation 2): they prove the module's
// codec and envelope shape (the shared builder nodus_v2_evm.c since Nodus EVM
// Faz 4) — NOT that a node accepts the envelope (the node decodes these
// bytes with the same codec, but no node runs here).
import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';
import { keccak_256 } from '@noble/hashes/sha3';

const wasmBytes = readFileSync(new URL('../src/nodus/send.wasm', import.meta.url));
const EVM_ENTRY_POINTS = [
  'nsw_evm_net_set', 'nsw_evm_available', 'nsw_evm_data_alloc', 'nsw_evm_access_reset', 'nsw_evm_access_add', 'nsw_evm_set_decl',
  'nsw_evm_call', 'nsw_evm_create', 'nsw_evm_deposit', 'nsw_evm_withdraw', 'nsw_evm_redeem',
  'nsw_evm_built_op', 'nsw_evm_built_to', 'nsw_evm_built_value', 'nsw_evm_built_gas', 'nsw_evm_built_nonce', 'nsw_evm_built_units',
  'nsw_evm_built_amount', 'nsw_evm_built_dest', 'nsw_evm_built_ticket', 'nsw_evm_built_data_len',
  // Nodus EVM Faz 4: the evm_estimate hand-over, the EVM generation, the §18 reads
  'nsw_evm_set_estimate', 'nsw_evm_generation', 'nsw_evm_query_buf', 'nsw_evm_query', 'nsw_evm_query_json',
  // red-team 1 F11: the CREATE address of the signed deployment
  'nsw_evm_built_created'
];

test('the shipped send.wasm has every smart-contract entry point and no test-only one', () => {
  const exports = new Set(WebAssembly.Module.exports(new WebAssembly.Module(wasmBytes)).map(({ name }) => name));
  for (const name of EVM_ENTRY_POINTS) assert.ok(exports.has(name), `missing export ${name}`);
  assert.ok(![...exports].some(name => name.startsWith('nsw_test_evm')), 'a test-only EVM entry point is in the shipped module');
});

const PARITY_OUT = process.env.NODUS_SEND_PARITY_OUT;
const skip = !PARITY_OUT ? 'set NODUS_SEND_PARITY_OUT (build-nodus-send-wasm.sh parity)' : false;

async function testModule() {
  const path = join(PARITY_OUT, 'send-test-node.mjs');
  assert.ok(existsSync(path), `${path} is missing — run build-nodus-send-wasm.sh parity`);
  const { default: create } = await import(pathToFileURL(path).href);
  const M = await create();
  const num = (name, types = [], args = []) => M.ccall(name, 'number', types, args);
  const str = (name, types = [], args = []) => M.ccall(name, 'string', types, args);
  return { M, num, str };
}
const be = (v, n) => BigInt(v).toString(16).padStart(2 * n, '0');
function setData({ M, num }, hex) {
  if (!hex) { num('nsw_evm_data_alloc', ['number'], [0]); return; }
  const at = num('nsw_evm_data_alloc', ['number'], [hex.length / 2]);
  assert.ok(at);
  M.HEAPU8.set(Buffer.from(hex, 'hex'), at);
}
// encode through the module: op, to, value, gas, nonce, amount, dest, ticket
const enc = (mod, op, f) => mod.str('nsw_test_evm_call_hex', ['number', 'string', 'string', 'string', 'string', 'string', 'string', 'string'],
  [op, f.to ?? '', f.value ?? '', f.gas ?? '0', f.nonce ?? '0', f.amount ?? '0', f.dest ?? '', f.ticket ?? '']);
const roundtrip = (mod, op, hex) => mod.str('nsw_test_evm_call_roundtrip', ['number', 'string'], [op, hex]);

const TO = 'ab'.repeat(32), VALUE = '00'.repeat(24) + be(10n ** 18n, 8), ACC_ADDR = 'cd'.repeat(32), ACC_KEY = '01'.repeat(32);
const DEST = 'ee'.repeat(64), TICKET = '77'.repeat(64), DATA = 'a9059cbb' + '00'.repeat(64), INIT = '6080604052' + 'fe'.repeat(11);

test('EVM call bytes: each op equals the §2 layout and round-trips', { skip }, async () => {
  const mod = await testModule();
  // CALL with one access-list entry holding one key
  mod.num('nsw_evm_access_reset');
  assert.equal(mod.num('nsw_evm_access_add', ['string', 'string'], [ACC_ADDR, ACC_KEY]), 0, mod.str('nsw_error'));
  setData(mod, DATA);
  const call = enc(mod, 1, { to: TO, value: VALUE, gas: '100000', nonce: '7' });
  const callRef = '01' + TO + VALUE + be(100000, 8) + be(7, 8) + be(1, 2) + ACC_ADDR + be(1, 2) + ACC_KEY + be(DATA.length / 2, 4) + DATA;
  assert.equal(call, callRef);
  assert.equal(roundtrip(mod, 1, call), call);
  // CREATE, no access list
  mod.num('nsw_evm_access_reset');
  setData(mod, INIT);
  const create = enc(mod, 2, { value: '00'.repeat(32), gas: '3000000', nonce: '8' });
  assert.equal(create, '01' + '00'.repeat(32) + be(3000000, 8) + be(8, 8) + be(0, 2) + be(INIT.length / 2, 4) + INIT);
  assert.equal(roundtrip(mod, 2, create), create);
  // the bridge ops: exact lengths 17 / 81 / 137
  setData(mod, '');
  const dep = enc(mod, 3, { amount: '250000000', nonce: '9' });
  assert.equal(dep, '01' + be(250000000, 8) + be(9, 8));
  const wd = enc(mod, 4, { amount: '1', nonce: '10', dest: DEST });
  assert.equal(wd, '01' + be(1, 8) + be(10, 8) + DEST);
  const rd = enc(mod, 5, { amount: '42', dest: DEST, ticket: TICKET });
  assert.equal(rd, '01' + TICKET + be(42, 8) + DEST);
  assert.deepEqual([dep, wd, rd].map(h => h.length / 2), [17, 81, 137]);
  for (const [op, h] of [[3, dep], [4, wd], [5, rd]]) assert.equal(roundtrip(mod, op, h), h);
  assert.equal(enc(mod, 6, {}), '', 'unknown op');
});

test('EVM call bytes: the decoder refuses what the node refuses', { skip }, async () => {
  const mod = await testModule();
  setData(mod, '');
  mod.num('nsw_evm_access_reset');
  const dep = enc(mod, 3, { amount: '5', nonce: '1' });
  assert.equal(roundtrip(mod, 3, dep + '00'), '', 'trailing byte');
  assert.equal(roundtrip(mod, 3, dep.slice(0, -2)), '', 'short');
  assert.equal(roundtrip(mod, 3, '02' + dep.slice(2)), '', 'wrong version');
  assert.equal(roundtrip(mod, 4, dep), '', 'a deposit is not a withdraw');
  setData(mod, DATA);
  const call = enc(mod, 1, { to: TO, value: VALUE, gas: '1', nonce: '1' });
  assert.equal(roundtrip(mod, 1, call + 'ff'), '', 'trailing byte after data');
  // an access list that claims one entry with 2 keys but carries 1
  const head = '01' + TO + VALUE + be(1, 8) + be(1, 8);
  const lying = head + be(1, 2) + ACC_ADDR + be(2, 2) + ACC_KEY + be(0, 4);
  assert.equal(roundtrip(mod, 1, lying), '', 'key count past the data');
  // CREATE initcode: 49 152 bytes pass, 49 153 refuse (EIP-3860)
  const createHead = '01' + '00'.repeat(32) + be(1, 8) + be(1, 8) + be(0, 2);
  const ok = createHead + be(49152, 4) + '00'.repeat(49152);
  assert.equal(roundtrip(mod, 2, ok), ok);
  assert.equal(roundtrip(mod, 2, createHead + be(49153, 4) + '00'.repeat(49153)), '', 'initcode over the cap');
});

const OWNER = 'ab'.repeat(64), SEED32 = '5c'.repeat(32);
const out = (owner, amount, token = '00'.repeat(64)) => Buffer.from(owner, 'ascii').toString('hex') + be(amount, 8) + token + SEED32;
const fund = (role, nuls, outs) => '01' + be(role, 1) + be(nuls.length, 1) + nuls.join('') + be(outs.length, 1) + outs.join('');

test('EVMFUND call (the node\'s layout): round trip and refusals', { skip }, async () => {
  const mod = await testModule();
  const rt = h => mod.str('nsw_test_evmfund_roundtrip', ['string'], [h]);
  const n1 = '11'.repeat(64), n2 = '22'.repeat(64);
  const good = fund(2, [n1, n2], [out(OWNER, 5)]);
  assert.equal(rt(good), good);
  assert.equal(rt(fund(1, [n1], [])), fund(1, [n1], []));
  assert.equal(rt(fund(3, [n1], [])), fund(3, [n1], []));
  assert.equal(rt(fund(0, [n1], [])), '', 'role 0');
  assert.equal(rt(fund(4, [n1], [])), '', 'role 4');
  assert.equal(rt(fund(1, [n2, n1], [])), '', 'inputs not ascending');
  assert.equal(rt(fund(1, [n1, n1], [])), '', 'repeated input');
  assert.equal(rt(fund(1, [], [])), '', 'no input');
  // the node's bound (rtn_xfer_section_parse, RTN_SPEND_MAX_OUT): 0..16
  // change outputs — the former 0..1 was the codec's provisional choice
  const two = fund(1, [n1], [out(OWNER, 1), out(OWNER, 2)]);
  assert.equal(rt(two), two, 'two change outputs');
  const outs16 = Array.from({ length: 16 }, (_, i) => out(OWNER, i + 1));
  assert.equal(rt(fund(1, [n1], outs16)), fund(1, [n1], outs16), 'sixteen change outputs');
  assert.equal(rt(fund(1, [n1], [...outs16, out(OWNER, 17)])), '', 'seventeen change outputs');
  assert.equal(rt(fund(1, [n1], [out(OWNER.toUpperCase(), 1)])), '', 'upper-case owner');
  assert.equal(rt(fund(1, [n1], [out(OWNER, 0)])), '', 'zero amount');
  assert.equal(rt(fund(1, [n1], [out(OWNER, 1, '01'.repeat(64))])), '', 'non-native change');
  assert.equal(rt(good + '00'), '', 'trailing byte');
});

// ── the offline DEPOSIT build ────────────────────────────────────────────
const fill = (length, start) => Uint8Array.from({ length }, (_, i) => (start + i * 7) & 0xff);
const BUILD = {
  seed: fill(32, 3), chain: '33'.repeat(32), tip: '1000', gasPrice: '121', evmVer: '1', evmHash: '5a'.repeat(64),
  amount: '250000000', nonce: '0', expiry: '1090',
  coins: [['a1'.repeat(64), '100000000'], ['b2'.repeat(64), '300000000'], ['c3'.repeat(64), '50000000']],
  signRandom: fill(64, 70)
};
async function offlineDeposit({ weight = true, units = '0' } = {}) {
  const mod = await testModule(), { M, num, str } = mod;
  const [, , coreVer, coreHash] = str('nsw_test_pins_tuple', ['number'], [2]).split(':');
  if (weight) assert.equal(num('nsw_test_evm_op_weight', ['number', 'string'], [9, '1']), 0);
  M.HEAPU8.set(BUILD.seed, num('nsw_seed_buf'));
  M.HEAPU8.set(BUILD.signRandom, num('nsw_test_random_buf'));
  assert.equal(num('nsw_test_random_load', ['number'], [BUILD.signRandom.length]), 0);
  num('nsw_req_reset');
  for (const [n, a] of BUILD.coins) assert.equal(num('nsw_req_add_coin', ['string', 'string'], [n, a]), 0);
  num('nsw_evm_access_reset'); setData(mod, '');
  const rc = num('nsw_test_evm_build', Array(18).fill('string').map((t, i) => (i < 2 ? 'number' : t)),
    [2, 3, BUILD.chain, BUILD.tip, BUILD.gasPrice, coreVer, coreHash, BUILD.evmVer, BUILD.evmHash, '', '', '0', BUILD.nonce, BUILD.amount, '', '', units, BUILD.expiry]);
  if (rc !== 0) return { rc, error: str('nsw_error') };
  const at = num('nsw_built_env'), len = num('nsw_built_env_len');
  return {
    rc, env: Buffer.from(M.HEAPU8.subarray(at, at + len)), coreVer: Number(coreVer), fee: BigInt(str('nsw_built_fee')),
    change: BigInt(str('nsw_built_change')), units: BigInt(str('nsw_evm_built_units')), op: num('nsw_evm_built_op'),
    amount: str('nsw_evm_built_amount'), inputs: Array.from({ length: num('nsw_built_n_in') }, (_, i) => str('nsw_built_in', ['number'], [i])),
    intent: str('nsw_built_intent')
  };
}
// shared/dnac/env_wire.h "Canonical wire layout"
function parseEnvelope(b) {
  assert.equal(b.subarray(0, 16).toString('latin1'), 'NDS.ENVWIRE.v1\0\0');
  const n = b.readUInt16BE(41), legs = [];
  let off = 43 + 30 * n;
  for (let i = 0; i < n; i++) {
    const h = 43 + 30 * i;
    legs.push({ domain: b.readUInt32BE(h), op: b.readUInt32BE(h + 4), ver: b.readUInt32BE(h + 8), access: b[h + 12], kind: b[h + 13], callLen: b.readUInt32BE(h + 14), authLen: b.readUInt32BE(h + 18), effects: b.readUInt32BE(h + 22), effectBytes: b.readUInt32BE(h + 26) });
  }
  for (const leg of legs) { leg.call = b.subarray(off, off + leg.callLen).toString('hex'); off += leg.callLen; }
  return { expiry: b.readBigUInt64BE(17), fee: b.readBigUInt64BE(25), units: b.readBigUInt64BE(33), legs };
}

test('offline DEPOSIT build: [CORE op 9, role DEPOSIT] + [EVM op 3], amounts add up, same bytes twice', { skip }, async () => {
  const a = await offlineDeposit();
  assert.equal(a.rc, 0, a.error);
  const e = parseEnvelope(a.env);
  assert.equal(e.legs.length, 2);
  assert.deepEqual(e.legs.map(l => [l.domain, l.op, l.access, l.kind]), [[1, 9, 2, 1], [2, 3, 2, 1]]);
  assert.equal(e.legs[0].ver, a.coreVer);
  assert.equal(e.legs[1].ver, 1);
  assert.equal(e.legs[1].call, '01' + be(BUILD.amount, 8) + be(BUILD.nonce, 8));
  assert.equal(a.op, 3); assert.equal(a.amount, BUILD.amount);
  assert.equal(e.expiry, 1090n); assert.equal(e.fee, a.fee); assert.equal(e.units, a.units);
  assert.ok(a.units > 0n);
  // fee = max(floor, units × gas price); the floor is below this product here
  assert.equal(a.fee, a.units * 121n);
  // the funding call: role DEPOSIT, the inputs ascending, one change to the sender
  const call = Buffer.from(e.legs[0].call, 'hex');
  assert.equal(call[0], 1); assert.equal(call[1], 2);
  const nIn = call[2];
  const nuls = Array.from({ length: nIn }, (_, i) => call.subarray(3 + 64 * i, 3 + 64 * (i + 1)).toString('hex'));
  assert.deepEqual(nuls, [...nuls].sort());
  assert.deepEqual(nuls, a.inputs);
  const amounts = new Map(BUILD.coins);
  const inSum = nuls.reduce((s, n) => s + BigInt(amounts.get(n)), 0n);
  assert.equal(inSum, BigInt(BUILD.amount) + a.fee + a.change);
  // same inputs, same fixed randomness: the same envelope byte for byte
  const b = await offlineDeposit();
  assert.equal(b.env.toString('hex'), a.env.toString('hex'));
  assert.equal(b.intent, a.intent);
});

test('offline build refusals: no weight for CORE op 9, a ceiling below the minimum', { skip }, async () => {
  const noWeight = await offlineDeposit({ weight: false });
  assert.notEqual(noWeight.rc, 0);
  assert.match(noWeight.error, /not available under the network's current transaction rules/);
  const low = await offlineDeposit({ units: '1' });
  assert.notEqual(low.rc, 0);
  assert.match(low.error, /below this transaction's minimum/);
});

// ── red-team 1: F11 (CREATE address), F9 (estimate bounds) ───────────────

// The engine's oracle vectors, read from the generated header itself (no
// transcription): `static const uint8_t NAME[32] = { 0x.., ... };` and
// `#define NAME 0x..u`.
let oracleText;
const oracle = () => (oracleText ??= readFileSync(new URL('../../shared/evm/tests/addr32_vectors.h', import.meta.url), 'utf8'));
function oracleBytes(name) {
  const m = new RegExp(`static const uint8_t ${name}\\[32\\] = \\{([^}]*)\\}`).exec(oracle());
  assert.ok(m, `${name} is in addr32_vectors.h`);
  return m[1].match(/0x[0-9a-f]{2}/g).map(b => b.slice(2)).join('');
}
function oracleNonce(name) {
  const m = new RegExp(`#define ${name} (0x[0-9a-f]+)u`).exec(oracle());
  assert.ok(m, `${name} is in addr32_vectors.h`);
  return BigInt(m[1]);
}

test('F11: the shared CREATE-address rule equals the engine oracle vectors', { skip }, async () => {
  const { str } = await testModule();
  const at = (sender, nonce) => str('nsw_test_evm_create_address', ['string', 'string'], [sender, nonce.toString()]);
  const factoryNonce = oracleNonce('ADDR32_NONCE_FACTORY');
  assert.equal(factoryNonce, 0x7fn);
  const cases = [
    [oracleBytes('ADDR32_FACTORY'), factoryNonce, oracleBytes('ADDR32_EXP_CREATE_FACTORY_N7F')],
    [oracleBytes('ADDR32_FACTORY'), factoryNonce + 1n, oracleBytes('ADDR32_EXP_CREATE_FACTORY_N80')],
    [oracleBytes('ADDR32_CREATOR0'), oracleNonce('ADDR32_NONCE_CREATOR0'), oracleBytes('ADDR32_EXP_TXCREATE_CREATOR0')],
    [oracleBytes('ADDR32_CREATOR1'), oracleNonce('ADDR32_NONCE_CREATOR1'), oracleBytes('ADDR32_EXP_TXCREATE_CREATOR1')]
  ];
  for (const [sender, nonce, expected] of cases) assert.equal(at(sender, nonce), expected, `sender ${sender.slice(0, 8)}… nonce ${nonce}`);
  assert.equal(at('ab'.repeat(31), 0n), '', 'a 31-byte sender is refused');
});

// One offline EVM build on a fresh TEST module (generation 2 + op 9 weight
// 1, the fixed seed / randomness / coins of BUILD).
async function offlineEvm({ op, to = '', value = '', gas = '0', nonce = '0', amount = '0', data = '', estimate = ['0', '0'] }) {
  const mod = await testModule(), { M, num, str } = mod;
  const [, , coreVer, coreHash] = str('nsw_test_pins_tuple', ['number'], [2]).split(':');
  assert.equal(num('nsw_test_evm_op_weight', ['number', 'string'], [9, '1']), 0);
  M.HEAPU8.set(BUILD.seed, num('nsw_seed_buf'));
  M.HEAPU8.set(BUILD.signRandom, num('nsw_test_random_buf'));
  assert.equal(num('nsw_test_random_load', ['number'], [BUILD.signRandom.length]), 0);
  num('nsw_req_reset');
  for (const [n, a] of BUILD.coins) assert.equal(num('nsw_req_add_coin', ['string', 'string'], [n, a]), 0);
  num('nsw_evm_access_reset'); setData(mod, data);
  assert.equal(num('nsw_evm_set_estimate', ['string', 'string'], estimate), 0);
  const rc = num('nsw_test_evm_build', Array(18).fill('string').map((t, i) => (i < 2 ? 'number' : t)),
    [2, op, BUILD.chain, BUILD.tip, BUILD.gasPrice, coreVer, coreHash, BUILD.evmVer, BUILD.evmHash, to, value, gas, nonce, amount, '', '', '0', BUILD.expiry]);
  if (rc !== 0) return { rc, error: str('nsw_error') };
  return { rc, units: BigInt(str('nsw_evm_built_units')), created: str('nsw_evm_built_created'), recipient: str('nsw_built_recipient'), nIn: num('nsw_built_n_in') };
}

test('F11: an offline CREATE build carries the address of its signed sender and nonce; other ops none', { skip }, async () => {
  // the sender: SHA3-512(pk)[0..32] — a DEPOSIT's recipient is this
  // wallet's own fingerprint, SHA3-512(pk), from the same seed
  const deposit = await offlineEvm({ op: 3, nonce: '5', amount: BUILD.amount });
  assert.equal(deposit.rc, 0, deposit.error);
  assert.equal(deposit.created, '', 'a DEPOSIT deploys nothing');
  const sender = deposit.recipient.slice(0, 64);
  const create = await offlineEvm({ op: 2, value: '00'.repeat(32), gas: '100000', nonce: '5', data: '602a60005360016000f3' });
  assert.equal(create.rc, 0, create.error);
  // independently: keccak256(rlp([sender_32, 5])) = keccak(0xe2 ‖ 0xa0 ‖ sender ‖ 0x05)
  const expected = Buffer.from(keccak_256(Uint8Array.from(Buffer.from(`e2a0${sender}05`, 'hex')))).toString('hex');
  assert.equal(create.created, expected);
  const { str } = await testModule();
  assert.equal(str('nsw_test_evm_create_address', ['string', 'string'], [sender, '5']), expected);
  const call = await offlineEvm({ op: 1, to: TO, value: '00'.repeat(32), gas: '50000', nonce: '5' });
  assert.equal(call.rc, 0, call.error);
  assert.equal(call.created, '', 'a CALL deploys nothing');
});

test('F9: an offline CALL refuses a malformed estimate and takes one at the read bound', { skip }, async () => {
  const READS_BASE = 16334n;                // (30 000 000 + 2 099) / 2 100 + 2 048
  const callWith = ue => offlineEvm({ op: 1, to: TO, value: '00'.repeat(32), gas: '50000', estimate: [ue.toString(), '50000'] });
  // no estimate: the minimum of this envelope's shape — one input, one
  // change, the default declaration, no access list: the REFERENCE shape
  const ref = await offlineEvm({ op: 1, to: TO, value: '00'.repeat(32), gas: '50000' });
  assert.equal(ref.rc, 0, ref.error);
  assert.equal(ref.nIn, 1, 'one funding input: the reference shape');
  const R = ref.units;
  const atRef = await callWith(R);
  assert.equal(atRef.rc, 0, atRef.error);
  assert.equal(atRef.units, R);
  const atBound = await callWith(R + READS_BASE);
  assert.equal(atBound.rc, 0, atBound.error);
  assert.equal(atBound.units, R + READS_BASE);
  const over = await callWith(R + READS_BASE + 1n);
  assert.notEqual(over.rc, 0);
  assert.match(over.error, /more reads than a transaction may make/);
  const below = await callWith(R - 1n);
  assert.notEqual(below.rc, 0);
  assert.match(below.error, /below the smallest one possible/);
});

// red-team 1 F4: the §18 query argument text's array tag `U` (an evm_logs
// cursor "c" = [h, x, li]) encodes to a CBOR array of uints, and the parser
// refuses text the u64 rules refuse. nsw_test_evm_args_hex = the entry
// count ":" the CBOR map entries in hex ("" = refused).
test('§18 query arguments: key=U:a,b,c is a CBOR array of 1..3 u64; bad text refused', { skip }, async () => {
  const { M, num, str } = await testModule();
  const args = text => {
    const bytes = new TextEncoder().encode(text);
    const at = num('nsw_evm_query_buf', ['number'], [bytes.length]);
    assert.ok(at);
    M.HEAPU8.set(bytes, at);
    return str('nsw_test_evm_args_hex', ['number'], [bytes.length]);
  };
  // "c" = 61 63; array(3) = 83; uints 1 2 3
  assert.equal(args('c=U:1,2,3'), '1:6163' + '83' + '010203');
  assert.equal(args('c=U:0'), '1:6163' + '81' + '00');
  assert.equal(args('c=U:18446744073709551615'), '1:6163' + '81' + '1bffffffffffffffff');
  // with a u entry before it: "fh" = 62 66 68; 2^32 = 1b 0000000100000000
  assert.equal(args('fh=u:1;c=U:0,4294967296,7'), '2:626668' + '01' + '6163' + '83' + '00' + '1b0000000100000000' + '07');
  for (const bad of ['c=U:', 'c=U:,1', 'c=U:1,', 'c=U:1,,2', 'c=U:1,2,3,4', 'c=U:18446744073709551616', 'c=U:01', 'c=U:1 ,2',
    'c=U:-1', 'c=U:1,2,99999999999999999999999', 'c=V:1']) {
    assert.equal(args(bad), '', bad);
  }
});
