/**
 * Nodus — Channel Crypto Implementation
 *
 * AES-256-GCM with counter-based nonces for frame-level encryption.
 * Key derived from Kyber1024 shared secret via HKDF-SHA3-256.
 *
 * Uses EVP API directly (not qgp_aes wrapper) because:
 * - Counter-based nonce (wrapper generates random nonce)
 * - Empty payload support (wrapper rejects len=0)
 *
 * @file nodus_channel_crypto.c
 */

#include "crypto/nodus_channel_crypto.h"
#include "crypto/hash/hkdf_sha3.h"
#include "crypto/utils/qgp_log.h"
#include <openssl/evp.h>
#include <string.h>

#include "crypto/utils/qgp_safe_string.h"   /* Phase 03: unsafe-string poison guard */

#define LOG_TAG "CH_CRYPTO"

extern void qgp_secure_memzero(void *ptr, size_t len);

static const char *CHANNEL_HKDF_INFO = "nodus-channel-v1";

int nodus_channel_crypto_init(nodus_channel_crypto_t *cc,
                               const uint8_t shared_secret[32],
                               const uint8_t nonce_c[32],
                               const uint8_t nonce_s[32],
                               nodus_channel_role_t role)
{
    if (!cc || !shared_secret || !nonce_c || !nonce_s)
        return -1;

    /* C1: we must never emit the legacy all-zero fixed field — that is what a
     * pre-fix peer uses, and picking it would collide with them. */
    if (role != NODUS_CHANNEL_ROLE_INITIATOR &&
        role != NODUS_CHANNEL_ROLE_RESPONDER) {
        QGP_LOG_ERROR(LOG_TAG, "init: invalid role %d", (int)role);
        return -1;
    }

    /* NOTE: the C1 re-init guard deliberately lives at the CALLSITES, not here.
     * This function cannot distinguish a live channel from uninitialised memory
     * (callers legitimately pass a fresh stack/heap struct whose bytes are
     * garbage), and its long-standing contract is to zero the state first.
     * Callers that hold a LONG-LIVED, known-zeroed instance (circuit handles,
     * conn structs) must check `established` themselves before re-keying —
     * re-keying in place resets tx_counter to 0 under a possibly-repeated key,
     * which is an immediate (key, nonce) reuse. See nodus_circuit_attach_keyed
     * and the key_init handlers. */
    memset(cc, 0, sizeof(*cc));

    /* salt = nonce_c || nonce_s (64 bytes) */
    uint8_t salt[64];
    memcpy(salt, nonce_c, 32);
    memcpy(salt + 32, nonce_s, 32);

    int rc = hkdf_sha3_256(salt, sizeof(salt),
                           shared_secret, 32,
                           (const uint8_t *)CHANNEL_HKDF_INFO,
                           strlen(CHANNEL_HKDF_INFO),
                           cc->key, NODUS_CHANNEL_KEY_LEN);

    qgp_secure_memzero(salt, sizeof(salt));

    if (rc != 0) {
        QGP_LOG_ERROR(LOG_TAG, "HKDF key derivation failed");
        return -1;
    }

    cc->tx_counter = 0;
    memset(cc->rx_counter, 0, sizeof(cc->rx_counter));
    cc->my_role = (uint8_t)role;
    cc->established = true;

    QGP_LOG_INFO(LOG_TAG, "Channel crypto established (role=%s)",
                 role == NODUS_CHANNEL_ROLE_INITIATOR ? "initiator" : "responder");
    return 0;
}

/**
 * Build 12-byte AES-GCM nonce.
 * Format: [8 bytes counter LE][1 byte role][3 bytes zero]
 *
 * NIST SP 800-38D §8.2.1 deterministic construction: bytes 0..7 are the
 * invocation field (a monotonic counter — "the invocation field typically is
 * either 1) an integer counter..."), byte 8 is the fixed field identifying the
 * context/direction. Two roles = two distinct fixed fields, so the two
 * directions can never share an IV even though they share one key.
 *
 * Layout note: this INVERTS §8.2.1's non-binding interoperability suggestion
 * ("this Recommendation suggests, but does not require, that the leading 32 bits
 * of the IV hold the fixed field"). The `shall` there binds only that the field
 * positions stay fixed for the life of the key, which holds. The counter is kept
 * in the leading bytes because the wire nonce is parsed that way by every
 * deployed peer — moving it would break them. Do NOT "correct" this to the
 * suggested layout.
 *
 * A 64-bit invocation field allows 2^64 frames per (role, key); §8.3's 2^32 cap
 * does not bind here ("unless an implementation only uses 96-bit IVs that are
 * generated by the deterministic construction" — ours are exactly that).
 */
static void counter_to_nonce(uint64_t counter, uint8_t role, uint8_t nonce[12])
{
    memset(nonce, 0, 12);
    for (int i = 0; i < 8; i++)
        nonce[i] = (uint8_t)(counter >> (i * 8));
    nonce[8] = role;
}

int nodus_channel_encrypt(nodus_channel_crypto_t *cc,
                           const uint8_t *plaintext, size_t plaintext_len,
                           uint8_t *out, size_t out_cap,
                           size_t *out_len)
{
    if (!cc || !cc->established || !out || !out_len)
        return -1;
    if (!plaintext && plaintext_len > 0)
        return -1;

    size_t needed = plaintext_len + NODUS_CHANNEL_OVERHEAD;
    if (out_cap < needed)
        return -1;

    /* Build nonce from counter + OUR role (C1: separates the two directions) */
    uint8_t nonce[NODUS_CHANNEL_NONCE_LEN];
    counter_to_nonce(cc->tx_counter, cc->my_role, nonce);

    /* Output layout: [nonce(12)][ciphertext][tag(16)] */
    memcpy(out, nonce, NODUS_CHANNEL_NONCE_LEN);

    uint8_t *ct_out = out + NODUS_CHANNEL_NONCE_LEN;
    uint8_t *tag_out = out + NODUS_CHANNEL_NONCE_LEN + plaintext_len;

    EVP_CIPHER_CTX *ctx = EVP_CIPHER_CTX_new();
    if (!ctx) return -1;

    int ret = -1;
    int len = 0;

    if (EVP_EncryptInit_ex(ctx, EVP_aes_256_gcm(), NULL, cc->key, nonce) != 1)
        goto cleanup;

    if (plaintext_len > 0) {
        if (EVP_EncryptUpdate(ctx, ct_out, &len, plaintext, (int)plaintext_len) != 1)
            goto cleanup;
    }

    if (EVP_EncryptFinal_ex(ctx, ct_out + len, &len) != 1)
        goto cleanup;

    if (EVP_CIPHER_CTX_ctrl(ctx, EVP_CTRL_GCM_GET_TAG, NODUS_CHANNEL_TAG_LEN, tag_out) != 1)
        goto cleanup;

    cc->tx_counter++;
    *out_len = needed;
    ret = 0;

cleanup:
    EVP_CIPHER_CTX_free(ctx);
    if (ret != 0)
        QGP_LOG_ERROR(LOG_TAG, "AES-GCM encrypt failed (counter=%llu)",
                      (unsigned long long)cc->tx_counter);
    return ret;
}

int nodus_channel_decrypt(nodus_channel_crypto_t *cc,
                           const uint8_t *in, size_t in_len,
                           uint8_t *out, size_t out_cap,
                           size_t *out_len)
{
    if (!cc || !cc->established || !in || !out || !out_len)
        return -1;

    if (in_len < NODUS_CHANNEL_OVERHEAD)
        return -1;

    size_t ct_len = in_len - NODUS_CHANNEL_OVERHEAD;
    if (ct_len > 0 && out_cap < ct_len)
        return -1;

    /* Extract nonce, ciphertext, tag */
    const uint8_t *nonce = in;
    const uint8_t *ct = in + NODUS_CHANNEL_NONCE_LEN;
    const uint8_t *tag = in + NODUS_CHANNEL_NONCE_LEN + ct_len;

    /* Extract counter + role from nonce for the replay / reflection checks.
     * Both are read from the PLAINTEXT wire nonce, before any GCM work, so a
     * reflected or malformed frame costs no decrypt CPU. */
    uint64_t msg_counter = 0;
    for (int i = 7; i >= 0; i--)
        msg_counter = (msg_counter << 8) | nonce[i];
    uint8_t msg_role = nonce[8];

    /* C1 reflection guard. Both directions share one key, and the receiver must
     * accept whatever role the wire carries (a legacy peer sends 0x00, an
     * upgraded peer sends the opposite role) — that is what keeps the migration
     * coordination-free. The one thing we can always reject is our OWN role: a
     * node never legitimately receives a frame it could have sent. Without this,
     * an on-path attacker could reflect our own ciphertext back at us and it
     * would authenticate (same key) and dispatch as peer-origin, and its counter
     * would advance our replay window against the real peer.
     *
     * Residual (documented): legacy<->legacy (both 0x00) stays unguarded until
     * both ends upgrade; an upgraded node is guarded even when talking to a
     * legacy peer. */
    if (msg_role == cc->my_role) {
        QGP_LOG_ERROR(LOG_TAG,
                      "Reflection rejected: frame carries OUR role=0x%02x "
                      "(cc=%p) — own frame reflected back",
                      (unsigned)msg_role, (void *)cc);
        return -1;
    }

    if (msg_role >= NODUS_CHANNEL_ROLE_COUNT) {
        QGP_LOG_ERROR(LOG_TAG, "Invalid role byte 0x%02x in nonce",
                      (unsigned)msg_role);
        return -1;
    }

    /* Replay window is tracked PER role, so the peer's stream and a legacy
     * stream cannot advance each other's baseline. */
    if (msg_counter < cc->rx_counter[msg_role]) {
        QGP_LOG_ERROR(LOG_TAG,
                      "Replay detected: role=0x%02x counter=%llu < expected=%llu cc=%p tx=%llu",
                      (unsigned)msg_role,
                      (unsigned long long)msg_counter,
                      (unsigned long long)cc->rx_counter[msg_role],
                      (void *)cc,
                      (unsigned long long)cc->tx_counter);
        return -1;
    }

    EVP_CIPHER_CTX *ctx = EVP_CIPHER_CTX_new();
    if (!ctx) return -1;

    int ret = -1;
    int len = 0;

    if (EVP_DecryptInit_ex(ctx, EVP_aes_256_gcm(), NULL, cc->key, nonce) != 1)
        goto cleanup;

    if (ct_len > 0) {
        if (EVP_DecryptUpdate(ctx, out, &len, ct, (int)ct_len) != 1)
            goto cleanup;
    }

    /* Set expected tag (copy to mutable buffer — OpenSSL API requires non-const) */
    uint8_t tag_copy[NODUS_CHANNEL_TAG_LEN];
    memcpy(tag_copy, tag, NODUS_CHANNEL_TAG_LEN);
    if (EVP_CIPHER_CTX_ctrl(ctx, EVP_CTRL_GCM_SET_TAG, NODUS_CHANNEL_TAG_LEN, tag_copy) != 1)
        goto cleanup;

    int final_len = 0;
    if (EVP_DecryptFinal_ex(ctx, out + len, &final_len) != 1) {
        QGP_LOG_ERROR(LOG_TAG, "AES-GCM auth failed (tampered or wrong key)");
        goto cleanup;
    }

    /* Advance the window for THIS role only, and only after the GCM tag
     * verified — a forged nonce must never move the baseline. */
    cc->rx_counter[msg_role] = msg_counter + 1;
    *out_len = (size_t)(len + final_len);
    ret = 0;

cleanup:
    EVP_CIPHER_CTX_free(ctx);
    return ret;
}

void nodus_channel_crypto_clear(nodus_channel_crypto_t *cc)
{
    if (!cc) return;
    qgp_secure_memzero(cc, sizeof(*cc));
}
