/**
 * Nodus — cometbft @709fd12b C port, wave R1-C: `types/validator.go` +
 * `types/validator_set.go` tests (INACTIVE layer).
 *
 * ── WHAT IT PROVES ─────────────────────────────────────────────────────
 * That the validator set that produces ValidatorsHash and elects every
 * proposer is the reference's. If this file failed, one of these would be
 * false:
 *   · a validator's address is SHA3-512(pubkey)[0..31] — the derivation
 *     this tree already uses for a witness id — and ValidateBasic
 *     RE-DERIVES it rather than trusting the one it was handed, so an
 *     address cannot be forged onto a key;
 *   · ValidatorsHash is the Merkle root over SimpleValidator{PubKey,
 *     VotingPower} leaves in ValidatorsByVotingPower order (power
 *     descending, address ascending), and an EMPTY set hashes to H("");
 *   · THE PROPOSER SEQUENCE IS COMETBFT'S. The 99-step sequence of
 *     TestProposerSelection1 (validator_set_test.go:221-241) and the
 *     40/50/30 proportionality of TestProposerSelection2 (:296-334) are
 *     the reference's own expected values, and this port reproduces them
 *     step for step;
 *   · the average that centres the priorities is computed at 128 bits —
 *     TestAvgProposerPriority's MaxInt64 and MinInt64 rows
 *     (validator_set_test.go:474-506) are exactly the cases an int64
 *     accumulator gets wrong, and getting them wrong changes who
 *     proposes;
 *   · a change set refuses a duplicate address, a negative power and a
 *     power above MaxTotalVotingPower; a zero power is a REMOVAL, not an
 *     error; and NewValidatorSet refuses a removal where
 *     UpdateWithChangeSet allows one;
 *   · a total voting power above MaxTotalVotingPower is a FAULT and not a
 *     verdict — a caller must never turn it into "this block is invalid";
 *   · safeAddClip and safeSubClip CLIP to the int64 ends instead of
 *     refusing, which is the J4 deviation of the deviation register that
 *     this module exists not to repeat;
 *   · GetProposer returns the STORED proposer, not a recomputed one. The
 *     two genuinely differ right after an election, because the elected
 *     validator has just been pushed back by the total voting power.
 *
 * ── WHAT IT REQUIRES ───────────────────────────────────────────────────
 * A default build. No compile flags, no environment variables, no
 * network, no files, no clock, no RNG. Safe under `ctest -j`. It allocates
 * a little over 2 MB on the heap (the change-set scratch and a 128-slot
 * validator array, each validator carrying a 2592-byte key) and frees it.
 *
 * ── WHAT IT LEAVES BEHIND ──────────────────────────────────────────────
 * Nothing. No files, no directories, no processes, no global state.
 *
 * ── HOW IT CAN LIE ─────────────────────────────────────────────────────
 *  1. The SHA3-512 digests are SELF-CONSISTENT FREEZES, not cometbft
 *     vectors: cometbft hashes with SHA-256 and the substitution is ours.
 *     They were derived by shared/dnac/tests/cmt_vset_oracle.py, an
 *     implementation independent of this C, so they pin agreement between
 *     two implementations and that the shape has not drifted. They do NOT
 *     establish that the shape is the reference's.
 *     THE PROPOSER SEQUENCES ARE DIFFERENT IN KIND — those ARE cometbft's
 *     own expected values, copied from its test file, and the oracle
 *     reproduces them from an independently written algorithm before it
 *     will emit anything.
 *  2. The proposer-selection sets are KEYLESS with short addresses,
 *     exactly as validator_set_test.go:400-402's `newValidator` builds
 *     them. That is what makes the reference's vectors reusable, and it
 *     means those cases exercise the ARITHMETIC and the tie-break, never
 *     the key handling. The hash cases carry real 2592-byte keys.
 *  3. Nothing here builds a 128-validator set or a real ML-DSA-87 key
 *     pair. The capacity bound is tested at its edge, not at scale.
 *  4. VerifyCommit and the light-client methods are NOT ported (stage D),
 *     so nothing here says anything about commit verification.
 *
 * @file test_cmt_validator_set.c
 */

#include "dnac/cmt_validator_set.h"
#include "dnac/cmt_merkle.h"
#include "dnac/cmt_tmhash.h"

#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#define CHECK(cond, msg) do { \
    if (!(cond)) { \
        fprintf(stderr, "CHECK failed at %s:%d: %s\n", __FILE__, __LINE__, (msg)); \
        return 1; \
    } \
} while (0)

/* ══ vectors — GENERATED by shared/dnac/tests/cmt_vset_oracle.py ═══════ */

static const uint8_t V_ADDR_0[32] = {
    0xc9, 0x0f, 0x0c, 0x07, 0x50, 0xd6, 0x75, 0xd1, 0xc4, 0xb5, 0x6c, 0x41,
    0xe0, 0x3f, 0xf6, 0x88, 0x1b, 0xa4, 0xae, 0xbe, 0x40, 0xd6, 0x86, 0xe4,
    0xa0, 0x9a, 0xed, 0xc7, 0x08, 0xd5, 0xa5, 0x3d,
};
static const uint8_t V_ADDR_1[32] = {
    0xfd, 0x02, 0xf7, 0x09, 0xa0, 0x29, 0x7e, 0x70, 0xb0, 0x5b, 0xd0, 0x6f,
    0xd8, 0xb5, 0x8d, 0xb7, 0x43, 0x3b, 0x35, 0x99, 0xa9, 0x88, 0xfb, 0xa2,
    0xa7, 0x96, 0x60, 0x56, 0x91, 0x67, 0x76, 0xe6,
};
static const uint8_t V_ADDR_2[32] = {
    0x6e, 0x1c, 0xa8, 0xee, 0xa6, 0x1c, 0xb9, 0x14, 0x07, 0x89, 0x22, 0x55,
    0x61, 0xeb, 0x86, 0x4c, 0x35, 0xc8, 0xbf, 0xf6, 0xdc, 0x3a, 0xee, 0x81,
    0x9b, 0x46, 0xe3, 0x81, 0xc3, 0x16, 0x4b, 0x2d,
};
static const uint8_t V_ADDR_3[32] = {
    0xcc, 0x3b, 0x3e, 0xd2, 0xd7, 0xd2, 0x75, 0xab, 0x10, 0x6c, 0x49, 0x38,
    0xe4, 0x3e, 0xa9, 0xa1, 0xcb, 0x1c, 0x44, 0x8a, 0xd7, 0x6f, 0x81, 0xff,
    0x5f, 0x19, 0x75, 0x84, 0x5e, 0x4e, 0x87, 0x64,
};

/* The empty tree's root, H("") — also crypto/merkle/hash.go:16-18. */
static const uint8_t V_VSET_HASH_EMPTY[64] = {
    0xa6, 0x9f, 0x73, 0xcc, 0xa2, 0x3a, 0x9a, 0xc5, 0xc8, 0xb5, 0x67, 0xdc,
    0x18, 0x5a, 0x75, 0x6e, 0x97, 0xc9, 0x82, 0x16, 0x4f, 0xe2, 0x58, 0x59,
    0xe0, 0xd1, 0xdc, 0xc1, 0x47, 0x5c, 0x80, 0xa6, 0x15, 0xb2, 0x12, 0x3a,
    0xf1, 0xf5, 0xf9, 0x4c, 0x11, 0xe3, 0xe9, 0x40, 0x2c, 0x3a, 0xc5, 0x58,
    0xf5, 0x00, 0x19, 0x9d, 0x95, 0xb6, 0xd3, 0xe3, 0x01, 0x75, 0x85, 0x86,
    0x28, 0x1d, 0xcd, 0x26,
};
/* Delta C-1: re-derived after the oracle's validator_leaf stopped
 * wrapping the key in PublicKey twice (leaf 2600 bytes, not 2603). */
static const uint8_t V_VSET_HASH_1[64] = {
    0x46, 0x01, 0x38, 0xaf, 0x41, 0x52, 0xde, 0x8d, 0xdb, 0x9e, 0xca, 0xb0,
    0x97, 0x50, 0xa4, 0xad, 0x0b, 0xfa, 0xf1, 0x68, 0x82, 0x81, 0x71, 0x4a,
    0xfb, 0xf8, 0x64, 0x5a, 0xde, 0xcb, 0x90, 0xc1, 0x82, 0xb2, 0x12, 0x42,
    0x84, 0x21, 0x90, 0x8c, 0x42, 0xcb, 0x3f, 0x0c, 0xc1, 0xa4, 0x29, 0xad,
    0x69, 0x66, 0x8e, 0xfb, 0x3f, 0x0c, 0x32, 0x34, 0x2e, 0xb7, 0x81, 0xfe,
    0xd2, 0xeb, 0xf3, 0x2f,
};
static const uint8_t V_VSET_HASH_3[64] = {
    0x5f, 0x12, 0x74, 0x79, 0x70, 0x0e, 0xbb, 0x89, 0xbd, 0x04, 0x68, 0xa4,
    0xf2, 0x86, 0xdf, 0xde, 0x41, 0x5a, 0x60, 0xa0, 0xa0, 0x83, 0xdf, 0xa3,
    0x70, 0xb4, 0xaa, 0x8a, 0xae, 0xc2, 0xe5, 0x9f, 0x42, 0xa3, 0x91, 0x23,
    0xb7, 0xe9, 0xdf, 0xc7, 0xa0, 0xc0, 0x6b, 0xcd, 0xf3, 0x93, 0xe3, 0xfe,
    0x63, 0x5b, 0x7e, 0x3b, 0x77, 0xe8, 0x2b, 0xc5, 0xf8, 0xe4, 0x8d, 0x8c,
    0xa3, 0x0d, 0xd7, 0x89,
};
static const uint8_t V_VSET_HASH_4_TIE[64] = {
    0x54, 0x3a, 0x83, 0x52, 0x5c, 0x19, 0x0c, 0x05, 0x08, 0xfc, 0xb1, 0x44,
    0x1c, 0x15, 0x4d, 0x19, 0x44, 0x31, 0xe1, 0x43, 0x90, 0x5e, 0xb0, 0x6f,
    0x28, 0xeb, 0xeb, 0x43, 0xa2, 0x24, 0xce, 0x62, 0xa0, 0xcf, 0xa5, 0x71,
    0xd1, 0xab, 0xe4, 0x23, 0xb4, 0x0e, 0xcd, 0x83, 0xfb, 0x50, 0x43, 0x38,
    0x76, 0x57, 0x15, 0xc7, 0x9e, 0x0b, 0xa4, 0x49, 0x9d, 0x69, 0x65, 0x33,
    0x29, 0x70, 0x5a, 0x63,
};
/* The four-validator tie order as key indices — power 9 first, then the
 * three power-5 entries by ASCENDING address (key 2 < key 0 < key 1). */
static const int V_VSET_4_TIE_ORDER[4] = { 3, 2, 0, 1 };

/* cometbft's OWN expected proposer sequence, validator_set_test.go:232-236,
 * transcribed as indices: 0 = "bar", 1 = "baz", 2 = "foo". */
#define V_PROP_SEL_1_N 99
static const unsigned char V_PROP_SEL_1[99] = {
    2, 1, 2, 0, 2, 2, 1, 2, 0, 2, 2, 1, 2, 2, 0, 2, 1, 2, 2, 0,
    2, 2, 1, 2, 0, 2, 2, 1, 2, 0, 2, 2, 1, 2, 2, 0, 2, 1, 2, 2,
    0, 2, 1, 2, 2, 0, 2, 1, 2, 2, 0, 2, 1, 2, 2, 2, 1, 0, 2, 2,
    2, 1, 2, 0, 2, 2, 1, 2, 0, 2, 2, 1, 2, 0, 2, 2, 1, 2, 0, 2,
    2, 1, 2, 2, 0, 2, 1, 2, 2, 0, 2, 1, 2, 2, 0, 2, 1, 2, 2,
};
/* validator_set_test.go:305-334 — 4/12, 5/12 and 3/12 of the power over
 * 120 rounds. */
static const int V_PROP_SEL_2_COUNTS[3] = { 40, 50, 30 };

/* ══ fixtures ═════════════════════════════════════════════════════════ */

/** cmt_pb_oracle.py's `pat`: byte i = (seed + 7*i) mod 256. */
static void fill_pat(uint8_t *dst, size_t n, unsigned seed)
{
    size_t i;
    for (i = 0; i < n; i++) {
        dst[i] = (uint8_t)((seed + 7u * (unsigned)i) & 0xFFu);
    }
}

static void make_key(cmt_pb_public_key_t *pk, unsigned seed)
{
    memset(pk, 0, sizeof(*pk));
    pk->present = true;
    fill_pat(pk->key, CMT_PB_PUBKEY_LEN, seed);
}

/** A KEYLESS validator with a short literal address — exactly what
 *  validator_set_test.go:400-402's `newValidator` builds. */
static void make_bare(cmt_validator_t *v, const char *addr, int64_t power)
{
    size_t n = strlen(addr);
    memset(v, 0, sizeof(*v));
    memcpy(v->address, addr, n);
    v->address_len  = n;
    v->voting_power = power;
}

/** A keyless validator with a 20-byte address whose last byte is `tag` —
 *  the addr0/addr1/addr2 of validator_set_test.go:244-246. */
static void make_bare20(cmt_validator_t *v, uint8_t tag, int64_t power)
{
    memset(v, 0, sizeof(*v));
    v->address_len   = 20;
    v->address[19]   = tag;
    v->voting_power  = power;
}

/* Heap fixtures: the scratch is over a megabyte and a 128-slot validator
 * array is a third of one. Neither belongs on a stack. */
static cmt_valset_scratch_t *g_scratch;
static cmt_validator_t      *g_store;     /* CMT_VALSET_MAX slots */
static cmt_validator_t      *g_store2;    /* CMT_VALSET_MAX slots */
static uint8_t              *g_leafbuf;   /* leaf scratch for Hash()  */
static cmt_merkle_item_t    *g_items;

#define LEAFBUF_LEN ((size_t)CMT_VALSET_MAX * CMT_VALIDATOR_BYTES_MAX)

static int hash_set(cmt_validator_set_t *vs, uint8_t out[64])
{
    return cmt_validator_set_hash(vs, g_leafbuf, LEAFBUF_LEN, g_items,
                                  CMT_VALSET_MAX, out);
}

/* ══ 1. address derivation and ValidateBasic ══════════════════════════ */

static int t_address(void)
{
    cmt_pb_public_key_t pk;
    cmt_validator_t     v;
    uint8_t             addr[32];

    make_key(&pk, 0x11);
    CHECK(cmt_pub_key_address(&pk, addr) == CMT_OK, "address of key 0");
    CHECK(memcmp(addr, V_ADDR_0, 32) == 0,
          "address of key 0 is SHA3-512(key)[0..31]");

    make_key(&pk, 0x22);
    CHECK(cmt_pub_key_address(&pk, addr) == CMT_OK, "address of key 1");
    CHECK(memcmp(addr, V_ADDR_1, 32) == 0, "address of key 1");

    /* An ABSENT key has no address — the reference's nil PubKey. */
    memset(&pk, 0, sizeof(pk));
    CHECK(cmt_pub_key_address(&pk, addr) == CMT_REJECT,
          "an absent key has no address");
    CHECK(cmt_pub_key_address(NULL, addr) == CMT_FAULT, "NULL key is a fault");

    /* NewValidator derives the address; ValidateBasic re-derives it. */
    make_key(&pk, 0x11);
    CHECK(cmt_validator_new(&pk, 7, &v) == CMT_OK, "NewValidator");
    CHECK(v.address_len == 32 && memcmp(v.address, V_ADDR_0, 32) == 0,
          "NewValidator sets Address = pubKey.Address()");
    CHECK(v.voting_power == 7 && v.proposer_priority == 0,
          "NewValidator sets power and a zero priority");
    CHECK(cmt_validator_validate_basic(&v) == CMT_OK, "a derived validator");

    /* ⚠ THE ATTACK THIS CHECK EXISTS FOR: an address that does not belong
     * to the key must be refused, or a validator could claim another's
     * identity while signing with its own key. */
    v.address[0] ^= 0x01;
    CHECK(cmt_validator_validate_basic(&v) == CMT_REJECT,
          "an address not derived from the key is refused");
    v.address[0] ^= 0x01;

    /* bytes.Equal compares LENGTH too: a truncated address is not equal. */
    v.address_len = 31;
    CHECK(cmt_validator_validate_basic(&v) == CMT_REJECT,
          "a 31-byte address is refused");
    v.address_len = 32;

    v.voting_power = -1;
    CHECK(cmt_validator_validate_basic(&v) == CMT_REJECT,
          "a negative voting power is refused");
    v.voting_power = 7;

    v.pub_key.present = false;
    CHECK(cmt_validator_validate_basic(&v) == CMT_REJECT,
          "a validator with no key is refused");
    CHECK(cmt_validator_validate_basic(NULL) == CMT_REJECT,
          "a NULL validator is the reference's nil validator");
    return 0;
}

/* ══ 2. CompareProposerPriority ═══════════════════════════════════════ */

static int t_compare(void)
{
    cmt_validator_t        a, b;
    const cmt_validator_t *w = NULL;

    make_bare(&a, "aaa", 1);
    make_bare(&b, "bbb", 1);

    /* A nil receiver returns the other — what makes the fold work. */
    CHECK(cmt_validator_compare_proposer_priority(NULL, &b, &w) == CMT_OK &&
          w == &b, "a nil receiver returns the other");

    a.proposer_priority = 5;
    b.proposer_priority = 3;
    CHECK(cmt_validator_compare_proposer_priority(&a, &b, &w) == CMT_OK &&
          w == &a, "the higher priority wins");
    CHECK(cmt_validator_compare_proposer_priority(&b, &a, &w) == CMT_OK &&
          w == &a, "and it wins from either side");

    /* Equal priority: the LOWER address wins. */
    b.proposer_priority = 5;
    CHECK(cmt_validator_compare_proposer_priority(&a, &b, &w) == CMT_OK &&
          w == &a, "on a tie the lower address wins");
    CHECK(cmt_validator_compare_proposer_priority(&b, &a, &w) == CMT_OK &&
          w == &a, "and the tie-break is symmetric");

    /* bytes.Compare orders by length after the common prefix. */
    make_bare(&b, "aaaa", 1);
    b.proposer_priority = 5;
    CHECK(cmt_validator_compare_proposer_priority(&a, &b, &w) == CMT_OK &&
          w == &a, "a prefix sorts before the longer address");

    /* Two identical validators: the reference panics. */
    make_bare(&b, "aaa", 1);
    b.proposer_priority = 5;
    CHECK(cmt_validator_compare_proposer_priority(&a, &b, &w) == CMT_REJECT,
          "two identical validators cannot be compared");
    return 0;
}

/* ══ 3. the clipping arithmetic (J4) ══════════════════════════════════ */

static int t_safemath(void)
{
    int64_t out = 0;

    CHECK(!cmt_vs_safe_add(1, 2, &out) && out == 3, "safeAdd");
    CHECK(cmt_vs_safe_add(INT64_MAX, 1, &out), "safeAdd overflows at the top");
    CHECK(out == -1, "and writes the reference's -1 sentinel");
    CHECK(cmt_vs_safe_add(INT64_MIN, -1, &out),
          "safeAdd overflows at the bottom");
    CHECK(!cmt_vs_safe_sub(1, 2, &out) && out == -1, "safeSub");
    CHECK(cmt_vs_safe_sub(INT64_MIN, 1, &out), "safeSub underflows");
    CHECK(cmt_vs_safe_sub(INT64_MAX, -1, &out), "safeSub overflows");

    /* ⚠ THE J4 PROPERTY: the reference CLIPS, it does not refuse.
     * tm_proposer.c rejects outside ±2^40 instead; this module must not. */
    CHECK(cmt_vs_safe_add_clip(INT64_MAX, 1) == INT64_MAX,
          "safeAddClip clips at the top");
    CHECK(cmt_vs_safe_add_clip(INT64_MIN, -1) == INT64_MIN,
          "safeAddClip clips at the bottom");
    CHECK(cmt_vs_safe_add_clip(INT64_MAX, -1) == INT64_MAX - 1,
          "safeAddClip is ordinary addition in range");
    CHECK(cmt_vs_safe_sub_clip(INT64_MIN, 1) == INT64_MIN,
          "safeSubClip clips at the bottom");
    CHECK(cmt_vs_safe_sub_clip(INT64_MAX, -1) == INT64_MAX,
          "safeSubClip clips at the top");

    CHECK(!cmt_vs_safe_mul(0, INT64_MAX, &out) && out == 0, "safeMul by zero");
    CHECK(!cmt_vs_safe_mul(3, 4, &out) && out == 12, "safeMul");
    CHECK(cmt_vs_safe_mul(INT64_MAX, 2, &out), "safeMul overflows");
    /* The MinInt64 quirk: -b wraps back to MinInt64, so the reference
     * compares against a NEGATIVE divisor and reports overflow. */
    CHECK(cmt_vs_safe_mul(1, INT64_MIN, &out),
          "safeMul reports overflow for b = MinInt64 (reference quirk)");
    return 0;
}

/* ══ 4. the 128-bit average ═══════════════════════════════════════════ */

static int t_avg(void)
{
    cmt_validator_set_t vs;
    int64_t             avg = 0;
    size_t              i;
    struct { int n; int64_t p[3]; int64_t want; } tc[] = {
        { 3, { 0, 0, 0 },                        0            },
        { 3, { INT64_MAX, 0, 0 },                INT64_MAX / 3 },
        { 2, { INT64_MAX, 0, 0 },                INT64_MAX / 2 },
        { 2, { INT64_MAX, INT64_MAX, 0 },        INT64_MAX     },
        { 2, { INT64_MIN, INT64_MIN, 0 },        INT64_MIN     },
    };

    /* validator_set_test.go:474-506, TestAvgProposerPriority. Rows 3 and 4
     * SUM past int64 and are the whole reason for the 128-bit
     * accumulator; an int64 sum would wrap and give the wrong proposer. */
    for (i = 0; i < sizeof(tc) / sizeof(tc[0]); i++) {
        int j;
        CHECK(cmt_validator_set_init(&vs, g_store, CMT_VALSET_MAX) == CMT_OK,
              "init");
        for (j = 0; j < tc[i].n; j++) {
            make_bare(&g_store[j], "x", 0);
            g_store[j].address[0] = (uint8_t)('a' + j);
            g_store[j].proposer_priority = tc[i].p[j];
        }
        vs.validators_len = (size_t)tc[i].n;
        CHECK(cmt_validator_set_compute_avg_proposer_priority(&vs, &avg)
                  == CMT_OK, "computeAvgProposerPriority");
        CHECK(avg == tc[i].want, "the reference's expected average");
    }

    /* Euclidean division floors, so a negative sum rounds DOWN, not toward
     * zero: -1 / 3 is -1, never 0. */
    CHECK(cmt_validator_set_init(&vs, g_store, CMT_VALSET_MAX) == CMT_OK,
          "init");
    for (i = 0; i < 3; i++) {
        make_bare(&g_store[i], "x", 0);
        g_store[i].address[0] = (uint8_t)('a' + i);
        g_store[i].proposer_priority = 0;
    }
    g_store[0].proposer_priority = -1;
    vs.validators_len = 3;
    CHECK(cmt_validator_set_compute_avg_proposer_priority(&vs, &avg) == CMT_OK,
          "avg of {-1, 0, 0}");
    CHECK(avg == -1, "Euclidean division FLOORS: -1/3 is -1, not 0");

    vs.validators_len = 0;
    CHECK(cmt_validator_set_compute_avg_proposer_priority(&vs, &avg)
              == CMT_REJECT, "an empty set has no average");
    return 0;
}

/* ══ 5. ValidatorsHash ════════════════════════════════════════════════ */

static int t_hash(void)
{
    cmt_validator_set_t vs;
    cmt_pb_public_key_t pk;
    uint8_t             got[64];
    const unsigned      seeds[4] = { 0x11, 0x22, 0x33, 0x44 };
    const int64_t       tie_pw[4] = { 5, 5, 5, 9 };
    size_t              i;

    /* An EMPTY set is the empty tree, H(""). */
    CHECK(cmt_validator_set_init(&vs, g_store, CMT_VALSET_MAX) == CMT_OK,
          "init");
    CHECK(hash_set(&vs, got) == CMT_OK, "Hash of an empty set");
    CHECK(memcmp(got, V_VSET_HASH_EMPTY, 64) == 0,
          "Hash() of an empty validator set is H(\"\")");

    /* One validator. */
    make_key(&pk, seeds[0]);
    CHECK(cmt_validator_new(&pk, 10, &g_store[0]) == CMT_OK, "new");
    vs.validators_len = 1;
    CHECK(hash_set(&vs, got) == CMT_OK, "Hash of one validator");
    CHECK(memcmp(got, V_VSET_HASH_1, 64) == 0, "the one-validator root");

    /* Three, IN ValidatorsByVotingPower ORDER: 30, 20, 10. */
    {
        const unsigned s3[3] = { 0x22, 0x33, 0x11 };
        const int64_t  p3[3] = { 30, 20, 10 };
        for (i = 0; i < 3; i++) {
            make_key(&pk, s3[i]);
            CHECK(cmt_validator_new(&pk, p3[i], &g_store[i]) == CMT_OK, "new");
        }
        vs.validators_len = 3;
        CHECK(hash_set(&vs, got) == CMT_OK, "Hash of three");
        CHECK(memcmp(got, V_VSET_HASH_3, 64) == 0, "the three-validator root");

        /* ⚠ ORDER IS PART OF THE ROOT. Swapping two members changes it, so
         * a set assembled in another order does not hash alike — which is
         * why updateWithChangeSet sorts at :674. */
        {
            cmt_validator_t tmp = g_store[0];
            uint8_t         other[64];
            g_store[0] = g_store[1];
            g_store[1] = tmp;
            CHECK(hash_set(&vs, other) == CMT_OK, "Hash of the permutation");
            CHECK(memcmp(other, got, 64) != 0,
                  "leaf order is part of ValidatorsHash");
        }
    }

    /* Four with a POWER TIE, which the ASCENDING address breaks. Build
     * them in DOCUMENT order and let the set's own sort place them. */
    for (i = 0; i < 4; i++) {
        make_key(&pk, seeds[i]);
        CHECK(cmt_validator_new(&pk, tie_pw[i], &g_store[i]) == CMT_OK, "new");
    }
    {
        cmt_validator_t *ptrs[4];
        for (i = 0; i < 4; i++) {
            ptrs[i] = &g_store[i];
        }
        cmt_validators_sort_by_voting_power(ptrs, 4);
        for (i = 0; i < 4; i++) {
            CHECK(ptrs[i] == &g_store[(size_t)V_VSET_4_TIE_ORDER[i]],
                  "power DESC, then address ASC");
        }
        for (i = 0; i < 4; i++) {
            g_store2[i] = *ptrs[i];
        }
    }
    CHECK(cmt_validator_set_init(&vs, g_store2, CMT_VALSET_MAX) == CMT_OK,
          "init");
    vs.validators_len = 4;
    CHECK(hash_set(&vs, got) == CMT_OK, "Hash of four with a tie");
    CHECK(memcmp(got, V_VSET_HASH_4_TIE, 64) == 0,
          "the tie-broken four-validator root");

    /* A leaf is at most CMT_VALIDATOR_BYTES_MAX, and a keyless validator
     * has no leaf at all. */
    {
        uint8_t buf[CMT_VALIDATOR_BYTES_MAX];
        size_t  len = 0;
        CHECK(cmt_validator_bytes(&g_store2[0], buf, sizeof(buf), &len)
                  == CMT_OK, "Bytes()");
        CHECK(len <= CMT_VALIDATOR_BYTES_MAX,
              "a leaf fits CMT_VALIDATOR_BYTES_MAX");
        CHECK(cmt_validator_bytes(&g_store2[0], buf, len - 1, &len)
                  == CMT_REJECT, "an exact-size-minus-one buffer is refused");
        g_store2[0].pub_key.present = false;
        CHECK(cmt_validator_bytes(&g_store2[0], buf, sizeof(buf), &len)
                  == CMT_REJECT, "a keyless validator has no leaf");
    }
    return 0;
}

/* ══ 6. TestProposerSelection1 — cometbft's own sequence ══════════════ */

static int t_proposer_selection_1(void)
{
    cmt_validator_set_t vs;
    cmt_validator_t     seed[3];
    cmt_validator_t     prop;
    int                 i;
    static const char  *names[3] = { "bar", "baz", "foo" };

    /* validator_set_test.go:222-226 — keyless, exactly as newValidator
     * (:400-402) builds them. */
    make_bare(&seed[0], "foo", 1000);
    make_bare(&seed[1], "bar", 300);
    make_bare(&seed[2], "baz", 330);

    CHECK(cmt_validator_set_init(&vs, g_store, CMT_VALSET_MAX) == CMT_OK,
          "init");
    CHECK(cmt_validator_set_new(&vs, seed, 3, g_scratch) == CMT_OK,
          "NewValidatorSet");

    for (i = 0; i < V_PROP_SEL_1_N; i++) {
        const char *want = names[V_PROP_SEL_1[i]];
        CHECK(cmt_validator_set_get_proposer(&vs, &prop) == CMT_OK,
              "GetProposer");
        CHECK(prop.address_len == 3 &&
              memcmp(prop.address, want, 3) == 0,
              "the proposer at this step is cometbft's");
        CHECK(cmt_validator_set_increment_proposer_priority(&vs, 1) == CMT_OK,
              "IncrementProposerPriority(1)");
    }

    /* :195-197 — non-positive `times` panics. */
    CHECK(cmt_validator_set_increment_proposer_priority(&vs, 0) == CMT_REJECT,
          "IncrementProposerPriority(0) is refused");
    CHECK(cmt_validator_set_increment_proposer_priority(&vs, -1) == CMT_REJECT,
          "IncrementProposerPriority(-1) is refused");
    return 0;
}

/* ══ 7. TestProposerSelection2 — order and proportionality ════════════ */

static int t_proposer_selection_2(void)
{
    cmt_validator_set_t vs;
    cmt_validator_t     seed[3];
    cmt_validator_t     prop;
    int                 counts[3] = { 0, 0, 0 };
    int                 i;

    /* :248-259 — equal power goes in ADDRESS order, repeatedly. */
    for (i = 0; i < 3; i++) {
        make_bare20(&seed[i], (uint8_t)i, 100);
    }
    CHECK(cmt_validator_set_init(&vs, g_store, CMT_VALSET_MAX) == CMT_OK, "i");
    CHECK(cmt_validator_set_new(&vs, seed, 3, g_scratch) == CMT_OK, "new");
    for (i = 0; i < 15; i++) {
        CHECK(cmt_validator_set_get_proposer(&vs, &prop) == CMT_OK, "prop");
        CHECK(prop.address[19] == (uint8_t)(i % 3),
              "equal power proposes in address order");
        CHECK(cmt_validator_set_increment_proposer_priority(&vs, 1) == CMT_OK,
              "inc");
    }

    /* :296-334 — 4/12, 5/12 and 3/12 of the power over 120 rounds. */
    make_bare20(&seed[0], 0, 4);
    make_bare20(&seed[1], 1, 5);
    make_bare20(&seed[2], 2, 3);
    CHECK(cmt_validator_set_init(&vs, g_store, CMT_VALSET_MAX) == CMT_OK, "i");
    CHECK(cmt_validator_set_new(&vs, seed, 3, g_scratch) == CMT_OK, "new");
    for (i = 0; i < 120; i++) {
        CHECK(cmt_validator_set_get_proposer(&vs, &prop) == CMT_OK, "prop");
        counts[prop.address[19]]++;
        CHECK(cmt_validator_set_increment_proposer_priority(&vs, 1) == CMT_OK,
              "inc");
    }
    for (i = 0; i < 3; i++) {
        CHECK(counts[i] == V_PROP_SEL_2_COUNTS[i],
              "each validator proposes in proportion to its power");
    }

    /* :264-292 — one validator with 400 of 600 proposes once, one with
     * 401 proposes twice in a row. The boundary is the whole point. */
    make_bare20(&seed[0], 0, 100);
    make_bare20(&seed[1], 1, 100);
    make_bare20(&seed[2], 2, 400);
    CHECK(cmt_validator_set_init(&vs, g_store, CMT_VALSET_MAX) == CMT_OK, "i");
    CHECK(cmt_validator_set_new(&vs, seed, 3, g_scratch) == CMT_OK, "new");
    CHECK(cmt_validator_set_get_proposer(&vs, &prop) == CMT_OK, "prop");
    CHECK(prop.address[19] == 2, "the strongest proposes first");
    CHECK(cmt_validator_set_increment_proposer_priority(&vs, 1) == CMT_OK, "i");
    CHECK(cmt_validator_set_get_proposer(&vs, &prop) == CMT_OK, "prop");
    CHECK(prop.address[19] == 0, "400 of 600 does not propose twice");

    make_bare20(&seed[2], 2, 401);
    CHECK(cmt_validator_set_init(&vs, g_store, CMT_VALSET_MAX) == CMT_OK, "i");
    CHECK(cmt_validator_set_new(&vs, seed, 3, g_scratch) == CMT_OK, "new");
    CHECK(cmt_validator_set_get_proposer(&vs, &prop) == CMT_OK, "prop");
    CHECK(prop.address[19] == 2, "the strongest proposes first");
    CHECK(cmt_validator_set_increment_proposer_priority(&vs, 1) == CMT_OK, "i");
    CHECK(cmt_validator_set_get_proposer(&vs, &prop) == CMT_OK, "prop");
    CHECK(prop.address[19] == 2, "401 of 601 DOES propose twice in a row");
    CHECK(cmt_validator_set_increment_proposer_priority(&vs, 1) == CMT_OK, "i");
    CHECK(cmt_validator_set_get_proposer(&vs, &prop) == CMT_OK, "prop");
    CHECK(prop.address[19] == 0, "and then the smallest address");
    return 0;
}

/* ══ 8. GetProposer returns the STORED proposer ═══════════════════════ */

static int t_get_proposer_is_stored(void)
{
    cmt_validator_set_t    vs;
    cmt_validator_t        seed[3], prop;
    const cmt_validator_t *found = NULL;

    make_bare(&seed[0], "foo", 1000);
    make_bare(&seed[1], "bar", 300);
    make_bare(&seed[2], "baz", 330);
    CHECK(cmt_validator_set_init(&vs, g_store, CMT_VALSET_MAX) == CMT_OK, "i");
    CHECK(cmt_validator_set_new(&vs, seed, 3, g_scratch) == CMT_OK, "new");

    CHECK(vs.has_proposer, "NewValidatorSet stores the proposer it elected");
    CHECK(cmt_validator_set_get_proposer(&vs, &prop) == CMT_OK, "prop");

    /* ⚠ THE DISTINCTION: findProposer picks the CURRENT maximum, but the
     * stored proposer was pushed back by the total voting power the moment
     * it was elected (:190). The two therefore disagree, and GetProposer
     * must return the STORED one — a set that recomputed here would elect
     * a different validator from the rest of the cluster. */
    CHECK(cmt_validator_set_find_proposer(&vs, &found) == CMT_OK, "find");
    CHECK(memcmp(found->address, prop.address, 3) != 0,
          "findProposer and the stored proposer differ after an election");

    /* With the field cleared, GetProposer DOES fall back to findProposer. */
    vs.has_proposer = false;
    CHECK(cmt_validator_set_get_proposer(&vs, &prop) == CMT_OK, "prop");
    CHECK(memcmp(found->address, prop.address, 3) == 0,
          "an unset proposer falls back to findProposer");
    CHECK(vs.has_proposer, "and the fallback fills the field in");
    return 0;
}

/* ══ 9. the change set ════════════════════════════════════════════════ */

static int t_change_set(void)
{
    cmt_validator_set_t vs;
    cmt_validator_t     seed[3], chg[3];
    int32_t             idx = 0;
    cmt_validator_t     got;

    /* A base set of three. */
    make_bare20(&seed[0], 0, 10);
    make_bare20(&seed[1], 1, 20);
    make_bare20(&seed[2], 2, 30);
    CHECK(cmt_validator_set_init(&vs, g_store, CMT_VALSET_MAX) == CMT_OK, "i");
    CHECK(cmt_validator_set_new(&vs, seed, 3, g_scratch) == CMT_OK, "new");
    CHECK(cmt_validator_set_size(&vs) == 3, "three members");

    /* NewValidatorSet uses allowDeletes = FALSE: a zero power is refused. */
    {
        cmt_validator_set_t vz;
        cmt_validator_t     z[2];
        make_bare20(&z[0], 0, 10);
        make_bare20(&z[1], 1, 0);
        CHECK(cmt_validator_set_init(&vz, g_store2, CMT_VALSET_MAX) == CMT_OK,
              "i");
        CHECK(cmt_validator_set_new(&vz, z, 2, g_scratch) == CMT_REJECT,
              "NewValidatorSet refuses a zero-power entry");
    }

    /* UPDATE an existing power. */
    make_bare20(&chg[0], 1, 50);
    CHECK(cmt_validator_set_update_with_change_set(&vs, chg, 1, g_scratch)
              == CMT_OK, "update an existing member");
    CHECK(cmt_validator_set_size(&vs) == 3, "the size is unchanged");
    CHECK(cmt_validator_set_get_by_address(&vs, chg[0].address, 20, &idx, &got)
              == CMT_OK && idx >= 0, "still present");
    CHECK(got.voting_power == 50, "with the new power");
    CHECK(vs.validators[0].voting_power == 50,
          "and the set is sorted by voting power, descending");

    /* ADD a new member. Its priority is the -1.125*P entry penalty, i.e.
     * strictly negative — the un-bond/re-bond defence (:518-525). */
    make_bare20(&chg[0], 3, 5);
    CHECK(cmt_validator_set_update_with_change_set(&vs, chg, 1, g_scratch)
              == CMT_OK, "add a new member");
    CHECK(cmt_validator_set_size(&vs) == 4, "four members");
    CHECK(cmt_validator_set_get_by_address(&vs, chg[0].address, 20, &idx, &got)
              == CMT_OK && idx >= 0, "the new member is present");
    CHECK(got.proposer_priority < 0,
          "a new member starts at a negative priority");

    /* REMOVE, which is a change with power 0. */
    make_bare20(&chg[0], 3, 0);
    CHECK(cmt_validator_set_update_with_change_set(&vs, chg, 1, g_scratch)
              == CMT_OK, "a zero power is a REMOVAL");
    CHECK(cmt_validator_set_size(&vs) == 3, "back to three");
    CHECK(cmt_validator_set_get_by_address(&vs, chg[0].address, 20, &idx, NULL)
              == CMT_OK && idx == -1, "and the member is gone");

    /* An EMPTY change list changes nothing and succeeds (:625-627). */
    CHECK(cmt_validator_set_update_with_change_set(&vs, NULL, 0, g_scratch)
              == CMT_OK, "an empty change set is a no-op");
    CHECK(cmt_validator_set_size(&vs) == 3, "still three");

    /* ── negatives ── */

    /* A DUPLICATE address in one change set (:419-422). */
    make_bare20(&chg[0], 1, 11);
    make_bare20(&chg[1], 1, 12);
    CHECK(cmt_validator_set_update_with_change_set(&vs, chg, 2, g_scratch)
              == CMT_REJECT, "a duplicate address is refused");
    CHECK(cmt_validator_set_size(&vs) == 3, "and the set is unchanged");

    /* A NEGATIVE power (:425-427). */
    make_bare20(&chg[0], 1, -1);
    CHECK(cmt_validator_set_update_with_change_set(&vs, chg, 1, g_scratch)
              == CMT_REJECT, "a negative voting power is refused");

    /* A power above MaxTotalVotingPower (:428-431). */
    make_bare20(&chg[0], 1, CMT_MAX_TOTAL_VOTING_POWER + 1);
    CHECK(cmt_validator_set_update_with_change_set(&vs, chg, 1, g_scratch)
              == CMT_REJECT, "a power above MaxTotalVotingPower is refused");

    /* Removing a member that is not there (:580-582). */
    make_bare20(&chg[0], 9, 0);
    CHECK(cmt_validator_set_update_with_change_set(&vs, chg, 1, g_scratch)
              == CMT_REJECT, "removing an absent member is refused");

    /* Removing EVERY member would empty the set (:640-642). */
    make_bare20(&chg[0], 0, 0);
    make_bare20(&chg[1], 1, 0);
    make_bare20(&chg[2], 2, 0);
    CHECK(cmt_validator_set_update_with_change_set(&vs, chg, 3, g_scratch)
              == CMT_REJECT, "emptying the set is refused");
    CHECK(cmt_validator_set_size(&vs) == 3, "and it is still unchanged");

    /* Two updates whose sum passes MaxTotalVotingPower (:483-485). */
    make_bare20(&chg[0], 0, CMT_MAX_TOTAL_VOTING_POWER);
    make_bare20(&chg[1], 1, CMT_MAX_TOTAL_VOTING_POWER);
    CHECK(cmt_validator_set_update_with_change_set(&vs, chg, 2, g_scratch)
              == CMT_REJECT, "a total above MaxTotalVotingPower is refused");
    CHECK(cmt_validator_set_size(&vs) == 3, "unchanged");

    /* ── verifyUpdates must NOT reorder the caller's list (:475) ──
     *
     * Every rejection above left the set at {tag0:10, tag1:50, tag2:30}.
     * Two updates on EXISTING members whose DELTA order is the reverse of
     * their ADDRESS order: tag0 -> 100 is delta +90, tag1 -> 51 is delta
     * +1, so sorting by delta yields [tag1, tag0] while processChanges
     * produced [tag0, tag1].
     *
     * applyUpdates (:534-537) requires address order — it merges two
     * sorted lists in a single pass. Sorting the caller's array in place
     * inside verifyUpdates feeds it the delta order, and the merge then
     * emits tag0 TWICE (once with its stale power, once updated) for four
     * entries where three were predicted, which this port refuses as a
     * size mismatch. So the defect shows up as a spurious CMT_REJECT of a
     * perfectly valid change set.
     *
     * This case needs a NON-EMPTY existing set: when the set is empty the
     * merge degenerates to an append and the final sort hides the order. */
    make_bare20(&chg[0], 0, 100);
    make_bare20(&chg[1], 1, 51);
    CHECK(cmt_validator_set_update_with_change_set(&vs, chg, 2, g_scratch)
              == CMT_OK,
          "two updates in delta order != address order are ACCEPTED");
    CHECK(cmt_validator_set_size(&vs) == 3,
          "and produce three members, not a duplicated one");
    make_bare20(&chg[0], 0, 0);
    CHECK(cmt_validator_set_get_by_address(&vs, chg[0].address, 20, &idx, &got)
              == CMT_OK && idx >= 0 && got.voting_power == 100,
          "the larger-delta update landed");
    make_bare20(&chg[0], 1, 0);
    CHECK(cmt_validator_set_get_by_address(&vs, chg[0].address, 20, &idx, &got)
              == CMT_OK && idx >= 0 && got.voting_power == 51,
          "the smaller-delta update landed");
    make_bare20(&chg[0], 2, 0);
    CHECK(cmt_validator_set_get_by_address(&vs, chg[0].address, 20, &idx, &got)
              == CMT_OK && idx >= 0 && got.voting_power == 30,
          "and the untouched member kept its power");
    return 0;
}

/* ══ 10. MaxTotalVotingPower is a FAULT, not a verdict ════════════════ */

static int t_total_voting_power(void)
{
    cmt_validator_set_t vs;
    int64_t             tvp = 0;
    size_t              i;

    CHECK(cmt_validator_set_init(&vs, g_store, CMT_VALSET_MAX) == CMT_OK, "i");
    for (i = 0; i < 3; i++) {
        make_bare20(&g_store[i], (uint8_t)i, 10);
    }
    vs.validators_len = 3;
    CHECK(cmt_validator_set_total_voting_power(&vs, &tvp) == CMT_OK, "total");
    CHECK(tvp == 30, "the sum of the powers");

    /* At the boundary exactly: MaxTotalVotingPower is allowed. */
    vs.total_voting_power = 0;
    g_store[0].voting_power = CMT_MAX_TOTAL_VOTING_POWER - 20;
    CHECK(cmt_validator_set_total_voting_power(&vs, &tvp) == CMT_OK,
          "exactly MaxTotalVotingPower is allowed");
    CHECK(tvp == CMT_MAX_TOTAL_VOTING_POWER, "and it is the total");

    /* ⚠ ONE OVER IS A FAULT. It must NOT be -1: a caller that took a
     * verdict from here would declare a block invalid on what is an
     * internal inconsistency of this process. */
    vs.total_voting_power = 0;
    g_store[0].voting_power = CMT_MAX_TOTAL_VOTING_POWER - 19;
    CHECK(cmt_validator_set_total_voting_power(&vs, &tvp) == CMT_FAULT,
          "one over MaxTotalVotingPower is a FAULT");
    CHECK(cmt_validator_set_total_voting_power(&vs, &tvp) != CMT_REJECT,
          "and it is NOT a verdict");

    /* validator_set_test.go:460-472 — three MaxInt64 members. */
    vs.total_voting_power = 0;
    for (i = 0; i < 3; i++) {
        g_store[i].voting_power = INT64_MAX;
    }
    CHECK(cmt_validator_set_update_total_voting_power(&vs) == CMT_FAULT,
          "three MaxInt64 members overflow the total");
    return 0;
}

/* ══ 11. ValidateBasic and the codec round trip ═══════════════════════ */

static int t_set_validate_and_proto(void)
{
    cmt_validator_set_t     vs, back;
    cmt_pb_validator_set_t  pb;
    cmt_pb_validator_t     *pb_slots;
    cmt_pb_public_key_t     pk;
    cmt_validator_t         seed[3];
    size_t                  i;
    int                     rc;

    pb_slots = calloc(CMT_VALSET_MAX, sizeof(*pb_slots));
    CHECK(pb_slots != NULL, "alloc");

    for (i = 0; i < 3; i++) {
        make_key(&pk, (unsigned)(0x11 + 0x11 * i));
        CHECK(cmt_validator_new(&pk, (int64_t)(10 + 10 * i), &seed[i])
                  == CMT_OK, "new");
    }
    CHECK(cmt_validator_set_init(&vs, g_store, CMT_VALSET_MAX) == CMT_OK, "i");
    CHECK(cmt_validator_set_new(&vs, seed, 3, g_scratch) == CMT_OK, "new set");
    CHECK(cmt_validator_set_validate_basic(&vs) == CMT_OK, "a valid set");

    /* A proposer that is not a member is ErrProposerNotInVals (:112). */
    {
        cmt_validator_t saved = vs.proposer;
        vs.proposer.address[0] ^= 0xFF;
        CHECK(cmt_validator_set_validate_basic(&vs) == CMT_REJECT,
              "a proposer whose address is not derived from its key");
        vs.proposer = saved;
        make_key(&pk, 0x55);
        CHECK(cmt_validator_new(&pk, 10, &vs.proposer) == CMT_OK, "new");
        CHECK(cmt_validator_set_validate_basic(&vs) == CMT_REJECT,
              "a valid proposer that is not a member is refused");
        vs.proposer = saved;
        CHECK(cmt_validator_set_validate_basic(&vs) == CMT_OK, "restored");
    }

    /* ToProto ZEROES TotalVotingPower (:901) — the reference's comment at
     * :899-900 says the proto bytes are sometimes used as a hash, so the
     * cached value must not leak into them.
     *
     * ⚠ THIS ASSERTION IS ONLY MEANINGFUL BECAUSE THE CACHE IS NON-ZERO.
     * If the set's total were 0 the check would pass against an
     * implementation that copied it, so the cache is proven populated
     * first. The defect being guarded is "copied the total", not
     * "forgot to write it". */
    {
        int64_t cached = 0;
        CHECK(cmt_validator_set_total_voting_power(&vs, &cached) == CMT_OK,
              "total");
        CHECK(cached == 60, "the set's cached total is 10 + 20 + 30");
        CHECK(vs.total_voting_power == 60, "and it is in the struct");
    }
    memset(&pb, 0, sizeof(pb));
    pb.validators     = pb_slots;
    pb.validators_cap = CMT_VALSET_MAX;
    CHECK(cmt_validator_set_to_proto(&vs, &pb) == CMT_OK, "ToProto");
    CHECK(pb.total_voting_power == 0,
          "ToProto zeroes TotalVotingPower even though the set caches 60");
    CHECK(pb.validators_len == 3 && pb.has_proposer, "shape");

    /* FromProto RECOMPUTES the total and never trusts the wire (:933-938),
     * and ends in ValidateBasic (:940). */
    pb.total_voting_power = INT64_MAX;          /* a lying peer */
    CHECK(cmt_validator_set_init(&back, g_store2, CMT_VALSET_MAX) == CMT_OK,
          "i");
    back.total_voting_power = 999;              /* a stale cache */
    CHECK(cmt_validator_set_from_proto(&pb, &back) == CMT_OK, "FromProto");
    CHECK(back.total_voting_power == 10 + 20 + 30,
          "FromProto recomputes the total and ignores the wire value");
    CHECK(back.validators_len == 3, "three members came back");

    /* A validator whose address does not belong to its key is refused at
     * the decode boundary, because FromProto ends in ValidateBasic. */
    pb.validators[0].address[0] ^= 0x01;
    rc = cmt_validator_set_from_proto(&pb, &back);
    CHECK(rc == CMT_REJECT, "a forged address is refused by FromProto");
    pb.validators[0].address[0] ^= 0x01;

    /* An absent proposer is an error (:926-929). */
    pb.has_proposer = false;
    CHECK(cmt_validator_set_from_proto(&pb, &back) == CMT_REJECT,
          "a proto with no proposer is refused");
    pb.has_proposer = true;
    CHECK(cmt_validator_set_from_proto(NULL, &back) == CMT_REJECT,
          "a nil proto is refused");

    /* ValidatorSetFromExistingValidators keeps powers and priorities and
     * only re-sorts (:947-966). */
    {
        cmt_validator_set_t ex;
        CHECK(cmt_validator_set_init(&ex, g_store2, CMT_VALSET_MAX) == CMT_OK,
              "i");
        CHECK(cmt_validator_set_from_existing_validators(&ex, seed, 3)
                  == CMT_OK, "FromExistingValidators");
        CHECK(ex.validators_len == 3 && ex.has_proposer, "shape");
        CHECK(ex.validators[0].voting_power == 30,
              "sorted by voting power, descending");
        CHECK(ex.total_voting_power == 60, "the total is recomputed");
        CHECK(cmt_validator_set_from_existing_validators(&ex, seed, 0)
                  == CMT_REJECT, "an empty list is refused");
        seed[1].address[0] ^= 0x01;
        CHECK(cmt_validator_set_from_existing_validators(&ex, seed, 3)
                  == CMT_REJECT, "a member failing ValidateBasic is refused");
        seed[1].address[0] ^= 0x01;
    }

    free(pb_slots);
    return 0;
}

/* ══ 12. capacity ═════════════════════════════════════════════════════ */

static int t_capacity(void)
{
    cmt_validator_set_t vs;

    /* The set's capacity bound is refused, never truncated. */
    CHECK(cmt_validator_set_init(&vs, g_store, CMT_VALSET_MAX + 1)
              == CMT_REJECT, "a capacity above CMT_VALSET_MAX is refused");
    CHECK(cmt_validator_set_init(&vs, g_store, CMT_VALSET_MAX) == CMT_OK,
          "exactly CMT_VALSET_MAX is allowed");
    CHECK(CMT_VALSET_MAX == 128, "the ceiling is ledger_ids.h's 128");
    CHECK(CMT_VALSET_MAX_CHANGES == 256,
          "a change set may remove all and add all");
    CHECK(CMT_MAX_TOTAL_VOTING_POWER == INT64_MAX / 8,
          "MaxTotalVotingPower is MaxInt64/8");
    CHECK(CMT_PRIORITY_WINDOW_SIZE_FACTOR == 2, "the window factor is 2");
    return 0;
}

/* ══ main ═════════════════════════════════════════════════════════════ */

int main(void)
{
    int rc = 0;

    g_scratch = malloc(sizeof(*g_scratch));
    g_store   = calloc(CMT_VALSET_MAX, sizeof(*g_store));
    g_store2  = calloc(CMT_VALSET_MAX, sizeof(*g_store2));
    g_leafbuf = malloc(LEAFBUF_LEN);
    g_items   = calloc(CMT_VALSET_MAX, sizeof(*g_items));
    if (g_scratch == NULL || g_store == NULL || g_store2 == NULL ||
        g_leafbuf == NULL || g_items == NULL) {
        fprintf(stderr, "out of memory\n");
        return 1;
    }

    if (rc == 0) { rc = t_address();                 }
    if (rc == 0) { rc = t_compare();                 }
    if (rc == 0) { rc = t_safemath();                }
    if (rc == 0) { rc = t_avg();                     }
    if (rc == 0) { rc = t_hash();                    }
    if (rc == 0) { rc = t_proposer_selection_1();    }
    if (rc == 0) { rc = t_proposer_selection_2();    }
    if (rc == 0) { rc = t_get_proposer_is_stored();  }
    if (rc == 0) { rc = t_change_set();              }
    if (rc == 0) { rc = t_total_voting_power();      }
    if (rc == 0) { rc = t_set_validate_and_proto();  }
    if (rc == 0) { rc = t_capacity();                }

    free(g_scratch);
    free(g_store);
    free(g_store2);
    free(g_leafbuf);
    free(g_items);

    if (rc == 0) {
        printf("test_cmt_validator_set: 12 groups OK\n");
    }
    return rc;
}
