/**
 * Nodus — cometbft @709fd12b C port, wave R1-C: `types/params.go` tests
 * (INACTIVE layer).
 *
 * ── WHAT IT PROVES ─────────────────────────────────────────────────────
 * That ConsensusHash and the parameter rules are the reference's. If this
 * file failed, one of these would be false:
 *   · ConsensusHash is the FLAT hash of the marshalled
 *     HashedParams{Block.MaxBytes, Block.MaxGas} — no Merkle tree — and
 *     the default parameters' preimage is the 16-byte
 *     `088080c00a10ffffffffffffffffff01` the port map pins at REV 3.2;
 *   · NOTHING ELSE IS IN THAT HASH. Changing the evidence bounds, the key
 *     types, the app version or the vote-extension height leaves
 *     ConsensusHash byte-identical, which is exactly what lets the
 *     parameter set evolve without a header change — and, read the other
 *     way, is why the public-key TYPE NAME is not consensus-critical;
 *   · ValidateBasic refuses a zero MaxBytes, a MaxBytes below -1 or above
 *     the 100 MB ceiling, a MaxGas below -1, a non-positive evidence age
 *     or duration, an evidence size above the block bound, a negative
 *     evidence size, a negative vote-extension height, an empty key-type
 *     list and an unknown key type;
 *   · ValidateUpdate implements the ten-row table at params.go:209-219 —
 *     vote extensions cannot be disabled once enabled, cannot be moved to
 *     a past height, and cannot be modified once enabled;
 *   · VoteExtensionsEnabled refuses a height below 1 rather than
 *     answering, and reads an enable height of 0 as NEVER, not as "from
 *     height zero";
 *   · Update applies a sub-message WHOLE when it is present and leaves it
 *     alone when it is absent.
 *
 * ── WHAT IT REQUIRES ───────────────────────────────────────────────────
 * A default build. No compile flags, no environment variables, no
 * network, no files, no clock, no RNG. Safe under `ctest -j`. A few
 * hundred bytes on the stack.
 *
 * ── WHAT IT LEAVES BEHIND ──────────────────────────────────────────────
 * Nothing.
 *
 * ── HOW IT CAN LIE ─────────────────────────────────────────────────────
 *  1. The two SHA3-512 digests are SELF-CONSISTENT FREEZES derived by
 *     shared/dnac/tests/cmt_vset_oracle.py, not cometbft vectors — that
 *     project hashes with SHA-256. The PREIMAGE, however, is checked
 *     against the port map's REV 3.2 golden value, which was derived from
 *     the pinned `params.pb.go`, so the encoding half is grounded even
 *     though the digest half is ours.
 *  2. The key-type name CMT_PUBKEY_TYPE_MLDSA87_NAME is an OPEN QUESTION
 *     for the operator (cmt_params.h). Nothing here asserts its value —
 *     only that the check compares strings and refuses an unknown one. A
 *     green run says nothing about whether that string is the right one.
 *  3. ToProto and ConsensusParamsFromProto are NOT ported (R2 store work),
 *     so nothing here says anything about the parameter wire format —
 *     including the reference's missing nil guard at params.go:349-365,
 *     which is recorded in the header and left for whoever ports it.
 *
 * @file test_cmt_params.c
 */

#include "dnac/cmt_params.h"
#include "dnac/cmt_tmhash.h"

#include <stdio.h>
#include <stdint.h>
#include <string.h>

#define CHECK(cond, msg) do { \
    if (!(cond)) { \
        fprintf(stderr, "CHECK failed at %s:%d: %s\n", __FILE__, __LINE__, (msg)); \
        return 1; \
    } \
} while (0)

/* ══ vectors — GENERATED by shared/dnac/tests/cmt_vset_oracle.py ═══════ */

/* preimage 088080c00a10ffffffffffffffffff01 (the REV 3.2 golden value) */
static const uint8_t V_CONSENSUS_HASH_DEFAULT[64] = {
    0xc0, 0x4d, 0x44, 0x87, 0xc5, 0x72, 0xf1, 0x6c, 0xdb, 0x4f, 0x5d, 0xca,
    0xe9, 0x9f, 0xcb, 0x96, 0x81, 0xe2, 0x59, 0x28, 0x71, 0x20, 0xa5, 0x7d,
    0x5c, 0x30, 0xb3, 0x94, 0x87, 0xdd, 0xd1, 0xdc, 0x7e, 0x23, 0xcd, 0x46,
    0x0a, 0xde, 0xf4, 0x0b, 0x02, 0x09, 0x31, 0x33, 0x17, 0x27, 0xfa, 0x62,
    0x5d, 0x15, 0x4c, 0x09, 0x5e, 0x54, 0x40, 0xd6, 0x77, 0x36, 0x58, 0x27,
    0x6a, 0x93, 0xa0, 0xed,
};
/* preimage 0801 — a second point, so the test cannot pass on one constant */
static const uint8_t V_CONSENSUS_HASH_1_0[64] = {
    0x3d, 0x7d, 0x7e, 0x7a, 0x22, 0xad, 0xf6, 0xc6, 0xf6, 0x08, 0x01, 0x03,
    0x43, 0x78, 0xb7, 0x18, 0x0b, 0x75, 0x98, 0x95, 0xec, 0xa1, 0x27, 0x04,
    0xce, 0xc2, 0xfd, 0x95, 0xc3, 0xa4, 0x49, 0x16, 0xb7, 0x2d, 0x43, 0xb6,
    0x5b, 0xe5, 0xc5, 0x9c, 0xb6, 0x82, 0x7d, 0xc9, 0xe6, 0xcd, 0xf2, 0xc2,
    0xf4, 0xa3, 0x5b, 0x5e, 0x1a, 0x9f, 0x68, 0xc6, 0x17, 0x06, 0xbc, 0x28,
    0x59, 0x85, 0xab, 0x79,
};

/* ══ 1. the defaults ══════════════════════════════════════════════════ */

static int t_defaults(void)
{
    cmt_consensus_params_t p;

    cmt_default_consensus_params(&p);
    CHECK(p.block.max_bytes == 22020096, "DefaultBlockParams MaxBytes (21MB)");
    CHECK(p.block.max_gas == -1, "DefaultBlockParams MaxGas is -1");
    CHECK(p.evidence.max_age_num_blocks == 100000, "MaxAgeNumBlocks");
    /* 48 hours in NANOSECONDS — a time.Duration is not seconds. */
    CHECK(p.evidence.max_age_duration_ns == (int64_t)48 * 3600 * 1000000000,
          "MaxAgeDuration is 48 hours expressed in nanoseconds");
    CHECK(p.evidence.max_bytes == 1048576, "evidence MaxBytes (1MB)");
    CHECK(p.version.app == 0, "DefaultVersionParams App");
    /* 0 MEANS NEVER, not "from height zero" — params.go:129-130. */
    CHECK(p.abci.vote_extensions_enable_height == 0,
          "DefaultABCIParams: vote extensions are not required");
    CHECK(p.validator.pub_key_types_len == 1, "one key type");
    CHECK(strcmp(p.validator.pub_key_types[0],
                 CMT_PUBKEY_TYPE_MLDSA87_NAME) == 0,
          "the one key type is this chain's");
    CHECK(cmt_consensus_params_validate_basic(&p) == CMT_OK,
          "the defaults are valid");

    /* The three size constants come from cmt_bits.h, not from a copy. */
    CHECK(CMT_MAX_BLOCK_SIZE_BYTES == 104857600, "MaxBlockSizeBytes");
    CHECK(CMT_BLOCK_PART_SIZE_BYTES == 65536, "BlockPartSizeBytes");
    CHECK(CMT_MAX_BLOCK_PARTS_COUNT == 104857600 / 65536 + 1,
          "MaxBlockPartsCount");
    return 0;
}

/* ══ 2. ConsensusHash ═════════════════════════════════════════════════ */

static int t_hash(void)
{
    cmt_consensus_params_t p, q;
    uint8_t                a[64], b[64];

    cmt_default_consensus_params(&p);
    CHECK(cmt_consensus_params_hash(&p, a) == CMT_OK, "Hash");
    CHECK(memcmp(a, V_CONSENSUS_HASH_DEFAULT, 64) == 0,
          "ConsensusHash of the default parameters");

    /* A second point, so a constant-returning implementation fails. */
    memset(&q, 0, sizeof(q));
    q.block.max_bytes = 1;
    q.block.max_gas   = 0;
    CHECK(cmt_consensus_params_hash(&q, b) == CMT_OK, "Hash");
    CHECK(memcmp(b, V_CONSENSUS_HASH_1_0, 64) == 0,
          "ConsensusHash of {1, 0}");
    CHECK(memcmp(a, b, 64) != 0, "and the two differ");

    /* ⚠ ONLY THE TWO BLOCK FIELDS ARE IN THE HASH. Everything else may
     * change without moving the header leaf — params.go:268-271. */
    q = p;
    q.evidence.max_age_num_blocks = 7;
    q.evidence.max_bytes          = 99;
    q.evidence.max_age_duration_ns = 1;
    q.version.app                 = 42;
    q.abci.vote_extensions_enable_height = 5;
    q.validator.pub_key_types_len = 0;
    CHECK(cmt_consensus_params_hash(&q, b) == CMT_OK, "Hash");
    CHECK(memcmp(a, b, 64) == 0,
          "evidence, version, ABCI and key types are NOT in ConsensusHash");

    /* But the two that ARE in it move it. */
    q = p;
    q.block.max_gas = 0;
    CHECK(cmt_consensus_params_hash(&q, b) == CMT_OK, "Hash");
    CHECK(memcmp(a, b, 64) != 0, "Block.MaxGas IS in ConsensusHash");
    q = p;
    q.block.max_bytes = 22020097;
    CHECK(cmt_consensus_params_hash(&q, b) == CMT_OK, "Hash");
    CHECK(memcmp(a, b, 64) != 0, "Block.MaxBytes IS in ConsensusHash");

    CHECK(cmt_consensus_params_hash(NULL, a) == CMT_FAULT, "NULL is a fault");
    return 0;
}

/* ══ 3. ValidateBasic ═════════════════════════════════════════════════ */

static int t_validate_basic(void)
{
    cmt_consensus_params_t p;

#define BAD(field_setup, msg) do {                                   \
        cmt_default_consensus_params(&p);                            \
        field_setup;                                                 \
        CHECK(cmt_consensus_params_validate_basic(&p) == CMT_REJECT, msg); \
    } while (0)
#define GOOD(field_setup, msg) do {                                  \
        cmt_default_consensus_params(&p);                            \
        field_setup;                                                 \
        CHECK(cmt_consensus_params_validate_basic(&p) == CMT_OK, msg); \
    } while (0)

    BAD(p.block.max_bytes = 0,  "a zero Block.MaxBytes is refused");
    BAD(p.block.max_bytes = -2, "a Block.MaxBytes below -1 is refused");
    GOOD(p.block.max_bytes = -1,
         "-1 means unbounded and IS allowed");
    BAD(p.block.max_bytes = (int64_t)CMT_MAX_BLOCK_SIZE_BYTES + 1,
        "a Block.MaxBytes above the 100 MB ceiling is refused");
    GOOD(p.block.max_bytes = CMT_MAX_BLOCK_SIZE_BYTES,
         "exactly the ceiling is allowed");

    BAD(p.block.max_gas = -2, "a Block.MaxGas below -1 is refused");
    GOOD(p.block.max_gas = -1, "-1 is allowed");
    GOOD(p.block.max_gas = 0,  "0 is allowed");

    BAD(p.evidence.max_age_num_blocks = 0,
        "a zero evidence MaxAgeNumBlocks is refused");
    BAD(p.evidence.max_age_num_blocks = -1,
        "a negative evidence MaxAgeNumBlocks is refused");
    BAD(p.evidence.max_age_duration_ns = 0,
        "a zero evidence MaxAgeDuration is refused");

    BAD(p.evidence.max_bytes = p.block.max_bytes + 1,
        "evidence larger than a block is refused");
    GOOD(p.evidence.max_bytes = p.block.max_bytes,
         "evidence exactly the size of a block is allowed");
    BAD(p.evidence.max_bytes = -1, "a negative evidence MaxBytes is refused");
    /* With MaxBytes -1 the evidence bound is the hard ceiling, not -1. */
    GOOD((p.block.max_bytes = -1, p.evidence.max_bytes =
              (int64_t)CMT_MAX_BLOCK_SIZE_BYTES),
         "an unbounded block measures evidence against the ceiling");
    BAD((p.block.max_bytes = -1, p.evidence.max_bytes =
              (int64_t)CMT_MAX_BLOCK_SIZE_BYTES + 1),
        "and one byte past the ceiling is still refused");

    BAD(p.abci.vote_extensions_enable_height = -1,
        "a negative VoteExtensionsEnableHeight is refused");

    BAD(p.validator.pub_key_types_len = 0, "an empty key-type list is refused");
    BAD(memcpy(p.validator.pub_key_types[0], "nosuchtype", 11),
        "an unknown key type is refused");
    BAD(p.validator.pub_key_types_len = CMT_PARAMS_MAX_PUBKEY_TYPES + 1,
        "more key types than capacity is refused");

    CHECK(cmt_consensus_params_validate_basic(NULL) == CMT_FAULT,
          "NULL is a fault");

    /* IsValidPubkeyType compares STRINGS. Its VALUE is an open question
     * for the operator, so nothing here asserts what the string is. */
    cmt_default_consensus_params(&p);
    CHECK(cmt_is_valid_pubkey_type(&p.validator,
                                   CMT_PUBKEY_TYPE_MLDSA87_NAME),
          "the configured type is valid");
    CHECK(!cmt_is_valid_pubkey_type(&p.validator, "ed25519"),
          "a type that is not configured is not valid");
    CHECK(!cmt_is_valid_pubkey_type(&p.validator, ""),
          "the empty string is not valid");
    CHECK(!cmt_is_valid_pubkey_type(NULL, CMT_PUBKEY_TYPE_MLDSA87_NAME),
          "NULL params");
#undef BAD
#undef GOOD
    return 0;
}

/* ══ 4. VoteExtensionsEnabled ═════════════════════════════════════════ */

static int t_vote_extensions(void)
{
    cmt_abci_params_t a;
    bool              on = true;

    a.vote_extensions_enable_height = 0;
    CHECK(cmt_abci_params_vote_extensions_enabled(a, 1, &on) == CMT_OK, "h=1");
    CHECK(!on, "an enable height of 0 means NEVER");
    CHECK(cmt_abci_params_vote_extensions_enabled(a, 1000000, &on) == CMT_OK,
          "h large");
    CHECK(!on, "and it still means never at a large height");

    a.vote_extensions_enable_height = 10;
    CHECK(cmt_abci_params_vote_extensions_enabled(a, 9, &on) == CMT_OK, "h=9");
    CHECK(!on, "off below the enable height");
    CHECK(cmt_abci_params_vote_extensions_enabled(a, 10, &on) == CMT_OK, "h=10");
    CHECK(on, "on AT the enable height");
    CHECK(cmt_abci_params_vote_extensions_enabled(a, 11, &on) == CMT_OK, "h=11");
    CHECK(on, "and above it");

    /* h < 1 is the reference's panic — a verdict, not an answer. */
    CHECK(cmt_abci_params_vote_extensions_enabled(a, 0, &on) == CMT_REJECT,
          "height 0 is refused, not answered");
    CHECK(cmt_abci_params_vote_extensions_enabled(a, -1, &on) == CMT_REJECT,
          "a negative height is refused");
    CHECK(cmt_abci_params_vote_extensions_enabled(a, 1, NULL) == CMT_FAULT,
          "NULL out is a fault");
    return 0;
}

/* ══ 5. ValidateUpdate — the ten-row table ════════════════════════════ */

static int t_validate_update(void)
{
    cmt_consensus_params_t       p;
    cmt_consensus_params_proto_t u;

    cmt_default_consensus_params(&p);
    memset(&u, 0, sizeof(u));

    /* 1: a nil update, or one with no ABCI section, always passes. */
    CHECK(cmt_consensus_params_validate_update(&p, NULL, 100) == CMT_OK,
          "row 1: a nil update passes");
    u.has_abci = false;
    CHECK(cmt_consensus_params_validate_update(&p, &u, 100) == CMT_OK,
          "row 1: an update with no ABCI section passes");

    u.has_abci = true;

    /* 2: a negative height never passes. */
    u.abci.vote_extensions_enable_height = -1;
    CHECK(cmt_consensus_params_validate_update(&p, &u, 100) == CMT_REJECT,
          "row 2: a negative enable height is refused");

    /* 3: currently off, staying off. */
    p.abci.vote_extensions_enable_height = 0;
    u.abci.vote_extensions_enable_height = 0;
    CHECK(cmt_consensus_params_validate_update(&p, &u, 100) == CMT_OK,
          "row 3: off staying off passes");

    /* 4: unchanged. */
    p.abci.vote_extensions_enable_height = 50;
    u.abci.vote_extensions_enable_height = 50;
    CHECK(cmt_consensus_params_validate_update(&p, &u, 100) == CMT_OK,
          "row 4: an unchanged height passes");

    /* 5: ⚠ cannot be DISABLED once it has taken effect. */
    p.abci.vote_extensions_enable_height = 50;
    u.abci.vote_extensions_enable_height = 0;
    CHECK(cmt_consensus_params_validate_update(&p, &u, 100) == CMT_REJECT,
          "row 5: vote extensions cannot be disabled once enabled");
    CHECK(cmt_consensus_params_validate_update(&p, &u, 50) == CMT_REJECT,
          "row 5: not even in the very block they took effect");

    /* 6: a proposal that has NOT taken effect yet may be withdrawn. */
    CHECK(cmt_consensus_params_validate_update(&p, &u, 49) == CMT_OK,
          "row 6: a future enable height may be cancelled");

    /* 7: never to a past or current height. */
    p.abci.vote_extensions_enable_height = 0;
    u.abci.vote_extensions_enable_height = 100;
    CHECK(cmt_consensus_params_validate_update(&p, &u, 100) == CMT_REJECT,
          "row 7: the CURRENT height is refused");
    CHECK(cmt_consensus_params_validate_update(&p, &u, 101) == CMT_REJECT,
          "row 7: a PAST height is refused");

    /* 8: currently off, scheduled for the future. */
    CHECK(cmt_consensus_params_validate_update(&p, &u, 99) == CMT_OK,
          "row 8: an off chain may schedule a future height");

    /* 9: ⚠ cannot be MODIFIED once it has taken effect. */
    p.abci.vote_extensions_enable_height = 50;
    u.abci.vote_extensions_enable_height = 200;
    CHECK(cmt_consensus_params_validate_update(&p, &u, 100) == CMT_REJECT,
          "row 9: vote extensions cannot be modified once enabled");

    /* 10: a future proposal may be moved to another future height. */
    p.abci.vote_extensions_enable_height = 150;
    CHECK(cmt_consensus_params_validate_update(&p, &u, 100) == CMT_OK,
          "row 10: one future height may be replaced by another");

    CHECK(cmt_consensus_params_validate_update(NULL, &u, 1) == CMT_FAULT,
          "NULL params is a fault");
    return 0;
}

/* ══ 6. Update ════════════════════════════════════════════════════════ */

static int t_update(void)
{
    cmt_consensus_params_t       p, out;
    cmt_consensus_params_proto_t u;

    cmt_default_consensus_params(&p);
    memset(&u, 0, sizeof(u));

    /* A nil update is a plain copy and does NOT modify the original.
     * Compared FIELD BY FIELD: a struct assignment is not required to
     * copy padding bytes, so a memcmp over the whole struct would be
     * comparing values C does not define. */
    CHECK(cmt_consensus_params_update(&p, NULL, &out) == CMT_OK, "nil update");
    CHECK(out.block.max_bytes == p.block.max_bytes &&
          out.block.max_gas == p.block.max_gas &&
          out.evidence.max_age_num_blocks == p.evidence.max_age_num_blocks &&
          out.evidence.max_age_duration_ns == p.evidence.max_age_duration_ns &&
          out.evidence.max_bytes == p.evidence.max_bytes &&
          out.version.app == p.version.app &&
          out.abci.vote_extensions_enable_height ==
              p.abci.vote_extensions_enable_height &&
          out.validator.pub_key_types_len == p.validator.pub_key_types_len &&
          strcmp(out.validator.pub_key_types[0],
                 p.validator.pub_key_types[0]) == 0,
          "a nil update copies every field");

    /* An ABSENT sub-message leaves its fields alone. */
    CHECK(cmt_consensus_params_update(&p, &u, &out) == CMT_OK, "empty update");
    CHECK(out.block.max_bytes == p.block.max_bytes &&
          out.version.app == p.version.app,
          "absent sub-messages leave their fields alone");

    /* A PRESENT sub-message is applied WHOLE, zeros included — the code,
     * not the comment at params.go:292, is the authority. */
    u.has_block         = true;
    u.block.max_bytes   = 1024;
    u.block.max_gas     = 0;
    CHECK(cmt_consensus_params_update(&p, &u, &out) == CMT_OK, "block update");
    CHECK(out.block.max_bytes == 1024, "the new MaxBytes");
    CHECK(out.block.max_gas == 0,
          "and a ZERO MaxGas is applied, not skipped as 'non-zero' implies");
    CHECK(p.block.max_gas == -1, "the original is not modified");

    u.has_version = true;
    u.version.app = 9;
    u.has_abci    = true;
    u.abci.vote_extensions_enable_height = 77;
    CHECK(cmt_consensus_params_update(&p, &u, &out) == CMT_OK, "update");
    CHECK(out.version.app == 9 &&
          out.abci.vote_extensions_enable_height == 77, "both applied");
    CHECK(out.evidence.max_bytes == p.evidence.max_bytes,
          "and evidence, which was absent, is untouched");

    /* A key-type list longer than the capacity is refused. */
    u.has_validator = true;
    u.validator.pub_key_types_len = CMT_PARAMS_MAX_PUBKEY_TYPES + 1;
    CHECK(cmt_consensus_params_update(&p, &u, &out) == CMT_REJECT,
          "an over-long key-type list is refused");

    CHECK(cmt_consensus_params_update(NULL, &u, &out) == CMT_FAULT, "NULL");
    CHECK(cmt_consensus_params_update(&p, &u, NULL) == CMT_FAULT, "NULL out");
    return 0;
}

int main(void)
{
    int rc = 0;

    if (rc == 0) { rc = t_defaults();        }
    if (rc == 0) { rc = t_hash();            }
    if (rc == 0) { rc = t_validate_basic();  }
    if (rc == 0) { rc = t_vote_extensions(); }
    if (rc == 0) { rc = t_validate_update(); }
    if (rc == 0) { rc = t_update();          }

    if (rc == 0) {
        printf("test_cmt_params: 6 groups OK\n");
    }
    return rc;
}
