/**
 * test_qgp_deb.c - qgp phase 1 against the independent oracle KAT
 * (scripts/qgp-sign/qgp_deb_kat.json, generated by qgp_deb_oracle.py from the
 * APPROVED bytes doc only) plus real ML-DSA-87 round trips.
 *
 *  1. package vectors: M_pkg, the prefix, the `_qgp.sig` header and member bytes
 *     byte-compared; the DUMMY signature must NOT verify;
 *  2. every package reject vector refused with the oracle's reason;
 *  3. trust chain / trust accept vectors: M_trust byte-compared, chain
 *     prev_digest, rebuilt 64 KiB boundary file;
 *  4. every trust reject vector refused with the oracle's reason;
 *  5. real keys: deb-sign / deb-verify, file signature (signatures are
 *     randomized: verified, never byte-compared);
 *  6. real-key trust chain acceptance and its refusals (prev_digest mismatch,
 *     zeros on a non-first file, revoked signer, lowered floor, ...);
 *  7. Debian version comparison cases from deb-version(7), the package policy
 *     (floor + highest accepted, R2-5), the dpkg-deb field parser and the
 *     state directory round trip.
 */
#define _GNU_SOURCE
#include <json-c/json.h>
#include <limits.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>

#include "qgp_core.h"
#include "qgp_deb.h"
#include "qgp_debver.h"
#include "qgp_filesig.h"
#include "qgp_io.h"
#include "qgp_state.h"
#include "qgp_trust.h"

#include "crypto/utils/qgp_log.h"
#include "crypto/utils/qgp_safe_string.h"

#define LOG_TAG "TEST_QGP"

static int g_fail = 0;
static int g_pass = 0;

#define CHECK(cond, ...) do { \
        if (cond) { g_pass++; } \
        else { g_fail++; QGP_LOG_ERROR(LOG_TAG, "FAIL %s:%d: " #cond, __FILE__, __LINE__); \
               QGP_LOG_ERROR(LOG_TAG, __VA_ARGS__); } \
    } while (0)

/* ---------------------------------------------------------------- helpers */

typedef struct {
    uint8_t *p;
    size_t   n;
} blob_t;

static void blob_free(blob_t *b) { free(b->p); b->p = NULL; b->n = 0; }

static blob_t hex_blob(const char *hex)
{
    blob_t b = { NULL, 0 };
    size_t hn = hex ? strlen(hex) : 0;
    if (hn % 2 != 0)
        return b;
    b.p = malloc(hn / 2 ? hn / 2 : 1);
    if (!b.p)
        return b;
    if (qgp_hex_decode_lower(hex, hn, b.p, hn / 2) != 0) {
        free(b.p);
        b.p = NULL;
        return b;
    }
    b.n = hn / 2;
    return b;
}

static json_object *jget(json_object *o, const char *key)
{
    json_object *v = NULL;
    if (!o || !json_object_object_get_ex(o, key, &v))
        return NULL;
    return v;
}

static const char *jstr(json_object *o, const char *key)
{
    json_object *v = jget(o, key);
    return v ? json_object_get_string(v) : NULL;
}

static int64_t jint(json_object *o, const char *key)
{
    json_object *v = jget(o, key);
    return v ? json_object_get_int64(v) : -1;
}

/* o[key]["hex"] decoded */
static blob_t jhex_of(json_object *o, const char *key)
{
    return hex_blob(jstr(jget(o, key), "hex"));
}

static int eq_hex(const uint8_t *p, size_t n, const char *hex)
{
    blob_t b = hex_blob(hex);
    int ok = b.p && b.n == n && memcmp(b.p, p, n) == 0;
    blob_free(&b);
    return ok;
}

static void sha3_hex(const uint8_t *p, size_t n, char out[2 * QGP_HASH_LEN + 1])
{
    uint8_t h[QGP_HASH_LEN];
    qgp_sha3_512(p, n, h);
    qgp_hex_encode(h, QGP_HASH_LEN, out);
}

/* Trust-file bytes from parts (layout §2). */
static blob_t build_trust_file(uint64_t serial, const uint8_t signer[QGP_HASH_LEN],
                               const uint8_t *body, size_t body_len, const uint8_t sig[QGP_SIG_LEN])
{
    blob_t f;
    f.n = QGP_TRUST_FIXED + body_len + 2 + QGP_SIG_LEN;
    f.p = malloc(f.n);
    if (!f.p) { f.n = 0; return f; }
    f.p[0] = 0x01;
    qgp_be64_put(f.p + 1, serial);
    memcpy(f.p + 9, signer, QGP_HASH_LEN);
    qgp_be32_put(f.p + 73, (uint32_t)body_len);
    memcpy(f.p + 77, body, body_len);
    qgp_be16_put(f.p + 77 + body_len, QGP_SIG_LEN);
    memcpy(f.p + 79 + body_len, sig, QGP_SIG_LEN);
    return f;
}

/* "key <fp> <pk>" line, NUL-terminated, malloc'd. */
static char *key_line(const uint8_t pk[QGP_PK_LEN])
{
    uint8_t fp[QGP_HASH_LEN];
    qgp_sha3_512(pk, QGP_PK_LEN, fp);
    char *s = malloc(4 + 2 * QGP_HASH_LEN + 1 + 2 * QGP_PK_LEN + 1);
    if (!s)
        return NULL;
    memcpy(s, "key ", 4);
    qgp_hex_encode(fp, QGP_HASH_LEN, s + 4);
    s[4 + 2 * QGP_HASH_LEN] = ' ';
    qgp_hex_encode(pk, QGP_PK_LEN, s + 4 + 2 * QGP_HASH_LEN + 1);
    return s;
}

static char *revoked_line(const uint8_t pk[QGP_PK_LEN])
{
    uint8_t fp[QGP_HASH_LEN];
    qgp_sha3_512(pk, QGP_PK_LEN, fp);
    char *s = malloc(8 + 2 * QGP_HASH_LEN + 1);
    if (!s)
        return NULL;
    memcpy(s, "revoked ", 8);
    qgp_hex_encode(fp, QGP_HASH_LEN, s + 8);
    return s;
}

static int cmp_cstr(const void *a, const void *b)
{
    return strcmp(*(const char *const *)a, *(const char *const *)b);
}

/* Canonical body: lines sorted bytewise (strcmp == bytewise for ASCII), each + LF. */
static blob_t body_of(const char **lines, size_t n)
{
    const char **s = malloc(n * sizeof(*s));
    blob_t b = { NULL, 0 };
    if (!s)
        return b;
    memcpy(s, lines, n * sizeof(*s));
    qsort(s, n, sizeof(*s), cmp_cstr);
    size_t total = 0;
    for (size_t i = 0; i < n; i++)
        total += strlen(s[i]) + 1;
    b.p = malloc(total ? total : 1);
    if (b.p) {
        size_t o = 0;
        for (size_t i = 0; i < n; i++) {
            size_t l = strlen(s[i]);
            memcpy(b.p + o, s[i], l);
            o += l;
            b.p[o++] = '\n';
        }
        b.n = total;
    }
    free(s);
    return b;
}

/* ------------------------------------------------- 1/2: package vectors */

static int load_kat_trust_state(json_object *kat, size_t idx, qgp_trust_state_t *st)
{
    json_object *chain = jget(kat, "trust_chain");
    json_object *e = json_object_array_get_idx(chain, idx);
    const char *body = jstr(e, "body");
    if (!body)
        return -1;
    return qgp_trust_parse_body((const uint8_t *)body, strlen(body), st) == QGP_OK ? 0 : -1;
}

static void check_package_vector(json_object *vec, const char *name, const qgp_trust_state_t *st,
                                 const uint8_t dummy_sig[QGP_SIG_LEN])
{
    blob_t full = jhex_of(vec, "full_deb");
    blob_t prefix = jhex_of(vec, "prefix");
    CHECK(full.p && prefix.p, "%s: hex missing", name);
    if (!full.p || !prefix.p) { blob_free(&full); blob_free(&prefix); return; }

    size_t plen = (size_t)jint(vec, "prefix_len");
    CHECK(prefix.n == plen, "%s: prefix_len", name);
    CHECK(qgp_deb_parse_unsigned(prefix.p, prefix.n) == QGP_OK, "%s: unsigned prefix parse", name);

    qgp_deb_sig_info_t info;
    uint8_t m[QGP_M_PKG_LEN];
    const uint8_t *pk = NULL;
    qgp_rc_t rc = qgp_deb_check(full.p, full.n, st, &info, m, &pk);
    CHECK(rc == QGP_OK, "%s: layout check %s", name, qgp_rc_str(rc));
    if (rc == QGP_OK) {
        CHECK(info.prefix_len == plen, "%s: parsed prefix_len", name);
        CHECK(memcmp(full.p, prefix.p, plen) == 0, "%s: prefix bytes", name);
        CHECK(eq_hex(m, sizeof(m), jstr(vec, "M_pkg_hex")), "%s: M_pkg bytes", name);
        CHECK(eq_hex(info.key_id, QGP_HASH_LEN, jstr(vec, "key_id")), "%s: key_id", name);
        /* independent recomputation from the prefix alone */
        uint8_t m2[QGP_M_PKG_LEN];
        CHECK(qgp_deb_m_pkg(info.key_id, prefix.p, prefix.n, m2) == QGP_OK &&
              memcmp(m, m2, sizeof(m)) == 0, "%s: M_pkg recompute", name);
        CHECK(eq_hex(full.p + plen, QGP_AR_HDR_LEN, jstr(vec, "qgp_sig_header_hex")),
              "%s: _qgp.sig header bytes", name);
        CHECK(memcmp(full.p + plen, QGP_DEB_SIG_HEADER, QGP_AR_HDR_LEN) == 0,
              "%s: QGP_DEB_SIG_HEADER", name);
        uint8_t member[QGP_MEMBER_LEN];
        qgp_deb_build_member(info.key_id, plen, dummy_sig, member);
        blob_t mem = jhex_of(vec, "qgp_sig_member");
        CHECK(mem.p && mem.n == QGP_MEMBER_LEN && memcmp(mem.p, member, QGP_MEMBER_LEN) == 0,
              "%s: member bytes (built)", name);
        CHECK(memcmp(full.p + plen + QGP_AR_HDR_LEN, member, QGP_MEMBER_LEN) == 0,
              "%s: member bytes (in file)", name);
        CHECK(full.n == plen + QGP_AR_HDR_LEN + QGP_MEMBER_LEN, "%s: file length", name);
        blob_free(&mem);
        /* the DUMMY signature is not ML-DSA-87: a real verifier must refuse */
        CHECK(qgp_deb_verify(full.p, full.n, st, NULL) == QGP_E_SIGNATURE,
              "%s: dummy signature must not verify", name);
    }
    blob_free(&full);
    blob_free(&prefix);
}

static void test_kat_packages(json_object *kat, const uint8_t dummy_sig[QGP_SIG_LEN])
{
    qgp_trust_state_t st;
    CHECK(load_kat_trust_state(kat, 2, &st) == 0, "trust_file_3 body parse");

    check_package_vector(jget(kat, "package"), "package", &st, dummy_sig);
    check_package_vector(jget(kat, "package_odd_data"), "package_odd_data", &st, dummy_sig);

    json_object *acc = jget(kat, "package_accept");
    size_t n_acc = json_object_array_length(acc);
    for (size_t i = 0; i < n_acc; i++) {
        json_object *v = json_object_array_get_idx(acc, i);
        const char *name = jstr(v, "name");
        blob_t full = jhex_of(v, "full_deb");
        qgp_deb_sig_info_t info;
        uint8_t m[QGP_M_PKG_LEN];
        qgp_rc_t rc = qgp_deb_check(full.p, full.n, &st, &info, m, NULL);
        CHECK(rc == QGP_OK, "%s: accept %s", name, qgp_rc_str(rc));
        CHECK(rc == QGP_OK && info.prefix_len == (size_t)jint(v, "prefix_len"), "%s: prefix_len", name);
        CHECK(rc == QGP_OK && eq_hex(m, sizeof(m), jstr(v, "M_pkg_hex")), "%s: M_pkg", name);
        blob_free(&full);
    }
    /* counts.package_accept = package + package_odd_data + package_accept[] */
    CHECK(jint(jget(kat, "counts"), "package_accept") == (int64_t)(2 + n_acc), "counts.package_accept");

    json_object *rej = jget(kat, "package_reject");
    size_t n_rej = json_object_array_length(rej);
    CHECK(jint(jget(kat, "counts"), "package_reject") == (int64_t)n_rej, "counts.package_reject");
    for (size_t i = 0; i < n_rej; i++) {
        json_object *v = json_object_array_get_idx(rej, i);
        const char *name = jstr(v, "name");
        const char *want = jstr(v, "expected_reason");
        blob_t b = jhex_of(v, "bytes");
        CHECK(b.p != NULL || jint(jget(v, "bytes"), "len") == 0, "%s: bytes hex", name);
        qgp_deb_sig_info_t info;
        uint8_t m[QGP_M_PKG_LEN];
        qgp_rc_t rc = qgp_deb_check(b.p ? b.p : (const uint8_t *)"", b.n, &st, &info, m, NULL);
        CHECK(rc != QGP_OK, "%s: must be refused", name);
        CHECK(strcmp(qgp_rc_str(rc), want) == 0, "%s: reason %s, oracle %s", name, qgp_rc_str(rc), want);
        CHECK(qgp_deb_verify(b.p ? b.p : (const uint8_t *)"", b.n, &st, NULL) != QGP_OK,
              "%s: verify must refuse", name);
        blob_free(&b);
    }
    qgp_trust_state_free(&st);
}

/* ---------------------------------------------- 3/4: trust vectors */

typedef struct {
    blob_t             file[3];
    qgp_trust_stored_t stored[3];
    int                loaded[3];
} kat_chain_t;

static void test_kat_trust(json_object *kat, const uint8_t dummy_sig[QGP_SIG_LEN], kat_chain_t *kc)
{
    json_object *chain = jget(kat, "trust_chain");
    CHECK(json_object_array_length(chain) == 3, "trust_chain length");
    for (size_t i = 0; i < 3; i++) {
        json_object *e = json_object_array_get_idx(chain, i);
        const char *name = jstr(e, "name");
        kc->file[i] = jhex_of(e, "file");
        qgp_trust_file_t tf;
        uint8_t m[QGP_M_TRUST_LEN];
        const uint8_t *pk = NULL;
        qgp_rc_t rc = qgp_trust_check(kc->file[i].p, kc->file[i].n,
                                      i == 0 ? NULL : &kc->stored[i - 1], &tf, m, &pk);
        CHECK(rc == QGP_OK, "%s: accept %s", name, qgp_rc_str(rc));
        if (rc == QGP_OK) {
            CHECK(eq_hex(m, sizeof(m), jstr(e, "M_trust_hex")), "%s: M_trust bytes", name);
            CHECK(eq_hex(m + 24, QGP_HASH_LEN, jstr(e, "prev_digest")), "%s: prev_digest", name);
            CHECK(tf.serial == (uint64_t)jint(e, "serial"), "%s: serial", name);
            CHECK(eq_hex(tf.signer, QGP_HASH_LEN, jstr(e, "signer_key_id")), "%s: signer", name);
            const char *body = jstr(e, "body");
            CHECK(body && tf.body_len == strlen(body) && memcmp(tf.body, body, tf.body_len) == 0,
                  "%s: body", name);
            uint8_t m2[QGP_M_TRUST_LEN];
            CHECK(qgp_trust_m_trust(tf.serial, m + 24, tf.signer, tf.body, tf.body_len, m2) == QGP_OK &&
                  memcmp(m, m2, sizeof(m)) == 0, "%s: M_trust recompute", name);
            qgp_trust_file_free(&tf);
            CHECK(qgp_trust_verify(kc->file[i].p, kc->file[i].n, i == 0 ? NULL : &kc->stored[i - 1],
                                   NULL) == QGP_E_SIGNATURE, "%s: dummy signature must not verify", name);
        }
        kc->loaded[i] = qgp_trust_stored_load(kc->file[i].p, kc->file[i].n, &kc->stored[i]) == QGP_OK;
        CHECK(kc->loaded[i], "%s: load as stored", name);
    }

    /* trust_accept extras */
    json_object *ta = jget(kat, "trust_accept");
    json_object *keys = jget(jget(jget(kat, "dummy"), "public_keys"), "keys");
    for (size_t i = 0; i < json_object_array_length(ta); i++) {
        json_object *e = json_object_array_get_idx(ta, i);
        const char *name = jstr(e, "name");
        blob_t f = jhex_of(e, "file");
        const qgp_trust_stored_t *stored = &kc->stored[2];
        if (strcmp(name, "body_exactly_64KiB_bootstrap") == 0) {
            /* hex withheld (limit 0): rebuild from the construction and the dummy keys */
            const char *lines[13];
            char *own[13] = { 0 };
            size_t fixed = 0;
            for (int k = 1; k <= 12; k++) {
                char kn[8];
                snprintf(kn, sizeof(kn), "K%d", k);
                json_object *ke = jget(keys, kn);
                size_t ln = 4 + 128 + 1 + 5184;
                own[k - 1] = malloc(ln + 1);
                snprintf(own[k - 1], ln + 1, "key %s %s", jstr(ke, "fp"), jstr(ke, "pk_hex"));
                lines[k - 1] = own[k - 1];
                fixed += ln + 1;
            }
            size_t name_len = QGP_BODY_MAX - fixed - strlen("floor  1.0\n");
            own[12] = malloc(6 + name_len + 4 + 1);
            memcpy(own[12], "floor ", 6);
            memset(own[12] + 6, 'a', name_len);
            memcpy(own[12] + 6 + name_len, " 1.0", 5);
            lines[12] = own[12];
            blob_t body = body_of(lines, 13);
            char h[2 * QGP_HASH_LEN + 1];
            sha3_hex(body.p, body.n, h);
            CHECK(body.n == QGP_BODY_MAX && strcmp(h, jstr(e, "body_sha3_512")) == 0,
                  "%s: rebuilt body", name);
            blob_t k1 = hex_blob(jstr(jget(keys, "K1"), "fp"));
            f = build_trust_file(1, k1.p, body.p, body.n, dummy_sig);
            sha3_hex(f.p, f.n, h);
            CHECK(strcmp(h, jstr(jget(e, "file"), "sha3_512")) == 0, "%s: rebuilt file digest", name);
            blob_free(&k1);
            blob_free(&body);
            for (int k = 0; k < 13; k++)
                free(own[k]);
            stored = NULL;
        }
        qgp_trust_file_t tf;
        uint8_t m[QGP_M_TRUST_LEN];
        qgp_rc_t rc = qgp_trust_check(f.p, f.n, stored, &tf, m, NULL);
        CHECK(rc == QGP_OK, "%s: accept %s", name, qgp_rc_str(rc));
        CHECK(rc == QGP_OK && eq_hex(m, sizeof(m), jstr(e, "M_trust_hex")), "%s: M_trust", name);
        if (rc == QGP_OK)
            qgp_trust_file_free(&tf);
        blob_free(&f);
    }

    /* trust rejects */
    json_object *tr = jget(kat, "trust_reject");
    for (size_t i = 0; i < json_object_array_length(tr); i++) {
        json_object *e = json_object_array_get_idx(tr, i);
        const char *name = jstr(e, "name");
        const char *want = jstr(e, "expected_reason");
        const char *sn = jstr(e, "stored_state");
        const qgp_trust_stored_t *stored = NULL;
        if (strcmp(sn, "trust_file_1") == 0) stored = &kc->stored[0];
        else if (strcmp(sn, "trust_file_2") == 0) stored = &kc->stored[1];
        else if (strcmp(sn, "trust_file_3") == 0) stored = &kc->stored[2];

        if (strncmp(name, "prev_digest_", 12) == 0) {
            /* layout accepts; the verifier's preimage is the chain's M_trust */
            size_t fi = strcmp(name, "prev_digest_mismatch") == 0 ? 2 : 1;
            qgp_trust_file_t tf;
            uint8_t m[QGP_M_TRUST_LEN];
            qgp_rc_t rc = qgp_trust_check(kc->file[fi].p, kc->file[fi].n, stored, &tf, m, NULL);
            CHECK(rc == QGP_OK, "%s: layout accepts", name);
            CHECK(rc == QGP_OK && eq_hex(m, sizeof(m), jstr(e, "verifier_preimage_hex")),
                  "%s: verifier preimage", name);
            CHECK(!eq_hex(m, sizeof(m), jstr(e, "signer_preimage_hex")),
                  "%s: signer preimage differs", name);
            if (rc == QGP_OK)
                qgp_trust_file_free(&tf);
            continue;
        }

        blob_t f = jhex_of(e, "file");
        if (strcmp(name, "body_over_64KiB") == 0) {
            /* hex withheld: one byte over the boundary body; the size check
             * fires on body_len before the body is looked at, so any bytes do */
            size_t over = QGP_BODY_MAX + 1;
            uint8_t *body = malloc(over);
            memset(body, 'a', over);
            uint8_t signer[QGP_HASH_LEN] = { 0 };
            f = build_trust_file(1, signer, body, over, dummy_sig);
            free(body);
        }
        CHECK(f.p != NULL, "%s: file bytes", name);
        qgp_trust_file_t tf;
        uint8_t m[QGP_M_TRUST_LEN];
        qgp_rc_t rc = qgp_trust_check(f.p, f.n, stored, &tf, m, NULL);
        CHECK(rc != QGP_OK, "%s: must be refused", name);
        CHECK(strcmp(qgp_rc_str(rc), want) == 0, "%s: reason %s, oracle %s", name, qgp_rc_str(rc), want);
        if (rc == QGP_OK)
            qgp_trust_file_free(&tf);
        blob_free(&f);
    }
    CHECK(jint(jget(kat, "counts"), "trust_reject") == (int64_t)json_object_array_length(tr),
          "counts.trust_reject");
}

/* ------------------------------------------- 5: real-key packages + files */

typedef struct {
    uint8_t pk[QGP_PK_LEN];
    uint8_t sk[QGP_SK_LEN];
    uint8_t fp[QGP_HASH_LEN];
} tkey_t;

static int make_key(tkey_t *k)
{
    if (qgp_dsa87_keypair(k->pk, k->sk) != 0)
        return -1;
    return qgp_sha3_512(k->pk, QGP_PK_LEN, k->fp);
}

static void test_real_packages(json_object *kat, const tkey_t *a, const tkey_t *b)
{
    const char *vecs[] = { "package", "package_odd_data" };
    char *la = key_line(a->pk), *lb = key_line(b->pk), *ra = revoked_line(a->pk);
    const char *l1[] = { la };
    const char *l2[] = { lb, ra };
    blob_t body1 = body_of(l1, 1), body2 = body_of(l2, 2);
    qgp_trust_state_t st_a, st_revoked;
    CHECK(qgp_trust_parse_body(body1.p, body1.n, &st_a) == QGP_OK, "state {A}");
    CHECK(qgp_trust_parse_body(body2.p, body2.n, &st_revoked) == QGP_OK, "state {B, revoked A}");

    for (size_t v = 0; v < 2; v++) {
        blob_t prefix = jhex_of(jget(kat, vecs[v]), "prefix");
        uint8_t *sd = NULL;
        size_t sn = 0;
        qgp_rc_t rc = qgp_deb_sign(prefix.p, prefix.n, a->sk, a->pk, &sd, &sn);
        CHECK(rc == QGP_OK, "%s: deb-sign %s", vecs[v], qgp_rc_str(rc));
        if (rc == QGP_OK) {
            CHECK(sn == prefix.n + QGP_AR_HDR_LEN + QGP_MEMBER_LEN, "%s: signed length", vecs[v]);
            CHECK(memcmp(sd, prefix.p, prefix.n) == 0, "%s: prefix unchanged", vecs[v]);
            CHECK(memcmp(sd + prefix.n, QGP_DEB_SIG_HEADER, QGP_AR_HDR_LEN) == 0, "%s: header", vecs[v]);
            const uint8_t *mem = sd + prefix.n + QGP_AR_HDR_LEN;
            CHECK(mem[0] == 0x01 && memcmp(mem + 1, a->fp, QGP_HASH_LEN) == 0 &&
                  qgp_be64_get(mem + 65) == prefix.n && qgp_be16_get(mem + 73) == QGP_SIG_LEN,
                  "%s: member fields", vecs[v]);
            qgp_deb_sig_info_t info;
            CHECK(qgp_deb_verify(sd, sn, &st_a, &info) == QGP_OK, "%s: verify", vecs[v]);
            CHECK(qgp_deb_verify(sd, sn, &st_revoked, NULL) == QGP_E_REVOKED_KEY, "%s: revoked", vecs[v]);
            uint8_t *sd2 = NULL;
            size_t sn2 = 0;
            CHECK(qgp_deb_sign(sd, sn, a->sk, a->pk, &sd2, &sn2) == QGP_E_EXTRA_MEMBER,
                  "%s: re-sign refused", vecs[v]);
            free(sd2);
            /* a byte inside a member payload (not a header field): signature must fail */
            sd[prefix.n - 2] ^= 0x01;
            CHECK(qgp_deb_verify(sd, sn, &st_a, NULL) == QGP_E_SIGNATURE, "%s: tampered prefix", vecs[v]);
            sd[prefix.n - 2] ^= 0x01;
            sd[sn - 1] ^= 0x01;
            CHECK(qgp_deb_verify(sd, sn, &st_a, NULL) == QGP_E_SIGNATURE, "%s: tampered sig", vecs[v]);
            sd[sn - 1] ^= 0x01;
            CHECK(qgp_deb_verify(sd, sn, &st_a, NULL) == QGP_OK, "%s: restored", vecs[v]);
        }
        free(sd);
        sd = NULL;
        CHECK(qgp_deb_sign(prefix.p, prefix.n, a->sk, b->pk, &sd, &sn) == QGP_E_KEY_MISMATCH,
              "%s: sk/pk mismatch refused", vecs[v]);
        free(sd);
        blob_free(&prefix);
    }

    /* file signature (deviation: not in the approved bytes) */
    const uint8_t data[] = "qgp file signature test\n";
    uint8_t sig[QGP_SIG_LEN], m[QGP_M_FILE_LEN];
    CHECK(qgp_filesig_msg_v1_UNAPPROVED(data, sizeof(data) - 1, m) == QGP_OK, "file msg");
    {
        static const uint8_t tag[16] = { 'N','D','S','.','Q','G','P','F','I','L','E','.','v','1',0,0 };
        uint8_t h[QGP_HASH_LEN];
        qgp_sha3_512(data, sizeof(data) - 1, h);
        CHECK(memcmp(m, tag, 16) == 0 && qgp_be64_get(m + 16) == sizeof(data) - 1 &&
              memcmp(m + 24, h, QGP_HASH_LEN) == 0, "file msg layout");
    }
    CHECK(qgp_filesig_sign_v1_UNAPPROVED(data, sizeof(data) - 1, a->sk, a->pk, sig) == QGP_OK, "file sign");
    CHECK(qgp_filesig_verify_v1_UNAPPROVED(data, sizeof(data) - 1, sig, sizeof(sig), a->pk) == QGP_OK,
          "file verify");
    CHECK(qgp_filesig_verify_v1_UNAPPROVED(data, sizeof(data) - 2, sig, sizeof(sig), a->pk) == QGP_E_SIGNATURE,
          "file verify: truncated data");
    CHECK(qgp_filesig_verify_v1_UNAPPROVED(data, sizeof(data) - 1, sig, sizeof(sig), b->pk) == QGP_E_SIGNATURE,
          "file verify: wrong key");
    CHECK(qgp_filesig_verify_v1_UNAPPROVED(data, sizeof(data) - 1, sig, sizeof(sig) - 1, a->pk) == QGP_E_SIG_LEN,
          "file verify: short signature");
    CHECK(qgp_filesig_sign_v1_UNAPPROVED(data, sizeof(data) - 1, a->sk, b->pk, sig) == QGP_E_KEY_MISMATCH,
          "file sign: sk/pk mismatch");

    qgp_trust_state_free(&st_a);
    qgp_trust_state_free(&st_revoked);
    blob_free(&body1);
    blob_free(&body2);
    free(la);
    free(lb);
    free(ra);
}

/* ----------------------------------------- 6: real-key trust chain */

/* Sign an arbitrary M_trust (used to build files the maker would refuse). */
static blob_t sign_trust_raw(uint64_t serial, const uint8_t prev[QGP_HASH_LEN], const tkey_t *k,
                             const blob_t *body)
{
    uint8_t m[QGP_M_TRUST_LEN], sig[QGP_SIG_LEN];
    size_t sl = 0;
    blob_t f = { NULL, 0 };
    if (qgp_trust_m_trust(serial, prev, k->fp, body->p, body->n, m) != QGP_OK)
        return f;
    if (qgp_dsa87_sign(sig, &sl, m, sizeof(m), k->sk) != 0 || sl != QGP_SIG_LEN)
        return f;
    return build_trust_file(serial, k->fp, body->p, body->n, sig);
}

static void test_real_trust_chain(const tkey_t *a, const tkey_t *b, const tkey_t *c)
{
    char *ka = key_line(a->pk), *kb = key_line(b->pk), *kc = key_line(c->pk);
    char *ra = revoked_line(a->pk), *rb = revoked_line(b->pk);
    const char *l1[] = { ka };
    const char *l2[] = { ka, kb, "floor qgp-kat 1.0" };
    const char *l3[] = { kb, ra, "floor qgp-kat 1.1" };
    blob_t b1 = body_of(l1, 1), b2 = body_of(l2, 3), b3 = body_of(l3, 3);

    uint8_t *f1 = NULL, *f2 = NULL, *f3 = NULL;
    size_t n1 = 0, n2 = 0, n3 = 0;
    qgp_trust_stored_t s1, s2, s3;
    memset(&s1, 0, sizeof(s1)); memset(&s2, 0, sizeof(s2)); memset(&s3, 0, sizeof(s3));

    CHECK(qgp_trust_make(b1.p, b1.n, 1, NULL, a->sk, a->pk, &f1, &n1) == QGP_OK, "make f1 (bootstrap)");
    CHECK(qgp_trust_verify(f1, n1, NULL, NULL) == QGP_OK, "accept f1 (bootstrap)");
    CHECK(qgp_trust_stored_load(f1, n1, &s1) == QGP_OK, "store f1");
    CHECK(qgp_trust_make(b2.p, b2.n, 2, &s1, a->sk, a->pk, &f2, &n2) == QGP_OK, "make f2 (adds B)");
    CHECK(qgp_trust_verify(f2, n2, &s1, NULL) == QGP_OK, "accept f2");
    CHECK(qgp_trust_stored_load(f2, n2, &s2) == QGP_OK, "store f2");
    CHECK(qgp_trust_make(b3.p, b3.n, 3, &s2, b->sk, b->pk, &f3, &n3) == QGP_OK, "make f3 (B revokes A)");
    CHECK(qgp_trust_verify(f3, n3, &s2, NULL) == QGP_OK, "accept f3 (rotation)");
    CHECK(qgp_trust_stored_load(f3, n3, &s3) == QGP_OK, "store f3");

    /* chain order matters */
    CHECK(qgp_trust_verify(f3, n3, &s1, NULL) == QGP_E_SIGNER_NOT_TRUSTED, "f3 against f1: B unknown");
    CHECK(qgp_trust_verify(f2, n2, &s2, NULL) == QGP_E_SERIAL_NOT_INCREASING, "replay f2");
    CHECK(qgp_trust_verify(f2, n2, NULL, NULL) == QGP_E_SIGNATURE,
          "f2 as bootstrap: layout passes (A in own body), prev_digest zeros != signed prev");
    CHECK(qgp_trust_verify(f3, n3, NULL, NULL) == QGP_E_SIGNATURE,
          "f3 as bootstrap: prev_digest zeros != signed prev");

    /* prev_digest mismatch: B signs serial 3 chained to f1 instead of f2 */
    uint8_t prev1[QGP_HASH_LEN], zeros[QGP_HASH_LEN] = { 0 };
    qgp_sha3_512(f1, n1, prev1);
    blob_t bad = sign_trust_raw(3, prev1, b, &b3);
    {
        qgp_trust_file_t tf;
        uint8_t m[QGP_M_TRUST_LEN];
        qgp_rc_t rc = qgp_trust_check(bad.p, bad.n, &s2, &tf, m, NULL);
        CHECK(rc == QGP_OK, "prev mismatch: layout accepts");
        if (rc == QGP_OK)
            qgp_trust_file_free(&tf);
    }
    CHECK(qgp_trust_verify(bad.p, bad.n, &s2, NULL) == QGP_E_SIGNATURE, "prev mismatch refused");
    blob_free(&bad);
    bad = sign_trust_raw(2, zeros, a, &b2);
    CHECK(qgp_trust_verify(bad.p, bad.n, &s1, NULL) == QGP_E_SIGNATURE, "zeros prev on non-first refused");
    blob_free(&bad);

    /* revoked signer: A signs serial 4 against s3 */
    uint8_t *fx = NULL;
    size_t nx = 0;
    CHECK(qgp_trust_make(b3.p, b3.n, 4, &s3, a->sk, a->pk, &fx, &nx) == QGP_E_SIGNER_REVOKED,
          "maker refuses a revoked signer");
    free(fx); fx = NULL;
    uint8_t prev3[QGP_HASH_LEN];
    qgp_sha3_512(f3, n3, prev3);
    bad = sign_trust_raw(4, prev3, a, &b3);
    CHECK(qgp_trust_verify(bad.p, bad.n, &s3, NULL) == QGP_E_SIGNER_REVOKED, "revoked signer refused");
    blob_free(&bad);

    /* floors: Debian comparison, not dotted integers */
    const char *lo[] = { kb, ra, "floor qgp-kat 1.1~rc1" };
    blob_t blo = body_of(lo, 3);
    bad = sign_trust_raw(4, prev3, b, &blo);
    CHECK(qgp_trust_verify(bad.p, bad.n, &s3, NULL) == QGP_E_FLOOR_LOWERED, "1.1~rc1 < 1.1 lowered");
    blob_free(&bad);
    const char *hi[] = { kb, ra, "floor qgp-kat 1:0.1" };
    blob_t bhi = body_of(hi, 3);
    CHECK(qgp_trust_make(bhi.p, bhi.n, 4, &s3, b->sk, b->pk, &fx, &nx) == QGP_OK, "epoch raises the floor");
    free(fx); fx = NULL;
    const char *nofl[] = { kb, ra };
    blob_t bnf = body_of(nofl, 2);
    CHECK(qgp_trust_make(bnf.p, bnf.n, 4, &s3, b->sk, b->pk, &fx, &nx) == QGP_E_FLOOR_DROPPED, "floor dropped");
    free(fx); fx = NULL;
    const char *norev[] = { kb, "floor qgp-kat 1.1" };
    blob_t bnr = body_of(norev, 2);
    CHECK(qgp_trust_make(bnr.p, bnr.n, 4, &s3, b->sk, b->pk, &fx, &nx) == QGP_E_REVOCATION_DROPPED,
          "revocation dropped");
    free(fx); fx = NULL;
    /* self-revocation (oracle R-SIGNER): B revokes itself, C remains */
    const char *self[] = { kc, ra, rb, "floor qgp-kat 1.1" };
    blob_t bself = body_of(self, 4);
    CHECK(qgp_trust_make(bself.p, bself.n, 4, &s3, b->sk, b->pk, &fx, &nx) == QGP_OK,
          "self-revocation accepted (R-SIGNER)");
    free(fx); fx = NULL;
    /* wrong pk for sk */
    CHECK(qgp_trust_make(bself.p, bself.n, 4, &s3, b->sk, c->pk, &fx, &nx) == QGP_E_KEY_MISMATCH,
          "maker: sk/pk mismatch");
    free(fx); fx = NULL;

    /* body tamper keeps the layout canonical, breaks the signature */
    if (f2 && n2 > 0) {
        uint8_t *t = malloc(n2);
        memcpy(t, f2, n2);
        uint8_t *pos = memmem(t + QGP_TRUST_FIXED, n2 - QGP_TRUST_FIXED, "qgp-kat 1.0", 11);
        CHECK(pos != NULL, "f2 floor present");
        if (pos) {
            pos[10] = '5';   /* 1.0 -> 1.5 */
            CHECK(qgp_trust_verify(t, n2, &s1, NULL) == QGP_E_SIGNATURE, "tampered body refused");
        }
        free(t);
    }

    /* state directory round trip */
    char dir[] = "/tmp/qgp-test-XXXXXX";
    if (mkdtemp(dir)) {
        qgp_trust_stored_t ld;
        CHECK(qgp_state_load_trust(dir, &ld) == QGP_E_NO_TRUST_STATE, "empty dir: no state");
        CHECK(qgp_state_store_trust(dir, f3, n3) == QGP_OK, "store trust");
        CHECK(qgp_state_load_trust(dir, &ld) == QGP_OK && ld.file_len == n3 &&
              memcmp(ld.file, f3, n3) == 0 && ld.parsed.serial == 3, "load trust");
        qgp_trust_stored_free(&ld);
        qgp_accepted_list_t acc, acc2;
        CHECK(qgp_state_load_accepted(dir, &acc) == QGP_OK && acc.n == 0, "no accepted-versions yet");
        CHECK(qgp_accepted_set(&acc, "zeta", "1.0") == QGP_OK &&
              qgp_accepted_set(&acc, "alpha", "2:1.0-3") == QGP_OK &&
              qgp_accepted_set(&acc, "zeta", "1.1") == QGP_OK, "accepted set");
        CHECK(qgp_state_store_accepted(dir, &acc) == QGP_OK, "store accepted");
        CHECK(qgp_state_load_accepted(dir, &acc2) == QGP_OK && acc2.n == 2 &&
              strcmp(acc2.v[0].pkg, "alpha") == 0 && strcmp(qgp_accepted_get(&acc2, "zeta"), "1.1") == 0,
              "load accepted");
        qgp_accepted_free(&acc);
        qgp_accepted_free(&acc2);
        char p[PATH_MAX];
        snprintf(p, sizeof(p), "%s/%s", dir, QGP_STATE_TRUST_FILE);
        unlink(p);
        snprintf(p, sizeof(p), "%s/%s", dir, QGP_STATE_ACCEPTED_FILE);
        unlink(p);
        rmdir(dir);
    } else {
        CHECK(0, "mkdtemp");
    }

    const uint8_t unsorted[] = "zeta 1.0\nalpha 1.0\n";
    qgp_accepted_list_t bad_acc;
    CHECK(qgp_accepted_parse(unsorted, sizeof(unsorted) - 1, &bad_acc) == QGP_E_STATE_CORRUPT,
          "accepted-versions unsorted refused");

    qgp_trust_stored_free(&s1);
    qgp_trust_stored_free(&s2);
    qgp_trust_stored_free(&s3);
    free(f1); free(f2); free(f3);
    blob_free(&b1); blob_free(&b2); blob_free(&b3);
    blob_free(&blo); blob_free(&bhi); blob_free(&bnf); blob_free(&bnr); blob_free(&bself);
    free(ka); free(kb); free(kc); free(ra); free(rb);
}

/* --------------------------------------- 7: deb-version(7), policy, fields */

static int vcmp(const char *a, const char *b)
{
    int c = 0;
    if (qgp_debver_cmp(a, strlen(a), b, strlen(b), &c) != QGP_OK)
        return 99;
    return c < 0 ? -1 : (c > 0 ? 1 : 0);
}

static void test_debver(void)
{
    /* deb-version(7): "the following parts are in sorted order: '~~', '~~a',
     * '~', the empty part, 'a'" — as suffixes of the same upstream version. */
    const char *order[] = { "1.0~~", "1.0~~a", "1.0~", "1.0", "1.0a" };
    for (size_t i = 0; i < 5; i++)
        for (size_t j = 0; j < 5; j++) {
            int want = i < j ? -1 : (i > j ? 1 : 0);
            CHECK(vcmp(order[i], order[j]) == want, "order %s vs %s", order[i], order[j]);
        }

    struct { const char *a, *b; int want; } cases[] = {
        /* epoch: omitted = 0, compared first */
        { "1:0.1",      "9.9",        1 },
        { "0:1.0",      "1.0",        0 },
        { "2:1.0",      "10:0.1",    -1 },
        /* digit runs compared numerically */
        { "1.10",       "1.9",        1 },
        { "1.010",      "1.10",       0 },
        { "1.0",        "1.00",       0 },
        { "1.2.3",      "1.2.10",    -1 },
        { "12345678901234567890.1", "12345678901234567890.2", -1 },  /* > 64-bit digit run */
        { "99999999999999999999",   "100000000000000000000",  -1 },
        /* letters sort earlier than all non-letters */
        { "1.0a",       "1.0+",      -1 },
        { "1.0a",       "1.0.",      -1 },
        { "1.0+",       "1.0.",      -1 },   /* non-letters in ASCII order: '+' 0x2b < '.' 0x2e */
        { "1.0A",       "1.0a",      -1 },   /* letters in ASCII order */
        /* tilde sorts before anything, even the end of a part */
        { "1.0~rc1",    "1.0",       -1 },
        { "1.0~rc1",    "1.0~rc2",   -1 },
        { "1.0~~",      "1.0~",      -1 },
        /* revision: split at the LAST hyphen, compared after upstream */
        { "1.0-1",      "1.0-2",     -1 },
        { "1.0-10",     "1.0-9",      1 },
        { "1.0",        "1.0-1",     -1 },   /* absence earlier than presence */
        { "1.0",        "1.0-0",      0 },   /* empty digit run counts as zero */
        { "2.0-1~bpo1", "2.0-1",     -1 },
        { "1-2-3",      "1-2-4",     -1 },   /* upstream "1-2" */
        { "1.0-1",      "1.0.1-1",   -1 },
        { "1:2:3",      "1:2:4",     -1 },   /* colon allowed in upstream with an epoch */
    };
    for (size_t i = 0; i < sizeof(cases) / sizeof(cases[0]); i++) {
        CHECK(vcmp(cases[i].a, cases[i].b) == cases[i].want, "cmp %s %s", cases[i].a, cases[i].b);
        CHECK(vcmp(cases[i].b, cases[i].a) == -cases[i].want, "cmp %s %s (reversed)", cases[i].b, cases[i].a);
    }

    const char *invalid[] = {
        "", "a1.0", "~1", "1.0-", ":1.0", "1:", "a:1.0", "1.0_1", "1.0 1", "1.0-a_b",
        "1:2.0-3:4", "1.0:1", "1.0-1:2", "1234567890:1.0", "-1", "1.0\n"
    };
    for (size_t i = 0; i < sizeof(invalid) / sizeof(invalid[0]); i++)
        CHECK(qgp_debver_check(invalid[i], strlen(invalid[i])) == QGP_E_BAD_VERSION,
              "invalid version '%s'", invalid[i]);
    const char *valid[] = { "0", "1.0", "1:1.0", "1.0-1", "1.0+dfsg-1~deb12u1", "2:1.0~rc1+git.1-0.1", "1-2-3" };
    for (size_t i = 0; i < sizeof(valid) / sizeof(valid[0]); i++)
        CHECK(qgp_debver_check(valid[i], strlen(valid[i])) == QGP_OK, "valid version '%s'", valid[i]);

    /* package names, deb-src-control(5) */
    CHECK(qgp_debpkg_name_valid("nodus", 5) && qgp_debpkg_name_valid("libc6", 5) &&
          qgp_debpkg_name_valid("g++-12", 6) && qgp_debpkg_name_valid("0ad", 3), "valid names");
    CHECK(!qgp_debpkg_name_valid("a", 1) && !qgp_debpkg_name_valid("Nodus", 5) &&
          !qgp_debpkg_name_valid("-x", 2) && !qgp_debpkg_name_valid("a_b", 3) &&
          !qgp_debpkg_name_valid(".ab", 3), "invalid names");
}

static void test_policy_and_fields(void)
{
    /* a state needs a key: use a dummy one (fp = SHA3(pk)) */
    uint8_t pk[QGP_PK_LEN];
    for (size_t i = 0; i < sizeof(pk); i++) pk[i] = (uint8_t)i;
    char *kl = key_line(pk);
    const char *lines[] = { kl, "floor nodus 0.23.18" };
    blob_t body = body_of(lines, 2);
    qgp_trust_state_t st;
    CHECK(qgp_trust_parse_body(body.p, body.n, &st) == QGP_OK, "policy state");

    qgp_accepted_list_t acc;
    memset(&acc, 0, sizeof(acc));
    int rec = 0;
    CHECK(qgp_policy_check(&st, &acc, "nodus", "0.23.17", 0, &rec) == QGP_E_BELOW_FLOOR, "below floor");
    CHECK(qgp_policy_check(&st, &acc, "nodus", "0.23.17", 1, &rec) == QGP_E_BELOW_FLOOR,
          "floor has no override");
    CHECK(qgp_policy_check(&st, &acc, "nodus", "0.23.18", 0, &rec) == QGP_OK && rec == 1, "at floor, record");
    CHECK(qgp_accepted_set(&acc, "nodus", "0.23.20") == QGP_OK, "record 0.23.20");
    CHECK(qgp_policy_check(&st, &acc, "nodus", "0.23.19", 0, &rec) == QGP_E_DOWNGRADE, "downgrade refused");
    CHECK(qgp_policy_check(&st, &acc, "nodus", "0.23.19", 1, &rec) == QGP_OK && rec == 0,
          "downgrade override, record kept");
    CHECK(qgp_policy_check(&st, &acc, "nodus", "0.23.20", 0, &rec) == QGP_OK && rec == 0, "reinstall same");
    CHECK(qgp_policy_check(&st, &acc, "nodus", "0.23.20~rc1", 0, &rec) == QGP_E_DOWNGRADE, "~rc below release");
    CHECK(qgp_policy_check(&st, &acc, "nodus", "0.23.20-1", 0, &rec) == QGP_OK && rec == 1, "revision raises");
    CHECK(qgp_policy_check(&st, &acc, "qgp", "0.1.0", 0, &rec) == QGP_OK && rec == 1, "no floor, new package");
    qgp_accepted_free(&acc);
    qgp_trust_state_free(&st);
    blob_free(&body);
    free(kl);

    qgp_control_fields_t f;
    const char ok1[] = "Package: nodus\nVersion: 1:0.23.18-1\nArchitecture: amd64\n";
    CHECK(qgp_control_fields_parse(ok1, sizeof(ok1) - 1, &f) == QGP_OK &&
          strcmp(f.pkg, "nodus") == 0 && strcmp(f.ver, "1:0.23.18-1") == 0 && strcmp(f.arch, "amd64") == 0,
          "fields parse");
    const char ok2[] = "Version: 1.0\nArchitecture: all\nPackage: qgp\n";
    CHECK(qgp_control_fields_parse(ok2, sizeof(ok2) - 1, &f) == QGP_OK, "fields any order");
    const char missing[] = "Package: qgp\nVersion: 1.0\n";
    CHECK(qgp_control_fields_parse(missing, sizeof(missing) - 1, &f) == QGP_E_BAD_CONTROL_FIELDS, "missing field");
    const char dup[] = "Package: qgp\nPackage: qgp\nVersion: 1.0\nArchitecture: all\n";
    CHECK(qgp_control_fields_parse(dup, sizeof(dup) - 1, &f) == QGP_E_BAD_CONTROL_FIELDS, "duplicate field");
    const char badname[] = "Package: QGP\nVersion: 1.0\nArchitecture: all\n";
    CHECK(qgp_control_fields_parse(badname, sizeof(badname) - 1, &f) == QGP_E_BAD_PACKAGE_NAME, "bad name");
    const char badver[] = "Package: qgp\nVersion: x1.0\nArchitecture: all\n";
    CHECK(qgp_control_fields_parse(badver, sizeof(badver) - 1, &f) == QGP_E_BAD_VERSION, "bad version");
    const char cont[] = "Package: qgp\n more\nVersion: 1.0\nArchitecture: all\n";
    CHECK(qgp_control_fields_parse(cont, sizeof(cont) - 1, &f) == QGP_E_BAD_CONTROL_FIELDS, "continuation");
    const char nolf[] = "Package: qgp\nVersion: 1.0\nArchitecture: all";
    CHECK(qgp_control_fields_parse(nolf, sizeof(nolf) - 1, &f) == QGP_E_BAD_CONTROL_FIELDS, "no final LF");
}

int main(void)
{
    json_object *kat = json_object_from_file(QGP_KAT_PATH);
    if (!kat) {
        QGP_LOG_ERROR(LOG_TAG, "cannot read %s", QGP_KAT_PATH);
        return 1;
    }
    blob_t dummy_sig = hex_blob(jstr(jget(jget(kat, "dummy"), "signature"), "hex"));
    CHECK(dummy_sig.n == QGP_SIG_LEN, "dummy signature length");
    CHECK(eq_hex(QGP_DEB_SIG_HEADER, QGP_AR_HDR_LEN, jstr(jget(kat, "constants"), "qgp_sig_ar_header_hex")),
          "constants: _qgp.sig header");

    if (dummy_sig.n == QGP_SIG_LEN) {
        test_kat_packages(kat, dummy_sig.p);
        kat_chain_t kc;
        memset(&kc, 0, sizeof(kc));
        test_kat_trust(kat, dummy_sig.p, &kc);
        for (int i = 0; i < 3; i++) {
            if (kc.loaded[i])
                qgp_trust_stored_free(&kc.stored[i]);
            blob_free(&kc.file[i]);
        }
    }

    tkey_t *keys = calloc(3, sizeof(*keys));
    CHECK(keys && make_key(&keys[0]) == 0 && make_key(&keys[1]) == 0 && make_key(&keys[2]) == 0,
          "keypair generation");
    if (keys) {
        test_real_packages(kat, &keys[0], &keys[1]);
        test_real_trust_chain(&keys[0], &keys[1], &keys[2]);
        free(keys);
    }
    test_debver();
    test_policy_and_fields();

    blob_free(&dummy_sig);
    json_object_put(kat);
    QGP_LOG_INFO(LOG_TAG, "%d passed, %d failed", g_pass, g_fail);
    return g_fail == 0 ? 0 : 1;
}
