#!/bin/bash
# Nodus v5 Build & Deploy Script
#
# Builds the Nodus v5 DHT server and installs it.
#
# Usage:
#   ./build-nodus-v5.sh           # Build + install + restart service
#   ./build-nodus-v5.sh --debug   # Build with AddressSanitizer
#   ./build-nodus-v5.sh --help    # Show help

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
NODUS_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
MONOREPO_ROOT="$(cd "$NODUS_DIR/.." && pwd)"

INSTALL_DIR="/usr/local/bin"
DATA_DIR="/var/lib/nodus"
CONFIG_FILE="/etc/nodus-v5.conf"
SERVICE_NAME="nodus-v5"

# Parse arguments
DEBUG_BUILD=0
BUILD_TYPE="Release"

for arg in "$@"; do
    case $arg in
        --debug)
            DEBUG_BUILD=1
            BUILD_TYPE="Debug"
            SERVICE_NAME="nodus-v5-debug"
            ;;
        --help|-h)
            echo "Nodus v5 Build & Deploy Script"
            echo ""
            echo "Usage: $0 [OPTIONS]"
            echo ""
            echo "Options:"
            echo "  --debug     Build with AddressSanitizer (separate service)"
            echo "  --help      Show this help"
            echo ""
            echo "First-time install:"
            echo "  - Creates ${DATA_DIR}/{data,identity}"
            echo "  - Copies config to ${CONFIG_FILE}"
            echo "  - Installs binary to ${INSTALL_DIR}/nodus-server"
            echo "  - Installs and starts systemd service"
            echo ""
            echo "Update:"
            echo "  - Pulls latest code"
            echo "  - Rebuilds nodus-server"
            echo "  - Restarts service"
            exit 0
            ;;
    esac
done

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

echo -e "${GREEN}=== Nodus v5 Build Script (${BUILD_TYPE}) ===${NC}"
echo ""

# Check dependencies
check_deps() {
    local missing=()
    command -v cmake >/dev/null 2>&1 || missing+=("cmake")
    command -v make  >/dev/null 2>&1 || missing+=("make")
    command -v git   >/dev/null 2>&1 || missing+=("git")

    # Check dev libraries
    [ -f /usr/include/openssl/evp.h ] || missing+=("libssl-dev")
    [ -f /usr/include/sqlite3.h ]     || missing+=("libsqlite3-dev")

    if [ ${#missing[@]} -ne 0 ]; then
        echo -e "${RED}Missing dependencies: ${missing[*]}${NC}"
        echo "Install with: sudo apt install build-essential cmake git libssl-dev libsqlite3-dev libjson-c-dev"
        exit 1
    fi
}

# Pull latest code
pull_latest() {
    echo -e "${YELLOW}Pulling latest code...${NC}"
    cd "$MONOREPO_ROOT"
    git pull --no-rebase origin main 2>/dev/null || true
    COMMIT=$(git log --oneline -1)
    echo -e "${GREEN}Commit: $COMMIT${NC}"
    echo ""
}

# Build nodus-server
build_nodus() {
    echo -e "${YELLOW}Building nodus-server (${BUILD_TYPE})...${NC}"

    BUILD_DIR="$NODUS_DIR/build"
    mkdir -p "$BUILD_DIR"
    cd "$BUILD_DIR"

    if [ $DEBUG_BUILD -eq 1 ]; then
        cmake -DCMAKE_BUILD_TYPE=Debug \
              -DCMAKE_C_FLAGS="-fsanitize=address -fno-omit-frame-pointer -g" \
              -DCMAKE_EXE_LINKER_FLAGS="-fsanitize=address" \
              "$NODUS_DIR"
    else
        cmake -DCMAKE_BUILD_TYPE=Release "$NODUS_DIR"
    fi

    make -j$(nproc) nodus-server

    if [ ! -f "$BUILD_DIR/nodus-server" ]; then
        echo -e "${RED}Build failed: nodus-server not found${NC}"
        exit 1
    fi

    echo -e "${GREEN}Build successful${NC}"
    echo ""
}

# Install binary
install_binary() {
    BINARY_NAME="nodus-server"
    [ $DEBUG_BUILD -eq 1 ] && BINARY_NAME="nodus-server-debug"

    echo -e "${YELLOW}Installing ${BINARY_NAME} to ${INSTALL_DIR}/${NC}"
    sudo cp "$NODUS_DIR/build/nodus-server" "${INSTALL_DIR}/${BINARY_NAME}"
    sudo chmod +x "${INSTALL_DIR}/${BINARY_NAME}"

    SIZE=$(ls -lh "${INSTALL_DIR}/${BINARY_NAME}" | awk '{print $5}')
    echo -e "${GREEN}Installed: ${INSTALL_DIR}/${BINARY_NAME} ($SIZE)${NC}"
    echo ""
}

# First-time setup
first_time_install() {
    echo -e "${YELLOW}First-time installation...${NC}"

    # Create data directories
    sudo mkdir -p "${DATA_DIR}/data"
    sudo mkdir -p "${DATA_DIR}/identity"

    # Generate server identity if none exists
    if [ ! -f "${DATA_DIR}/identity/identity.dsa" ]; then
        echo -e "${YELLOW}Generating server identity...${NC}"
        # Identity will be auto-generated by nodus-server on first start
        echo "(Identity will be generated on first server start)"
    fi

    # Install config
    if [ ! -f "$CONFIG_FILE" ]; then
        echo "Installing config to ${CONFIG_FILE}..."
        sudo cp "$SCRIPT_DIR/nodus-v5.conf.example" "$CONFIG_FILE"
        echo -e "${YELLOW}NOTE: Edit ${CONFIG_FILE} to set seed_nodes for this server${NC}"
    fi

    # Install systemd service
    echo "Installing systemd service (${SERVICE_NAME})..."
    if [ $DEBUG_BUILD -eq 1 ]; then
        sudo tee /etc/systemd/system/${SERVICE_NAME}.service > /dev/null << EOF
[Unit]
Description=Nodus v5 - Post-Quantum DHT Server (Debug+ASAN)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=${INSTALL_DIR}/nodus-server-debug -c ${CONFIG_FILE}
Restart=on-failure
RestartSec=5
Environment="ASAN_OPTIONS=detect_leaks=1:log_path=/var/log/nodus-v5-asan"
ReadWritePaths=${DATA_DIR}

[Install]
WantedBy=multi-user.target
EOF
    else
        sudo cp "$SCRIPT_DIR/nodus-v5.service" /etc/systemd/system/${SERVICE_NAME}.service
    fi

    sudo systemctl daemon-reload
    sudo systemctl enable ${SERVICE_NAME}
    sudo systemctl start ${SERVICE_NAME}

    echo -e "${GREEN}Installation complete${NC}"
    echo ""
}

# Update existing
update_install() {
    echo -e "${YELLOW}Restarting ${SERVICE_NAME}...${NC}"
    sudo systemctl restart ${SERVICE_NAME}
    sleep 2
    echo -e "${GREEN}Service restarted${NC}"
    echo ""
}

# Show status
show_status() {
    echo -e "${YELLOW}Service status:${NC}"
    sudo systemctl status ${SERVICE_NAME} --no-pager -l 2>/dev/null | head -15 || true
}

# Main
check_deps
pull_latest
build_nodus
install_binary

if [ ! -f /etc/systemd/system/${SERVICE_NAME}.service ]; then
    first_time_install
else
    update_install
fi

show_status
