/**
 * @file fuzz_seed_gen.c
 * @brief Writes the seed corpora for the messenger fuzz targets added by
 *        web Connect package NC-5.
 *
 * Every seed comes from the REAL encoder of its format — no wire byte is
 * spelled out by hand here:
 *   anchor_json/    dna_identity_to_json / _to_json_unsigned (dna_profile.c)
 *                   of an identity carrying the fuzz_keys.h public keys,
 *                   signed over the unsigned form with qgp_dsa87_sign
 *   seal_decode/    dna_encrypt_message_raw_alg (dna_api.c) to the local
 *                   ML-KEM-1024 and round-3 keys; mode byte 0 (raw) and 1
 *                   (overlay: the real header bytes 10..19)
 *   offline_queue/  dht_serialize_messages (dht_offline_queue.c) of two
 *                   messages whose ciphertexts are real Seals
 *   contactlist/    dht_contactlist_publish (dht_contactlist.c), captured by
 *                   fuzz_dht_stub.c: mode 0 = the blob; mode 1 = its JSON
 *                   plaintext, recovered with dna_decrypt_message_raw
 *   salt_packet/    salt_agreement_publish / _publish_v2
 *                   (dht_salt_agreement.c), captured: mode 0 = the packet
 *                   with the harness's 2-byte length prefix; mode 1 = the
 *                   packet's data portion
 *
 * Keys are the fuzz_keys.h identities the harnesses use, so seal / list /
 * salt seeds decrypt and verify inside the targets. ML-DSA-87 signing is
 * randomized (shared/crypto/sign/dsa/config.h:6) and KEM/AES draw fresh
 * randomness, so a re-run writes different bytes of the same shape.
 *
 * Usage: fuzz_seed_gen <corpus-dir>   (subdirectories created if missing)
 * Exit status 0 = every seed written. Output goes through QGP_LOG only
 * (ring buffer / log file); the exit status is the result.
 */

#include <stdint.h>
#include <stddef.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <errno.h>
#include <sys/stat.h>

#include "dna_api.h"
#include "dht/client/dna_profile.h"
#include "dht/client/dht_contactlist.h"
#include "dht/shared/dht_offline_queue.h"
#include "dht/shared/dht_salt_agreement.h"
#include "crypto/sign/qgp_dilithium.h"
#include "crypto/utils/qgp_log.h"
#include "crypto/utils/qgp_types.h"
#include "fuzz_keys.h"
#include "fuzz_dht_stub.h"

#define LOG_TAG "FUZZ_SEED_GEN"

/* dht_contactlist.c:372-411 — magic(4) version(1) timestamp(8) expiry(8) */
#define CL_HEADER_BYTES   21
/* dna_api.c:62-74 header; bytes 10..19 = the overlay-mode patch window */
#define SEAL_PATCH_OFFSET 10
#define SEAL_PATCH_BYTES  10
/* dht_salt_agreement.c:36-46 */
#define SALT_PKT_DATA_V1  3386
#define SALT_PKT_DATA_V2  3388

static const char *g_root;
static int g_failures;

static void fail(const char *what) {
    QGP_LOG_ERROR(LOG_TAG, "%s failed", what);
    g_failures++;
}

static int ensure_dir(const char *path) {
    if (mkdir(path, 0755) == 0 || errno == EEXIST) {
        return 0;
    }
    QGP_LOG_ERROR(LOG_TAG, "mkdir %s failed", path);
    return -1;
}

/* Write mode byte (if mode >= 0) followed by data */
static void write_seed(const char *sub, const char *name, int mode,
                       const uint8_t *data, size_t len) {
    char path[4096];
    snprintf(path, sizeof(path), "%s/%s/%s", g_root, sub, name);
    FILE *f = fopen(path, "wb");
    int ok = f != NULL;
    if (ok && mode >= 0) {
        uint8_t m = (uint8_t)mode;
        ok = fwrite(&m, 1, 1, f) == 1;
    }
    if (ok && len) {
        ok = fwrite(data, 1, len, f) == len;
    }
    if (f && fclose(f) != 0) {
        ok = 0;
    }
    if (!ok) {
        QGP_LOG_ERROR(LOG_TAG, "write %s failed", path);
        g_failures++;
    } else {
        QGP_LOG_INFO(LOG_TAG, "wrote %s (%zu bytes)", path, len + (mode >= 0 ? 1 : 0));
    }
}

static void gen_anchor(const fuzz_identity_t *self) {
    dna_unified_identity_t *id = dna_identity_create();
    if (!id) {
        fail("dna_identity_create");
        return;
    }
    snprintf(id->fingerprint, sizeof(id->fingerprint), "%s", self->fp_hex);
    memcpy(id->dilithium_pubkey, self->sign_pk, sizeof(id->dilithium_pubkey));
    memcpy(id->kyber_pubkey, self->kyber_pk, sizeof(id->kyber_pubkey));
    snprintf(id->display_name, sizeof(id->display_name), "%s", "Fuzz Seed");
    snprintf(id->bio, sizeof(id->bio), "%s", "seed generated by fuzz_seed_gen");
    id->created_at = 1700000000ull;
    id->updated_at = 1700000001ull;
    id->timestamp = 1700000001ull;
    id->version = 1;

    /* legacy record: no ML-KEM key, no registered name */
    char *unsigned_json = dna_identity_to_json_unsigned(id);
    if (unsigned_json) {
        write_seed("anchor_json", "legacy_unsigned.json", -1,
                   (const uint8_t *)unsigned_json, strlen(unsigned_json));
        size_t sig_len = 0;
        if (qgp_dsa87_sign(id->signature, &sig_len, (const uint8_t *)unsigned_json,
                           strlen(unsigned_json), self->sign_sk) != 0) {
            fail("anchor sign");
        }
        free(unsigned_json);
    } else {
        fail("dna_identity_to_json_unsigned");
    }
    char *signed_json = dna_identity_to_json(id);
    if (signed_json) {
        write_seed("anchor_json", "legacy_signed.json", -1,
                   (const uint8_t *)signed_json, strlen(signed_json));
        free(signed_json);
    } else {
        fail("dna_identity_to_json");
    }

    /* migrated record with a registered name */
    memcpy(id->mlkem_pubkey, self->mlkem_pk, sizeof(id->mlkem_pubkey));
    id->has_mlkem_pubkey = true;
    id->has_registered_name = true;
    snprintf(id->registered_name, sizeof(id->registered_name), "%s", "fuzzseed");
    id->name_registered_at = 1700000000ull;
    id->name_expires_at = 1731536000ull;
    id->name_version = 1;
    signed_json = dna_identity_to_json(id);
    if (signed_json) {
        write_seed("anchor_json", "mlkem_named.json", -1,
                   (const uint8_t *)signed_json, strlen(signed_json));
        free(signed_json);
    } else {
        fail("dna_identity_to_json (mlkem)");
    }
    dna_identity_free(id);
}

static uint8_t *make_seal(dna_context_t *ctx, const fuzz_identity_t *self,
                          uint8_t alg, size_t *len_out) {
    static const char msg[] = "fuzz seed message";
    const uint8_t *pk = (alg == (uint8_t)QGP_KEY_TYPE_MLKEM1024) ? self->mlkem_pk : self->kyber_pk;
    uint8_t *seal = NULL;
    if (dna_encrypt_message_raw_alg(ctx, (const uint8_t *)msg, sizeof(msg) - 1,
                                    pk, self->sign_pk, self->sign_sk,
                                    1700000000ull, alg, &seal, len_out) != DNA_OK) {
        return NULL;
    }
    return seal;
}

static void gen_seal_and_queue(dna_context_t *ctx, const fuzz_identity_t *self) {
    size_t mlkem_len = 0, r3_len = 0;
    uint8_t *mlkem_seal = make_seal(ctx, self, (uint8_t)QGP_KEY_TYPE_MLKEM1024, &mlkem_len);
    uint8_t *r3_seal = make_seal(ctx, self, (uint8_t)QGP_KEY_TYPE_KEM1024, &r3_len);
    if (!mlkem_seal || !r3_seal) {
        fail("dna_encrypt_message_raw_alg");
        free(mlkem_seal);
        free(r3_seal);
        return;
    }
    write_seed("seal_decode", "raw_mlkem.bin", 0, mlkem_seal, mlkem_len);
    write_seed("seal_decode", "raw_kyber_r3.bin", 0, r3_seal, r3_len);
    if (mlkem_len >= SEAL_PATCH_OFFSET + SEAL_PATCH_BYTES) {
        write_seed("seal_decode", "overlay_header.bin", 1,
                   mlkem_seal + SEAL_PATCH_OFFSET, SEAL_PATCH_BYTES);
    }

    dht_offline_message_t msgs[2];
    memset(msgs, 0, sizeof(msgs));
    msgs[0].seq_num = 1;
    msgs[0].timestamp = 1700000000ull;
    msgs[0].expiry = 1700604800ull;
    msgs[0].sender = (char *)self->fp_hex;
    msgs[0].recipient = (char *)self->fp_hex;
    msgs[0].ciphertext = mlkem_seal;
    msgs[0].ciphertext_len = mlkem_len;
    msgs[1] = msgs[0];
    msgs[1].seq_num = 2;
    msgs[1].ciphertext = r3_seal;
    msgs[1].ciphertext_len = r3_len;
    uint8_t *blob = NULL;
    size_t blob_len = 0;
    if (dht_serialize_messages(msgs, 2, &blob, &blob_len) == 0 && blob) {
        write_seed("offline_queue", "two_real_seals.bin", -1, blob, blob_len);
        free(blob);
    } else {
        fail("dht_serialize_messages");
    }
    free(mlkem_seal);
    free(r3_seal);
}

static void gen_contactlist(dna_context_t *ctx, const fuzz_identity_t *self,
                            const fuzz_identity_t *contact) {
    const char *contacts[2] = { contact->fp_hex, self->fp_hex };
    uint8_t salt_a[DHT_CONTACTLIST_SALT_SIZE];
    for (size_t i = 0; i < sizeof(salt_a); i++) {
        salt_a[i] = (uint8_t)(0x11 * i);
    }
    const uint8_t *salts[2] = { salt_a, NULL };

    fuzz_dht_stub_reset();
    if (dht_contactlist_publish(self->fp_hex, contacts, 2, salts,
                                self->kyber_pk, self->kyber_sk,
                                self->sign_pk, self->sign_sk, 0) != 0) {
        fail("dht_contactlist_publish");
        return;
    }
    size_t len = 0;
    const uint8_t *blob = fuzz_dht_stub_last_put(&len);
    if (!blob || len < CL_HEADER_BYTES + 4) {
        fail("contact list capture");
        return;
    }
    write_seed("contactlist", "raw_blob.bin", 0, blob, len);

    /* Recover the JSON the real serializer produced */
    uint32_t enc_len = ((uint32_t)blob[CL_HEADER_BYTES] << 24) |
                       ((uint32_t)blob[CL_HEADER_BYTES + 1] << 16) |
                       ((uint32_t)blob[CL_HEADER_BYTES + 2] << 8) |
                       (uint32_t)blob[CL_HEADER_BYTES + 3];
    if ((size_t)enc_len > len - CL_HEADER_BYTES - 4) {
        fail("contact list enc_len");
        return;
    }
    uint8_t *plain = NULL, *sender = NULL, *sig = NULL;
    size_t plain_len = 0, sender_len = 0, sig_len = 0;
    uint64_t ts = 0;
    if (dna_decrypt_message_raw(ctx, blob + CL_HEADER_BYTES + 4, enc_len, self->kyber_sk,
                                &plain, &plain_len, &sender, &sender_len,
                                &sig, &sig_len, &ts) == DNA_OK && plain) {
        write_seed("contactlist", "sealed_json.bin", 1, plain, plain_len);
    } else {
        fail("contact list decrypt");
    }
    free(plain);
    free(sender);
    free(sig);
    fuzz_dht_stub_reset();
}

static void write_salt(const char *name_raw, const char *name_signed,
                       const uint8_t *pkt, size_t len, size_t data_size) {
    uint8_t *framed = malloc(len + 2);
    if (!framed) {
        fail("salt seed alloc");
        return;
    }
    framed[0] = (uint8_t)(len >> 8);
    framed[1] = (uint8_t)len;
    memcpy(framed + 2, pkt, len);
    write_seed("salt_packet", name_raw, 0, framed, len + 2);
    free(framed);
    if (len >= data_size) {
        /* mode 1 = signed; the real packet already carries the local
         * fingerprint in the entry the publisher chose, so the
         * force-into-entry-1 bit (2) stays clear */
        write_seed("salt_packet", name_signed, 1, pkt, data_size);
    }
}

static void gen_salt(const fuzz_identity_t *self, const fuzz_identity_t *contact) {
    uint8_t salt[SALT_AGREEMENT_SIZE];
    for (size_t i = 0; i < sizeof(salt); i++) {
        salt[i] = (uint8_t)(0xC3 ^ i);
    }
    size_t len = 0;
    const uint8_t *pkt;

    fuzz_dht_stub_reset();
    if (salt_agreement_publish_v2(self->fp_hex, contact->fp_hex, salt,
                                  self->kyber_pk, contact->kyber_pk,
                                  self->mlkem_pk, contact->mlkem_pk,
                                  self->sign_sk) == 0 &&
        (pkt = fuzz_dht_stub_last_put(&len)) != NULL) {
        write_salt("raw_v2.bin", "signed_v2.bin", pkt, len, SALT_PKT_DATA_V2);
    } else {
        fail("salt_agreement_publish_v2");
    }

    fuzz_dht_stub_reset();
    if (salt_agreement_publish(self->fp_hex, contact->fp_hex, salt,
                               self->kyber_pk, contact->kyber_pk,
                               self->sign_sk) == 0 &&
        (pkt = fuzz_dht_stub_last_put(&len)) != NULL) {
        write_salt("raw_v1.bin", "signed_v1.bin", pkt, len, SALT_PKT_DATA_V1);
    } else {
        fail("salt_agreement_publish");
    }
    fuzz_dht_stub_reset();
}

int main(int argc, char **argv) {
    if (argc != 2) {
        QGP_LOG_ERROR(LOG_TAG, "usage: fuzz_seed_gen <corpus-dir>");
        return 1;
    }
    g_root = argv[1];

    const char *subs[] = { "anchor_json", "seal_decode", "offline_queue",
                           "contactlist", "salt_packet" };
    char path[4096];
    if (ensure_dir(g_root) != 0) {
        return 1;
    }
    for (size_t i = 0; i < sizeof(subs) / sizeof(subs[0]); i++) {
        snprintf(path, sizeof(path), "%s/%s", g_root, subs[i]);
        if (ensure_dir(path) != 0) {
            return 1;
        }
    }

    fuzz_identity_t *self = calloc(1, sizeof(*self));
    fuzz_identity_t *contact = calloc(1, sizeof(*contact));
    dna_context_t *ctx = dna_context_new();
    if (!self || !contact || !ctx ||
        fuzz_identity_derive(self, FUZZ_ID_SELF) != 0 ||
        fuzz_identity_derive(contact, FUZZ_ID_CONTACT) != 0) {
        QGP_LOG_ERROR(LOG_TAG, "key derivation failed");
        free(self);
        free(contact);
        if (ctx) {
            dna_context_free(ctx);
        }
        return 1;
    }

    gen_anchor(self);
    gen_seal_and_queue(ctx, self);
    gen_contactlist(ctx, self, contact);
    gen_salt(self, contact);

    dna_context_free(ctx);
    free(self);
    free(contact);

    if (g_failures) {
        QGP_LOG_ERROR(LOG_TAG, "%d seed(s) failed", g_failures);
        return 1;
    }
    return 0;
}
