/**
 * @file test_trie.c
 * @brief Tests for the Nodus EVM state trie (trie/evm_trie.c) — design §6, I4.
 *
 * Expected values come from outside this C code:
 *   [O] trie/trie_vectors.h, generated by trie/trie_oracle.py (the
 *       reference merkle_patricia_trie.py @a87891f7 copied with the §6
 *       substitutions only; the oracle refuses to emit unless the same
 *       code, unsubstituted, reproduces official Prague post-state roots);
 *   [F] execution-spec-tests v5.4.0 fixtures_stable post-state roots
 *       (same two entries tests/test_rlp_mpt.c cites).
 *
 * What is checked:
 *   1. every [O] scenario replayed through the incremental trie with
 *      commits every 1 / 3 / 7 / 25 steps and only at the end, reopening
 *      the handle from the committed digest after each commit in some
 *      schedules (the restart case); every committed root that [O] gives
 *      must match, and the final root always;
 *   2. the same scenarios through the full-rebuild port (evm_trie_full.c)
 *      at every step [O] gives a root for;
 *   3. get() of every key ever touched after the final commit;
 *   4. the 1000-key end state inserted again in reverse order -> same root;
 *   5. commit without changes writes nothing and keeps the root;
 *      the empty root opens and commits with no store call;
 *   6. a store that lies: a flipped byte in a stored node, a missing node,
 *      a correctly-hashed non-canonical node, a correctly-hashed node of a
 *      shape patricialize never builds -> -2, sticky;
 *   7. [O] unsecured variable-length-key cases through evm_trie_full;
 *   8. evm_trie_full in keccak mode reproduces two [F] roots.
 */
#include "evm_trie.h"
#include "evm_trie_full.h"
#include "evm_trie_rlp.h"
#include "trie_vectors.h"
#include "crypto/hash/qgp_sha3.h"
#include "crypto/hash/keccak256.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static int g_fail;

#define CHECK(cond, ...)                                                    \
    do {                                                                    \
        if (!(cond)) {                                                      \
            printf("FAIL %s:%d: ", __FILE__, __LINE__);                     \
            printf(__VA_ARGS__);                                            \
            printf("\n");                                                   \
            g_fail++;                                                       \
        }                                                                   \
    } while (0)

/* ── in-memory node store (test only) ──────────────────────────────── */

typedef struct {
    int      used;
    uint8_t  digest[64];
    uint8_t *data;
    size_t   len;
} mslot;

typedef struct {
    mslot  *slots;
    size_t  cap;           /* power of two */
    size_t  count;
    size_t  n_get, n_put;
    int     put_conflict;  /* a digest put again with different bytes */
} mstore;

static size_t ms_index(const mstore *s, const uint8_t d[64])
{
    uint64_t v = 0;
    for (int i = 0; i < 8; i++) v = (v << 8) | d[i];
    return (size_t)(v & (s->cap - 1));
}

static mslot *ms_find(mstore *s, const uint8_t d[64])
{
    size_t i = ms_index(s, d);
    while (s->slots[i].used) {
        if (memcmp(s->slots[i].digest, d, 64) == 0) return &s->slots[i];
        i = (i + 1) & (s->cap - 1);
    }
    return NULL;
}

static int ms_grow(mstore *s)
{
    size_t ncap = s->cap ? s->cap * 2 : 1024;
    mslot *ns = calloc(ncap, sizeof(*ns));
    if (!ns) return -1;
    mslot *old = s->slots;
    size_t ocap = s->cap;
    s->slots = ns;
    s->cap = ncap;
    for (size_t i = 0; i < ocap; i++) {
        if (!old[i].used) continue;
        size_t j = ms_index(s, old[i].digest);
        while (s->slots[j].used) j = (j + 1) & (s->cap - 1);
        s->slots[j] = old[i];
    }
    free(old);
    return 0;
}

static int ms_get(void *ctx, const uint8_t d[64], uint8_t **rlp, size_t *len)
{
    mstore *s = ctx;
    s->n_get++;
    mslot *e = s->cap ? ms_find(s, d) : NULL;
    if (!e) return 1;
    uint8_t *p = malloc(e->len);
    if (!p) return -2;
    memcpy(p, e->data, e->len);
    *rlp = p;
    *len = e->len;
    return 0;
}

static int ms_put(void *ctx, const uint8_t d[64], const uint8_t *rlp,
                  size_t len)
{
    mstore *s = ctx;
    s->n_put++;
    if ((s->count + 1) * 2 > s->cap && ms_grow(s) != 0) return -2;
    mslot *e = ms_find(s, d);
    if (e) {
        if (e->len != len || memcmp(e->data, rlp, len) != 0)
            s->put_conflict = 1;
        return 0;
    }
    size_t i = ms_index(s, d);
    while (s->slots[i].used) i = (i + 1) & (s->cap - 1);
    s->slots[i].data = malloc(len);
    if (!s->slots[i].data) return -2;
    memcpy(s->slots[i].data, rlp, len);
    memcpy(s->slots[i].digest, d, 64);
    s->slots[i].len = len;
    s->slots[i].used = 1;
    s->count++;
    return 0;
}

static void ms_free(mstore *s)
{
    for (size_t i = 0; i < s->cap; i++) free(s->slots[i].data);
    free(s->slots);
    memset(s, 0, sizeof(*s));
}

static evm_trie_store_t ms_iface(mstore *s)
{
    evm_trie_store_t st = { s, ms_get, ms_put };
    return st;
}

/* ── shadow map of the current contents (test only) ────────────────── */

typedef struct {
    const uint8_t *key;
    size_t         key_len;
    const uint8_t *val;      /* NULL = deleted */
    size_t         val_len;
} shadow_ent;

typedef struct {
    shadow_ent *e;
    size_t      n;
} shadow;

static void shadow_apply(shadow *sh, const uint8_t *k, size_t kl,
                         const uint8_t *v, size_t vl)
{
    for (size_t i = 0; i < sh->n; i++) {
        if (sh->e[i].key_len == kl && memcmp(sh->e[i].key, k, kl) == 0) {
            sh->e[i].val = vl ? v : NULL;
            sh->e[i].val_len = vl;
            return;
        }
    }
    sh->e[sh->n].key = k;
    sh->e[sh->n].key_len = kl;
    sh->e[sh->n].val = vl ? v : NULL;
    sh->e[sh->n].val_len = vl;
    sh->n++;
}

/* full-rebuild root of the live shadow entries */
static int shadow_full_root(const shadow *sh, int secured, uint8_t root[64])
{
    evm_trie_full_kv *kv = calloc(sh->n ? sh->n : 1, sizeof(*kv));
    if (!kv) return -2;
    size_t m = 0;
    for (size_t i = 0; i < sh->n; i++) {
        if (!sh->e[i].val) continue;
        kv[m].key = sh->e[i].key;
        kv[m].key_len = sh->e[i].key_len;
        kv[m].val = sh->e[i].val;
        kv[m].val_len = sh->e[i].val_len;
        m++;
    }
    int rc = evm_trie_full_root(kv, m, secured, EVM_TRIE_FULL_SHA3_512, root);
    free(kv);
    return rc;
}

/* ── helpers ───────────────────────────────────────────────────────── */

static int t_set(evm_trie_t *t, int mode, const uint8_t *k, size_t kl,
                 const uint8_t *v, size_t vl)
{
    if (mode == TV_PATH) return evm_trie_set_path(t, k, v, vl);
    return evm_trie_set(t, k, kl, v, vl);
}

static int t_get(evm_trie_t *t, int mode, const uint8_t *k, size_t kl,
                 uint8_t **v, size_t *vl)
{
    if (mode == TV_PATH) return evm_trie_get_path(t, k, v, vl);
    return evm_trie_get(t, k, kl, v, vl);
}

/* get every key the shadow knows and compare */
static void check_gets(evm_trie_t *t, int mode, const shadow *sh,
                       const char *what)
{
    for (size_t i = 0; i < sh->n; i++) {
        uint8_t *v = NULL;
        size_t vl = 0;
        int rc = t_get(t, mode, sh->e[i].key, sh->e[i].key_len, &v, &vl);
        if (sh->e[i].val) {
            CHECK(rc == 0 && vl == sh->e[i].val_len &&
                  memcmp(v, sh->e[i].val, vl) == 0,
                  "%s: get key #%zu (rc %d)", what, i, rc);
        } else {
            CHECK(rc == 1, "%s: deleted key #%zu reads rc %d", what, i, rc);
        }
        free(v);
    }
}

/* ── 1-3: scenario replay ──────────────────────────────────────────── */

static void replay(const tv_scenario *sc, unsigned interval, int reopen,
                   int with_full, int with_gets)
{
    mstore ms = {0};
    evm_trie_store_t st = ms_iface(&ms);
    evm_trie_t *t = NULL;
    shadow sh = { calloc(sc->n ? sc->n : 1, sizeof(shadow_ent)), 0 };
    uint8_t root[64];
    int rc = evm_trie_open(&st, tv_empty_root, &t);
    CHECK(rc == 0 && sh.e, "%s: open", sc->name);
    if (rc != 0 || !sh.e) goto out;

    for (uint32_t i = 0; i < sc->n; i++) {
        const tv_step *s = &tv_steps[sc->first + i];
        const uint8_t *k = tv_blob + s->key_off;
        const uint8_t *v = tv_blob + s->val_off;
        rc = t_set(t, sc->mode, k, s->key_len, v, s->val_len);
        CHECK(rc == 0, "%s/%u/%d: step %u set rc %d", sc->name, interval,
              reopen, i, rc);
        if (rc != 0) goto out;
        shadow_apply(&sh, k, s->key_len, v, s->val_len);

        if (with_full && s->root >= 0) {
            uint8_t fr[64];
            rc = shadow_full_root(&sh, sc->mode == TV_SECURE, fr);
            CHECK(rc == 0 && memcmp(fr, tv_roots[s->root], 64) == 0,
                  "%s: full-rebuild root at step %u", sc->name, i);
        }

        int last = (i + 1 == sc->n);
        if (last || (interval && (i + 1) % interval == 0)) {
            rc = evm_trie_commit(t, root);
            CHECK(rc == 0, "%s/%u/%d: commit at step %u rc %d", sc->name,
                  interval, reopen, i, rc);
            if (rc != 0) goto out;
            if (s->root >= 0)
                CHECK(memcmp(root, tv_roots[s->root], 64) == 0,
                      "%s/%u/%d: root at step %u", sc->name, interval,
                      reopen, i);
            if (reopen) {
                evm_trie_close(t);
                t = NULL;
                rc = evm_trie_open(&st, root, &t);
                CHECK(rc == 0, "%s: reopen", sc->name);
                if (rc != 0) goto out;
            }
        }
    }

    rc = evm_trie_commit(t, root);
    CHECK(rc == 0 && memcmp(root, tv_roots[sc->final_root], 64) == 0,
          "%s/%u/%d: final root", sc->name, interval, reopen);
    CHECK(!ms.put_conflict, "%s: a digest was put with different bytes",
          sc->name);

    if (with_gets) {
        evm_trie_close(t);
        t = NULL;
        if (evm_trie_open(&st, root, &t) == 0)
            check_gets(t, sc->mode, &sh, sc->name);
    }
out:
    evm_trie_close(t);
    free(sh.e);
    ms_free(&ms);
}

static void test_scenarios(void)
{
    static const unsigned intervals[] = { 1, 3, 7, 25, 0 };
    size_t ns = sizeof(tv_scenarios) / sizeof(tv_scenarios[0]);
    for (size_t i = 0; i < ns; i++) {
        const tv_scenario *sc = &tv_scenarios[i];
        for (size_t j = 0; j < sizeof(intervals) / sizeof(intervals[0]); j++) {
            unsigned iv = intervals[j];
            replay(sc, iv, (j % 2) == 0, j == 0, j == 0 || j == 4);
        }
        printf("ok   scenario %s (%u steps)\n", sc->name, sc->n);
    }
}

/* ── 4: order independence (1000 keys) ─────────────────────────────── */

static const tv_scenario *find_scenario(const char *name)
{
    size_t ns = sizeof(tv_scenarios) / sizeof(tv_scenarios[0]);
    for (size_t i = 0; i < ns; i++)
        if (strcmp(tv_scenarios[i].name, name) == 0) return &tv_scenarios[i];
    return NULL;
}

static void test_order_independence(void)
{
    const tv_scenario *sc = find_scenario("random1000");
    CHECK(sc != NULL, "random1000 scenario present");
    if (!sc) return;
    shadow sh = { calloc(sc->n, sizeof(shadow_ent)), 0 };
    if (!sh.e) { CHECK(0, "alloc"); return; }
    for (uint32_t i = 0; i < sc->n; i++) {
        const tv_step *s = &tv_steps[sc->first + i];
        shadow_apply(&sh, tv_blob + s->key_off, s->key_len,
                     tv_blob + s->val_off, s->val_len);
    }
    mstore ms = {0};
    evm_trie_store_t st = ms_iface(&ms);
    evm_trie_t *t = NULL;
    uint8_t root[64];
    int rc = evm_trie_open(&st, tv_empty_root, &t);
    for (size_t i = sh.n; rc == 0 && i-- > 0;)
        if (sh.e[i].val)
            rc = evm_trie_set(t, sh.e[i].key, sh.e[i].key_len, sh.e[i].val,
                              sh.e[i].val_len);
    if (rc == 0) rc = evm_trie_commit(t, root);
    CHECK(rc == 0 && memcmp(root, tv_roots[sc->final_root], 64) == 0,
          "random1000 end state inserted in reverse order -> same root");
    evm_trie_close(t);
    ms_free(&ms);
    free(sh.e);
    printf("ok   order independence\n");
}

/* ── 5: no-op commit, empty root ───────────────────────────────────── */

static void test_noop_and_empty(void)
{
    uint8_t e[64], root[64];
    CHECK(evm_trie_empty_root(e) == 0 && memcmp(e, tv_empty_root, 64) == 0,
          "empty root = SHA3-512(0x80) [O]");

    mstore ms = {0};
    evm_trie_store_t st = ms_iface(&ms);
    evm_trie_t *t = NULL;
    int rc = evm_trie_open(&st, tv_empty_root, &t);
    uint8_t *v = NULL;
    size_t vl = 0;
    if (rc == 0) rc = evm_trie_commit(t, root);
    CHECK(rc == 0 && memcmp(root, tv_empty_root, 64) == 0 &&
          ms.n_get == 0 && ms.n_put == 0,
          "empty trie: open + commit, no store call");
    CHECK(evm_trie_get(t, (const uint8_t *)"x", 1, &v, &vl) == 1 &&
          ms.n_get == 0, "empty trie: get -> absent, no store call");
    CHECK(evm_trie_delete(t, (const uint8_t *)"x", 1) == 0,
          "empty trie: delete of an absent key");

    rc = evm_trie_set(t, (const uint8_t *)"a", 1, (const uint8_t *)"1", 1);
    if (rc == 0) rc = evm_trie_set(t, (const uint8_t *)"b", 1,
                                   (const uint8_t *)"2", 1);
    if (rc == 0) rc = evm_trie_commit(t, root);
    size_t puts = ms.n_put;
    uint8_t root2[64];
    if (rc == 0) rc = evm_trie_commit(t, root2);
    CHECK(rc == 0 && memcmp(root, root2, 64) == 0 && ms.n_put == puts,
          "commit without changes: same root, nothing written");
    CHECK(evm_trie_set(t, NULL, 1, (const uint8_t *)"1", 1) == -1 &&
          evm_trie_set(t, (const uint8_t *)"a", 1, NULL, 1) == -1,
          "invalid arguments -> -1");
    evm_trie_close(t);
    ms_free(&ms);
    printf("ok   no-op commit / empty root\n");
}

/* ── 6: a store that lies ──────────────────────────────────────────── */

static int build_store(mstore *ms, const tv_scenario *sc, uint8_t root[64])
{
    evm_trie_store_t st = ms_iface(ms);
    evm_trie_t *t = NULL;
    int rc = evm_trie_open(&st, tv_empty_root, &t);
    for (uint32_t i = 0; rc == 0 && i < sc->n; i++) {
        const tv_step *s = &tv_steps[sc->first + i];
        rc = t_set(t, sc->mode, tv_blob + s->key_off, s->key_len,
                   tv_blob + s->val_off, s->val_len);
    }
    if (rc == 0) rc = evm_trie_commit(t, root);
    evm_trie_close(t);
    return rc;
}

/* Get every live key of `sc` with a fresh handle each; count -2 results
 * and wrong values (a value returned that is not the expected one). */
static void probe_all(mstore *ms, const tv_scenario *sc,
                      const uint8_t root[64], size_t *faults, size_t *wrong)
{
    evm_trie_store_t st = ms_iface(ms);
    shadow sh = { calloc(sc->n, sizeof(shadow_ent)), 0 };
    *faults = *wrong = 0;
    if (!sh.e) { (*wrong)++; return; }
    for (uint32_t i = 0; i < sc->n; i++) {
        const tv_step *s = &tv_steps[sc->first + i];
        shadow_apply(&sh, tv_blob + s->key_off, s->key_len,
                     tv_blob + s->val_off, s->val_len);
    }
    for (size_t i = 0; i < sh.n; i++) {
        evm_trie_t *t = NULL;
        if (evm_trie_open(&st, root, &t) != 0) { (*wrong)++; continue; }
        uint8_t *v = NULL;
        size_t vl = 0;
        int rc = t_get(t, sc->mode, sh.e[i].key, sh.e[i].key_len, &v, &vl);
        if (rc == -2) {
            (*faults)++;
            /* sticky: the handle refuses everything afterwards */
            uint8_t r[64];
            if (evm_trie_commit(t, r) != -2 ||
                t_set(t, sc->mode, sh.e[i].key, sh.e[i].key_len,
                      (const uint8_t *)"z", 1) != -2)
                (*wrong)++;
        } else if (sh.e[i].val) {
            if (rc != 0 || vl != sh.e[i].val_len ||
                memcmp(v, sh.e[i].val, vl) != 0)
                (*wrong)++;
        } else if (rc != 1) {
            (*wrong)++;
        }
        free(v);
        evm_trie_close(t);
    }
    free(sh.e);
}

/* Store `bytes` under SHA3-512(bytes) and return the digest. */
static int put_raw_node(mstore *ms, const uint8_t *bytes, size_t len,
                        uint8_t d[64])
{
    if (qgp_sha3_512(bytes, len, d) != 0) return -1;
    return ms_put(ms, d, bytes, len);
}

static void test_lying_store(void)
{
    const tv_scenario *sc = find_scenario("random1000");
    CHECK(sc != NULL, "random1000 scenario present");
    if (!sc) return;
    uint8_t root[64];
    size_t faults, wrong;

    /* control: an honest store gives every value back */
    mstore ms = {0};
    CHECK(build_store(&ms, sc, root) == 0 &&
          memcmp(root, tv_roots[sc->final_root], 64) == 0, "build store");
    probe_all(&ms, sc, root, &faults, &wrong);
    CHECK(faults == 0 && wrong == 0, "honest store: %zu faults %zu wrong",
          faults, wrong);

    /* (a) the root node with one byte flipped */
    mslot *r = ms_find(&ms, root);
    CHECK(r != NULL, "root node stored");
    if (r) {
        r->data[r->len / 2] ^= 0x01;
        probe_all(&ms, sc, root, &faults, &wrong);
        CHECK(wrong == 0 && faults > 0, "flipped root byte: %zu faults %zu "
              "wrong", faults, wrong);
        r->data[r->len / 2] ^= 0x01;
    }

    /* (a') every other stored node, one at a time, byte flipped: each must
     * make at least one key fault and never yield a wrong value */
    size_t nodes = 0, bad = 0;
    for (size_t i = 0; i < ms.cap; i++) {
        mslot *e = &ms.slots[i];
        if (!e->used || e == r) continue;
        if (nodes++ % 37 != 0) continue;       /* a spread sample */
        e->data[0] ^= 0x80;
        probe_all(&ms, sc, root, &faults, &wrong);
        if (wrong != 0 || faults == 0) bad++;
        e->data[0] ^= 0x80;
    }
    CHECK(bad == 0, "flipped inner nodes: %zu bad samples", bad);

    /* (b) a node the store has lost */
    if (r) {
        uint8_t keep = r->digest[0];
        r->digest[0] ^= 0xff;                  /* unreachable under root */
        probe_all(&ms, sc, root, &faults, &wrong);
        CHECK(wrong == 0 && faults > 0, "missing root node -> -2");
        r->digest[0] = keep;
    }
    ms_free(&ms);

    /* (c) correctly hashed but non-canonical: a leaf at depth 0 holding a
     * 128-nibble key and the value "x". Canonical value encoding is the
     * byte 0x78 itself; the variant wraps it as 0x81 0x78. */
    uint8_t path[64];
    for (int i = 0; i < 64; i++) path[i] = (uint8_t)(0x11 * (i % 15) + 1);
    for (int variant = 0; variant < 2; variant++) {
        uint8_t node[80];
        size_t k = 0;
        size_t payload = 2 + 65 + (variant ? 2 : 1);
        node[k++] = 0xf8;
        node[k++] = (uint8_t)payload;
        node[k++] = 0xb8;                       /* string of 65 bytes */
        node[k++] = 65;
        node[k++] = 0x20;                       /* even-length leaf flag */
        memcpy(node + k, path, 64);
        k += 64;
        if (variant) node[k++] = 0x81;
        node[k++] = 0x78;
        mstore m2 = {0};
        uint8_t d[64];
        evm_trie_store_t st = ms_iface(&m2);
        evm_trie_t *t = NULL;
        uint8_t *v = NULL;
        size_t vl = 0;
        int rc = put_raw_node(&m2, node, k, d);
        if (rc == 0) rc = evm_trie_open(&st, d, &t);
        if (rc == 0) rc = evm_trie_get_path(t, path, &v, &vl);
        if (!variant)
            CHECK(rc == 0 && vl == 1 && v[0] == 0x78,
                  "hand-built canonical leaf reads back (control), rc %d", rc);
        else
            CHECK(rc == -2, "hashed but non-canonical leaf -> -2 (rc %d)", rc);
        free(v);
        evm_trie_close(t);
        ms_free(&m2);
    }

    /* (d) correctly hashed, canonical RLP, impossible shape: a branch with
     * a single child */
    {
        evm_trie_rlp_buf b = {0};
        uint8_t child[64];
        memset(child, 0x5a, sizeof(child));
        int rc = evm_trie_rlp_put_bytes(&b, child, 64);
        for (int i = 1; i < 17 && rc == 0; i++)
            rc = evm_trie_rlp_put_bytes(&b, NULL, 0);
        if (rc == 0) rc = evm_trie_rlp_wrap_list(&b, 0);
        mstore m2 = {0};
        uint8_t d[64];
        evm_trie_store_t st = ms_iface(&m2);
        evm_trie_t *t = NULL;
        uint8_t *v = NULL;
        size_t vl = 0;
        uint8_t p0[64] = {0};
        if (rc == 0) rc = put_raw_node(&m2, b.p, b.len, d);
        if (rc == 0) rc = evm_trie_open(&st, d, &t);
        if (rc == 0) rc = evm_trie_get_path(t, p0, &v, &vl);
        CHECK(rc == -2, "one-child branch -> -2 (rc %d)", rc);
        free(v);
        evm_trie_close(t);
        ms_free(&m2);
        evm_trie_rlp_buf_free(&b);
    }

    /* (e) a leaf whose key is one nibble short of the path */
    {
        uint8_t node[80];
        size_t k = 0;
        node[k++] = 0xf8;
        node[k++] = (uint8_t)(2 + 64 + 1);
        node[k++] = 0xb8;
        node[k++] = 64;
        node[k++] = 0x31;                       /* odd leaf, 127 nibbles */
        memset(node + k, 0x11, 63);
        k += 63;
        node[k++] = 0x07;
        mstore m2 = {0};
        uint8_t d[64];
        evm_trie_store_t st = ms_iface(&m2);
        evm_trie_t *t = NULL;
        uint8_t *v = NULL;
        size_t vl = 0;
        uint8_t p1[64];
        memset(p1, 0x11, sizeof(p1));
        int rc = put_raw_node(&m2, node, k, d);
        if (rc == 0) rc = evm_trie_open(&st, d, &t);
        if (rc == 0) rc = evm_trie_get_path(t, p1, &v, &vl);
        CHECK(rc == -2, "127-nibble leaf at the root -> -2 (rc %d)", rc);
        free(v);
        evm_trie_close(t);
        ms_free(&m2);
    }
    printf("ok   lying store\n");
}

/* ── 7: unsecured variable-length keys through the full port ───────── */

static void test_full_only(void)
{
    size_t nc = sizeof(tv_full_cases) / sizeof(tv_full_cases[0]);
    for (size_t i = 0; i < nc; i++) {
        const tv_full_case *fc = &tv_full_cases[i];
        evm_trie_full_kv kv[8];
        CHECK(fc->n <= 8, "full case size");
        if (fc->n > 8) continue;
        for (uint32_t j = 0; j < fc->n; j++) {
            const tv_kv *x = &tv_full_kvs[fc->first + j];
            kv[j].key = tv_blob + x->key_off;
            kv[j].key_len = x->key_len;
            kv[j].val = tv_blob + x->val_off;
            kv[j].val_len = x->val_len;
        }
        uint8_t r[64];
        int rc = evm_trie_full_root(kv, fc->n, 0, EVM_TRIE_FULL_SHA3_512, r);
        CHECK(rc == 0 && memcmp(r, tv_roots[fc->root], 64) == 0,
              "full-only case %s", fc->name);
    }
    printf("ok   full-only unsecured cases\n");
}

/* ── 8: keccak mode reproduces official roots [F] ──────────────────── */

static int hexval(char c)
{
    if (c >= '0' && c <= '9') return c - '0';
    if (c >= 'a' && c <= 'f') return c - 'a' + 10;
    if (c >= 'A' && c <= 'F') return c - 'A' + 10;
    return -1;
}

/* hex (optional 0x) -> right-aligned n bytes. @return 0 or -1. */
static int hex_right(const char *s, uint8_t *out, size_t n)
{
    if (s[0] == '0' && (s[1] == 'x' || s[1] == 'X')) s += 2;
    size_t len = strlen(s);
    memset(out, 0, n);
    if ((len + 1) / 2 > n) return -1;
    size_t o = n - (len + 1) / 2, i = 0;
    if (len % 2) {
        int v = hexval(s[0]);
        if (v < 0) return -1;
        out[o++] = (uint8_t)v;
        i = 1;
    }
    for (; i < len; i += 2) {
        int hi = hexval(s[i]), lo = hexval(s[i + 1]);
        if (hi < 0 || lo < 0) return -1;
        out[o++] = (uint8_t)(hi * 16 + lo);
    }
    return 0;
}

static long hex_exact(const char *s, uint8_t *out, size_t cap)
{
    if (s[0] == '0' && (s[1] == 'x' || s[1] == 'X')) s += 2;
    size_t len = strlen(s);
    if (len % 2 || len / 2 > cap) return -1;
    for (size_t i = 0; i < len; i += 2) {
        int hi = hexval(s[i]), lo = hexval(s[i + 1]);
        if (hi < 0 || lo < 0) return -1;
        out[i / 2] = (uint8_t)(hi * 16 + lo);
    }
    return (long)(len / 2);
}

/* RLP unsigned integer from big-endian bytes (leading zeros stripped) */
static int put_uint_be(evm_trie_rlp_buf *b, const uint8_t *be, size_t len)
{
    size_t i = 0;
    while (i < len && be[i] == 0) i++;
    return evm_trie_rlp_put_bytes(b, be + i, len - i);
}

typedef struct { const char *key, *val; } slot_vec;
typedef struct {
    const char *addr, *nonce, *balance, *code;
    slot_vec    slots[4];
    size_t      n_slots;
} acct_vec;

static int kstate_root(const acct_vec *accts, size_t n, uint8_t root[32])
{
    uint8_t addrs[8][20];
    evm_trie_rlp_buf vals[8] = {{0}};
    evm_trie_full_kv kv[8];
    int rc = (n <= 8) ? 0 : -1;
    for (size_t i = 0; i < n && rc == 0; i++) {
        const acct_vec *a = &accts[i];
        uint8_t nonce[8], bal[32], code[64], sroot[32], chash[32];
        uint8_t skeys[4][32];
        evm_trie_rlp_buf svals[4] = {{0}};
        evm_trie_full_kv skv[4];
        long clen = hex_exact(a->code, code, sizeof(code));
        if (hex_right(a->addr, addrs[i], 20) != 0 ||
            hex_right(a->nonce, nonce, 8) != 0 ||
            hex_right(a->balance, bal, 32) != 0 || clen < 0 ||
            a->n_slots > 4) { rc = -1; break; }
        for (size_t j = 0; j < a->n_slots && rc == 0; j++) {
            uint8_t sv[32];
            if (hex_right(a->slots[j].key, skeys[j], 32) != 0 ||
                hex_right(a->slots[j].val, sv, 32) != 0) { rc = -1; break; }
            rc = put_uint_be(&svals[j], sv, 32);
            skv[j].key = skeys[j];
            skv[j].key_len = 32;
            skv[j].val = svals[j].p;
            skv[j].val_len = svals[j].len;
        }
        if (rc == 0)
            rc = evm_trie_full_root(skv, a->n_slots, 1,
                                    EVM_TRIE_FULL_KECCAK256, sroot);
        for (size_t j = 0; j < 4; j++) evm_trie_rlp_buf_free(&svals[j]);
        if (rc != 0) break;
        if (keccak256(code, (size_t)clen, chash) != 0) { rc = -2; break; }
        /* encode_account, merkle_patricia_trie.py:193-210 */
        if (put_uint_be(&vals[i], nonce, 8) != 0 ||
            put_uint_be(&vals[i], bal, 32) != 0 ||
            evm_trie_rlp_put_bytes(&vals[i], sroot, 32) != 0 ||
            evm_trie_rlp_put_bytes(&vals[i], chash, 32) != 0 ||
            evm_trie_rlp_wrap_list(&vals[i], 0) != 0) { rc = -2; break; }
        kv[i].key = addrs[i];
        kv[i].key_len = 20;
        kv[i].val = vals[i].p;
        kv[i].val_len = vals[i].len;
    }
    if (rc == 0)
        rc = evm_trie_full_root(kv, n, 1, EVM_TRIE_FULL_KECCAK256, root);
    for (size_t i = 0; i < 8; i++) evm_trie_rlp_buf_free(&vals[i]);
    return rc;
}

static int eq_hex32(const uint8_t *got, const char *want)
{
    uint8_t w[32];
    return hex_exact(want, w, 32) == 32 && memcmp(got, w, 32) == 0;
}

static void test_keccak_fixture_roots(void)
{
    uint8_t r[32];
    /* EMPTY_TRIE_ROOT, merkle_patricia_trie.py:71-75 */
    CHECK(evm_trie_full_root(NULL, 0, 1, EVM_TRIE_FULL_KECCAK256, r) == 0 &&
          eq_hex32(r, "56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc0"
                      "01622fb5e363b421"),
          "keccak mode: empty trie root");

    /* [F] static/state_tests/stRevertTest/RevertInCreateInInit_Paris.json,
     * key "tests/static/state_tests/stRevertTest/RevertInCreateInInit_Paris
     * Filler.json::RevertInCreateInInit_Paris[fork_Prague-state_test-]",
     * post.Prague[0].state / .hash (as cited in tests/test_rlp_mpt.c) */
    static const acct_vec v1[] = {
        { "0x585f75c10ed2fcf2b3e63ccc35b175322ccef93a", "0x01",
          "0x63ffec2cc4", "0x", {{0}}, 0 },
        { "0x4db58b0f3a4921166333a88b945c9f460aeb9d78", "0x00", "0x0a", "0x",
          {{ "0x00", "0x01" }}, 1 },
        { "0xb88b3553c57a853ccdff28dd2c357c9cba295c20", "0x02", "0x00", "0x",
          {{ "0x00", "0x20" }, { "0x01", "0x112233" }}, 2 },
    };
    CHECK(kstate_root(v1, 3, r) == 0 &&
          eq_hex32(r, "7326d795472c88d6c24482b0bb566eac54de3fd4d18dc55e"
                      "5f1949a1b47b804c"),
          "keccak mode: fixture root RevertInCreateInInit_Paris[Prague][0]");

    /* [F] paris/eip7610_create_collision/test_init_collision_create_tx.json,
     * key "tests/paris/eip7610_create_collision/test_initcollision.py::
     * test_init_collision_create_tx[fork_Prague-tx_type_0-state_test-
     * non-empty-code-correct-initcode]", post.Prague[0].state / .hash */
    static const acct_vec v2[] = {
        { "0x7a2e68e12a5895764c4a090a9268132394082248", "0x01",
          "0x3635c9adc5de817b80", "0x", {{0}}, 0 },
        { "0x6d7015fc59e81bfc2287c77c50eb7ba268b763e6", "0x00", "0x00", "0x00",
          {{ "0x01", "0x01" }}, 1 },
        { "0x2adc25665018aa1fe0e6bc666dac8fc2697ff9ba", "0x00", "0x0927c0",
          "0x", {{0}}, 0 },
    };
    CHECK(kstate_root(v2, 3, r) == 0 &&
          eq_hex32(r, "f51c1cc0ca4eb07940d838dc30bdd3aabcf8231a9c6145db"
                      "893db1f707b4340a"),
          "keccak mode: fixture root test_init_collision_create_tx[Prague][0]");
    printf("ok   keccak-mode fixture roots\n");
}

int main(void)
{
    test_noop_and_empty();
    test_scenarios();
    test_order_independence();
    test_lying_store();
    test_full_only();
    test_keccak_fixture_roots();
    printf("%s: %d failure(s)\n", g_fail ? "FAILED" : "PASSED", g_fail);
    return g_fail ? 1 : 0;
}
