// Authored EN/TR guides. Source notes live in ../CONTENT_SOURCES.md.
const p = (en, tr) => [en, tr];
const s = (id, title, body) => ({ id, title, body });
export const guides = [
  {
    slug: 'getting-started', group: 'connect', title: p('Getting started', 'Başlangıç'),
    lead: p('Your first conversation starts with an identity you control.', 'İlk sohbetin, kontrolü sende olan bir kimlikle başlar.'),
    sections: [
      s('download', p('01. Get Connect', '01. Connect’i indir'), p('<p>Connect brings private messaging, a public wall and a wallet together. Current Android, Linux and Windows downloads still use the <strong>DNA Connect</strong> name during the Nodus transition.</p><p><a href="https://nodusnetwork.io/connect.html#download">Choose your download →</a></p>', '<p>Connect; özel mesajlaşmayı, herkese açık duvarı ve cüzdanı bir araya getirir. Nodus’a geçiş sırasında Android, Linux ve Windows indirmeleri hâlâ <strong>DNA Connect</strong> adını taşır.</p><p><a href="https://nodusnetwork.io/connect.html#download">İndirmelere git →</a></p>')),
      s('identity', p('02. Create your identity', '02. Kimliğini oluştur'), p('<p>Choose to create an identity in the app. Save the 24-word recovery phrase in order, then follow the name-registration steps. You do not need a phone number or email address.</p><div class="callout">Keep the phrase private. It controls your identity and derived wallet accounts. This wiki never asks you to enter it.</div>', '<p>Uygulamada kimlik oluşturmayı seç. 24 kelimelik kurtarma ifadesini sırasıyla kaydet, ardından isim kaydı adımlarını tamamla. Telefon numarası veya e-posta adresi gerekmez.</p><div class="callout">Kelimelerini gizli tut. Kimliğini ve türetilmiş cüzdan hesaplarını kontrol ederler. Bu wiki senden kurtarma ifadesi istemez.</div>')),
      s('conversation', p('03. Find your people', '03. İnsanlarına ulaş'), p('<p>Add a contact by their registered name. Private and group message content is encrypted before leaving your device. Voice messages, images and videos are supported; a voice message is different from a live call.</p><p><a href="messaging.html">Explore messaging →</a></p>', '<p>Bir kişiyi kayıtlı ismiyle ekle. Özel ve grup mesajlarının içeriği cihazından çıkmadan şifrelenir. Sesli mesaj, fotoğraf ve video desteklenir; sesli mesaj ile canlı arama farklı özelliklerdir.</p><p><a href="messaging.html">Mesajlaşmayı keşfet →</a></p>')),
      s('restore', p('Already have an identity?', 'Zaten bir kimliğin var mı?'), p('<p>Choose restore and enter your recovery phrase in the official app. It restores your keys and derived accounts. Recovering old messages depends on available synchronized data and any encrypted backup you enabled.</p><p><a href="recovery-phrase.html">Understand recovery →</a></p>', '<p>Resmî uygulamada geri yüklemeyi seç ve kurtarma ifadenle devam et. Anahtarların ve türetilmiş hesapların geri oluşturulur. Eski mesajların kurtarılması, erişilebilir eşitlenmiş verilere ve etkinleştirdiğin şifreli yedeğe bağlıdır.</p><p><a href="recovery-phrase.html">Kurtarmayı anla →</a></p>'))
    ]
  },
  {
    slug: 'identity', group: 'connect', title: p('Identity & profile', 'Kimlik ve profil'),
    lead: p('A name people can find. Keys you keep.', 'İnsanların bulabileceği bir isim. Sende kalan anahtarlar.'),
    sections: [
      s('name', p('Your name and keys', 'İsmin ve anahtarların'), p('<p>Your identity starts with keys created on your device. A registered name connects those keys to a readable handle, so contacts can find you without exchanging phone numbers.</p>', '<p>Kimliğin, cihazında oluşturulan anahtarlarla başlar. Kayıtlı isim bu anahtarları okunabilir bir adla ilişkilendirir; kişiler seni telefon numarası paylaşmadan bulabilir.</p>')),
      s('profile', p('Choose what you share', 'Ne paylaşacağını seç'), p('<p>Your avatar, bio, location and website are optional profile details. Published names, profiles and wallet addresses are discoverable. Signed records help detect tampering; signing does not make a record private.</p>', '<p>Avatar, biyografi, konum ve web sitesi isteğe bağlı profil bilgileridir. Yayınlanan isimler, profiller ve cüzdan adresleri bulunabilir. İmzalı kayıtlar değişikliklerin tespitine yardımcı olur; imza, kaydı gizli yapmaz.</p>')),
      s('payments', p('Payments by contact', 'Kişilere ödeme'), p('<p>Connect can look up a contact’s published wallet address for the chosen network. Review the recipient and network before confirming a transfer. Your private keys stay on your device.</p>', '<p>Connect, seçilen ağ için kişinin yayınladığı cüzdan adresini bulabilir. Transferi onaylamadan önce alıcıyı ve ağı kontrol et. Gizli anahtarların cihazında kalır.</p>')),
      s('qr', p('Identity approvals', 'Kimlik onayları'), p('<p>Supported services can request an identity approval through a QR login. Review the request in the app and approve only a login you started. Availability depends on the service and device.</p><p><a href="recovery-phrase.html">Moving to another device →</a></p>', '<p>Destekleyen hizmetler QR giriş ile kimlik onayı isteyebilir. İsteği uygulamada incele ve yalnızca kendin başlattığın girişi onayla. Kullanılabilirlik hizmete ve cihaza bağlıdır.</p><p><a href="recovery-phrase.html">Başka bir cihaza geçiş →</a></p>'))
    ]
  },
  {
    slug: 'messaging', group: 'connect', title: p('Messaging', 'Mesajlaşma'),
    lead: p('Private conversations, from a quick hello to a shared video.', 'Kısa bir merhabadan paylaşılan videolara, özel sohbetler.'),
    sections: [
      s('private', p('Private by default', 'Varsayılan olarak özel'), p('<p>Private and group message content is end-to-end encrypted. Encryption protects content between participants; it does not stop a recipient from copying a message or protect a device someone else controls.</p>', '<p>Özel ve grup mesajlarının içeriği uçtan uca şifrelenir. Şifreleme katılımcılar arasındaki içeriği korur; alıcının mesajı kopyalamasını engellemez veya başkasının kontrol ettiği cihazı güvenli hale getirmez.</p>')),
      s('media', p('More than text', 'Metinden fazlası'), p('<p>Send voice messages, photos and videos. The media outbox tracks uploads and supports resuming them. Message reactions, starred messages, delivery receipts and read receipts help you follow a conversation.</p>', '<p>Sesli mesaj, fotoğraf ve video gönder. Medya gönderim kuyruğu yüklemeleri takip eder ve sürdürmeyi destekler. Tepkiler, yıldızlı mesajlar, teslim ve okundu bilgileri sohbeti takip etmene yardımcı olur.</p>')),
      s('offline', p('When a contact is offline', 'Bir kişi çevrimdışıyken'), p('<p>The offline queue uses a default retention window of up to seven days for encrypted messages. Delivery depends on the recipient returning and the network retaining the data. This queue is separate from your long-term message history.</p>', '<p>Çevrimdışı kuyruk, şifreli mesajlar için varsayılan olarak yedi güne kadar saklama süresi kullanır. Teslimat, alıcının geri dönmesine ve verinin ağda bulunmasına bağlıdır. Bu kuyruk uzun süreli mesaj geçmişinden ayrıdır.</p>')),
      s('history', p('Keep your history', 'Geçmişini koru'), p('<p>Local conversation history is stored in encrypted application databases. Optional encrypted message backup is available in Settings → Data &amp; Storage. A recovery phrase recreates keys; it cannot recreate a message that no longer exists in any available backup or synchronized storage.</p><p><a href="security.html">Read the privacy boundaries →</a></p>', '<p>Yerel sohbet geçmişi şifreli uygulama veritabanlarında saklanır. İsteğe bağlı şifreli mesaj yedeği Ayarlar → Veri ve Depolama bölümündedir. Kurtarma ifadesi anahtarları yeniden oluşturur; erişilebilir bir yedekte veya eşitlenmiş depoda bulunmayan mesajı yeniden oluşturamaz.</p><p><a href="security.html">Gizliliğin kapsamını oku →</a></p>'))
    ]
  },
  {
    slug: 'contacts-groups', group: 'connect', title: p('Contacts & groups', 'Kişiler ve gruplar'),
    lead: p('Decide who can reach you and who belongs in the conversation.', 'Sana kimin ulaşacağına ve sohbette kimlerin olacağına karar ver.'),
    sections: [
      s('contacts', p('Add people by name', 'İsimle kişi ekle'), p('<p>Enter your friend’s registered name to add them. Connect does not need your phone’s address book. Incoming contact requests let you review who wants to connect.</p>', '<p>Arkadaşını eklemek için kayıtlı ismini gir. Connect telefonunun rehberine ihtiyaç duymaz. Gelen kişi isteklerinde sana ulaşmak isteyenleri inceleyebilirsin.</p>')),
      s('blocking', p('Manage requests and blocking', 'İstekleri ve engellemeyi yönet'), p('<p>Accept the requests you want. Manage blocked contacts from the Contacts screen; you can unblock later. Blocking controls contact requests and notifications in the app.</p>', '<p>İstediğin istekleri kabul et. Engellenen kişileri Kişiler ekranından yönetebilir, daha sonra engeli kaldırabilirsin. Engelleme, uygulamadaki kişi isteklerini ve bildirimleri kontrol eder.</p>')),
      s('groups', p('Bring a group together', 'Bir grubu bir araya getir'), p('<p>Create and name a group, then add people from your contacts. Group messages are encrypted for members. Members can invite contacts, so check membership when sharing sensitive information.</p><p><a href="messaging.html">Message and media guide →</a></p>', '<p>Bir grup oluştur, isim ver ve kişilerinden katılımcı ekle. Grup mesajları üyeler için şifrelenir. Üyeler kişi davet edebildiği için hassas bilgi paylaşırken grup üyelerini kontrol et.</p><p><a href="messaging.html">Mesaj ve medya rehberi →</a></p>'))
    ]
  },
  {
    slug: 'wallet', group: 'connect', title: p('Wallet', 'Cüzdan'),
    lead: p('Your accounts, together inside Connect.', 'Hesapların, Connect’in içinde bir arada.'),
    sections: [
      s('networks', p('One phrase, multiple networks', 'Tek ifade, birden fazla ağ'), p('<p>The wallet derives accounts for Cellframe, Ethereum, BNB Smart Chain, Solana and TRON, alongside the native DNAC development chain. These networks retain their own transaction rules and cryptography.</p>', '<p>Cüzdan; yerel DNAC geliştirme zincirinin yanında Cellframe, Ethereum, BNB Smart Chain, Solana ve TRON hesaplarını türetir. Bu ağların kendi işlem kuralları ve kriptografisi geçerlidir.</p>')),
      s('send', p('Send and receive', 'Gönder ve al'), p('<p>Select the network and asset, then choose a contact or enter the recipient address. QR codes support send and receive flows. Check the amount, destination, network and displayed fee before confirming. Transaction history shows your activity.</p>', '<p>Ağı ve varlığı seç; ardından bir kişi seç veya alıcı adresini gir. QR kodları gönderme ve alma akışlarını destekler. Onaylamadan önce tutarı, hedefi, ağı ve gösterilen ücreti kontrol et. İşlem geçmişinde hareketlerini görebilirsin.</p>')),
      s('swaps', p('Supported swaps', 'Desteklenen takaslar'), p('<p>Integrated DEX routes offer swaps on supported networks. Available routes, fees and transaction protection depend on the network and provider. A messaging security feature does not change the security of an external chain.</p>', '<p>Entegre DEX rotaları desteklenen ağlarda takas sunar. Rotalar, ücretler ve işlem koruması ağa ve sağlayıcıya bağlıdır. Mesajlaşmadaki bir güvenlik özelliği harici zincirin güvenliğini değiştirmez.</p>')),
      s('devnet', p('DNAC today, NODUS at testnet', 'Bugün DNAC, testnet ile NODUS'), p('<div class="callout">Native balances currently belong to the DNAC devnet. The network can reset. The Nodus name and NODUS ticker are planned for the testnet transition.</div><p><a href="chain.html">Understand the chain →</a></p>', '<div class="callout">Yerel bakiyeler şu anda DNAC devnet’ine aittir. Ağ sıfırlanabilir. Nodus adı ve NODUS ticker’ı testnet geçişi için planlanır.</div><p><a href="chain.html">Zinciri anla →</a></p>'))
    ]
  },
  {
    slug: 'wall', group: 'connect', title: p('The public wall', 'Herkese açık duvar'),
    lead: p('A place to share with your community.', 'Topluluğunla paylaşabileceğin bir alan.'),
    sections: [
      s('public', p('Posts are public', 'Gönderiler herkese açıktır'), p('<p>The Wall is the public side of Connect. Publish under your name, follow people, like posts and join comment threads. Unlike a private conversation, a public post is intended to be seen by others.</p>', '<p>Duvar, Connect’in herkese açık tarafıdır. İsminle paylaşım yap, kişileri takip et, gönderileri beğen ve yorumlara katıl. Özel sohbetten farklı olarak herkese açık gönderiler başkalarının görmesi içindir.</p>')),
      s('visibility', p('Choose what belongs in public', 'Herkese açık alanda ne paylaşacağını seç'), p('<p>A reader can copy or redistribute a post. Do not treat deletion as a guarantee that every copy disappears. Use private conversations for content intended only for selected recipients.</p>', '<p>Bir okuyucu gönderiyi kopyalayabilir veya yeniden paylaşabilir. Silmeyi, her kopyanın kaybolacağı garantisi olarak görme. Yalnızca seçili alıcılara yönelik içerik için özel sohbetleri kullan.</p>')),
      s('tips', p('Tips and existing assets', 'Bahşişler ve mevcut varlıklar'), p('<p>The existing app includes CPUNK tipping and devnet-related testing. Rebranding the website does not convert CPUNK into NODUS. Review the asset, network and fee shown by your installed app before approving a tip.</p><p><a href="wallet.html">Open the wallet guide →</a></p>', '<p>Mevcut uygulamada CPUNK bahşişleri ve devnet ile ilgili testler bulunur. Web sitesinin yeniden markalanması CPUNK’ı NODUS’a dönüştürmez. Bahşişi onaylamadan önce kurulu uygulamanın gösterdiği varlığı, ağı ve ücreti incele.</p><p><a href="wallet.html">Cüzdan rehberini aç →</a></p>'))
    ]
  },
  {
    slug: 'security', group: 'connect', title: p('Privacy & security', 'Gizlilik ve güvenlik'),
    lead: p('Understand what is protected, and what you choose to make public.', 'Neyin korunduğunu ve neyi herkese açtığını bil.'),
    sections: [
      s('content', p('Private content', 'Özel içerik'), p('<p>Private message bodies are end-to-end encrypted. Local application databases use SQLCipher encryption. Public profiles and wall posts are intentionally discoverable; they are not private messages.</p>', '<p>Özel mesaj içerikleri uçtan uca şifrelenir. Yerel uygulama veritabanları SQLCipher ile şifrelenir. Herkese açık profiller ve duvar gönderileri bulunabilir olacak şekilde tasarlanır; özel mesaj değildir.</p>')),
      s('metadata', p('Network visibility', 'Ağın görebildikleri'), p('<p>Nodes accepting connections can observe IP addresses, timing, traffic volume and routing metadata. Encryption of message content does not provide anonymity. TCP channel protection does not extend to all UDP discovery traffic.</p>', '<p>Bağlantıları kabul eden düğümler IP adreslerini, zamanlamayı, trafik hacmini ve yönlendirme metaverisini görebilir. Mesaj içeriğinin şifrelenmesi anonimlik sağlamaz. TCP kanal koruması tüm UDP keşif trafiğini kapsamaz.</p>')),
      s('device', p('Protect your device', 'Cihazını koru'), p('<p>Use the app’s PIN lock and supported biometrics alongside your device screen lock. Keep your recovery phrase private. Encryption cannot stop someone controlling an unlocked device or a recipient who shares a conversation.</p>', '<p>Uygulamanın PIN kilidini ve desteklenen biyometriyi cihaz ekran kilidiyle birlikte kullan. Kurtarma ifadeni gizli tut. Şifreleme, açık cihazı kontrol eden kişiyi veya sohbeti paylaşan alıcıyı durduramaz.</p>')),
      s('scope', p('Cryptography and review', 'Kriptografi ve inceleme'), p('<p>The current private-message implementation uses Kyber1024 round-3 and AES-256-GCM, with the Dilithium5 / ML-DSA-87 signature profile. Kyber round-3 predates ML-KEM/FIPS 203. These choices do not constitute an independent audit or certification.</p><p>The native libraries are Apache 2.0; the Flutter app has a separate source-available proprietary license.</p><p><a href="https://nodusnetwork.io/docs.html#security">Technical security scope →</a></p>', '<p>Mevcut özel mesaj uygulaması Kyber1024 round-3 ve AES-256-GCM ile Dilithium5 / ML-DSA-87 imza profilini kullanır. Kyber round-3, ML-KEM/FIPS 203’ten önceki sürümdür. Bu seçimler bağımsız denetim veya sertifika anlamına gelmez.</p><p>Yerel kütüphaneler Apache 2.0 lisanslıdır; Flutter uygulaması kaynak kodu görülebilen ayrı bir özel lisansa sahiptir.</p><p><a href="https://nodusnetwork.io/docs.html#security">Teknik güvenlik kapsamı →</a></p>'))
    ]
  },
  {
    slug: 'recovery-phrase', group: 'connect', title: p('Recovery & backups', 'Kurtarma ve yedekler'),
    lead: p('Keep your keys safe. Know what a backup brings back.', 'Anahtarlarını güvende tut. Yedeğin neyi geri getirdiğini bil.'),
    sections: [
      s('phrase', p('Your 24 words', '24 kelimen'), p('<p>The recovery phrase recreates your identity keys and derived wallet accounts. Save the words in their exact order, keep copies in secure places and never share them. Enter them only in the official app’s recovery flow.</p><div class="callout">No website, wiki, explorer or support request needs your recovery phrase.</div>', '<p>Kurtarma ifadesi kimlik anahtarlarını ve türetilmiş cüzdan hesaplarını yeniden oluşturur. Kelimeleri doğru sırayla kaydet, kopyaları güvenli yerlerde sakla ve paylaşma. Yalnızca resmî uygulamanın kurtarma akışında kullan.</p><div class="callout">Hiçbir web sitesi, wiki, gezgin veya destek isteği kurtarma ifadene ihtiyaç duymaz.</div>')),
      s('backup', p('Keys and history are different', 'Anahtarlar ve geçmiş farklıdır'), p('<p>A recovery phrase is not a copy of your message history or files. Enable encrypted message backup in Settings → Data &amp; Storage if you want that recovery option. Recovery still depends on the retained backup being available.</p>', '<p>Kurtarma ifadesi mesaj geçmişinin veya dosyalarının kopyası değildir. Bu kurtarma seçeneğini istiyorsan Ayarlar → Veri ve Depolama bölümünden şifreli mesaj yedeğini etkinleştir. Geri yükleme, saklanan yedeğin erişilebilir olmasına bağlıdır.</p>')),
      s('restore', p('Restore on another device', 'Başka bir cihazda geri yükle'), p('<ol><li>Install the official Connect release.</li><li>Choose restore and enter the phrase in order.</li><li>Allow available identity and contact records to synchronize.</li><li>Restore an available encrypted message backup when offered.</li></ol><p>Without the keys or phrase, support cannot reconstruct your identity for you.</p>', '<ol><li>Resmî Connect sürümünü kur.</li><li>Geri yüklemeyi seç ve kelimeleri sırasıyla gir.</li><li>Erişilebilir kimlik ve kişi kayıtlarının eşitlenmesini bekle.</li><li>Sunulduğunda erişilebilir şifreli mesaj yedeğini geri yükle.</li></ol><p>Anahtarların veya kurtarma ifaden olmadan destek ekibi kimliğini yeniden oluşturamaz.</p>'))
    ]
  },
  {
    slug: 'network', group: 'network', title: p('The resource network', 'Kaynak ağı'),
    lead: p('Storage at the core. Bandwidth and compute ahead.', 'Temelde depolama. Sırada bant genişliği ve hesaplama.'),
    sections: [
      s('storage', p('Storage · foundation implemented', 'Storage · temel geliştirildi'), p('<p>Nodus stores and replicates signed application records and media, including identity data and encrypted offline messages. Storage is broader than messaging: the planned capacity market will let people buy space for their own files and datasets.</p><p>Capacity offers, pricing, retention terms and service-verification rules remain future market work.</p>', '<p>Nodus; kimlik verileri ve şifreli çevrimdışı mesajlar dahil, imzalı uygulama kayıtlarını ve medyayı saklar ve çoğaltır. Depolama mesajlaşmadan daha geniştir: planlanan kapasite pazarı insanların kendi dosyaları ve veri kümeleri için alan almasını sağlayacak.</p><p>Kapasite teklifleri, fiyatlandırma, saklama koşulları ve hizmet doğrulama kuralları gelecekteki pazarın işleri arasındadır.</p>')),
      s('bandwidth', p('Bandwidth · service planned', 'Bandwidth · hizmet planlanıyor'), p('<p>The direction is a bandwidth service for VoIP and other network traffic. Encrypted endpoint-to-endpoint circuit relay and call signaling exist as building blocks. Live call media and the broader bandwidth market are separate work.</p>', '<p>Hedef, VoIP ve diğer ağ trafiği için bant genişliği hizmetidir. Uçtan uca şifreli devre aktarımı ve arama sinyalleşmesi yapı taşları olarak mevcuttur. Canlı arama medyası ve daha geniş bant genişliği pazarı ayrı işlerdir.</p>')),
      s('compute', p('Compute · market planned', 'Compute · pazar planlanıyor'), p('<p>The planned market connects compute demand with capacity for STARK proof generation, AI training and other workloads. A C STARK prover and verifier are implemented; scheduling, job trading and the distributed compute service are not launched.</p>', '<p>Planlanan pazar; STARK ispat üretimi, AI eğitimi ve diğer iş yükleri için hesaplama talebini kapasiteyle buluşturur. C STARK prover ve verifier geliştirildi; zamanlama, iş alım satımı ve dağıtık hesaplama hizmeti kullanıma açılmadı.</p>')),
      s('applications', p('Where the applications fit', 'Uygulamalar nerede duruyor?'), p('<p>Connect, Wallet and Identity are applications on the shared foundation. Chain provides the ledger; Scan makes indexed ledger data accessible. Node operation and admission depend on the particular network deployment.</p><p><a href="https://nodusnetwork.io/roadmap.html">Follow the development roadmap →</a></p>', '<p>Connect, Wallet ve Identity ortak temel üzerindeki uygulamalardır. Chain kayıt katmanını sağlar; Scan indekslenmiş zincir verisini erişilebilir kılar. Düğüm işletimi ve katılım, ilgili ağ kurulumuna bağlıdır.</p><p><a href="https://nodusnetwork.io/roadmap.html">Geliştirme yol haritasını takip et →</a></p>'))
    ]
  },
  {
    slug: 'chain', group: 'network', title: p('Chain & NODUS', 'Chain ve NODUS'),
    lead: p('The ledger behind the network’s next chapter.', 'Ağın sıradaki adımının arkasındaki kayıt katmanı.'),
    sections: [
      s('status', p('A development network', 'Bir geliştirme ağı'), p('<p>The native chain currently uses DNAC on devnet. It is a development environment and can be reset. The Nodus name and NODUS ticker are planned with testnet; no public testnet date is announced here.</p>', '<p>Yerel zincir şu anda devnet üzerinde DNAC kullanır. Bu bir geliştirme ortamıdır ve sıfırlanabilir. Nodus adı ve NODUS ticker’ı testnet ile planlanır; burada duyurulmuş bir herkese açık testnet tarihi yoktur.</p>')),
      s('ledger', p('What is implemented', 'Neler geliştirildi?'), p('<p>Development includes transparent UTXO accounting, native assets, staking, delegation and chain parameters. Ledger V2 adds modular domains and independent genesis. The CometBFT reference port includes a types layer and consensus core; host and ledger integration remain ongoing work.</p><p>These implementation milestones do not announce a deployed public service. Shielded payments remain development work.</p>', '<p>Geliştirme; şeffaf UTXO muhasebesini, yerel varlıkları, staking’i, delegasyonu ve zincir parametrelerini kapsar. Ledger V2 modüler alanlar ve bağımsız genesis ekler. CometBFT referans portunda tip katmanı ve konsensüs çekirdeği bulunur; sunucu ve kayıt entegrasyonu devam eden iştir.</p><p>Bu geliştirme adımları yayına alınmış herkese açık hizmet duyurusu değildir. Gizli ödemeler geliştirme konusudur.</p>')),
      s('explore', p('Read the ledger', 'Zinciri incele'), p('<p>Nodus Scan displays indexed blocks, transactions and address history. The current transparent ledger exposes transaction amounts and address information. Scan does not sign transactions or independently re-verify consensus certificates.</p><p><a href="https://scan.nodusnetwork.io/">Open Nodus Scan →</a></p>', '<p>Nodus Scan indekslenmiş blokları, işlemleri ve adres geçmişini gösterir. Mevcut şeffaf zincirde işlem tutarları ve adres bilgileri görülebilir. Scan işlem imzalamaz veya konsensüs sertifikalarını bağımsız olarak yeniden doğrulamaz.</p><p><a href="https://scan.nodusnetwork.io/">Nodus Scan’i aç →</a></p>'))
    ]
  },
  {
    slug: 'explorer', group: 'build', title: p('Using Nodus Scan', 'Nodus Scan kullanımı'),
    lead: p('Follow a block. Find a transaction. Understand an address.', 'Bir bloğu takip et. İşlem bul. Bir adresi incele.'),
    sections: [
      s('search', p('Find a record', 'Kayıt bul'), p('<p>Search by decimal block height, a full block or transaction hash, or an address fingerprint. Hashes and address fingerprints use 128 hexadecimal characters. If a term matches more than one record type, choose the result you need.</p>', '<p>Ondalık blok yüksekliği, tam blok veya işlem hash’i ya da adres parmak iziyle ara. Hash’ler ve adres parmak izleri 128 onaltılık karakter kullanır. Bir sorgu birden fazla kayıt türüyle eşleşirse istediğin sonucu seç.</p>')),
      s('records', p('Read the detail pages', 'Ayrıntı sayfalarını oku'), p('<p>Block pages show the header and transaction list. Transaction pages show inputs, outputs, fees and raw bytes. Address pages show indexed native balance and history, with unspent outputs requested separately from witnesses.</p>', '<p>Blok sayfaları başlığı ve işlem listesini gösterir. İşlem sayfalarında girdiler, çıktılar, ücretler ve ham baytlar bulunur. Adres sayfaları indekslenmiş yerel bakiye ve geçmişi gösterir; harcanmamış çıktılar doğrulayıcı düğümlerden ayrıca istenir.</p>')),
      s('freshness', p('Understand the data source', 'Veri kaynağını anla'), p('<p>Scan is a read-only indexer that trusts responses from its configured witness cluster. Indexed data can lag; separately requested live outputs may reflect a later block. An unavailable API is shown as unavailable, never as an empty chain or zero balance.</p><p>Current supply is the supply reported by the development chain. It is not a claim about market circulation.</p><p><a href="https://scan.nodusnetwork.io/">Explore the chain →</a></p>', '<p>Scan, yapılandırılmış doğrulayıcı kümesinin yanıtlarına güvenen salt okunur bir indeksleyicidir. İndeks gecikebilir; ayrıca istenen canlı çıktılar daha sonraki bir bloğa ait olabilir. Erişilemeyen API, boş zincir veya sıfır bakiye olarak gösterilmez.</p><p>Mevcut arz geliştirme zincirinin bildirdiği arzdır. Piyasa dolaşımı hakkında bir iddia değildir.</p><p><a href="https://scan.nodusnetwork.io/">Zinciri keşfet →</a></p>'))
    ]
  },
  {
    slug: 'developers', group: 'build', title: p('Build with Nodus', 'Nodus ile geliştir'),
    lead: p('Start with the code, the interfaces and their current boundaries.', 'Kodla, arayüzlerle ve mevcut kapsamlarıyla başla.'),
    sections: [
      s('components', p('Find the right component', 'Doğru bileşeni bul'), p('<ul><li><strong>messenger/</strong> — native C engine and Flutter application.</li><li><strong>nodus/</strong> — network server, SDK and embedded witness.</li><li><strong>dnac/</strong> — chain client and transaction builders.</li><li><strong>explorer/</strong> — read-only indexer and HTTP API.</li><li><strong>shared/</strong> — shared cryptography and wire codecs.</li></ul><p><a href="https://github.com/nocdem/dna">Browse the source repository →</a></p>', '<ul><li><strong>messenger/</strong> — yerel C motoru ve Flutter uygulaması.</li><li><strong>nodus/</strong> — ağ sunucusu, SDK ve gömülü doğrulayıcı.</li><li><strong>dnac/</strong> — zincir istemcisi ve işlem oluşturucular.</li><li><strong>explorer/</strong> — salt okunur indeksleyici ve HTTP API.</li><li><strong>shared/</strong> — ortak kriptografi ve wire codec’leri.</li></ul><p><a href="https://github.com/nocdem/dna">Kaynak depoyu incele →</a></p>')),
      s('api', p('Explorer API', 'Gezgin API’si'), p('<p>All endpoints use GET. Block and address lists accept a limit from 1 to 100. Pagination uses a strict <code>before</code> cursor: block height for blocks, ledger sequence for address history.</p><pre><code>/api/stats\n/api/blocks?limit=25\n/api/block/&lt;height-or-hash&gt;\n/api/tx/&lt;hash&gt;\n/api/address/&lt;fingerprint&gt;?limit=25\n/api/search?q=&lt;term&gt;</code></pre><p>Money fields are decimal strings in base units with eight decimals for DNAC. Preserve integer precision when formatting them. Unknown stats can be <code>null</code>; an unavailable index can return HTTP 503.</p>', '<p>Tüm uç noktalar GET kullanır. Blok ve adres listelerinde limit 1–100 arasındadır. Sayfalama kesin <code>before</code> sınırı kullanır: bloklar için yükseklik, adres geçmişi için kayıt sıra numarası.</p><pre><code>/api/stats\n/api/blocks?limit=25\n/api/block/&lt;height-or-hash&gt;\n/api/tx/&lt;hash&gt;\n/api/address/&lt;fingerprint&gt;?limit=25\n/api/search?q=&lt;term&gt;</code></pre><p>Para alanları, DNAC için sekiz ondalıklı temel birim cinsinden ondalık metinlerdir. Biçimlendirirken tamsayı hassasiyetini koru. Bilinmeyen istatistikler <code>null</code> olabilir; erişilemeyen indeks HTTP 503 döndürebilir.</p>')),
      s('references', p('Go deeper', 'Ayrıntılara geç'), p('<p><a href="https://nodusnetwork.io/docs.html">Architecture, Engine API, SDK, CLI and protocol references →</a></p><p>Read each component’s README and license before integrating. The native libraries and server are Apache 2.0. The Flutter app is source-available under its own proprietary license.</p>', '<p><a href="https://nodusnetwork.io/docs.html">Mimari, Engine API, SDK, CLI ve protokol kaynakları →</a></p><p>Entegrasyondan önce ilgili bileşenin README ve lisansını oku. Yerel kütüphaneler ve sunucu Apache 2.0 lisanslıdır. Flutter uygulamasının kaynak kodu, kendi özel lisansı altında görülebilir.</p>'))
    ]
  }
];
