import { createNetworkArt } from './network.js';

const turkish = {
  "skip": "İçeriğe geç",
  "nav.roadmap": "Yol haritası",
  "nav.developers": "Geliştiriciler",
  "hero.eyebrow": "Dijital dünyan için altyapı",
  "hero.title": "Senin dünyan.<br><span>Senin ağın.</span>",
  "hero.description": "Merkezinde depolama. Sırada bant genişliği ve hesaplama.<br> Uygulamalar ve kaynak pazarları için kuantum sonrası bir ağ.",
  "hero.explore": "Ekosistemi keşfet",
  "hero.meet": "Neden Nodus?",
  "hero.note": "Bağımsız araçlar. Ortak temeller.",
  "hero.art": "Birçok bağlantı. Ortak bir temel.",
  "hero.bottom": "Doğası gereği bağımsız. Nodus ile bağlı.",
  "hero.bottomRight": "İLETİŞİM / SAHİPLİK / ALTYAPI",
  "principle.one": "Gizlilik odaklı tasarım",
  "principle.two": "Kuantum sonrası temel",
  "principle.three": "Bağlantı için tasarlandı",
  "principle.four": "Açık kaynaklı altyapı",
  "ecosystem.label": "01 / EKOSİSTEM",
  "ecosystem.note": "Ağın üzerinde çalışan uygulamalar.",
  "ecosystem.title": "Bağ kurduğumuzda<br>güzel şeyler olur.",
  "ecosystem.description": "Connect, Identity, Wallet, Chain ve Scan, Nodus’un bir araya getirdiği temelleri kullanır. Uygulamalar, daha geniş bir ağa açılan kapılardır.",
  "connect.category": "SENİN KONUŞMALARIN",
  "connect.bubbleOne": "Aramızda kalsın.",
  "connect.bubbleTwo": "Olması gerektiği gibi.",
  "connect.artLabel": "UÇTAN UCA ŞİFRELİ",
  "connect.description": "Şifreli sohbetler, sesli mesajlar ve herkese açık sosyal paylaşımlar. Çevren tek yerde.",
  "connect.tag": "Mesajlaşma ve sosyal",
  "chain.category": "ORTAK TEMELİMİZ",
  "chain.artLabel": "TEMELDEN BAŞLAYARAK İNŞA EDİLDİ",
  "chain.description": "Uygulamaların kullandığı altyapıya entegre, yerel ödemeler ve ortak mutabakat.",
  "chain.tag": "Blokzincir altyapısı",
  "wallet.category": "DİJİTAL SAHİPLİĞİN",
  "wallet.artTitle": "Senin anahtarların.<br>Senin dünyan.",
  "wallet.artLabel": "TEK KURTARMA İFADESİ. BİRDEN FAZLA ZİNCİR.",
  "wallet.description": "Varlıkların senin kontrolünde. Connect’in içinde yaşayan çok zincirli bir cüzdan.",
  "wallet.tag": "Kontrolü sende olan cüzdan",
  "network.category": "KAYNAK AĞI",
  "network.artLabel": "DAĞITIK TASARIM",
  "network.description": "Bugün depolama altyapısı. İleride depolama, bant genişliği ve hesaplama pazarlarıyla büyüyen bir ağ.",
  "network.tag": "Storage · Bandwidth · Compute",
  "ecosystem.footer": "Tek ekosistem. Kendine ait kılmanın birçok yolu.",
  "ecosystem.docs": "Mimariyi keşfet",
  "technology.label": "02 / GÖRÜNENİN ÖTESİNDE",
  "technology.title": "Güçlü temeller.<br>İnsana açılan olanaklar.",
  "technology.description": "Önemli işler arka planda gerçekleşir. Böylece senin deneyimin sade kalabilir.",
  "technology.oneTitle": "Bugünün ötesini düşünmek.",
  "technology.oneBody": "Şifreli konuşmalardan zincir imzalarına kadar, kuantum sonrası kriptografi altyapının bir parçası.",
  "technology.oneMeta": "KUANTUM SONRASI KRİPTOGRAFİ",
  "technology.twoTitle": "Doğası gereği ortak.",
  "technology.twoBody": "Dağıtık altyapı, ekosistemi birbirine bağlar. Bağımsız düğümler ağı birlikte taşımaya yardımcı olur.",
  "technology.twoMeta": "MERKEZİYETSİZ ALTYAPI",
  "technology.threeTitle": "Yakından bakmaya açık.",
  "technology.threeBody": "Kaynak kodu incele, mimariyi anla ve bir sonraki adımın şekillenmesine katkıda bulun.",
  "technology.threeMeta": "KAYNAK KODU KEŞFET",
  "roadmap.label": "ADIM ADIM YAPTIKLARIMIZ",
  "roadmap.title": "Zamanla inşa edildi.<br>Gelişmeye devam ediyor.",
  "roadmap.description": "İlk messenger’dan kaynak ağına. Tarihli geliştirme adımlarını, süren çalışmaları ve şekillenen yeni hizmetleri takip et.",
  "faq.label": "BİRAZ DAHA BİLGİ",
  "faq.title": "Merak ettiklerin.",
  "faq.oneQ": "Nodus nedir?",
  "faq.oneA": "Nodus, kuantum sonrası bir altyapı ekosistemidir. Mevcut temelini depolama oluşturur; hedefi depolama kapasitesi, bant genişliği ve hesaplama pazarları sunan bir kaynak ağıdır. Connect, Wallet, Identity, Chain ve Scan bu ağa uygulama ve mutabakat katmanlarını getirir.",
  "faq.twoQ": "Zincir mainnet’te çalışıyor mu?",
  "faq.twoA": "Hayır. Zincir şu anda testnet’te ve coin’i NODUS.",
  "faq.threeQ": "DNA ile ilişkisi nedir?",
  "faq.threeA": "Nodus, DNA ekosisteminin CPUNK’tan ayrı yeni markasıdır. Geçiş boyunca mevcut kodda ve hizmet adreslerinde bazı DNA ve CPUNK adları bulunmaya devam eder.",
  "faq.fourQ": "Kaynak kodu nereden inceleyebilirim?",
  "faq.fourA": "Yerel kütüphaneler ve ağ Apache 2.0 lisanslıdır; Flutter uygulamasının kodu özel lisansla incelemeye açıktır. Geliştirici rehberinde kod ve bileşen lisanslarına ulaşabilirsin.",
  "faq.fourLink": "Geliştirici rehberi ↗",
  "closing.label": "GELECEK ORTAK BİR PROJE",
  "closing.title": "Bir bağlantı kur.<br>Kendi yolunu çiz.",
  "closing.cta": "Nodus’a ilk adımını at",
  "footer.tagline": "Doğası gereği bağımsız.<br>Nodus ile bağlı.",
  "footer.note": "Açıkça geliştiriliyor. Sıradaki adım için.",
  "footer.top": "Başa dön ↑",
  "docs.label": "GELİŞTİRİCİ REHBERİ",
  "docs.title": "Bağlantının<br>temelinden başla.",
  "docs.description": "Nodus ekosistemine kısa bir rehber. Bileşenleri tanı, kaynak kodu bul ve geliştirme sürecini takip et.",
  "docs.overviewNav": "Genel bakış",
  "docs.chainNav": "Chain ve coin",
  "docs.sourceNav": "Kaynak kod ve katkı",
  "docs.overviewTitle": "Ortak temeller üzerinde uygulamalar.",
  "docs.overviewBody": "Nodus, ekosistemin ortak altyapısıdır: bugün dağıtık depolama; ileride Storage, Bandwidth ve Compute hizmetleri ve pazarları. Connect, bu ağ üzerinde bir uygulamadır; yerel zincir ortak kayıt katmanını sağlar.",
  "docs.stackApp": "Uygulama deneyimi",
  "docs.stackEngine": "Yerel C kütüphaneleri ve istemci API’leri",
  "docs.stackNetwork": "Keşif, veri saklama, abonelik ve aktarım",
  "docs.stackChain": "Witness mutabakatı ve salt okunur gezgin",
  "docs.transitionTitle": "Yeni marka Nodus.",
  "docs.transitionBody": "DNA ekosistemi, CPUNK’tan ayrı olarak Nodus adıyla yeniden markalanıyor. Geçiş boyunca mevcut programlar, kaynak yolları ve hizmet adresleri bugünkü adlarını koruyor. DNA Connect uygulamaları artık dağıtılmıyor; Nodus Connect web’de önizleme olarak açık. Network sürüm adayı aşamasında; zincir testnet’te. Testnet coin’i NODUS; geçiş boyunca bazı kodlar ve araçlar hâlâ DNAC adını kullanıyor.",
  "docs.connectBody": "Connect; özel konuşmaları, herkese açık sosyal özellikleri ve entegre cüzdanı birleştirir. Flutter arayüzünün arkasında yerel C motoru bulunur; Android, Linux ve Windows için uygulama kodu vardır.",
  "docs.connectOne": "Uçtan uca şifreli birebir ve grup mesajları, grup anahtarı yönetimi, teslim ve okundu bilgisi.",
  "docs.connectTwo": "Dalga biçimi gösterimli sesli mesajlar, görseller, videolar ve kaldığı yerden devam eden kalıcı medya yükleme kuyruğu.",
  "docs.connectThree": "Yedi güne kadar saklanan çevrimdışı mesajlar; cihazlar arasında mesaj ve grup eşitleme.",
  "docs.connectSource": "Connect kaynak kodu ↗",
  "docs.walletBody": "Wallet, Connect’in içinde yer alır ve aynı kurtarma ifadesinden hesaplar türetir. Yerel Nodus Chain testnet’indeki NODUS’un yanında Ethereum, BNB Smart Chain, Solana, TRON ve Cellframe’i destekler. Mevcut testnet’te NODUS web cüzdandan ve web’deki Nodus Connect’ten (önizleme) gönderilir.",
  "docs.walletNote": "Dış ağlar kendi imza kurallarını ve güvenlik özelliklerini korur. Uygulamanın kuantum sonrası mesajlaşması, Ethereum, Solana veya başka bir ağın işlem kriptografisini değiştirmez.",
  "docs.walletSource": "Cüzdan özellikleri ve entegrasyonlar ↗",
  "docs.networkBody": "Nodus, mevcut temelini depolamanın oluşturduğu bir kaynak ağıdır. DHT imzalı uygulama kayıtlarını, medya deposu ikili içerikleri tutar. Çoğaltma, keşif, abonelikler, çevrimiçi durumu ve devre üzerinden aktarım bu altyapıyı uygulamalara bağlar.",
  "docs.networkOne": "Nodus Node sunucu yazılımıdır. C istemci SDK’sı; veri saklama, sorgulama, abonelik ve iletişim işlemlerini uygulamalara açar.",
  "docs.networkTwo": "Düğümler kayıtları ve medyayı çoğaltır. Saklama süresi kayıt türüne bağlıdır; kalıcı kimlik kayıtları ile geçici mesaj kuyrukları farklıdır.",
  "docs.networkThree": "Devre API’sı, açıkça seçilen uçtan uca şifreli bir mod sunar. Aktarıcılar yönlendirme kimliklerini görmeye devam eder; bu bir onion routing ağı değildir.",
  "docs.networkSource": "Network, Node ve SDK kaynak kodu ↗",
  "docs.chainTitle": "Nodus Chain ve NODUS",
  "docs.chainBody": "Yerel zincir şu anda testnet’te ve coin’i NODUS. Nodus içindeki BFT witness düğümleri zincirin yetkili kayıtlarını tutar. Mevcut testnet’te NODUS web cüzdandan ve web’deki Nodus Connect’ten (önizleme) ya da nodus-cli aracıyla gönderilir. DHT kimlik sorgulaması ile witness mutabakatı ayrı görevlerdir.",
  "docs.chainNote": "Coin adı: Nodus. Sembol: NODUS. Geçiş boyunca bazı kodlar ve araçlar hâlâ DNAC adını kullanıyor. Nodus, CPUNK’tan ayrı bir marka.",
  "docs.chainSource": "Zincir uygulaması ve durumu ↗",
  "docs.sourceTitle": "Bir sonraki adımı birlikte üretelim.",
  "docs.sourceBody": "Monorepo; C motorunu, Flutter uygulamasını, ağ sunucusu ve SDK’sını, zincir istemcisini, gezgini, web-wallet/ içindeki tarayıcı cüzdanını (geliştirme önizlemesi: <a href=\"https://wallet.nodusnetwork.io/\" target=\"_blank\" rel=\"noopener noreferrer\">wallet.nodusnetwork.io</a>), website/ içindeki bu web sitesini ve ortak kriptografi kodunu içerir. Bileşen README dosyaları ve yukarıdaki API dokümantasyonundan başlayabilirsin.",
  "docs.sourceCta": "GitHub’da aç ↗",
  "identity.category": "SENİN ADIN, SENİN KİMLİĞİN",
  "identity.artLabel": "ANAHTARLARINA BAĞLI BİR İSİM",
  "identity.description": "Anahtarlarına dayanan bir kimlik. Telefon numarası veya e-posta olmadan, insanları isimleriyle bul.",
  "identity.tag": "Kimlik ve kurtarma",
  "scan.category": "ZİNCİRE AÇILAN BİR PENCERE",
  "scan.artLabel": "TESTNET KAYITLARINI İNCELE",
  "scan.description": "Salt okunur blok gezgininde blokları takip et, işlemleri bul ve adres geçmişini incele.",
  "scan.tag": "Blok gezgini",
  "everyday.label": "GÜNLÜK HAYATTA BAĞ KURMAK İÇİN",
  "everyday.title": "Tek kimlik.<br>Birçok olanak.",
  "everyday.description": "Mesajlaşma, sosyal hayat ve cüzdan Connect’te bir arada. Bunlar, Nodus’a dönüşen mevcut DNA Connect uygulamasının özellikleri.",
  "everyday.privateTitle": "Sohbet yarım kalmasın.",
  "everyday.privateBody": "Özel ve grup sohbetleri, teslim ve okundu bilgisi, yedi güne kadar çevrimdışı mesaj kuyruğu.",
  "everyday.mediaTitle": "Kendini istediğin gibi anlat.",
  "everyday.mediaBody": "Sesli mesaj, fotoğraf ve video gönder. Kalıcı medya kuyruğu yüklemeleri takip eder ve kaldığı yerden sürdürür.",
  "everyday.socialTitle": "Dünyanla paylaş.",
  "everyday.socialBody": "Herkese açık profil duvarı, profiller ve takip sistemi çevreni bir araya getirir. Bu paylaşımlar diğer kişiler tarafından görülebilir.",
  "everyday.paymentTitle": "Sohbetteki kişiye ödeme yap.",
  "everyday.paymentBody": "Connect, kişinin cüzdan adresini çözümler. QR kodla gönderip alabilir, işlemi geçmişinden takip edebilirsin.",
  "everyday.networksTitle": "Ağlarını bir araya getir.",
  "everyday.networksBody": "Ethereum, BNB Smart Chain, Solana, TRON ve Cellframe; ayrıca testnet’te yerel NODUS. Mevcut testnet’te NODUS web cüzdandan ve web’deki Nodus Connect’ten (önizleme) gönderilir.",
  "everyday.recoveryTitle": "Kontrol ettiğin anahtarlarla başla.",
  "everyday.recoveryBody": "24 kelimelik kurtarma ifadesiyle kimliğini oluştur veya geri yükle. Kaydettiğin isim, insanların sana ulaşmasını sağlar.",
  "soon.label": "NODUS CONNECT / ÖNİZLEME",
  "soon.title": "Şimdi web’de, önizleme olarak.",
  "soon.body": "Nodus Connect web’de önizleme olarak açık: cüzdanın ve mesajların tek uygulamada, connect.nodusnetwork.io adresinde. Aynı 24 kelimelik kurtarma ifadesi mevcut kimliğini açar. DNA Connect uygulamaları artık dağıtılmıyor.",
  "foundation.label": "PARÇALAR NASIL BİRLEŞİYOR?",
  "foundation.title": "Ortak hizmetler.<br>Üretmek için alan.",
  "foundation.body": "Nodus ortak altyapıyı sağlar; Connect bunu iletişim için kullanır, Wallet ödemeleri deneyime ekler. Storage, Bandwidth ve Compute bu temeli kaynak pazarlarına genişletir. Chain ise ortak kayıt katmanıdır.",
  "foundation.cta": "Mimariyi incele ↗",
  "foundation.app": "Uygulama deneyimin",
  "foundation.engine": "Uygulamalar ve entegrasyonlar için API’ler",
  "foundation.network": "Bugün depolama; ileride daha geniş kaynak hizmetleri",
  "foundation.chain": "Ortak mutabakat ve zincir kayıtları",
  "faq.fiveQ": "Burada gizlilik ne anlama geliyor?",
  "faq.fiveA": "Özel mesaj içeriği uçtan uca şifrelidir. Herkese açık sosyal paylaşımlar açıktır; ağ düğümleri IP adresi ve bağlantı zamanı gibi metadatayı görebilir. Güvenliğin kapsamını geliştirici rehberinde bulabilirsin.",
  "faq.securityLink": "Güvenliğin kapsamı ↗",
  "closing.body": "Kod yaz, tasarımı iyileştir, uygulamayı çevir, öğrendiklerini belgele veya ağın testlerine katkı ver. Katılmanın birçok yolu var.",
  "soon.nav": "Nodus Connect — önizleme",
  "docs.identityBody": "Kimlik, telefon numarası veya e-posta hesabı yerine cihazda oluşturulan anahtarlarla başlar. Kaydedilen isim, Nodus DHT üzerindeki kriptografik kimlik kayıtlarına çözümlenir; böylece kişiler seni isminle bulabilir.",
  "docs.identity.create": "Bir kimlik oluştur veya 24 kelimelik BIP39 kurtarma ifadenle geri yükle.",
  "docs.identity.name": "Bir isim kaydet; profilini, avatarını ve biyografini düzenle.",
  "docs.identity.use": "Aynı kimliği kişiler, imzalı açık paylaşımlar ve cüzdan adresi keşfi için kullan.",
  "docs.identityRecovery": "Kurtarma ifadesi, anahtarları ve türetilmiş hesapları geri getirir. Her yerel dosyanın veya mesajın kurtarılabileceği anlamına gelmez; saklanan ve eşitlenen verilerin erişilebilirliği ayrıca sınırlıdır.",
  "docs.identitySource": "Depoda kimlik ve kurtarma ↗",
  "docs.connectFour": "Profiller, takip sistemi ve imzalı açık duvar paylaşımları. Bu sosyal paylaşımlar, özel sohbet içeriğinin aksine herkese açıktır.",
  "docs.connectStatus": "Özellik durumu: mevcut yerel uygulamada herkese açık kanallar devre dışı. Motorda sesli arama sinyalleşmesi bulunuyor; burada tamamlanmış bir arama hizmeti olarak sunulmuyor.",
  "docs.wallet.payment": "Kişi bilgilerini cüzdan adresine çözümleyerek sohbetten kripto gönder.",
  "docs.wallet.history": "Gönderme ve alma için QR kod kullan; bakiyeleri ve işlem geçmişini incele.",
  "docs.wallet.swaps": "Takas bugün uygulamada yok; komut satırı aracı DEX fiyat ve takas işlemlerini sunmaya devam ediyor.",
  "docs.networkOperation": "Sunucu bağımsız olarak derlenip işletilebilir. Çalışan belirli bir ağa erişim, o kurulumun yapılandırmasına ve katılım politikasına bağlıdır.",
  "docs.chain.ledger": "Şeffaf UTXO muhasebesi ve kuantum sonrası işlem imzaları.",
  "docs.chain.agreement": "Hash ile bağlı bloklar, durum taahhütleri ve witness mutabakatından oluşan kesinleşme sertifikaları.",
  "docs.chain.native": "Yerel varlıklar, staking, delegasyon, dönem sonu dağıtımı ve komite oyuyla zincir parametreleri geliştirildi; geliştirme ve entegrasyon sürüyor.",
  "docs.scanBody": "Scan, ürün ailesinin blok gezginidir. Mevcut gezgin, blokları ve işlemleri indeksler; salt okunur bir JSON API sunar. Arayüzünde blok ve işlem sorgulama, arama ve adres geçmişi bulunur.",
  "docs.scanNote": "Mevcut şeffaf zincirde işlem tutarları ve adres bilgileri görülebilir. Scan doğrulayıcı kümesinden indekslenen zincir verisini gösterir; cüzdan veya bağımsız konsensüs doğrulayıcısı değildir.",
  "docs.scanCta": "Nodus Scan’i aç ↗",
  "docs.scanSource": "Gezgin ve API kaynak kodu ↗",
  "docs.researchBody": "Ledger V2; modüler alanlar, atomik blok yürütme, kaynak ölçümü, manifest, talep işlemleri ve bağımsız genesis içeriyor. Güncel yerel kod ve entegrasyon senaryoları eski herkese açık mirror’ın ilerisinde: V2 geliştirme zinciri kendi genesis’inden başlayabiliyor. CometBFT referans portu birleştirildi ve testnet’i çalıştırıyor; eşler arası katmanı da 4004 portunda. Scan bu zinciri okuyor.",
  "docs.researchStatus": "STARK prover/verifier geliştirildi. İspat boyutu ve entegrasyon işleri devam edecek; ZK çalışması, kayıt ve konsensüs temelleri beklenerek 7 Ağustos kontrol noktasında beklemeye alındı. Gizli ödemeler ve hesaplama pazarı kullanıma açılmış hizmetler değildir.",
  "docs.researchSource": "ZK uygulamasının durumunu oku ↗",
  "docs.researchTitle": "Ledger V2, ispatlar ve süren entegrasyon",
  "docs.securityBody": "Özel mesajlar Kyber1024 round-3 ve AES-256-GCM kullanır; imzalar Dilithium5 / ML-DSA-87 profiline dayanır. Buradaki Kyber yapısı ML-KEM/FIPS 203 öncesine aittir; ML-KEM-1024’e (FIPS 203) geçiş sürüyor. Algoritma seçimi, bağımsız denetim veya sertifika anlamına gelmez.",
  "docs.security.contentTitle": "Mesaj içeriği",
  "docs.security.contentBody": "Uçtan uca şifreleme, özel mesaj gövdelerini korur. Herkese açık profiller ve duvar paylaşımları bilerek paylaşılır.",
  "docs.security.metadataTitle": "Ağ metadatası",
  "docs.security.metadataBody": "Bağlantıyı kabul eden düğümler IP adresini, zamanlamayı, hacmi ve yönlendirme metadatasını görebilir. TCP kanal şifrelemesi UDP keşif trafiğini kapsamaz ve anonimlik sağlamaz.",
  "docs.security.storageTitle": "Yerel depolama",
  "docs.security.storageBody": "SQLCipher, uygulamanın yerel veritabanlarını şifreler. Android ayrıca anahtarları sarmalamak için Android Keystore kullanır. Gizli anahtar işlemleri cihazda yürütülür; açık anahtarlar kimlik için paylaşılır.",
  "docs.securitySource": "Depoda güvenliğin kapsamı ↗",
  "docs.securityTitle": "Güvenliğin kapsamı.",
  "docs.engineBody": "Nodus Engine, Connect’in arkasındaki yerel C altyapısıdır. Uygulamalar; kimlik, kişiler, mesajlaşma, gruplar, medya ve cüzdan için asenkron API’sını kullanır. Flutter, FFI üzerinden entegre olur; Nodus istemci SDK’sı ağ erişimini sağlar.",
  "docs.engineCli": "Mevcut komut satırı aracı dna-connect-cli adını korur. dna komut grubu zincir sorgularını, bakiyeleri ve geliştirme işlemlerini sunar; grafik uygulama olmadan entegrasyonları test etmek için de kullanılabilir. Mevcut testnet’te NODUS transferleri nodus-cli aracıyla, web cüzdanla veya Nodus Connect ile yapılıyor.",
  "docs.engineApi": "Engine API referansı ↗",
  "docs.engineCommands": "Komut satırı rehberi ↗",
  "docs.engineSdk": "Nodus SDK başlık dosyası ↗",
  "docs.engineProtocol": "Protokol dokümantasyonu ↗",
  "docs.sourceContribute": "Kod, tasarım, çeviri, dokümantasyon, hata bildirimi ve ağ testleriyle katkı verebilirsin. Katılmadan önce ilgili bileşenin kurallarını ve lisansını incele.",
  "docs.licenseTitle": "Bileşenlere göre lisanslar",
  "docs.licenseBody": "Messenger C kütüphanesi, Nodus sunucusu, DNAC ve ortak kriptografi Apache 2.0 lisanslıdır. Flutter uygulamasının kodu özel lisansla incelemeye açıktır. Ekosistemin tamamı tek bir açık kaynak lisansına sahip değildir.",
  "docs.licenseSource": "Bileşen lisansları ↗",
  "docs.sourceReview": "Eylül 2026’ya kadar yerel uygulama, bileşen kayıtları ve git geçmişiyle karşılaştırıldı. Herkese açık aynalar yerel geliştirmeyi geriden takip edebilir. Geliştirme adımları ve tarihsel planlar sürüm duyurusu değildir.",
  "docs.researchNav": "Geliştirme aşamasında",
  "docs.securityNav": "Güvenliğin kapsamı",
  "services.label": "NODUS AĞI",
  "services.title": "Verilerin için alan.<br>İşlerin için bir ağ.",
  "services.intro": "Ağ, dağıtık depolamayla başlıyor. Sonraki adım kapasiteyle ihtiyacı buluşturmak: dosyaların için alan, bağlantıların için bant genişliği ve yoğun iş yükleri için hesaplama gücü.",
  "service.storage.status": "TEMELİ HAZIR",
  "service.storage.title": "Sohbetin ötesinde depolama.",
  "service.storage.body": "Nodus bugün uygulama kayıtlarını ve medyayı saklıyor, çoğaltıyor. Planlanan depolama pazarında kendi dosyaların ve verilerin için alan satın alabileceksin.",
  "service.storage.note": "Dağıtık depolama mevcut · Kapasite pazarı planlanıyor",
  "service.details": "Hizmeti tanı ↗",
  "service.bandwidth.status": "PLANLANAN HİZMET",
  "service.bandwidth.title": "Her bağlantı için kapasite.",
  "service.bandwidth.body": "VoIP görüşmelerini ve diğer ağ trafiğini taşıyacak bant genişliği katmanı. Mevcut şifreli aktarım ve arama sinyalleşmesi çalışmaları başlangıç noktasını oluşturuyor.",
  "service.bandwidth.note": "Aktarım temeli mevcut · Medya hizmeti planlanıyor",
  "service.compute.status": "PLANLANAN PAZAR",
  "service.compute.title": "Yapacağın işler için güç.",
  "service.compute.body": "STARK ispat üretimi, AI eğitimi ve diğer yoğun işler için hesaplama pazarı. C STARK prover zaten geliştirildi; dağıtık hesaplama hizmeti sonraki adım.",
  "service.compute.note": "C prover mevcut · Compute pazarı planlanıyor",
  "services.marketTitle": "Uygulamalar ihtiyacı doğurur. Ağ kaynakları bir araya getirir.",
  "services.marketBody": "Connect, bu altyapıda çalışan bir uygulamadır. Depolama ve hesaplama pazarları, Nodus’u kendi verileri ve iş yükleri için kapasite arayanlara açar.",
  "nav.network": "Ağ",
  "roadmap.asof": "Güncelleme: Ekim 2026",
  "roadmap.filter.all": "Tüm adımlar",
  "roadmap.filter.built": "Yaptıklarımız",
  "roadmap.filter.active": "Üzerinde çalışıyoruz",
  "roadmap.filter.planned": "Planlanan",
  "history.foundation.date": "EKİM 2025",
  "history.foundation.title": "İlk messenger temeli",
  "history.foundation.body": "DNA Messenger ve C kütüphane API’sı ortaya çıktı. Anahtar üretimi, şifreleme ve kurtarma ilk temeli oluşturdu.",
  "roadmap.state.built": "GELİŞTİRİLDİ",
  "history.dht.date": "KASIM 2025",
  "history.dht.title": "Dağıtık iletişim ve mobil temel",
  "history.dht.body": "Kasım boyunca DHT iletişimi, imzalı profiller, grup mesajlaşması, Android derlemeleri ve Flutter/FFI temeli eklendi.",
  "history.wallet.date": "ARALIK 2025",
  "history.wallet.title": "Cüzdan farklı ağlara açılıyor",
  "history.wallet.body": "Ethereum, Solana ve TRON desteği cüzdana eklendi; mevcut Cellframe entegrasyonu genişledi.",
  "history.dnac.date": "OCAK 2026",
  "history.dnac.title": "Yerel zincir geliştirmesi başlıyor",
  "history.dnac.body": "Yerel işlemler, cüzdan işlevleri ve zincir geliştirmesi için DNAC projesi oluşturuldu.",
  "history.nodus.date": "ŞUBAT–MART 2026",
  "history.nodus.title": "Nodus yerel ağ altyapısı oluyor",
  "history.nodus.body": "Saf C Nodus DHT, OpenDHT’nin yerini aldı. Uygulama entegrasyonu ve gömülü witness altyapısıyla depolama ve zincir aynı sunucu ailesinde buluştu.",
  "history.media.date": "MART–NİSAN 2026",
  "history.media.title": "Medya depolama ve şifreli aktarım",
  "history.media.body": "Kalıcı, sürdürülebilir medya yüklemeleri ve uçtan uca şifreli devreler, uygulamaların veri saklama ve aktarma olanaklarını genişletti.",
  "history.economics.date": "NİSAN 2026",
  "history.economics.title": "Staking, delegasyon ve zincir yönetişimi",
  "history.economics.body": "Doğrulayıcı ve delegasyon akışları, cüzdan ekranları, komite oyuyla parametreler, dönem sonu dağıtımı ve arz kontrolleri geliştirildi.",
  "history.proofs.date": "TEMMUZ 2026",
  "history.proofs.title": "Arama sinyalleşmesi, C ispatları ve Scan",
  "history.proofs.body": "Arama sinyalleşmesi ve aramaya özel anahtar anlaşması, C STARK prover/verifier ve JSON API’lı blok gezgini eklendi. Ardından toplu STARK çalışması geldi. Gerçek zamanlı arama medyası ayrı bir sonraki adım olarak kaldı.",
  "history.ledger.date": "AĞUSTOS 2026",
  "history.ledger.title": "Ledger V2 şekilleniyor",
  "history.ledger.body": "Modüler alanlar, atomik blok yürütme, manifest ve talep yapıları, bağımsız V2 genesis geliştirildi. Yeni kayıt yapısı kendi geliştirme zinciri olarak başlayabiliyor.",
  "history.integration.date": "EYLÜL 2026",
  "history.integration.title": "Ledger V2 entegrasyon senaryoları",
  "history.integration.body": "V2 Genesis Protocol; çok düğümlü başlangıç, katılım, kurtarma, yeniden başlatma ve dönem sınırı davranışlarını sınadı. Daha geniş konsensüs çalışmaları sürüyor.",
  "history.consensus.date": "EYLÜL 2026",
  "history.consensus.title": "Devnet’te CometBFT konsensüsü",
  "history.consensus.body": "CometBFT referans portu birleştirildi ve devnet’i çalıştırıyor; eşler arası katmanı da 4004 portunda. Scan bu zinciri okuyor. Testnet hazırlığı sürüyor.",
  "history.testnet.date": "30 EYLÜL 2026",
  "history.testnet.title": "Nodus Chain testnet’i yayında",
  "history.testnet.body": "Zincir, devnet’ten yedi doğrulayıcı düğümlü herkese açık testnet’e geçti ve yeni bir genesis ile başladı. Artık sıfırlama yok: bundan sonra zincir kurallarındaki değişiklikler önceden belirlenen bir blok yüksekliğinde devreye girer. Coin’i NODUS.",
  "history.forks.date": "EKİM 2026",
  "history.forks.title": "Testnet’te dört hard fork etkin",
  "history.forks.body": "Kural değişiklikleri önceden belirlenen bir blok yüksekliğinde devreye girer. İlki genesis belgesinde tanımlandı; sonraki üçü doğrulayıcı oylarıyla açıldı: oy gücüyle tartılan yönetişim onayları, konsensüs sınırlarıyla belirlenen blok boyutu ve 3.151. bloktan itibaren zincir üstü isimler. Scan bunları Hard fork’lar sayfasında listeler.",
  "history.names.date": "3 EKİM 2026",
  "history.names.title": "Web cüzdan ve Nodus Connect’te zincir isimleri",
  "history.names.body": "Nodus adresin için web cüzdandan veya Nodus Connect’ten bir isim kaydet; uzun bir adres yerine isme gönder. İsim 3–36 İngilizce harf ve rakamdan oluşur, ilk alan kazanır, adres başına bir tanedir ve kalıcıdır. Ücreti 3 karakter için 1.000 NODUS, 4 için 500, 5 için 100, 6 ve üstü için 1 NODUS’tur; ücret ödül rezervine gider ve doğrulayıcılar oylamayla değiştirebilir.",
  "history.multisig.date": "3 EKİM 2026",
  "history.multisig.title": "Web cüzdan ve Nodus Connect’te ortak kasalar",
  "history.multisig.body": "Ortak kasa, bir ödeme için N üyesinden M’inin onayını isteyen bir NODUS adresidir. Web cüzdandan veya Nodus Connect’ten, zincir ismi ya da kimlikle seçilen 2 ile 7 üyeli bir kasa oluştur; Nodus Connect’te üyelere mesajla haber verilir; üyeler kasayı tek dokunuşla ekler, ödemelerini önerir ve onaylar.",
  "history.scan2.date": "EKİM 2026",
  "history.scan2.title": "Scan: hard fork’lar, işlem hızı ve ödeme günleri",
  "history.scan2.body": "Scan her hard fork’u oylandığı ve geçerli olduğu blokla listeler, bir işlemi zincir ismiyle bulur; zincirin son bir dakika ve son bir saatteki saniye başına işlem sayısını 24 saatlik grafikle, tahmini tarihiyle bir sonraki ödeme gününü, geçmiş ödeme günlerini ve mevcut blok hızına göre tahmini APY’yi gösterir.",
  "history.split.date": "EKİM 2026",
  "history.split.title": "Ayrı bileşenlerden oluşan düğüm — geliştirildi, canlı düğümlerde henüz yok",
  "history.split.body": "Nodus sunucusu artık üç ayrı süreç olarak da çalışabiliyor: nodus-core, nodus-storage ve nodus-witness; hepsi kurulum betiği olan tek bir tar.gz paketinden kurulur. Tek parça birleşik sunucu varsayılan olarak kalıyor. Bir testnet düğümü üç süreçli düzeni deneme olarak çalıştırıyor; diğerleri birleşik sunucuyu çalıştırıyor.",
  "history.archive.date": "4 EKİM 2026",
  "history.archive.title": "Blok budama ve arşiv düğümleri — canlı, düğüm düğüm açılıyor",
  "history.archive.body": "Nodus 0.23.18 testnet’in yedi düğümünün hepsinde çalışıyor. Budanmış bir doğrulayıcı son 7 ödeme gününü (120.960 blok) ve genesis bağlantısını tutar; bir arşiv düğümü her bloğu tutar. Artık her düğüm yinelenen “seen commit” kopyasını siliyor, böylece zincir verisi daha yavaş büyüyor. Budama önce tek bir düğümde açıldı; diğerleri o düğüm denetlendikten sonra izleyecek.",
  "history.browser2.date": "EYLÜL 2026 / ŞİMDİ",
  "history.browser2.title": "Tarayıcıda Nodus",
  "history.browser2.body": "Web cüzdan, düğümlerin WebSocket girişi üzerinden testnet’te NODUS gönderiyor, alıyor ve delege ediyor; zincir ismine gönderebiliyor ve gönderim yaptığı her ağ için bir adres defteri tutuyor. Cüzdanı ve mesajları tek web uygulamasında toplayan Nodus Connect önizleme olarak açık. Her kişinin tek bir ismi var — zincir ismi, yoksa profil ismi — ve kimliği altında gösteriliyor. Connect, cihazın sakladıklarıyla (kişiler, konuşmalar, isimler) hemen açılıyor ve arka planda bağlanıyor; gönderim bağlantı kurulana kadar bekliyor.",
  "roadmap.state.active": "DEVAM EDİYOR",
  "history.airdrop.date": "EKİM 2026 / ŞİMDİ",
  "history.airdrop.title": "İlk airdrop: CPUNK topluluğu",
  "history.airdrop.body": "İlk kampanya CPUNK Community Airdrop’a, toplam %5’lik airdrop bütçesi içinden 10.000.000 NODUS ayrılır: toplam arzın %1’i. Airdrop sayfası katılım koşullarını ve payın nasıl hesaplandığını anlatıyor. Nodus Connect’ten kayıt olma ve talep etme yakında geliyor; başlangıç duyurulacak.",
  "history.roles.date": "SIRADAKİ",
  "history.roles.title": "Daha düşük validator stake’i ve düğüm rolleri",
  "history.roles.body": "Validator’ün kendi bağı tam 10 milyon NODUS yerine en az 2 milyon olur; fazlası kendine delege edilebilir. Depolama (1 milyon), hesaplama (1 milyon) ve bant genişliği (500.000) rolleri kendi stake’lerini alır ve bu miktarlar oylamayla değiştirilebilir. Aynı yükseltme tek bir validator için sayılan oy gücüne %10’dan başlayan bir tavan koyar ve sahibin anahtarını düğümün anahtarından ayırır. Yalnızca doğrulayıcıların oyladığı bir hard fork ile devreye girer.",
  "history.storage_reward.date": "SIRADAKİ",
  "history.storage_reward.title": "Depolama rolü ödülü",
  "history.storage_reward.body": "Depolama rolüne 1 milyon NODUS stake ile kayıt olan düğümler, doğrulayıcılar sakladıkları veriyi sunduklarını onayladığında Storage havuzundan eşit pay kazanır. Doğrulayıcılar depolama ödülü almaz; bir depolama düğümü ile bir doğrulayıcı aynı makine olabilir. Tasarım 4 Ekim 2026’da onaylandı ve geliştiriliyor; daha sonra doğrulayıcıların oyladığı bir hard fork ile devreye girer.",
  "history.storage_market.date": "SIRADAKİ",
  "history.storage_market.title": "Depolama kapasitesi pazarı",
  "history.storage_market.body": "Nodus ağı etrafında kurulacak depolama pazarından kişisel dosyalar ve uygulama verileri için alan satın alma.",
  "roadmap.state.planned": "PLANLANAN",
  "forks.label": "ZİNCİRİN KURAL DEĞİŞİKLİKLERİ",
  "forks.asof": "5 Ekim 2026’da güncellendi",
  "forks.title": "Hard fork’lar: canlı ve planlanan.",
  "forks.description": "Testnet hiçbir zaman sıfırlanmaz. Zincirin kurallarındaki bir değişiklik bir hard fork’tur: her doğrulayıcı yeni kuralı bilen sürümü çalıştırdıktan ve doğrulayıcılar oyladıktan sonra, üzerinde anlaşılan bir blok yüksekliğinde devreye girer. Planlanan bir fork’un o oylamaya kadar tarihi yoktur.",
  "forks.state.live": "CANLI",
  "forks.state.planned": "PLANLANAN",
  "forks.hf1.date": "HF-1 · BLOK 0",
  "forks.hf1.title": "Gas fiyatı",
  "forks.hf1.body": "Sistem işlemi olmayan her işlem, beyan ettiği iş için genesis belgesinde belirlenen birim fiyattan ve en az bir taban ücretle öder.",
  "forks.hf2.date": "HF-2 · BLOK 1.500",
  "forks.hf2.title": "Oy gücüne göre yönetişim",
  "forks.hf2.body": "Bir zincir parametresi değişikliğinin onayları doğrulayıcı başına bir oy olarak değil, oy gücüne göre (üçte ikiden fazla) sayılır. 724. blokta oylandı.",
  "forks.hf3.date": "HF-3 · BLOK 2.926",
  "forks.hf3.title": "Blok boyutunu konsensüs sınırları belirler",
  "forks.hf3.body": "Bir blok yalnızca konsensüs motorunun kendi sınırlarıyla sınırlanır; eski sabit bayt ve birim sınırları artık uygulanmaz. 2.206. blokta oylandı.",
  "forks.hf4.date": "HF-4 · BLOK 3.151",
  "forks.hf4.title": "Zincir üstü isimler",
  "forks.hf4.body": "İsim kaydını ekleyen yeni bir zincir kuralları seti: Nodus adresiniz için NODUS ile ödenen bir isim; fiyatları doğrulayıcılar oylamayla değiştirebilir. 2.431. blokta oylandı.",
  "forks.hf5.date": "HF-5 · SIRADAKİ",
  "forks.hf5.title": "Akıllı kontratlar: Nodus EVM",
  "forks.hf5.body": "Nodus için yazdığımız kendi EVM motorumuz, Ethereum akıllı kontratlarını Prague kurallarıyla çalıştırır (blob ve set-code işlemleri desteklenmez). Adresler 32 bayttır ve kuantum sonrası anahtarlardan türetilir. NODUS, yerleşik bir köprüyle kontratlara girer ve çıkar; zincirin arzı tam olarak korunur. Kod hazır ve Ethereum’un resmi Prague durum testlerinden geçiyor; yalnızca belgelenmiş bir Nodus kuralının (modexp girdisine sınır) farklı sonuç verdiği dokuz durum hariç. Henüz yayımlanmadı. Ancak her doğrulayıcı yeni sürümü çalıştırdıktan ve doğrulayıcılar oyladıktan sonra devreye girer.",
  "forks.hf6.date": "HF-6 · DAHA SONRA",
  "forks.hf6.title": "Daha düşük validator stake’i, düğüm rolleri ve güç tavanı",
  "forks.hf6.body": "Validator bağı en az 2 milyon NODUS’a iner; depolama, hesaplama ve bant genişliği rolleri kendi stake’lerini alır; tek bir validator için sayılan oy gücüne %10’dan başlayan bir tavan konur; sahibin anahtarı düğümün anahtarından ayrılır. Kararların çoğu verildi ve tasarım yazıldı; henüz geliştirilmedi.",
  "forks.storage.date": "DAHA SONRA",
  "forks.storage.title": "Depolama rolü ödülü",
  "forks.storage.body": "Depolama düğümleri, doğrulayıcılar sakladıkları veriyi sunduklarını onayladığında Storage havuzundan kazanır. Tasarım 4 Ekim 2026’da onaylandı ve geliştiriliyor; hazır olduğunda sıradaki fork numarasını alır.",
  "forks.scan": "Canlı fork’lar oylarıyla birlikte Scan’de ↗",
  "history.bandwidth_market.date": "SIRADAKİ",
  "history.bandwidth_market.title": "VoIP ve diğer bağlantılar için Bandwidth",
  "history.bandwidth_market.body": "Aktarım temelini gerçek zamanlı görüşmeler ve diğer ağ trafiği için bant genişliği hizmetine genişletme.",
  "history.compute_market.date": "SIRADAKİ",
  "history.compute_market.title": "Hesaplama pazarı",
  "history.compute_market.body": "STARK ispat üretimi işlerini ve AI eğitimi yüklerini hesaplama kapasitesi pazarıyla buluşturma.",
  "roadmap.evidence": "Tarihler, proje geçmişindeki geliştirme adımlarını gösterir. Bir bileşenin tamamlanması, ona bağlı tüm hizmetlerin açıldığı anlamına gelmez. Planlanan hizmetlerin duyurulmuş çıkış tarihi yoktur.",
  "roadmap.details": "Geliştirme durumu ve kaynaklar ↗",
  "docs.storageTitle": "Storage: uygulama verisi ve kapasite",
  "docs.storageBody": "Geliştirilen depolama; imzalı kayıtları, kimlik verilerini, çevrimdışı mesaj gruplarını ve medya çoğaltmayı kapsar. Ürün yönü, kullanıcıların kendi dosyaları ve veri kümeleri için depolama satın alabileceği bir pazara genişlemektir. Kapasite teklifleri, saklama koşulları, fiyatlama ve hizmet doğrulama kuralları bu gelecek pazarın parçasıdır.",
  "docs.bandwidthTitle": "Bandwidth: trafik ve gerçek zamanlı iletişim",
  "docs.bandwidthBody": "Şifreli devre aktarımı ve aramaya özel anahtar anlaşmasıyla arama sinyalleşmesi geliştirildi. VoIP ses aktarımı ve daha geniş bant genişliği hizmeti planlanıyor. Medya ve hızlı UDP yolu tasarım belgelerinde açık inceleme işleri var; yalnızca sinyalleşme, tamamlanmış bir arama ürünü değildir.",
  "docs.computeTitle": "Compute: ispat üretimi ve AI iş yükleri",
  "docs.computeBody": "Projede C STARK prover ve verifier zaten bulunuyor. Planlanan hesaplama pazarı; ispat üretimi, AI eğitimi ve diğer hesaplama işlerine yönelik ihtiyacı kapasiteyle buluşturacak. Çalışan prover bir yapı taşıdır; iş planlama, kaynak alım satımı ve dağıtık hesaplama hizmeti ayrı gelecek çalışmalardır.",
  "docs.developmentTitle": "Geliştirmenin bugünkü durumu",
  "docs.developmentBody": "Roadmap, Ekim 2025’ten başlayan geliştirme geçmişini izler. CometBFT referans portu birleştirildi ve testnet’i çalıştırıyor; eşler arası katmanı da 4004 portunda. Scan bu zinciri okuyor. Ledger V2 başlangıç, kurtarma ve dönem senaryoları geliştirme adımlarıdır; herkese açık yayın duyurusu değildir.",
  "docs.developmentLink": "Tarihli roadmap’i incele ↗",
  "docs.developmentNav": "Geliştirme süreci",
  "nav.manifesto": "Manifesto",
  "manifesto.label": "NODUS MANİFESTOSU",
  "manifesto.title": "Gizlilik bir<br>insan hakkıdır.",
  "manifesto.lead": "Kimliğin. Konuşmaların. Verilerin.<br>Karar her zaman senin olmalı.",
  "manifesto.right": "Nerede yaşarsa yaşasın, kim olursa olsun herkesin konuşmak, bağ kurmak ve üretmek için özel bir alana hakkı var. İnsanların dijital kimliklerinin anahtarlarını elinde tutabilmesi; neyi, kiminle ve ne kadar süreyle paylaşacağına kendisinin karar verebilmesi gerektiğine inanıyoruz.",
  "manifesto.whyTitle": "Nodus’u neden geliştiriyoruz?",
  "manifesto.why": "Bu inançla bir mesajlaşma uygulaması geliştirmeye başladık. Geliştirdikçe ihtiyaç büyüdü: kimlik, depolama, iletişim ve ödemeler için yönünü belirleyebildiğimiz bir altyapı gerekiyordu. Kendi ağımızı ve zincirimizi kurmak, mimarisinin, güvenliğinin ve geleceğinin sorumluluğunu üstlenmek demek. Kuantum sonrası kriptografi bu temelin parçası; çünkü özel bir konuşmanın gizliliği yıllar sonra da önemli olabilir.",
  "manifesto.future": "Nodus, bu çalışmayı ortak bir altyapı olarak ileriye taşıyor. Başlangıç noktası Storage; sırada Bandwidth ve Compute var. Hedefimiz, insanların kaynak sunabildiği ve ihtiyaç duyduğu kapasiteye ulaşabildiği bir ağ: dosyalar için alan, görüşmeler için bant genişliği, ispat üretimi ve AI eğitimi için hesaplama gücü. Uygulamalar bu ağı kullanmanın yolu. Bağımsızlık ise onu geliştirme nedenimiz.",
  "manifesto.identity": "Kontrolü sende olan bir kimlik.",
  "manifesto.data": "Paylaşımına senin karar verdiğin veri.",
  "manifesto.infrastructure": "Birlikte geliştirdiğimiz altyapı.",
  "home.exploreTitle": "Tek ağ.<br>Kendi yolunu bul.",
  "home.networkTitle": "Her şeyin temelindeki kaynaklar.",
  "home.networkBody": "Başlangıç noktası dağıtık depolama. Mevcut temeli ve depolama, bant genişliği, hesaplama için planlanan pazarları keşfet.",
  "home.networkLink": "Ağı tanı",
  "home.appsTitle": "Nodus günlük hayatında.",
  "home.appsBody": "Özel konuşmalar, sosyal paylaşımlar ve ödemeler. Uygulamaları ve onları bir araya getiren zinciri tanı.",
  "home.appsLink": "Ürünleri keşfet",
  "home.manifestoLink": "Manifestomuzu oku",
  "home.roadmapBody": "Bugüne kadar yaptıklarımız.<br>Önümüzdeki işler.",
  "nav.products": "Ürünler",
  "nav.home": "Ana sayfa",
  "product.connect.category": "SOHBET VE TOPLULUK",
  "product.connect.description": "Özel konuşmalar, herkese açık sosyal hayat ve elinin altında bir cüzdan.",
  "detail.docs": "Geliştirici rehberi",
  "detail.capabilities": "Daha yakından bak.",
  "product.connect.feature0": "Şifreli birebir ve grup sohbetleri; sesli mesaj, görsel ve video.",
  "product.connect.feature1": "Çevrimdışı teslim, okundu bilgisi ve kalıcı medya kuyruğu.",
  "product.connect.feature2": "Profiller, takip sistemi, herkese açık duvar paylaşımları ve sohbetten ödeme.",
  "product.connect.note": "Android, Linux ve Windows için DNA Connect uygulamaları artık dağıtılmıyor; Nodus Connect web’de önizleme olarak açık. Açık duvar paylaşımları başkaları tarafından görülebilir.",
  "detail.allProducts": "Tüm ürünler",
  "detail.next.connect": "Nodus Identity",
  "product.wallet.category": "KONTROL SENDE / ÇOK ZİNCİRLİ",
  "product.wallet.description": "Desteklenen ağların için Connect içinde tek cüzdan.",
  "detail.openConnect": "Connect’i keşfet",
  "product.wallet.feature0": "Ethereum, BNB Smart Chain, Solana, TRON, Cellframe ve testnet’te yerel NODUS.",
  "product.wallet.feature1": "Kişiye ödeme, QR ile gönderme ve alma, bakiyeler ve işlem geçmişi.",
  "product.wallet.feature2": "Tarayıcı cüzdanı <a href=\"https://wallet.nodusnetwork.io/\" target=\"_blank\" rel=\"noopener noreferrer\">wallet.nodusnetwork.io</a> adresinde geliştirme önizlemesinde.",
  "product.wallet.note": "Dış zincirler kendi kriptografisini korur.",
  "detail.wallet.heading": "Cüzdanın sundukları.",
  "detail.next.wallet": "Nodus Identity",
  "product.identity.category": "SENİN ANAHTARLARIN, SENİN İSMİN",
  "product.identity.description": "Kendi anahtarlarınla oluşturup geri yüklediğin bir kimlik.",
  "product.identity.feature0": "Telefon numarası veya e-posta adresi olmadan kimlik oluştur.",
  "product.identity.feature1": "DHT üzerindeki kriptografik kimliğine bağlı bir isim kaydet.",
  "product.identity.feature2": "Kimlik anahtarları ve türetilmiş cüzdan hesapları için 24 kelimelik kurtarma ifadesi kullan.",
  "product.identity.note": "Identity, Connect’in bir parçasıdır. Anahtar kurtarma, her yerel mesajın veya dosyanın geri gelmesini garanti etmez.",
  "detail.identity.heading": "Kimliğinle başla.",
  "detail.next.identity": "Nodus Wallet",
  "product.chain.category": "YEREL ZİNCİR / TESTNET",
  "product.chain.description": "Ortak ağ hizmetleriyle birlikte geliştirilen yerel mutabakat katmanı.",
  "product.chain.feature0": "Kuantum sonrası imzalar ve BFT witness düğümleriyle şeffaf UTXO muhasebesi.",
  "product.chain.feature1": "Geliştirme; yerel varlıkları, staking’i, delegasyonu ve zincir parametrelerini kapsar.",
  "product.chain.feature2": "Testnet coin’i: NODUS. Geçiş boyunca bazı kodlar ve araçlar hâlâ DNAC adını kullanıyor.",
  "product.chain.note": "Testnet zaten Ledger V2 ile çalışıyor. Gizli işlemler geliştirme konusu olmaya devam ediyor. Burada halka açık bir çıkış tarihi duyurulmamıştır.",
  "detail.chain.heading": "Ortak kayıt katmanı.",
  "detail.next.chain": "Yol haritasını incele",
  "product.scan.category": "BLOK GEZGİNİ / TESTNET",
  "product.scan.description": "Testnet zincirine salt okunur bir bakış.",
  "product.scan.feature0": "İndekslenmiş blokları ve işlemleri incele.",
  "product.scan.feature1": "İşlem ara ve adres geçmişini görüntüle.",
  "product.scan.feature2": "Gezginin JSON API’sıyla entegrasyon geliştir.",
  "product.scan.note": "Nodus Scan testnet zincirini okur ve tutarları NODUS olarak gösterir. Geçiş boyunca bazı kodlar ve araçlar hâlâ DNAC adını kullanıyor.",
  "detail.scan.heading": "Testnet’e bir bakış.",
  "detail.next.scan": "Nodus Identity",
  "nav.wiki": "Wiki",
  "nav.scan": "Scan",
  "resources.title": "Ağa biraz daha yakından bak.",
  "resources.body": "Bir rehber bul, zinciri takip et veya geliştirmeye başla.",
  "resources.wiki": "Wiki ile öğren",
  "resources.wikiBody": "Kimliğin, sohbetlerin, cüzdanın ve kaynak ağı için rehberler.",
  "resources.scan": "Scan ile keşfet",
  "resources.scanBody": "Testnet’teki blokları, işlemleri ve adres geçmişini incele.",
  "resources.build": "Nodus ile geliştir",
  "resources.buildBody": "Ekosistemin arkasındaki mimari, API’ler ve kod.",
  "docs.wikiPrompt": "Uygulama yardımı mı arıyorsun? Wiki ile başla.",
  "footer.terms": "Hizmet Şartları",
  "footer.privacy": "Gizlilik",
  "nav.tokenomics": "Tokenomik",
  "tok.label": "TOKENOMİK / TESTNET",
  "tok.title": "NODUS arzı.",
  "tok.intro": "Nodus Chain bir testnet. Coin’i NODUS’un toplam arzı sabit: zincirin genesis’ine yazılmış 1.000.000.000; yeni coin basılmaz. Bu sayfa arzın nasıl dağıtıldığını ve doğrulayıcı ödüllerinin nasıl ödendiğini gösterir. Güncel rakamlar için Scan’e bak.",
  "tok.supplyNav": "Sabit arz",
  "tok.allocationNav": "Dağılım",
  "tok.poolsNav": "Genesis’te nasıl tutuluyor",
  "tok.rewardsNav": "Doğrulayıcı ödülleri",
  "tok.liveNav": "Güncel rakamlar",
  "tok.supplyTitle": "Sabit bir arz.",
  "tok.supplyBody": "Toplam arz 1.000.000.000 NODUS. Tutarın tamamı ilk bloktan itibaren vardır ve aşağıdaki tahsislere bölünmüştür. Yeni NODUS basılmaz: doğrulayıcı ödülleri aynı sabit arzın parçası olan bir rezervden ödenir.",
  "tok.testnetNote": "Nodus Chain şu anda bir testnet. Bu sayfa testnet genesis’inin tuttuğu dağılımı anlatır. Fiyat veya değer hakkında hiçbir şey söylemez ve bir teklif değildir.",
  "tok.allocationTitle": "Dağılım.",
  "tok.allocationBody": "Toplam arzı on bir tahsis oluşturur.",
  "tok.colAllocation": "Tahsis",
  "tok.colAmount": "NODUS",
  "tok.colShare": "Pay",
  "tok.rowRewards": "Doğrulayıcı ödülleri",
  "tok.rowStorage": "Storage",
  "tok.rowCompute": "Compute",
  "tok.rowBandwidth": "Bandwidth",
  "tok.rowFuture": "Gelecekteki hizmetler",
  "tok.rowSecurity": "Güvenlik / bug bounty",
  "tok.rowLiquidity": "Likidite",
  "tok.rowFounder": "Kurucu",
  "tok.rowEcosystem": "Ekosistem / geliştirici hibeleri",
  "tok.rowFoundation": "Foundation",
  "tok.rowAirdrop": "Airdrop bütçesi",
  "tok.airdropBudget": "50.000.000 NODUS’luk airdrop bütçesinin (toplam arzın %5’i) 10.000.000’u (%1) ilk CPUNK Community Airdrop’a, 40.000.000’u (%4) gelecekteki airdrop’lara ayrılır. <a href=\"airdrop.html#overview\">İlk CPUNK airdrop’unu incele →</a>",
  "tok.rowTotal": "Toplam",
  "tok.poolsTitle": "Genesis’te nasıl tutuluyor.",
  "tok.poolsBody": "Testnet genesis’i her tahsisi beş biçimden birinde tutar.",
  "tok.poolsReward": "<strong>Ödül rezervi — 200.000.000.</strong> Zincirin kendisi tutar ve aşağıda anlatıldığı gibi epoch epoch doğrulayıcılara öder.",
  "tok.poolsService": "<strong>Hizmet havuzları — 300.000.000.</strong> Storage (100.000.000), Compute (100.000.000), Bandwidth (50.000.000) ve Gelecekteki hizmetler (50.000.000) zincir durumunda kilitlidir. Hiçbir anahtar onları kontrol etmez ve onları serbest bırakan bir kural henüz yoktur.",
  "tok.poolsFoundation": "<strong>Foundation multisig’i — 380.000.000.</strong> Güvenlik / bug bounty (50.000.000), Likidite (150.000.000), Ekosistem / geliştirici hibeleri (100.000.000), Foundation (30.000.000) ve Airdrop bütçesi (50.000.000) ilk bloktan itibaren coin olarak vardır ve Foundation’ın 2-of-3 multisig adresine aittir: her harcama üç anahtarından ikisini gerektirir.",
  "tok.poolsStake": "<strong>Genesis doğrulayıcı stake’leri — 70.000.000.</strong> Zincir, her biri 10.000.000 stake eden yedi doğrulayıcıyla başlar. Bu stake’ler Foundation tahsisinden karşılanır; Foundation’ın kendi coin’lerinin 100.000.000’un 30.000.000’u olmasının nedeni budur. Bir genesis doğrulayıcısı ayrıldığında stake’i Foundation multisig adresine döner.",
  "tok.poolsFounder": "<strong>Kurucu — 50.000.000.</strong> Yalnız kurucunun anahtarının claim edebildiği bir genesis tahsisi.",
  "tok.rewardsTitle": "Doğrulayıcı ödülleri.",
  "tok.rewardsBody": "Doğrulayıcılara yeni coin’den değil, 200.000.000’luk ödül rezervinden ödeme yapılır.",
  "tok.rewardsEpoch": "Bir epoch 720 bloktur. Her epoch’un sonunda rezervin 1/65.536’sı (aşağı yuvarlanarak) o epoch’u yöneten doğrulayıcılar arasında stake’leri oranında paylaştırılır: kendi stake’leri artı onlara delege edilen miktar.",
  "tok.rewardsCommission": "Delege edilmiş stake’in kazandığı kısımdan doğrulayıcı komisyonunu alır, kalanı delegatörlerine delegasyonları oranında gider. Her doğrulayıcı kendi komisyonunu belirler; üst sınır %50.",
  "tok.rewardsBar": "Bir epoch’a yeterince katılmayan doğrulayıcı o epoch için hiçbir şey kazanmaz, delegatörleri de kazanmaz; o pay rezervde kalır.",
  "tok.rewardsPayout": "Ödüller her epoch kaydedilir ve her 24 epoch’ta bir ödenir.",
  "tok.rewardsFees": "Token oluşturma ücreti dahil işlem ücretleri ödül rezervine eklenir. Yakılmazlar.",
  "tok.liveTitle": "Güncel rakamlar.",
  "tok.liveBody": "Yukarıdaki rakamlar genesis dağılımıdır. <a href=\"https://scan.nodusnetwork.io/stats.html\">Scan İstatistikler</a> sayfasını aç ve Toplam arz / Dolaşımdaki arz değerlerinin altındaki <strong>Detaylar</strong>’ı seç; kalan ödül rezervini ve her hizmet havuzunu görürsün.",
  "tok.liveCirculating": "Dolaşımdaki arz; ödül rezervi, hizmet havuzları ve claim edilmemiş tahsis dışında var olan her coin’dir. Stake edilmiş coin’ler ve Foundation’ın coin’leri dolaşımda sayılır. İlk blokta bu 450.000.000 NODUS idi: Foundation’ın 380.000.000’u ve 70.000.000’luk doğrulayıcı stake’leri.",
  "tok.liveCta": "Güncel arzı Scan’de gör ↗",
  "tok.earnNav": "NODUS nasıl kazanılır",
  "tok.epochsNav": "Epoch’lar ve ödeme günleri",
  "tok.calcNav": "Ödül nasıl hesaplanır",
  "tok.validatorNav": "Doğrulayıcı çalıştırmak",
  "tok.delegateNav": "Delege etmek",
  "tok.rolesNav": "Roller",
  "tok.plannedNav": "Planlanan değişiklikler",
  "tok.earnTitle": "NODUS nasıl kazanılır.",
  "tok.earnBody": "Testnet’te bugün NODUS kazanmanın iki yolu var ve ikisi de ödül rezervinden ödenir: bir doğrulayıcı çalıştırmak ya da NODUS’u bir doğrulayıcıya delege etmek. Aşağıdaki bölümler her birinin ne gerektirdiğini, ödülün nasıl hesaplandığını ve ne zaman ödendiğini anlatır. Bir bölüm planlandığını söylemedikçe burada anlatılan her şey zincirin bugün çalıştırdığı kurallardır.",
  "tok.earnValidator": "<strong>Doğrulayıcı çalıştır.</strong> Kendi NODUS’unu bağlarsın, blok imzalayan bir düğüm çalıştırırsın ve her epoch ödülünden stake’in oranında pay, ayrıca delegatörlerinden komisyon kazanırsın.",
  "tok.earnDelegate": "<strong>Delege et.</strong> NODUS’unu başkasının çalıştırdığı bir doğrulayıcıya bağlarsın. O doğrulayıcının ödülünden, komisyonu düşüldükten sonra pay kazanırsın. Düğüm çalıştırmazsın.",
  "tok.earnLive": "Kalan rezerv ve diğer güncel rakamlar Scan’de; aşağıdaki <a href=\"#live\">Güncel rakamlar</a> bölümüne bak.",
  "tok.epochsTitle": "Epoch’lar ve ödeme günleri.",
  "tok.epochsBody": "Ödüller epoch’larla sayılır ve ödeme günlerinde ödenir.",
  "tok.epochsLength": "<strong>Bir epoch 720 bloktur.</strong> İşlem varken bloklar yaklaşık 4–5 saniyede bir, zincir boştayken 60 saniyede bir gelir. Bu yüzden bir epoch zincir yoğunken kabaca bir saat, boştayken en fazla yaklaşık on iki saat sürer.",
  "tok.epochsReward": "<strong>Epoch başına ödül</strong>, ödül rezervinin 65.536’ya bölünüp aşağı yuvarlanmasıdır. 200.000.000’luk rezervin tamamıyla bu epoch başına yaklaşık 3.051 NODUS eder. Rezerv ödendikçe yavaşça küçülür, ücretlerle yeniden büyür; çünkü her işlem ücreti rezerve eklenir.",
  "tok.epochsPayday": "<strong>Ödeme günü her 24 epoch’ta bir.</strong> Ödüller her epoch’un sonunda hesaplanır ve her 24 epoch’ta bir, kazananın adresine sıradan coin olarak ödenir.",
  "tok.epochsLeave": "<strong>Ayrılmak ödülleri silmez.</strong> Stake’ini çeker ya da delegasyonunu geri alırsan, o ana kadar kazandığın ödüller yine normal ödeme gününde ödenir.",
  "tok.calcTitle": "Ödül nasıl hesaplanır.",
  "tok.calcBody": "Her epoch’un sonunda zincir her payı üç adımda hesaplar.",
  "tok.calcStepValidators": "<strong>1. Doğrulayıcılar arasında.</strong> Epoch ödülü, o epoch’u yöneten doğrulayıcılar arasında stake’leri oranında paylaştırılır: her doğrulayıcının kendi bağladığı miktar artı ona yapılan delegasyonlar.",
  "tok.calcStepInside": "<strong>2. Doğrulayıcının payı içinde.</strong> Doğrulayıcı kendi stake’inin kazandığı kısmı alır. Delege edilmiş stake’in kazandığı kısımdan da komisyonunu alır.",
  "tok.calcStepDelegators": "<strong>3. Delegatörlere.</strong> Delege edilmiş kısmın kalanı, doğrulayıcının delegatörlerine delegasyonları oranında gider.",
  "tok.calcRulesIntro": "Stake’in kazanıp kazanmayacağını üç kural belirler.",
  "tok.calcWholeEpoch": "<strong>Yalnız tam epoch’lar.</strong> Bir epoch için yalnız o epoch boyunca baştan sona bağlı kalan stake kazanır.",
  "tok.calcParticipation": "<strong>Katılım.</strong> Bir doğrulayıcı bir epoch’ta blokların en az %50’sini imzalamalı ve epoch’un son 120 bloğunda en az bir kez imza atmalıdır. Bunu karşılamayan doğrulayıcı o epoch için hiçbir şey kazanmaz, delegatörleri de ondan hiçbir şey kazanmaz. Bunu art arda iki epoch’ta karşılamayan doğrulayıcı aktif kümeden çıkarılır.",
  "tok.calcRemainder": "<strong>Kazanılmayan rezervde kalır.</strong> Kimsenin kazanmadığı paylar ve yuvarlama artıkları ödenmez; ödül rezervinde kalır.",
  "tok.calcExample": "<strong>Bir örnek, tahmin değil.</strong> Eşit stake’li yedi doğrulayıcı yaklaşık 3.051 NODUS’luk bir epoch ödülünü paylaşır; her biri o epoch için yaklaşık 436 NODUS alır. Bir doğrulayıcının toplam stake’inin %1’ine sahip olan ve o doğrulayıcının %10 komisyon aldığı bir delegatör, o epoch için %1 × 436 × %90 ≈ 3,9 NODUS alır — ve bu yalnız doğrulayıcı katılım kuralını karşıladıysa geçerlidir. Gerçek rakamlar o anki rezerve, stake’lere ve komisyonlara bağlıdır.",
  "tok.calcSlashing": "<strong>Slashing yok.</strong> Bugün hiçbir stake, ne doğrulayıcının ne delegatörün, hiçbir zaman kesilmez. Katılım kuralını karşılamamak o epoch’un ödülüne mal olur, stake’e değil.",
  "tok.validatorTitle": "Doğrulayıcı çalıştırmak.",
  "tok.validatorBody": "Bir doğrulayıcı blok imzalayan ve ağın verisini saklayan bir düğüm çalıştırır.",
  "tok.validatorBond": "Doğrulayıcı olmak için kendi NODUS’undan <strong>tam olarak 10.000.000 bağla</strong>.",
  "tok.validatorSet": "<strong>En fazla 32 doğrulayıcı aktiftir.</strong> Önceki epoch sınırında dondurulan bakiyelere göre toplam stake’leriyle (kendi bağladıkları artı delegasyonlar) seçilirler. Yeni bir doğrulayıcı seçilebilmeden önce iki tam epoch bekler. 32’nin dışında kalan doğrulayıcılar imza görevi ve ödülü olmayan uygun adaylar olarak bekler ve her epoch yeniden sıralanır.",
  "tok.validatorCommission": "<strong>Komisyonu</strong> doğrulayıcı belirler; %0 ile %50 arası. Artış ancak en az iki epoch sonra geçerli olur, böylece delegatörler önce ayrılabilir; düşüş hemen geçerli olur.",
  "tok.validatorLeave": "<strong>Ayrılmak.</strong> Stake’ini çektikten sonra doğrulayıcı, içinde bulunduğu dondurulmuş liste sona erene kadar kümede kalır ve o zamana kadar düğümünü çalıştırmaya ve imza atmaya devam etmelidir. Ardından bağladığı miktar harcanabilmeden önce 84 epoch boyunca kilitli kalır.",
  "tok.validatorTools": "<strong>Araçlar.</strong> Bugün doğrulayıcılar komut satırı aracı nodus-cli ile kurulur. Web cüzdanındaki “Doğrulayıcı ol” düğmesi kaldırıldı; <a href=\"#planned\">Planlanan değişiklikler</a> altında anlatılan değişiklikle geri gelecek.",
  "tok.validatorGenesis": "<strong>Başlangıçta</strong> zincirde her biri 10.000.000’luk yedi Foundation doğrulayıcısı vardır.",
  "tok.delegateTitle": "Delege etmek.",
  "tok.delegateBody": "Delege etmek, düğüm çalıştırmadan kazanmanı sağlar.",
  "tok.delegateMin": "<strong>En az 100 NODUS.</strong> Bir doğrulayıcının en fazla 2.048 delegatörü olabilir.",
  "tok.delegateWallet": "<strong>Web cüzdanından ya da Nodus Connect’ten.</strong> Delege etme işlemi web cüzdanında ya da Nodus Connect’te, Earn bölümünde yapılır.",
  "tok.delegateEarn": "<strong>Kazandığın</strong>, yukarıdaki hesabı izler: doğrulayıcının katılım kuralını karşıladığı her tam epoch için, doğrulayıcının delege edilmiş payından senin kısmın, komisyonu düşülerek.",
  "tok.delegateLeave": "<strong>Delegasyonu geri almak.</strong> Stake’in doğrulayıcının oy gücünden çıkana kadar bağlı kalır, ardından 12 epoch boyunca kilitlenir. Başka bir doğrulayıcıya geçmek de delegasyonu geri almak sayılır.",
  "tok.rolesTitle": "Roller.",
  "tok.rolesBody": "Ağda dört tür iş var: doğrulama, storage, compute ve bandwidth. Bugün yalnız doğrulamanın kendi stake’i ve ödülü var.",
  "tok.colRole": "Rol",
  "tok.colToday": "Bugün",
  "tok.colPlannedStake": "Planlanan stake",
  "tok.roleValidator": "Doğrulayıcı",
  "tok.roleValidatorToday": "Tam olarak 10.000.000 bağlanır; epoch ödülünü kazanır",
  "tok.roleValidatorPlanned": "En az 2.000.000",
  "tok.roleStorageToday": "Doğrulayıcılar yapar; henüz ayrı bir ödül yok",
  "tok.roleComputeToday": "Henüz ayrı bir rol yok",
  "tok.roleBandwidthToday": "Henüz ayrı bir rol yok",
  "tok.rolesPools": "Storage (100.000.000), Compute (100.000.000), Bandwidth (50.000.000) ve Gelecekteki hizmetler (50.000.000) havuzları kilitlidir ve onları serbest bırakan bir kural henüz yoktur. Tablodaki planlanan stake’ler <a href=\"#planned\">Planlanan değişiklikler</a> altında anlatılır.",
  "tok.plannedTitle": "Planlanan değişiklikler.",
  "tok.plannedNote": "<strong>Planlandı, canlı değil.</strong> Aşağıdaki değişikliklere karar verildi ama zincirde çalışmıyorlar. Yalnız oylanarak kabul edilen bir hard fork ile gelirler ve rakamlar hâlâ değişebilir.",
  "tok.plannedBond": "<strong>Daha düşük doğrulayıcı bağı.</strong> Doğrulayıcı bağı en az 2.000.000 NODUS’a iner. Bağın üstünde stake ettiğin her şey kendine delegasyon sayılır ve her delegasyon gibi 12 epoch kilitlidir.",
  "tok.plannedRoles": "<strong>Kendi stake’i olan ayrı roller.</strong> Storage 1.000.000, compute 1.000.000, bandwidth 500.000 ve doğrulayıcı 2.000.000. Bu miktarlar oylamayla değiştirilebilen zincir parametreleri olur.",
  "tok.plannedCap": "<strong>Güç sınırı.</strong> Tek bir doğrulayıcı için sayılan güç sınırlanır; başlangıçta toplam gücün %10’u, oylamayla değiştirilebilir. Sınırın üstündeki stake sayılmaz ve hiçbir şey kazanmaz; sınıra kadar olan kısım normal kazanır.",
  "tok.plannedKeys": "<strong>Ayrı sahip ve düğüm anahtarları.</strong> Sahibin anahtarı — parayı koyan ve stake’i çekebilen cüzdan — sunucudaki düğüm anahtarından ayrılır. Böylece bir düğüm çalıştırıp ona web cüzdanından stake edebilirsin ve sahip bir multisig olabilir.",
  "tok.plannedStorage": "<strong>Storage ödülleri.</strong> Storage rolüne 1.000.000 NODUS stake ile kayıt olan düğümler, doğrulayıcılar sakladıkları veriyi sunduklarını onayladığında Storage havuzundan eşit pay kazanır. Doğrulayıcılar storage ödülü almaz; bir storage düğümü ile bir doğrulayıcı aynı makine olabilir. Tasarım 4 Ekim 2026’da onaylandı ve geliştiriliyor; daha sonra doğrulayıcıların oyladığı bir hard fork ile devreye girer.",
  "nav.airdrop": "Airdrop",
  "air.label": "AIRDROP / TESTNET",
  "air.title": "Airdrop.",
  "air.intro": "CPUNK Community Airdrop, Nodus’un ilk airdrop kampanyasıdır; ardından başka airdrop’lar da yapılacak. Bu sayfa ilk kampanyaya kimlerin katılabileceğini, nasıl kaydolacağını ve payını nasıl alacağını anlatır.",
  "air.overviewNav": "İlk kampanya: CPUNK",
  "air.whoNav": "Hangi CPUNK sayılır",
  "air.shareNav": "Payın",
  "air.stepsNav": "Adım adım",
  "air.checksNav": "Nasıl denetlenir",
  "air.safetyNav": "Güvende kal",
  "air.moreNav": "Daha fazlası",
  "air.overviewTitle": "İlk airdrop: CPUNK topluluğu.",
  "air.overviewBody": "CPUNK Community Airdrop, CPUNK sahipleri arasında 10.000.000 NODUS paylaştırır. 365 gün (bir yıl) boyunca her gün ödenir ve her gün bir önceki günün payını alırsın. Yakında başlıyor; kesin başlangıç duyurulacak. Aşağıdaki koşullar yalnızca bu ilk kampanya için geçerlidir.",
  "air.testnetNote": "Nodus Chain şu anda bir testnet. Bu sayfa airdrop’un nasıl işlediğini anlatır. Fiyat veya değer hakkında hiçbir şey söylemez ve bir teklif değildir.",
  "air.whoTitle": "Hangi CPUNK sayılır.",
  "air.whoBody": "Yalnızca kendi Nodus Connect cüzdanının CPUNK adresinde tutulan CPUNK sayılır.",
  "air.whoAddress": "<strong>Nodus Connect CPUNK adresin.</strong> Nodus Connect bu adresi, bir Cellframe Backbone adresini, 24 kelimelik kurtarma ifadenden türetir.",
  "air.whoExchange": "<strong>Borsada değil.</strong> Bir borsada tutulan CPUNK sayılmaz.",
  "air.whoOther": "<strong>Başka cüzdan yok.</strong> Airdrop’a başka hiçbir cüzdan bağlanmaz.",
  "air.shareTitle": "Payın.",
  "air.shareBody": "Payın, adresinin ne kadar CPUNK tuttuğuna göre belirlenir.",
  "air.shareUnits": "<strong>1.000.000 CPUNK’lık tam birimler.</strong> CPUNK, 1.000.000’luk tam birimlerle sayılır. 1.000.000 CPUNK’tan az tutan bir adres hiçbir şey almaz.",
  "air.shareLowest": "<strong>Her günün en düşük bakiyesi.</strong> Adresin, her gün o günün en düşük bakiyesiyle sayılır.",
  "air.stepsTitle": "Adım adım.",
  "air.step1": "<strong>1. Nodus Connect hesabını oluştur.</strong> <a href=\"https://connect.nodusnetwork.io/\">connect.nodusnetwork.io</a> adresini aç, hesabını oluştur ve 24 kelimelik kurtarma ifadeni bir yere yaz.",
  "air.step2": "<strong>2. CPUNK adresini bul.</strong> Connect’in cüzdanında CPUNK adresini bul.",
  "air.step3": "<strong>3. CPUNK’ını oraya taşı.</strong> CPUNK’ını şu an nerede tutuyorsan oradan bu adrese gönder.",
  "air.step4": "<strong>4. Airdrop’a kaydol.</strong> Nodus Connect’e bir “Register for airdrop” düğmesi geliyor. Kayıt tek tıklamadır; hiçbir şey taşınmaz ve hiçbir şey ödenmez.",
  "air.step5": "<strong>5. Nodus Connect’te ismini seç.</strong> Kaydolduktan sonra, zincir üstü isminin kaydını karşılaman için sana az miktarda NODUS gönderilir. Bu yalnızca en az 1.000.000 CPUNK tutan bir adres içindir.",
  "air.step6": "<strong>6. Her gün Claim’e bas.</strong> Connect’i aç ve Claim’e bas; bir geri sayım ne kadar süren kaldığını gösterir. Her gün bir önceki günün payını alırsın. Zamanında alınmayan pay airdrop havuzuna geri döner ve kalan günlere paylaştırılır.",
  "air.checksTitle": "Nasıl denetlenir.",
  "air.checksSign": "<strong>Cihazında imzalanır.</strong> Kaydolduğunda Connect, CPUNK adresinin ve Nodus hesabının birbirine ait olduğunu cihazında imzalar. Kurtarma ifaden cihazından hiç çıkmaz.",
  "air.checksService": "<strong>Airdrop hizmeti denetler.</strong> Nodus Foundation’ın airdrop hizmeti imzaları ve bakiyeleri denetler ve NODUS’u gönderir.",
  "air.checksPublished": "<strong>Her gün yayımlanır.</strong> Her günün sayılan adres listesi parmak iziyle (hash) birlikte yayımlanır; böylece herkes ödemeleri denetleyebilir.",
  "air.safetyTitle": "Güvende kal.",
  "air.safetyBody": "<strong>Sana asla özelden mesaj atmayız ve kurtarma ifadeni asla istemeyiz.</strong> Yalnızca nodusnetwork.io üzerindeki bağlantıları kullan.",
  "air.moreTitle": "Daha fazlası.",
  "air.moreBody": "NODUS arzının tüm dağılımı için <a href=\"tokenomics.html#allocation\">Tokenomik</a> sayfasına bak.",
  "air.connectCta": "Nodus Connect’i aç ↗",
  "team.label": "EKİP",
  "team.title": "Nodus’un arkasındakiler",
  "team.founderRole": "Kurucu ve Baş Mimar, Nodus Foundation",
  "team.cfoRole": "CFO, Nodus Foundation",
  "legal.label": "HUKUKİ",
  "legal.email": "<strong>E-posta:</strong> <a href=\"mailto:legal@nodusnetwork.io\">legal@nodusnetwork.io</a>",
  "legal.website": "<strong>Web sitesi:</strong> <a href=\"https://nodusnetwork.io/\">nodusnetwork.io</a>",
  "legal.source": "<strong>Kaynak kodu:</strong> <a href=\"https://github.com/nocdem/dna\" target=\"_blank\" rel=\"noopener noreferrer\">github.com/nocdem/dna</a>",
  "terms.title": "Hizmet Şartları",
  "terms.subtitle": "Nodus Connect — Kuantum Sonrası Şifreli İletişim Uygulaması. Mevcut Android, Linux ve Windows sürümleri DNA Connect adını korur.",
  "terms.effective_date": "Yürürlük Tarihi: 5 Nisan 2026 · Son Güncelleme: 23 Eylül 2026",
  "terms.s1.title": "1. Şartların Kabulü",
  "terms.s1.p1": "Nodus Connect’i (“Uygulama”) indirerek, yükleyerek veya kullanarak bu Hizmet Şartları’na bağlı olmayı kabul etmiş olursunuz. Bu şartları kabul etmiyorsanız Uygulamayı kullanmayın.",
  "terms.s1.highlight": "Nodus Connect; merkeziyetsiz, eşler arası bir mesajlaşma uygulamasıdır. Hesap kurtarma, içerik denetleme veya veri erişimi için iletişime geçilecek merkezi bir hizmet sağlayıcı yoktur. Kurtarma ifadenizi ve ağda yayınladığınız tüm içerikleri korumak tamamen sizin sorumluluğunuzdadır.",
  "terms.s2.title": "2. Yeterlilik",
  "terms.s2.p1": "Nodus Connect’i kullanabilmek için en az 13 yaşında olmanız gerekir. Bulunduğunuz yargı bölgesinde reşit değilseniz ebeveyn veya yasal vasi onayı almanız gerekmektedir. Uygulamayı kullanarak bu yeterlilik şartlarını karşıladığınızı beyan ve taahhüt edersiniz.",
  "terms.s2.p2": "Bulunduğunuz ülke veya bölgedeki tüm yürürlükteki yasalara uymanız gerekir. Uygulama, yerel yasalarla yasaklanan yerlerde kullanılamaz.",
  "terms.s3.title": "3. Hesabınız ve Kurtarma İfadeniz",
  "terms.s3.p1": "Nodus Connect hiçbir sunucuda kullanıcı hesabı tutmaz. Kimliğiniz, 24 kelimelik BIP39 kurtarma ifadesinden türetilmiş, yerel olarak oluşturulmuş kuantum sonrası bir kriptografik anahtar çiftidir.",
  "terms.s3.p2": "<strong>Kurtarma ifadenizin tek sorumlusu sizsiniz.</strong> Cihazınızı kaybetmeniz durumunda kimliğinize, mesajlarınıza, kişilerinize ve cüzdanlarınıza erişimi geri kazanmanın tek yolu budur. Asla kimseyle paylaşmayın. Sizin için kurtarmamız mümkün değildir — hiçbir destek ekibi, yardım masası veya merkezi hizmetin buna erişimi yoktur.",
  "terms.s3.li1": "Kurtarma ifadesinin kaybedilmesi, kimliğinize ve ilişkili kripto para bakiyelerinize kalıcı erişim kaybı anlamına gelir.",
  "terms.s3.li2": "Kurtarma ifadesinin üçüncü bir tarafa ifşa edilmesi, kimliğinize, mesajlarınıza ve cüzdanlarınıza tam erişim hakkı verir.",
  "terms.s3.li3": "Kurtarma ifadenizi çevrimdışı olarak, kağıt veya donanım üzerinde, birden fazla güvenli konumda saklayın.",
  "terms.s4.title": "4. Kullanım Lisansı",
  "terms.s4.p1": "Nodus Connect uygulamasının (Flutter) kodu özel lisansla incelemeye açıktır. Messenger C kütüphanesi, Nodus sunucusu, DNAC ve ortak kriptografi Apache 2.0 lisanslıdır. Ekosistemin tamamı tek bir açık kaynak lisansına sahip değildir. Kaynak kodu <a href=\"https://github.com/nocdem/dna\" target=\"_blank\" rel=\"noopener noreferrer\">github.com/nocdem/dna</a> adresinde mevcuttur. Bu Şartlara tabi olmak kaydıyla, Uygulamayı sahip olduğunuz veya kontrol ettiğiniz cihazlara yükleme ve kullanma konusunda size kişisel, münhasır olmayan, devredilemez bir lisans verilmektedir.",
  "terms.s4.p2": "Yetkilendirme almadan Nodus Connect veya DNA Connect adını ya da markasını kullanarak Uygulamanın değiştirilmiş sürümlerini dağıtamazsınız, güvenlik kontrollerini aşmak amacıyla ikili dosyayı tersine mühendislik işlemine tabi tutamazsınız veya Uygulamayı bu Şartları ya da yürürlükteki yasaları ihlal etmek için kullanamazsınız.",
  "terms.s5.title": "5. Kabul Edilebilir Kullanım",
  "terms.s5.p1": "Nodus Connect’i aşağıdaki amaçlarla KULLANMAMAYI kabul edersiniz:",
  "terms.s5.li1": "Yasadışı, taciz edici, hakaret içeren, kötüleyici, tehditkar, müstehcen veya başka herhangi bir sakıncalı içerik göndermek.",
  "terms.s5.li2": "Herhangi bir kişi veya kuruluşun kimliğine bürünmek ya da herhangi bir kişi veya kuruluşla bağlantınızı yanlış beyan etmek.",
  "terms.s5.li3": "Kötücül yazılım, virüs, fidye yazılımı veya herhangi bir zararlı kod dağıtmak.",
  "terms.s5.li4": "Diğer kullanıcıları hedef alan oltalama, dolandırıcılık veya sahtecilik faaliyetlerinde bulunmak.",
  "terms.s5.li5": "Çocuk cinsel istismarı materyali (CSAM) veya küçüklerin istismarını içeren herhangi bir içeriği yayınlamak, iletmek veya talep etmek.",
  "terms.s5.li6": "Telif hakkı, marka veya ticari sırlar dahil fikri mülkiyet haklarını ihlal etmek.",
  "terms.s5.li7": "Nodus merkeziyetsiz ağının bütünlüğüne, performansına veya güvenliğine müdahale etmek ya da bunları bozmak.",
  "terms.s5.li8": "Diğer kullanıcıların kimliklerine, mesajlarına veya cüzdanlarına yetkisiz erişim girişiminde bulunmak.",
  "terms.s5.li9": "Uygulamayı kara para aklama, terör finansmanı, yaptırım ihlali veya diğer yasadışı mali faaliyetler için kullanmak.",
  "terms.s5.p2": "Nodus Connect merkeziyetsiz olduğundan, merkezi bir uygulama makamı yoktur. İhlaller aşağıdaki iletişim bilgileri aracılığıyla proje ekibine bildirilebilir, ancak yaptırım nihayetinde Nodus ağı operatörlerine ve ihlalcinin yargı bölgesindeki yerel kolluk kuvvetlerine bağlıdır.",
  "terms.s6.title": "6. Kullanıcı Tarafından Oluşturulan İçerik",
  "terms.s6.p1": "Uygulama aracılığıyla yayınladığınız tüm içeriklerin — doğrudan mesajlar, grup mesajları, duvar gönderileri, yorumlar, profil bilgileri ve medya ekleri dahil — tam mülkiyeti size aittir.",
  "terms.s6.p2": "Merkeziyetsiz ağa içerik yayınlayarak, ağ operatörlerine bu içeriği hedeflenen alıcılara ulaştırma amacıyla depolama, çoğaltma ve iletme konusunda münhasır olmayan, dünya çapında, telifsiz bir lisans vermiş olursunuz. Bu lisans, içerik ağ TTL (yaşam süresi) süresine göre sona erdiğinde veya siz içeriği kaldırdığınızda sona erer.",
  "terms.s6.p3": "<strong>Yayınladığınız içeriğin tek sorumlusu sizsiniz.</strong> Herkese açık olarak yayınlanan içerik (duvar gönderileri, herkese açık profil) Nodus ağının birçok düğümünde çoğaltılabilir ve önbelleğe alınabilir; tam silinmesi garanti edilemez.",
  "terms.s7.title": "7. Kripto Para Cüzdanı",
  "terms.s7.p1": "Nodus Connect, çoklu zincir kripto para cüzdanı özelliği (Cellframe, Ethereum, Solana, TRON, BSC) içermektedir. Aşağıdakileri kabul ve beyan edersiniz:",
  "terms.s7.li1": "<strong>Saklama dışı:</strong> Özel anahtarlar kurtarma ifadenizden türetilir ve cihazınızda yerel olarak saklanır. Özel anahtarlarınıza veya fonlarınıza hiçbir zaman erişimimiz yoktur.",
  "terms.s7.li2": "<strong>Geri alınamazlık:</strong> Kripto para işlemleri geri alınamaz. Yanlış bir adrese gönderim veya hatalı tutar girilmesi kalıcı kayba yol açabilir.",
  "terms.s7.li3": "<strong>Değer dalgalanması:</strong> Kripto para değerleri dalgalanır. Belirli bir değer veya fiyat garantisi vermiyoruz.",
  "terms.s7.li4": "<strong>Vergi sorumluluğu:</strong> Kripto para işlemlerinize ilişkin geçerli vergilerin belirlenmesi ve ödenmesinden yalnızca siz sorumlusunuz.",
  "terms.s7.li5": "<strong>Mevzuata uyum:</strong> Kripto para düzenlemeleri yargı bölgelerine göre değişir. Tarafınıza uygulanan tüm yasalara uymak sizin sorumluluğunuzdadır.",
  "terms.s7.li6": "<strong>Finansal tavsiye değildir:</strong> Uygulama; finansal, yatırım, vergi veya hukuki tavsiye sağlamaz. Gösterilen fiyat bilgileri yalnızca referans amaçlıdır.",
  "terms.s7.li7": "<strong>Ağ ücretleri:</strong> Blok zinciri işlemleri, madencilere/doğrulayıcılara ödenen ağ ücretlerine (gas) tabidir. Bu ücretler tarafımızca tahsil edilmez.",
  "terms.s8.title": "8. Merkeziyetsiz Ağ Uyarısı",
  "terms.s8.p1": "Nodus Connect, mesaj teslimi, profil keşfi ve içerik depolaması için Nodus merkeziyetsiz eşler arası ağını kullanır. Aşağıdakileri kabul edersiniz:",
  "terms.s8.li1": "Temel ağ altyapısı şu anda proje ekibi tarafından sürdürülmekte olup, ağ bağımsız düğüm işletimi için tasarlanmıştır.",
  "terms.s8.li2": "Mesaj teslimi en iyi çaba esasınadır ve garanti edilmez. Mesajlar ağ koşulları, düğüm kesintileri veya TTL süresi dolması nedeniyle gecikebilir veya kaybolabilir.",
  "terms.s8.li3": "Ağa yayınlanan içerik birden fazla düğümde kalabilir ve düğümler depolamaya devam ettiği sürece erişilebilir olabilir.",
  "terms.s8.li4": "Ağın içeriği denetleyecek, politika uygulayacak veya işlemleri geri alacak merkezi bir otoritesi yoktur.",
  "terms.s8.li5": "Ağın erişilebilirliği gönüllü düğüm operatörlerine bağlıdır ve garanti edilemez.",
  "terms.s9.title": "9. Üçüncü Taraf Hizmetler",
  "terms.s9.p1": "Uygulama, cüzdan işlevselliği için üçüncü taraf blok zinciri RPC uç noktalarına (Cellframe, Ethereum, Solana, TRON, BSC) ve bir kripto para fiyat API’sine (BitcoinTry) bağlanır. Bu hizmetler bağımsız sağlayıcılar tarafından işletilmekte olup kendi şart ve politikalarına tabidir.",
  "terms.s9.p2": "Üçüncü taraf hizmetleri kontrol etmiyoruz, garanti vermiyoruz ve sorumluluk kabul etmiyoruz. Üçüncü taraf verilerinin erişilebilirliği, doğruluğu ve güvenliği garanti edilmez.",
  "terms.s10.title": "10. Garanti Reddi; Sorumluluk Sınırlaması",
  "terms.s10.p1": "Nodus Connect, açık veya zımni herhangi bir garanti verilmeksizin “OLDUĞU GİBİ” ve “MEVCUT OLDUĞU ŞEKİLDE” sağlanır; buna satılabilirlik, belirli bir amaca uygunluk, ihlal etmeme veya kesintisiz erişilebilirlik garantileri de dahil ancak bunlarla sınırlı değildir.",
  "terms.s10.p2": "Yürürlükteki yasaların izin verdiği azami ölçüde, Nodus Foundation, katkıda bulunanları veya bağlı kuruluşları; bu tür zararların olasılığı bildirilmiş olsa dahi, Uygulamayı kullanmanızdan kaynaklanan veya bununla ilgili herhangi bir dolaylı, arızi, özel, sonuç niteliğinde veya cezai zarar ya da kâr, gelir, veri veya kripto para kaybından sorumlu tutulamaz.",
  "terms.s10.p3": "Bazı yargı bölgeleri belirli garantilerin hariç tutulmasına veya sorumluluk sınırlamalarına izin vermez. Bu tür yargı bölgelerinde sorumluluk, yasaların izin verdiği azami ölçüde sınırlıdır.",
  "terms.s11.title": "11. Tazminat",
  "terms.s11.p1": "Uygulamayı kullanmanızdan, bu Şartları ihlal etmenizden, yürürlükteki herhangi bir yasayı ihlal etmenizden veya üçüncü tarafların haklarını ihlal etmenizden kaynaklanan her türlü talep, zarar, yükümlülük, kayıp, masraf veya giderlerden (makul avukatlık ücretleri dahil) Nodus Foundation’ı, katkıda bulunanlarını ve bağlı kuruluşlarını tazmin etmeyi ve zararsız tutmayı kabul edersiniz.",
  "terms.s12.title": "12. Fesih",
  "terms.s12.p1": "Uygulamayı kaldırarak istediğiniz zaman kullanmayı bırakabilirsiniz. Sunucu tarafında bir hesap bulunmadığından, bizim tarafımızda bir silme işlemi gerekmez. Ağdaki herkese açık profil verileriniz, TTL süresine göre otomatik olarak sona erecektir.",
  "terms.s12.p2": "Uygulamanın geliştirilmesini, Nodus ağ altyapısını veya ilgili hizmetleri herhangi bir zamanda, herhangi bir nedenle sonlandırma hakkımızı saklı tutarız. Ağ merkeziyetsiz olduğundan, çekirdek ekibin çekilmesi ağın kendisinin sona ermesi anlamına gelmeyebilir.",
  "terms.s13.title": "13. Şartlarda Yapılacak Değişiklikler",
  "terms.s13.p1": "Bu Şartları zaman zaman güncelleyebiliriz. Değişiklikler, güncellenmiş bir “Son Güncelleme” tarihiyle bu sayfaya yansıtılacaktır. Önemli değişiklikler uygulama içi bildirimler veya proje web sitesi aracılığıyla duyurulabilir. Değişikliklerden sonra Uygulamayı kullanmaya devam etmeniz, revize edilmiş Şartları kabul ettiğiniz anlamına gelir.",
  "terms.s14.title": "14. Uygulanacak Hukuk",
  "terms.s14.p1": "Bu Şartlar, Nodus Foundation’ın merkezinin bulunduğu yargı bölgesinin yasalarına tabidir; kanunlar ihtilafı hükümleri dikkate alınmaz. Bu Şartlardan doğan uyuşmazlıklar öncelikle iyi niyetli müzakere yoluyla; müzakere başarısız olursa bağlayıcı tahkim veya ilgili yargı bölgesinin yetkili mahkemeleri aracılığıyla çözülecektir.",
  "terms.s14.p2": "Uygulamayı kullanımınız; veri koruma, telekomünikasyon ve kripto para düzenlemeleri dahil ancak bunlarla sınırlı olmamak üzere ikamet ettiğiniz yerdeki yerel yasalara da tabi olabilir. Bu tür yasalara uyum sizin sorumluluğunuzdadır.",
  "terms.s15.title": "15. İletişim",
  "terms.s15.p1": "Bu Hizmet Şartları hakkında sorularınız varsa:",
  "privacy.title": "Gizlilik Politikası",
  "privacy.subtitle": "Nodus Connect — Kuantum Sonrası Şifreli İletişim Uygulaması. Mevcut Android, Linux ve Windows sürümleri DNA Connect adını korur.",
  "privacy.effective_date": "Yürürlük Tarihi: 17 Mart 2026 · Son Güncelleme: 23 Eylül 2026",
  "privacy.label.purpose": "Amaç:",
  "privacy.label.storage": "Depolama:",
  "privacy.label.required": "Gerekli mi?",
  "privacy.s1.title": "1. Genel Bakış",
  "privacy.s1.p1": "Nodus Connect, kuantum sonrası kriptografi üzerine inşa edilmiş merkeziyetsiz, eşler arası bir mesajlaşma uygulamasıdır. Bu gizlilik politikası, uygulamanın hangi verilere eriştiğini, bunların nasıl kullanıldığını ve bir kullanıcı olarak haklarınızı açıklar.",
  "privacy.s1.highlight": "Nodus Connect, merkezi sunuculara hiçbir kişisel veri toplamaz, saklamaz veya iletmez. Her internet bağlantısında olduğu gibi, cihazınızın bağlandığı ağ düğümleri IP adresinizi ve bağlantı zamanlamasını görebilir. Tüm iletişim, NIST onaylı kuantum sonrası algoritmalar (anahtar kapsülleme için Kyber1024, imzalar için Dilithium5) ile uçtan uca şifrelenir.",
  "privacy.s2.title": "2. Toplamadığımız Veriler",
  "privacy.s2.p1": "Nodus Connect, gizliliği temel ilke olarak benimser. Aşağıdakileri toplamayız:",
  "privacy.s2.li1": "Kişisel bilgiler (ad, e-posta, telefon numarası)",
  "privacy.s2.li2": "Mesaj içeriği — tüm mesajlar uçtan uca şifrelenir ve yalnızca hedef alıcı tarafından okunabilir",
  "privacy.s2.li3": "Cihazınızdaki kişi listeleri veya adres defterleri",
  "privacy.s2.li4": "Konum verileri",
  "privacy.s2.li5": "Kullanım analitiği veya telemetri",
  "privacy.s2.li6": "Reklam tanımlayıcıları",
  "privacy.s2.li7": "İzleme amaçlı cihaz parmak izleri",
  "privacy.s2.li8": "Tarama geçmişi veya uygulama kullanım kalıpları",
  "privacy.s2.p2": "<strong>Tek istisna — isteğe bağlı hata ayıklama günlükleri.</strong> Uygulama, <em>Ayarlar → Veri ve Depolama → Geliştiriciye Hata Ayıklama Günlüğü Gönder</em> seçeneğiyle sorun giderme amacıyla uygulama günlüğünüzü gönüllü olarak geliştiriciye göndermenizi sağlar. Bu özelliği kullandığınızda: günlük, anımsatıcı ifadeler, özel anahtarlar ve kimlik bilgisi benzeri değerlerden temizlenir; ardından geliştiricinin açık anahtarına hibrit şifrelenir (Kyber1024 + AES-256-GCM) ve DHT üzerinden iletilir. DHT düğümleri dahil başka hiçbir taraf günlüğü okuyamaz. Bu özellik tamamen isteğe bağlıdır ve yalnızca düğmeye açıkça bastığınızda çalışır. Günlükler teslim edilmezse 1 saat sonra sona erer.",
  "privacy.s3.title": "3. Cihazınızda Yerel Olarak Saklanan Veriler",
  "privacy.s3.p1": "Aşağıdaki veriler yalnızca cihazınızda saklanır ve bize asla iletilmez:",
  "privacy.s3.crypto_title": "Kriptografik Materyal",
  "privacy.s3.crypto_r1_data": "Dilithium5 imzalama anahtar çifti",
  "privacy.s3.crypto_r1_purpose": "Kimlik doğrulama ve mesaj imzalama",
  "privacy.s3.crypto_r1_storage": "Yerel dosya (identity.dsa), kurtarma ifadesinden türetilir. Android’de, Android Keystore TEE tarafından sarmalanır (donanım destekli AES-256-GCM) — sarmalama anahtarı güvenli donanımdan asla çıkmaz.",
  "privacy.s3.crypto_r2_data": "Kyber1024 şifreleme anahtar çifti",
  "privacy.s3.crypto_r2_purpose": "Kuantum sonrası anahtar kapsülleme",
  "privacy.s3.crypto_r2_storage": "Yerel dosya (identity.kem), kurtarma ifadesinden türetilir. Android’de, Android Keystore TEE tarafından sarmalanır (donanım destekli AES-256-GCM) — sarmalama anahtarı güvenli donanımdan asla çıkmaz.",
  "privacy.s3.crypto_r3_data": "Kurtarma ifadesi (24 kelime)",
  "privacy.s3.crypto_r3_purpose": "Hesap yedekleme ve kurtarma",
  "privacy.s3.crypto_r3_storage": "Kyber1024 açık anahtarıyla şifrelenir (mnemonic.enc). Asla düz metin olarak saklanmaz.",
  "privacy.s3.crypto_r4_data": "DHT düğüm kimliği",
  "privacy.s3.crypto_r4_purpose": "Merkeziyetsiz ağda kimlik doğrulama",
  "privacy.s3.crypto_r4_storage": "Yerel olarak önbelleklenir (dht_identity.bin), kurtarma ifadesinden deterministik olarak türetilir",
  "privacy.s3.app_title": "Uygulama Verileri",
  "privacy.s3.app_r1_data": "Kişi listesi",
  "privacy.s3.app_r1_purpose": "Güvenilir kişileri ve engelleme listesini yönetme",
  "privacy.s3.app_r1_storage": "Yerel SQLite veritabanı (contacts.db)",
  "privacy.s3.app_r2_data": "Mesaj geçmişi",
  "privacy.s3.app_r2_purpose": "Sohbet yedekleme ve görüntüleme",
  "privacy.s3.app_r2_storage": "Yerel SQLite veritabanı (messages.db)",
  "privacy.s3.app_r3_data": "Profil önbelleği",
  "privacy.s3.app_r3_purpose": "Kişilerin görünen adlarını, avatarlarını ve açık anahtarlarını önbellekleme",
  "privacy.s3.app_r3_storage": "Yerel SQLite veritabanları (profiles.db, keyserver_cache.db)",
  "privacy.s3.app_r4_data": "Duvar gönderisi önbelleği",
  "privacy.s3.app_r4_purpose": "Herkese açık gönderilere, yorumlara ve beğenilere çevrimdışı erişim",
  "privacy.s3.app_r4_storage": "Yerel SQLite veritabanı (wall_cache.db)",
  "privacy.s3.app_r5_data": "Grup ve kanal verileri",
  "privacy.s3.app_r5_purpose": "Grup üyelikleri, şifreli grup anahtarları, kanal abonelikleri (kanallar şu anda devre dışıdır)",
  "privacy.s3.app_r5_storage": "Yerel SQLite veritabanları (groups.db, channel_subscriptions.db)",
  "privacy.s3.app_r6_data": "Cüzdan bakiyesi ve işlem önbelleği",
  "privacy.s3.app_r6_purpose": "Cüzdan bakiyelerini ve işlem geçmişini görüntüleme",
  "privacy.s3.app_r6_storage": "Yerel SQLite veritabanı (wallet_cache.db). Özel anahtarlar asla saklanmaz — kurtarma ifadesinden isteğe bağlı olarak türetilir.",
  "privacy.s3.app_r7_data": "Cüzdan adres defteri",
  "privacy.s3.app_r7_purpose": "Etiketli kayıtlı alıcı adresleri",
  "privacy.s3.app_r7_storage": "Yerel SQLite veritabanı (addressbook.db)",
  "privacy.s3.app_r8_data": "Uygulama kilidi PIN’i",
  "privacy.s3.app_r8_purpose": "İsteğe bağlı uygulama kilidi doğrulaması",
  "privacy.s3.app_r8_storage": "Rastgele tuz ile PBKDF2-SHA256 özeti, Android Keystore (planlanan iOS sürümünde iOS Keychain) içinde saklanır (işletim sistemi tarafından şifrelenir)",
  "privacy.s3.app_r9_data": "Uygulama tercihleri",
  "privacy.s3.app_r9_purpose": "Biyometrik kilit, bildirim tercihleri gibi ayarlar",
  "privacy.s3.app_r9_storage": "İşletim sistemi tarafından yönetilen yerel depolama (SharedPreferences)",
  "privacy.s3.p2": "Yerel SQLite veritabanları, <strong>SQLCipher</strong> ile şifrelenir (sayfa başı HMAC-SHA512 bütünlük kontrolüyle AES-256-CBC). Her veritabanının şifreleme anahtarı, kimlik materyalinizden PBKDF2 kullanılarak türetilir ve işletim sistemi anahtar deposunda — Android Keystore (planlanan iOS sürümünde iOS Keychain) — saklanır. Cihazınız kaybolur veya çalınırsa, fiziksel erişimle bile veritabanı içerikleri okunamaz. Hassas kriptografik materyal (kurtarma ifadesi, PIN) yukarıda açıklandığı gibi ek özel şifreleme kullanır.",
  "privacy.s4.title": "4. Merkeziyetsiz Ağ (DHT)",
  "privacy.s4.p1": "Nodus Connect, mesaj teslimi ve profil keşfi için Nodus adlı merkeziyetsiz bir hash tablosu (DHT) ağı kullanır. Bu ağa yayınlanan veriler iki kategoriye ayrılır:",
  "privacy.s4.public_title": "Herkese Açık Veriler (DHT düğümleri ve diğer kullanıcılar tarafından okunabilir)",
  "privacy.s4.public_li1": "<strong>Herkese açık profil:</strong> Açık kriptografik anahtarlarınız, kayıtlı görünen adınız, biyografiniz, avatarınız, konumunuz, web siteniz, sosyal bağlantılarınız ve cüzdan adresleriniz. Bu veriler, başkalarının sizi bulabilmesi ve sizinle iletişim kurabilmesi için kasıtlı olarak herkese açıktır.",
  "privacy.s4.public_li2": "<strong>Duvar gönderileri, yorumlar ve beğeniler:</strong> Yayınlamayı tercih ettiğiniz herkese açık gönderiler, yorumlar ve beğeniler ağdaki herkes tarafından görülebilir. Gönderiler imzalıdır ancak şifrelenmez.",
  "privacy.s4.public_li3": "Herkese açık kanallar şu anda devre dışıdır ve gelecekteki bir sürümde yeniden etkinleştirilecektir. <strong>Kanal gönderileri ve meta verileri:</strong> Kanal adı, açıklaması ve gönderileri dahil herkese açık kanal içerikleri DHT düğümleri tarafından okunabilir.",
  "privacy.s4.encrypted_title": "Şifreli Veriler (DHT düğümleri tarafından okunamaz)",
  "privacy.s4.encrypted_li1": "<strong>Doğrudan mesajlar:</strong> Kyber1024 anahtar kapsülleme ve AES-256-GCM ile şifrelenir. Yalnızca hedef alıcı şifreyi çözebilir.",
  "privacy.s4.encrypted_li2": "<strong>Grup mesajları:</strong> Grup Şifreleme Anahtarı (GEK) ile şifrelenir, Kyber1024 kapsülleme aracılığıyla grup üyelerine dağıtılır.",
  "privacy.s4.encrypted_li3": "<strong>Kişi listeleri ve adres defterleri:</strong> Kendi Kyber1024 açık anahtarınızla kendinden şifreli.",
  "privacy.s4.encrypted_li4": "<strong>Mesaj yedekleri:</strong> Kendi Kyber1024 açık anahtarınızla kendinden şifreli.",
  "privacy.s4.encrypted_li5": "<strong>Grup üyelik listeleri:</strong> Kendi Kyber1024 açık anahtarınızla kendinden şifreli.",
  "privacy.s4.encrypted_li6": "<strong>Medya ekleri (görseller, videolar, sesli mesajlar):</strong> Kyber1024 anahtar kapsülleme + AES-256-GCM ile şifrelenir. Dosyalar parçalanır ve Nodus medya depolama katmanında saklanır; yalnızca hedef alıcı (veya grup üyeleri) şifreyi çözebilir.",
  "privacy.s4.p2": "Hiçbir merkezi sunucu özel anahtarlarınızı saklamaz veya bunlara erişemez. DHT düğümleri herkese açık profil bilgilerini ve duvar gönderilerini okuyabilir, ancak özel mesajlarınızı, kişi listelerinizi veya grup üyeliklerinizi okuyamaz. Her internet bağlantısında olduğu gibi, cihazınızın bağlandığı ağ düğümleri IP adresinizi ve bağlantı zamanlamasını görebilir.",
  "privacy.s5.title": "5. Cihaz İzinleri",
  "privacy.s5.p1": "Nodus Connect aşağıdaki Android izinlerini ister:",
  "privacy.s5.perm_r1_name": "İnternet",
  "privacy.s5.perm_r1_purpose": "Mesajlaşma için merkeziyetsiz DHT ağına bağlanma",
  "privacy.s5.perm_r1_required": "Evet",
  "privacy.s5.perm_r2_name": "Ağ Durumu",
  "privacy.s5.perm_r2_purpose": "Mesaj teslimi için çevrimiçi/çevrimdışı durumunu algılama",
  "privacy.s5.perm_r2_required": "Evet",
  "privacy.s5.perm_r3_name": "Kamera",
  "privacy.s5.perm_r3_purpose": "Profil avatarı için fotoğraf çekme ve kişi eklemek için QR kod tarama",
  "privacy.s5.perm_r3_required": "Hayır — isteğe bağlı",
  "privacy.s5.perm_r4_name": "Biyometrik",
  "privacy.s5.perm_r4_purpose": "Uygulama kilidi — parmak izi veya yüz tanıma ile kimlik doğrulama",
  "privacy.s5.perm_r4_required": "Hayır — isteğe bağlı",
  "privacy.s5.perm_r5_name": "Bildirimler",
  "privacy.s5.perm_r5_purpose": "Yeni mesajlar için uyarı alma",
  "privacy.s5.perm_r5_required": "Hayır — isteğe bağlı (Android 13+)",
  "privacy.s5.perm_r6_name": "Titreşim",
  "privacy.s5.perm_r6_purpose": "Bildirimler için dokunsal geri bildirim",
  "privacy.s5.perm_r6_required": "Hayır — isteğe bağlı",
  "privacy.s5.perm_r7_name": "Wi-Fi Durumu",
  "privacy.s5.perm_r7_purpose": "Ağ bağlantılarını optimize etmek için Wi-Fi bağlantısını algılama",
  "privacy.s5.perm_r7_required": "Evet",
  "privacy.s5.perm_r8_name": "Pil Optimizasyonu Muafiyeti",
  "privacy.s5.perm_r8_purpose": "Arka planda mesaj teslimini aktif tutma (kullanıcı tarafından Ayarlar’dan tetiklenir)",
  "privacy.s5.perm_r8_required": "Hayır — isteğe bağlı",
  "privacy.s5.p2": "Hiçbir izin reklam, izleme veya veri toplama amacıyla kullanılmaz. Kamera ve biyometrik erişim yalnızca bu özellikleri açıkça kullandığınızda etkinleştirilir.",
  "privacy.s6.title": "6. Üçüncü Taraf Hizmetler",
  "privacy.s6.p1": "Nodus Connect hiçbir üçüncü taraf analitik, reklam veya izleme hizmeti entegre etmez. Özellikle:",
  "privacy.s6.li1": "Google Analytics veya Firebase Analytics yok",
  "privacy.s6.li2": "Facebook SDK yok",
  "privacy.s6.li3": "Reklam ağları yok",
  "privacy.s6.li4": "Dışarıya veri ileten çökme raporlama servisleri yok",
  "privacy.s6.p2": "Uygulama, cüzdan işlevselliği için aşağıdaki üçüncü taraf hizmetlere bağlanır:",
  "privacy.s6.li5": "<strong>Blok zinciri RPC uç noktaları</strong> (Cellframe, Ethereum, BSC, Solana, TRON) — cüzdan bakiyesi sorguları ve işlem yayını için. Bu bağlantılar yalnızca açık cüzdan adresinizi iletir — asla özel anahtarları değil.",
  "privacy.s6.li6": "<strong>BitcoinTry API</strong> (api.bitcointry.com) — anlık kripto para fiyat verileri için. Kişisel veri veya cüzdan adresi gönderilmez — yalnızca token çifti tanımlayıcıları (ör. ETH_USDT).",
  "privacy.s7.title": "7. Şifreleme ve Güvenlik",
  "privacy.s7.p1": "Tüm kriptografik işlemler NIST onaylı kuantum sonrası algoritmaları kullanır:",
  "privacy.s7.li1": "<strong>Anahtar Kapsülleme:</strong> ML-KEM (Kyber1024) — NIST Kategori 5",
  "privacy.s7.li2": "<strong>Dijital İmzalar:</strong> ML-DSA (Dilithium5) — NIST Kategori 5",
  "privacy.s7.li3": "<strong>Simetrik Şifreleme:</strong> Mesaj içeriği için AES-256-GCM",
  "privacy.s7.li4": "<strong>Özet Fonksiyonu:</strong> Kimlik parmak izleri için SHA3-512",
  "privacy.s7.p2": "Bu algoritmalar hem klasik hem de kuantum bilgisayar saldırılarına karşı dayanıklı olacak şekilde tasarlanmıştır. Özel anahtarlarınız cihazınızdan asla ayrılmaz.",
  "privacy.s8.title": "8. Veri Saklama ve Silme",
  "privacy.s8.li1": "Tüm veriler cihazınızda saklanır. Uygulamayı kaldırmak tüm yerel verileri siler.",
  "privacy.s8.li2": "Herkese açık profil verileri, erişilebilirliği sürdürmek için cihazınız tarafından ağda periyodik olarak yenilenir.",
  "privacy.s8.li3": "Duvar gönderilerinin ağdaki ömrü 30 gündür ve otomatik olarak sona erer.",
  "privacy.s8.li4": "Hesabınızı istediğiniz zaman uygulamayı kaldırarak silebilirsiniz. Sunucu tarafında silinecek bir hesap yoktur.",
  "privacy.s9.title": "9. Çocukların Gizliliği",
  "privacy.s9.p1": "Nodus Connect, 13 yaşından küçük çocuklardan bilerek herhangi bir bilgi toplamaz. Uygulama, hesap oluşturmak için herhangi bir kişisel bilgi gerektirmez — yalnızca yerel olarak oluşturulan bir kriptografik anahtar çifti.",
  "privacy.s10.title": "10. Bu Politikadaki Değişiklikler",
  "privacy.s10.p1": "Bu gizlilik politikasını zaman zaman güncelleyebiliriz. Değişiklikler bu sayfada güncellenmiş bir “Son Güncelleme” tarihiyle yansıtılacaktır. Değişikliklerden sonra Nodus Connect’i kullanmaya devam etmeniz, revize edilmiş politikayı kabul ettiğiniz anlamına gelir.",
  "privacy.s11.title": "11. İletişim",
  "privacy.s11.p1": "Bu gizlilik politikası veya Nodus Connect’in veri uygulamaları hakkında sorularınız varsa:",
  "nav.about": "Hakkında",
  "nav.wallet": "Web cüzdanı",
  "nav.soon": "yakında",
  "nav.preview": "önizleme",
  "nav.resourceNetwork": "Kaynak ağı",
  "nav.openWallet": "Cüzdanı aç",
  "soonPage.crumb": "Önizleme",
  "soonPage.openWallet": "Nodus Connect’i aç (önizleme)",
  "soonPage.about": "Nodus Connect hakkında"
};

const sitePages = new Set(["/","/index.html","/ecosystem.html","/network.html","/manifesto.html","/roadmap.html","/docs.html","/connect.html","/connect-soon.html","/wallet.html","/identity.html","/chain.html","/scan.html","/terms.html","/privacy.html","/tokenomics.html","/airdrop.html"]);

// Keep bookmarks shared from the earlier homepage working after the split.
const legacyPages={
  "#ecosystem": "ecosystem.html",
  "#network-services": "network.html",
  "#manifesto": "manifesto.html",
  "#roadmap": "roadmap.html",
  "#download": "connect.html#soon",
  "#connect-features": "connect.html#connect-features",
  "#technology": "network.html#technology"
};
if(document.body.dataset.page==='index' && legacyPages[window.location.hash]) {
  const destination=new URL(legacyPages[window.location.hash],window.location.href);
  destination.search=window.location.search;
  window.location.replace(destination.href);
}

const translatedElements = [...document.querySelectorAll('[data-i18n]')];
const english = new Map(translatedElements.map(element=>[element,element.innerHTML]));
const languageToggle = document.querySelector('.language-toggle');
const menuToggle = document.querySelector('.menu-toggle');
const navigation = document.querySelector('#main-nav');
// Header link groups are disclosure buttons; aria-expanded is their only open state.
const navGroups = [...document.querySelectorAll('.nav-group')];
const desktopNav = window.matchMedia('(min-width:1101px)');
const motionButton = document.querySelector('.motion-toggle');
const reducedMotion = window.matchMedia('(prefers-reduced-motion: reduce)');
let language = 'en';
let motionPaused = false;

function updateMotionLabel() {
  if (!motionButton) return;
  const off=motionPaused || reducedMotion.matches;
  motionButton.disabled=reducedMotion.matches;
  motionButton.setAttribute('aria-pressed',String(off));
  motionButton.setAttribute('aria-label',reducedMotion.matches ? (language==='tr'?'Azaltılmış hareket tercihi etkin':'Reduced motion preference enabled') : (language==='tr'?(off?'Animasyonu sürdür':'Animasyonu duraklat'):(off?'Resume animation':'Pause animation')));
  motionButton.firstElementChild.textContent=off?'▷':'Ⅱ';
}

function setGroup(group,open) {
  group.querySelector('.nav-group-toggle').setAttribute('aria-expanded',String(open));
}

function closeGroups(except) {
  navGroups.forEach(group=>{if(group!==except)setGroup(group,false);});
}

function setMenu(open) {
  if (!open) closeGroups();
  if (!menuToggle || !navigation) return;
  menuToggle.setAttribute('aria-expanded',String(open));
  menuToggle.setAttribute('aria-label',language==='tr'?(open?'Menüyü kapat':'Menüyü aç'):(open?'Close menu':'Open menu'));
  navigation.classList.toggle('open',open);
}

function setLanguage(next) {
  language=next==='tr'?'tr':'en';
  document.documentElement.lang=language;
  translatedElements.forEach(element=>{
    const key=element.dataset.i18n;
    // Both dictionaries are authored with the page. No user input is rendered as HTML.
    element.innerHTML=language==='tr'?(turkish[key]??english.get(element)):english.get(element);
  });
  languageToggle.firstChild.textContent=language.toUpperCase()+' ';
  languageToggle.setAttribute('aria-label',language==='en'?'Switch to Turkish':'İngilizceye geç');
  document.querySelectorAll('.wordmark').forEach(link=>link.setAttribute('aria-label',language==='tr'?'Nodus ana sayfa':'Nodus home'));
  document.querySelectorAll('a[href]').forEach(link=>{
    if(link.getAttribute('href').startsWith('#'))return;
    const url=new URL(link.getAttribute('href'),window.location.href);
    const nodusOrigin=['https://nodusnetwork.io','https://wiki.nodusnetwork.io','https://scan.nodusnetwork.io'].includes(url.origin);
    const localPage=url.origin===window.location.origin && (sitePages.has(url.pathname) || /^\/(wiki|scan)\//.test(url.pathname));
    if(!nodusOrigin && !localPage)return;
    url.searchParams.set('lang',language);
    link.setAttribute('href',url.origin===window.location.origin?`${url.pathname}${url.search}${url.hash}`:url.href);
  });
  if(navigation)navigation.setAttribute('aria-label',language==='tr'?'Ana gezinme':'Main navigation');
  const filters=document.querySelector('.roadmap-filters');
  if(filters)filters.setAttribute('aria-label',language==='tr'?'Yol haritasını filtrele':'Filter roadmap');
  const sidebar=document.querySelector('.docs-sidebar');
  if(sidebar)sidebar.setAttribute('aria-label',language==='tr'?'Bu sayfada':'On this page');
  const art=document.querySelector('.hero-art');
  if(art)art.setAttribute('aria-label',language==='tr'?'Soyut, örgü biçiminde bir ağ heykeli':'An abstract woven network sculpture');
  const scroll=document.querySelector('.hero-bottom>a');
  if(scroll)scroll.setAttribute('aria-label',language==='tr'?'Nodus’u keşfet':'Explore Nodus');
  const principleSection=document.querySelector('.principles');
  if(principleSection)principleSection.setAttribute('aria-label',language==='tr'?'Nodus ilkeleri':'Nodus principles');
  document.title=language==='tr'?document.body.dataset.titleTr:document.body.dataset.titleEn;
  setMenu(false);
  updateMotionLabel();
  const currentUrl=new URL(window.location.href);
  currentUrl.searchParams.set('lang',language);
  history.replaceState(null,'',currentUrl);
  try { localStorage.setItem('nodus-language',language); } catch { /* Language still works when storage is blocked. */ }
}

let initialLanguage=new URLSearchParams(window.location.search).get('lang');
if(!initialLanguage){try{initialLanguage=localStorage.getItem('nodus-language');}catch{/* English is the default. */}}
setLanguage(initialLanguage);
languageToggle.addEventListener('click',()=>setLanguage(language==='en'?'tr':'en'));
menuToggle?.addEventListener('click',()=>setMenu(menuToggle.getAttribute('aria-expanded')!=='true'));
navigation?.addEventListener('click',event=>{if(event.target.closest('a'))setMenu(false);});
document.addEventListener('keydown',event=>{
  if(event.key!=='Escape')return;
  const openGroup=navGroups.find(group=>group.querySelector('.nav-group-toggle').getAttribute('aria-expanded')==='true');
  if(openGroup){setGroup(openGroup,false);openGroup.querySelector('.nav-group-toggle').focus();return;}
  if(menuToggle?.getAttribute('aria-expanded')==='true'){setMenu(false);menuToggle.focus();}
});
document.addEventListener('click',event=>{
  if(!event.target.closest('.site-header'))setMenu(false);
  else if(!event.target.closest('.main-nav'))closeGroups();
});
desktopNav.addEventListener('change',()=>setMenu(false));

// Without this class, CSS opens the groups on hover and focus so the links work without JavaScript.
navigation?.classList.add('nav-ready');
navGroups.forEach(group=>{
  const toggle=group.querySelector('.nav-group-toggle');
  // A desktop mouse opens the group on hover, so its click never closes it; keyboard and touch toggle.
  const hoverMode=event=>event.pointerType==='mouse' && desktopNav.matches;
  toggle.addEventListener('click',event=>{
    const open=hoverMode(event) || toggle.getAttribute('aria-expanded')!=='true';
    closeGroups(group);
    setGroup(group,open);
  });
  group.addEventListener('pointerenter',event=>{if(hoverMode(event)){closeGroups(group);setGroup(group,true);}});
  group.addEventListener('pointerleave',event=>{if(hoverMode(event))setGroup(group,false);});
  group.addEventListener('focusout',event=>{if(event.relatedTarget && !group.contains(event.relatedTarget))setGroup(group,false);});
});

document.querySelectorAll('.faq-list details').forEach(detail=>detail.addEventListener('toggle',()=>{
  if(detail.open)document.querySelectorAll('.faq-list details').forEach(other=>{if(other!==detail)other.open=false;});
}));

const canvas=document.querySelector('#network-art');
if(canvas){
  const art=createNetworkArt(canvas);
  motionButton.addEventListener('click',()=>{motionPaused=!motionPaused;art.setPaused(motionPaused);updateMotionLabel();});
  reducedMotion.addEventListener('change',updateMotionLabel);
}


// Roadmap filters keep the selected category when the page language changes.
document.querySelectorAll('[data-roadmap-filter]').forEach(button => {
  button.addEventListener('click', () => {
    const selected = button.dataset.roadmapFilter;
    document.querySelectorAll('[data-roadmap-filter]').forEach(filter => {
      filter.setAttribute('aria-pressed', String(filter === button));
    });
    document.querySelectorAll('[data-milestone-status]').forEach(item => {
      item.hidden = selected !== 'all' && item.dataset.milestoneStatus !== selected;
    });
  });
});
