import { writeFile, mkdir } from 'node:fs/promises';
import { readFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { guides } from './wiki/content.mjs';

// Cache busting: the shared assets are served with a long max-age while the HTML is not cached, so a page must ask
// for the exact asset version it was built with — otherwise a browser pairs new HTML with an old script.
const assetVersion = path => createHash('sha256').update(readFileSync(new URL(path, import.meta.url))).digest('hex').slice(0, 12);
const versioned = (href, path) => `${href}?v=${assetVersion(path)}`;

const escape = value => String(value).replaceAll('&', '&amp;').replaceAll('"', '&quot;').replaceAll('<', '&lt;').replaceAll('>', '&gt;');
const text = (en, tr, tag = 'span', attrs = '') => `<${tag} ${attrs} data-tr="${escape(tr)}">${en}</${tag}>`;
const groupNames = { connect: ['Use Connect', 'Connect’i kullan'], network: ['Understand the network', 'Ağı anla'], build: ['Explore & build', 'Keşfet ve geliştir'] };
const output = async (path, body) => writeFile(new URL(path, import.meta.url), body + '\n');
const anchor = (href, en, tr, attrs = '') => `<a href="${href}" ${attrs}>${text(en, tr)}</a>`;
function shell(site, slug, title, description, content) {
  const origin = `https://${site}.nodusnetwork.io`;
  const suffix = site === 'wiki' ? 'Wiki' : 'Scan';
  return `<!DOCTYPE html>
<html lang="en"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="theme-color" content="#141612"><title>${escape(title[0])} — Nodus ${suffix}</title>
<meta name="description" content="${escape(description[0])}">
<link rel="canonical" href="${origin}/${slug === 'index' ? '' : slug + '.html'}">
<meta property="og:title" content="${escape(title[0])} — Nodus ${suffix}"><meta property="og:description" content="${escape(description[0])}">
<meta property="og:type" content="website"><meta property="og:site_name" content="Nodus ${suffix}">
<meta property="og:url" content="${origin}/${slug === 'index' ? '' : slug + '.html'}">
<meta name="robots" content="${site === 'scan' && !['index', 'stats', 'hardforks'].includes(slug) ? 'noindex, follow' : 'index, follow'}">
<link rel="icon" href="../assets/nodus-mark.svg" type="image/svg+xml">
<link rel="preload" href="../assets/fonts/inter-latin.woff2" as="font" type="font/woff2" crossorigin>
<link rel="stylesheet" href="${versioned('../portal.css', './portal.css')}"><script src="${versioned('../portal.js', './portal.js')}" defer></script>
${site === 'wiki' ? (slug === 'index' ? `<script src="${versioned('search.js', './wiki/search.js')}" defer></script>` : '') : `<script src="${versioned('app.js', './scan/app.js')}" defer></script>`}
</head><body class="${site}-site" data-page="${slug}" data-title-tr="${escape(title[1])} — Nodus ${suffix}">
${anchor('#main', 'Skip to content', 'İçeriğe geç', 'class="skip-link"')}
<header class="portal-header"><div class="wrap"><a class="portal-brand" href="${site === 'scan' ? 'https://nodusnetwork.io/' : './'}" aria-label="${site === 'scan' ? 'Nodus home (nodusnetwork.io)' : `Nodus ${suffix}`}"><img src="../assets/nodus-mark.svg" alt="" width="34" height="34">nodus<span class="portal-name">${suffix.toLowerCase()}</span></a>
<nav class="portal-nav" aria-label="Main navigation" data-label-tr="Ana gezinme">${anchor('https://nodusnetwork.io/', 'Nodus ↗', 'Nodus ↗')}${anchor('https://wiki.nodusnetwork.io/', 'Wiki', 'Wiki')}${anchor('https://scan.nodusnetwork.io/', 'Scan', 'Scan', site === 'scan' && slug === 'index' ? 'aria-current="page"' : '')}${site === 'scan' ? anchor('stats.html', 'Statistics', 'İstatistikler', slug === 'stats' ? 'aria-current="page"' : '') + anchor('hardforks.html', 'Hard forks', 'Hard fork’lar', slug === 'hardforks' ? 'aria-current="page"' : '') : ''}${anchor('https://nodusnetwork.io/docs.html', 'Developers', 'Geliştiriciler')}${anchor('https://connect.nodusnetwork.io/', 'Nodus Connect — preview ↗', 'Nodus Connect — önizleme ↗', 'class="wide-only"')}</nav><button type="button" class="portal-language" aria-label="Switch to Turkish">EN</button></div></header>
<main class="wrap" id="main">${content}</main>
<footer class="portal-footer"><div class="wrap"><div><p>© 2026 Nodus · ${suffix}</p>${site === 'scan' ? text('Read-only index from the witness cluster. Consensus certificates are not independently re-verified. Nodus testnet.', 'Doğrulayıcı kümesinden salt okunur indeks. Konsensüs sertifikaları bağımsız olarak yeniden doğrulanmaz. Nodus testnet.', 'p') : text('Independent by nature. Connected by Nodus.', 'Doğasında bağımsızlık. Bağlantısında Nodus.', 'p')}</div><nav>${anchor('https://nodusnetwork.io/manifesto.html', 'Manifesto ↗', 'Manifesto ↗')}${anchor('https://nodusnetwork.io/roadmap.html', 'Roadmap ↗', 'Yol haritası ↗')}${anchor('https://github.com/nocdem/dna', 'Source ↗', 'Kaynak ↗')}</nav></div></footer>
</body></html>`;
}
function sidebars(current) {
  const links = guides.map(g => anchor(g.slug + '.html', ...g.title, g.slug === current ? 'aria-current="page"' : '')).join('');
  const sidebar = `<aside class="wiki-sidebar"><a href="./" class="sidebar-home">${text('← Knowledge home', '← Bilgi merkezi')}</a>${Object.entries(groupNames).map(([group, name]) => `<div class="sidebar-group">${text(...name, 'h2')}${guides.filter(g => g.group === group).map(g => anchor(g.slug + '.html', ...g.title, g.slug === current ? 'aria-current="page"' : '')).join('')}</div>`).join('')}</aside>`;
  return { sidebar, mobile: `<details class="mobile-guides">${text('Browse all guides', 'Tüm rehberleri göster', 'summary')}<nav aria-label="Guides" data-label-tr="Rehberler">${anchor('./', 'Knowledge home', 'Bilgi merkezi')}${links}</nav></details>` };
}
function guideLink(g, i) {
  return `<a class="guide-link" href="${g.slug}.html"><span class="number">${String(i + 1).padStart(2, '0')}</span><div>${text(...g.title, 'h3')}${text(...g.lead, 'p')}</div><span class="arrow" aria-hidden="true">↗</span></a>`;
}
await mkdir(new URL('scan/', import.meta.url), { recursive: true });
const homeSides = sidebars('index');
await output('wiki/index.html', shell('wiki', 'index', ['Knowledge, shared.', 'Bilgi, paylaştıkça.'], ['Guides for Connect, the Nodus resource network and developers.', 'Connect, Nodus kaynak ağı ve geliştiriciler için rehberler.'], `<div class="wiki-layout">${homeSides.sidebar}<div class="wiki-main">${homeSides.mobile}<section class="wiki-hero">${text('NODUS / KNOWLEDGE BASE', 'NODUS / BİLGİ MERKEZİ', 'span', 'class="portal-kicker"')}${text('Find your way.<br>Make it yours.', 'Yolunu bul.<br>Kendine ait kıl.', 'h1')}${text('From your first conversation to building on the network. Clear guides for every step.', 'İlk sohbetinden ağ üzerinde geliştirmeye kadar. Her adım için anlaşılır rehberler.', 'p', 'class="lead"')}<div class="wiki-search">${text('Search the guides', 'Rehberlerde ara', 'label', 'for="wiki-search"')}<input id="wiki-search" type="search" placeholder="Try recovery, storage or transactions…" data-placeholder-tr="Kurtarma, depolama veya işlem ara…" autocomplete="off"><span class="search-hint" aria-hidden="true">⌕</span><div id="wiki-results" class="wiki-search-results" aria-live="polite"></div><noscript><p>Browse the guides below. / Aşağıdaki rehberleri kullanabilirsin.</p></noscript></div></section>${Object.entries(groupNames).map(([group, name]) => `<section><div class="section-heading">${text(...name, 'h2')}${text('A little knowledge goes a long way.', 'Biraz bilgi, çok yol aldırır.')}</div><div class="guide-list">${guides.filter(g => g.group === group).map(guideLink).join('')}</div></section>`).join('')}<section class="wiki-highlight"><div>${text('Privacy is a human right.', 'Gizlilik bir insan hakkıdır.', 'h2')}${text('The belief behind the network we are building.', 'İnşa ettiğimiz ağın arkasındaki inanç.', 'p')}</div>${anchor('https://nodusnetwork.io/manifesto.html', 'Read the manifesto ↗', 'Manifestoyu oku ↗', 'class="button"')}</section></div></div>`));
for (const [i, guide] of guides.entries()) {
  const sides = sidebars(guide.slug);
  const prev = guides[i - 1], next = guides[i + 1];
  const pager = `<nav class="article-pager" aria-label="Related guides" data-label-tr="Diğer rehberler">${prev ? `<a href="${prev.slug}.html">${text('Previous', 'Önceki')}${text('← ' + prev.title[0], '← ' + prev.title[1], 'strong')}</a>` : '<div></div>'}${next ? `<a href="${next.slug}.html">${text('Next', 'Sonraki')}${text(next.title[0] + ' →', next.title[1] + ' →', 'strong')}</a>` : anchor('./', 'All guides →', 'Tüm rehberler →')}</nav>`;
  const article = `<div class="wiki-layout">${sides.sidebar}<div class="wiki-main">${sides.mobile}<div class="article-grid"><article class="wiki-article"><nav class="breadcrumbs">${anchor('./', 'Knowledge home', 'Bilgi merkezi')}<span>/</span>${text(...groupNames[guide.group])}</nav><header class="article-header">${text(...guide.title, 'h1')}${text(...guide.lead, 'p', 'class="lead"')}<div class="article-meta">${text('REVIEWED SEPTEMBER 2026', 'EYLÜL 2026’DA İNCELENDİ')}${text('EN / TR', 'EN / TR')}</div></header>${guide.sections.map(section => `<section id="${section.id}">${text(...section.title, 'h2')}${text(...section.body, 'div', 'class="guide-body"')}</section>`).join('')}${pager}</article><aside class="article-toc">${text('On this page', 'Bu sayfada', 'h2')}${guide.sections.map(s => anchor('#' + s.id, ...s.title)).join('')}</aside></div></div></div>`;
  await output(`wiki/${guide.slug}.html`, shell('wiki', guide.slug, guide.title, guide.lead, article));
}
const searchIndex = guides.map(g => ({ slug: g.slug, title: g.title, lead: g.lead, text: [0, 1].map(i => g.sections.map(s => s.title[i] + ' ' + s.body[i].replace(/<[^>]*>/g, ' ')).join(' ')) }));
await output('wiki/search-index.json', JSON.stringify(searchIndex));
const search = `<label class="search-label" for="search-input">${text('Block height, full hash or address fingerprint', 'Blok yüksekliği, tam hash veya adres parmak izi')}</label><form id="search-form" class="search-form" autocomplete="off"><input id="search-input" class="search-input" type="search" maxlength="128" placeholder="Search the testnet ledger…" data-placeholder-tr="Testnet zincirinde ara…" required><button type="submit" class="btn-primary">${text('Search →', 'Ara →')}</button></form><div id="search-results" class="search-results" aria-live="polite"></div><div id="staleness-banner" class="staleness-banner hidden" role="status"></div>`;
const scanPages = ['index', 'stats', 'block', 'tx', 'address', 'hardforks'];
for (const slug of scanPages) {
  // hardforks: explorer /api/governance, rendered by scan/app.js into #hardforks-content.
  const titles = { index: ['Read the network.', 'Ağı incele.'], stats: ['Statistics', 'İstatistikler'], block: ['Block details', 'Blok ayrıntıları'], tx: ['Transaction details', 'İşlem ayrıntıları'], address: ['Address overview', 'Adres özeti'], hardforks: ['Hard forks', 'Hard fork’lar'] };
  const desc = slug === 'stats' ? ['Supply, throughput and reward payouts on the Nodus testnet.', 'Nodus testnet ağında arz, işlem hızı ve ödül ödemeleri.'] : ['Blocks, transactions and address history on the Nodus testnet.', 'Nodus testnet ağındaki bloklar, işlemler ve adres geçmişi.'];
  const hero = `<section class="scan-hero"><div>${text('NODUS SCAN / TESTNET', 'NODUS SCAN / TESTNET', 'span', 'class="devnet-tag"')}${text(...titles[slug], 'h1')}${text(...desc, 'p')}</div>${slug === 'index' ? '<div class="scan-art" aria-hidden="true"><img src="../assets/artwork/scan-v1.webp" width="220" height="147" alt=""></div>' : ''}</section>`;
  const status = `<div class="scan-status"><span id="api-status" role="status">${text('Connecting to the index…', 'İndekse bağlanıyor…')}</span><button id="refresh-data" type="button" class="btn-secondary">${text('Refresh ↻', 'Yenile ↻')}</button></div>`;
  // Supply buckets: decision docs/plans/decisions/2026-09-30-scan-supply-buckets.md (explorer /api/stats).
  const stats = `<section class="stats-grid" id="stats-cards" aria-label="Chain statistics" data-label-tr="Zincir istatistikleri"><div class="stat-card">${text('Indexed height','İndeks yüksekliği','div','class="stat-label"')}<div class="stat-value mono" id="stat-height">—</div></div><div class="stat-card">${text('Total supply / Circulating supply','Toplam arz / Dolaşımdaki arz','div','class="stat-label"')}<div class="stat-value mono supply-values"><span id="stat-total">—</span> <span>/</span> <span id="stat-circulating">—</span> <span>NODUS</span></div><button type="button" class="stat-details" id="supply-details-toggle" aria-expanded="false" aria-controls="supply-details">${text('Details ▾', 'Detaylar ▾')}</button></div></section>`
    + `<section class="supply-buckets" id="supply-details" hidden aria-label="Supply buckets" data-label-tr="Arz kovaları">${text('Where the supply is', 'Arz nerede', 'h2', 'class="section-title"')}<div class="table-scroll" tabindex="0" role="region" aria-label="Supply buckets" data-label-tr="Arz kovaları"><table class="data-table bucket-table"><thead><tr>${[['Bucket','Kova'],['Amount','Tutar']].map(t => text(...t,'th','scope="col"')).join('')}</tr></thead><tbody>${[['reward','Validator rewards remaining','Kalan validator ödülü'],['storage','Storage','Depolama'],['compute','Compute','Hesaplama'],['bandwidth','Bandwidth','Bant genişliği'],['future','Future services','Gelecekteki hizmetler']].map(([id,en,tr]) => `<tr>${text(en,tr,'th','scope="row"')}<td class="mono" id="bucket-${id}">—</td></tr>`).join('')}</tbody></table></div>`
    + text('Amounts are in NODUS. The total supply is fixed. Circulating supply is every coin outside the reward reserve, the service pools and the unclaimed allocation — staked coins and the Foundation’s coins included.', 'Tutarlar NODUS cinsindendir. Toplam arz sabittir. Dolaşımdaki arz; ödül rezervi, hizmet havuzları ve claim edilmemiş tahsis dışındaki her coin’dir — stake edilmiş coin’ler ve Foundation’ın coin’leri dahil.', 'p', 'class="scan-explanation"') + `<p class="scan-explanation">${anchor('https://nodusnetwork.io/tokenomics.html', 'How the supply is allocated: Tokenomics ↗', 'Arzın nasıl dağıtıldığı: Tokenomik ↗')}</p></section>`;
  // Throughput: explorer /api/tps (applied transactions per second by block time), rendered by scan/app.js.
  const tps = `<section aria-label="Throughput" data-label-tr="İşlem hızı">${text('Throughput', 'İşlem hızı', 'h2', 'class="section-title"')}<div class="stats-grid" id="tps-cards">${[['minute','Last minute','Son dakika'],['hour','Last hour','Son saat']].map(([id,en,tr]) => `<div class="stat-card">${text(en,tr,'div','class="stat-label"')}<div class="stat-value mono" id="tps-${id}">—</div></div>`).join('')}<div class="stat-card">${text('Last 24 hours, per hour (UTC)', 'Son 24 saat, saatlik (UTC)', 'div', 'class="stat-label"')}<div id="tps-chart"></div></div></div>`
    + text('TPS = applied transactions per second, measured by block time up to the newest indexed block. Refused transactions are not counted.', 'TPS = saniyede uygulanan işlem sayısı; en yeni indekslenmiş bloğa kadar blok zamanıyla ölçülür. Reddedilen işlemler sayılmaz.', 'p', 'class="scan-explanation"')
    // Next payday + APY estimate use /api/tps; payout history loads independently from /api/paydays.
    + `<div class="detail-grid" id="tps-details">${[['payday-next','Next payday','Sonraki ödeme günü'],['apy-value','Estimated APY at the current block pace','Mevcut blok hızında tahmini APY']].map(([id,en,tr]) => `${text(en,tr,'div','class="detail-label"')}<div class="detail-value mono" id="${id}">—</div>`).join('')}</div>`
    + text('Rewards are paid every 17 280 blocks (24 epochs of 720). The payday estimate follows the current block pace; blocks are slower when the chain is idle, so the date can move later.', 'Ödüller her 17 280 blokta (720 bloklık 24 epoch) ödenir. Ödeme günü tahmini mevcut blok hızını izler; zincir boştayken bloklar yavaşlar, tarih ileri kayabilir.', 'p', 'class="scan-explanation"')
    + text('APY estimate: the reward reserve paid out at 1/65 536 per epoch, at the last 24 hours’ block pace, divided by the active validators’ stake — before validator commission; participation rules apply. Fees that refill the reserve are not counted.', 'APY tahmini: ödül rezervinin epoch başına 1/65 536 oranında ödenmesi, son 24 saatin blok hızıyla, aktif validatorların stake’ine bölünür — validator komisyonu düşülmeden; katılım kuralları geçerlidir. Rezervi dolduran ücretler hesaba katılmaz.', 'p', 'class="scan-explanation"')
    + `${text('Paydays', 'Ödeme günleri', 'h2', 'class="section-title"')}<div class="table-scroll" tabindex="0" role="region" aria-label="Paydays" data-label-tr="Ödeme günleri"><table class="data-table"><thead><tr>${[['Block','Blok'],['Time','Zaman'],['Total paid','Ödenen toplam'],['Recipients','Alıcı sayısı']].map(t => text(...t,'th','scope="col"')).join('')}</tr></thead><tbody id="paydays-tbody"><tr><td colspan="4" class="loading">${text('Loading payouts…', 'Ödemeler yükleniyor…')}</td></tr></tbody></table></div><p id="paydays-coverage" class="scan-explanation"></p><div id="paydays-error" role="status"></div><button id="paydays-more" type="button" class="btn-secondary payout-more" hidden>${text('Load older paydays', 'Önceki ödeme günlerini yükle')}</button>`
    + text('Open a payday block to see recipient addresses and amounts. Payouts happen at the block boundary and are listed separately from transactions. Amounts appear only for periods covered by the available payout records.', 'Alıcı adreslerini ve tutarları görmek için ödeme bloğunu aç. Ödemeler blok sınırında yapılır ve işlemlerden ayrı listelenir. Tutarlar yalnızca mevcut ödeme kayıtlarının kapsadığı dönemler için gösterilir.', 'p', 'class="scan-explanation"') + `</section>`;
  const blocks = `<section>${text('Latest blocks', 'Son bloklar', 'h2', 'class="section-title"')}${text('Scroll horizontally to see every column ↔', 'Tüm sütunları görmek için yana kaydır ↔', 'p', 'class="table-hint"')}<div class="table-scroll" tabindex="0" role="region" aria-label="Latest blocks" data-label-tr="Son bloklar"><table class="data-table"><thead><tr>${[['Height','Yükseklik'],['Block hash','Blok hash’i'],['Time','Zaman'],['Transactions','İşlemler']].map(t => text(...t,'th','scope="col"')).join('')}</tr></thead><tbody id="blocks-tbody"><tr><td colspan="4" class="loading">${text('Loading…', 'Yükleniyor…')}</td></tr></tbody></table></div><div id="blocks-pager" class="pager hidden"><button id="pg-first" class="btn-page" aria-label="Newest page" data-label-tr="En yeni sayfa">«</button><button id="pg-prev" class="btn-page" aria-label="Previous page" data-label-tr="Önceki sayfa">‹</button><span class="pager-label">${text('Page', 'Sayfa')}<input id="pg-input" class="pager-input" type="text" inputmode="numeric" aria-label="Go to page" data-label-tr="Sayfaya git"> / <span id="pg-total">1</span></span><button id="pg-next" class="btn-page" aria-label="Next page" data-label-tr="Sonraki sayfa">›</button><button id="pg-last" class="btn-page" aria-label="Oldest page" data-label-tr="En eski sayfa">»</button></div></section>`;
  const details = `<div id="${slug}-content" class="detail-content" aria-live="polite"></div>`;
  // Planned forks: static text (not on the chain yet). Numbering: decision
  // docs/plans/decisions/2026-10-05-hf-numbering-evm-hf5.md (EVM = HF-5, role stake = HF-6).
  const planned = `<section aria-label="Planned hard forks" data-label-tr="Planlanan hard fork’lar">${text('Planned hard forks', 'Planlanan hard fork’lar', 'h2', 'class="section-title"')}`
    + text('Not on the chain yet. A planned fork has no date: it switches on at a block height only after every validator runs a release that knows it and the validators vote it in.', 'Henüz zincirde değil. Planlanan bir fork’un tarihi yoktur: ancak her doğrulayıcı onu bilen sürümü çalıştırdıktan ve doğrulayıcılar oyladıktan sonra bir blok yüksekliğinde devreye girer.', 'p', 'class="scan-explanation"')
    + `<ul class="scan-explanation">${[
      ['<strong>HF-5 — Smart contracts: Nodus EVM.</strong> Our own EVM engine runs Ethereum smart contracts under the Prague rules (blob and set-code transactions are not supported), with 32-byte addresses from post-quantum keys and a built-in bridge for NODUS. Built and tested; not released yet.', '<strong>HF-5 — Akıllı kontratlar: Nodus EVM.</strong> Kendi EVM motorumuz Ethereum akıllı kontratlarını Prague kurallarıyla çalıştırır (blob ve set-code işlemleri desteklenmez); adresler kuantum sonrası anahtarlardan 32 bayt, NODUS için yerleşik köprü. Hazır ve test edildi; henüz yayımlanmadı.'],
      ['<strong>HF-6 — Lower validator stake, node roles and a power cap.</strong> A validator bond of at least 2,000,000 NODUS, storage / compute / bandwidth roles with their own stake, voting power capped from 10%, and the owner’s key separate from the node’s key. Designed; not built yet.', '<strong>HF-6 — Daha düşük validator stake’i, düğüm rolleri ve güç tavanı.</strong> En az 2.000.000 NODUS validator bağı, kendi stake’leri olan depolama / hesaplama / bant genişliği rolleri, %10’dan başlayan oy gücü tavanı ve düğümün anahtarından ayrı sahip anahtarı. Tasarlandı; henüz geliştirilmedi.'],
      ['<strong>Storage role reward.</strong> Storage nodes earn from the Storage pool when validators confirm they serve stored data. Being built; it takes the next fork number when it is ready.', '<strong>Depolama rolü ödülü.</strong> Depolama düğümleri, doğrulayıcılar sakladıkları veriyi sunduklarını onayladığında Storage havuzundan kazanır. Geliştiriliyor; hazır olduğunda sıradaki fork numarasını alır.']
    ].map(([en, tr]) => text(en, tr, 'li')).join('')}</ul></section>`;
  const footer = `<div class="scan-guide-link">${text('Make sense of what you see.', 'Gördüğün veriyi anlamlandır.')}${anchor('https://wiki.nodusnetwork.io/explorer.html', 'How to use Nodus Scan ↗', 'Nodus Scan nasıl kullanılır? ↗')}${anchor('https://wiki.nodusnetwork.io/developers.html#api', 'API reference ↗', 'API rehberi ↗')}</div><noscript><p>Scan needs JavaScript to request chain data. / Zincir verisini almak için JavaScript gerekir.</p></noscript>`;
  await output(`scan/${slug}.html`, shell('scan', slug, titles[slug], desc, hero + search + status + (slug === 'index' ? blocks : slug === 'stats' ? stats + tps : slug === 'hardforks' ? details + planned : details) + footer));
}
for (const site of ['wiki', 'scan']) {
  const pages = site === 'wiki' ? ['', ...guides.map(g => g.slug + '.html')] : ['', 'stats.html', 'hardforks.html'];
  await output(`${site}/sitemap.xml`, `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${pages.map(p => `<url><loc>https://${site}.nodusnetwork.io/${p}</loc></url>`).join('')}</urlset>`);
  await output(`${site}/robots.txt`, `User-agent: *\nAllow: /\n${site === 'scan' ? 'Disallow: /api/\n' : ''}\nSitemap: https://${site}.nodusnetwork.io/sitemap.xml`);
}
console.log(`Built ${guides.length + 1} Wiki pages and ${scanPages.length} Scan pages.`);
