/**
 * @file test_addr32.c
 * @brief Nodus EVM 32-byte address mode (cfg.addr_bytes = 32) — engine checks.
 *
 * Spec under test: docs/plans/2026-10-04-nodus-evm-engine-design.md §2
 * (decision docs/plans/decisions/2026-10-04-nodus-evm-domain.md, item 3;
 * Kurultay nodus-evm-k1 consensus item 2). The official Ethereum state tests only
 * cover addr_bytes = 20; this file pins the 32-byte behaviour with
 * hand-assembled bytecode run through the public API (evm.h) over the
 * test-only in-memory backend (tests/evm_membackend.c).
 *
 * Every account address used below has non-zero HIGH 12 bytes unless it is
 * deliberately a "20-byte projection" (12 zero bytes || the same low 20) or
 * a numeric precompile address. Addresses, init code, salt and the expected
 * CREATE / CREATE2 / create-tx addresses come from tests/addr32_vectors.h,
 * generated by tests/addr32_oracle.py (its own Keccak-f[1600] and RLP; no
 * engine or shared/crypto code).
 *
 * Checks (each prints PASS/FAIL under its name):
 *   check1_env_opcodes_push_full_word
 *       ADDRESS / CALLER / ORIGIN / COINBASE push all 32 bytes (CALLER !=
 *       ORIGIN: the observing contract is reached through an intermediary).
 *   check2_stack_address_uses_full_word
 *       CALL / STATICCALL / DELEGATECALL / CALLCODE / BALANCE / EXTCODESIZE /
 *       EXTCODEHASH / EXTCODECOPY / SELFDESTRUCT beneficiary: twin accounts
 *       with the same low 20 bytes and different high 12 bytes are distinct,
 *       and the 20-byte projection (absent) reads as empty.
 *   check3_create_create2_full_hash
 *       CREATE = keccak256(rlp([sender_32, nonce])) at nonces 0x7f and 0x80;
 *       CREATE2 = keccak256(0xff || sender_32 || salt || keccak256(init));
 *       all 32 bytes, pushed on the stack and used as the account key.
 *   check4_precompile_match_full_word
 *       0x00..01 is ecrecover (returns 32 bytes for a valid signature);
 *       0xff*12 || 0..01 is an ordinary empty account (returns nothing,
 *       receives value). Same for identity 0x04.
 *   check5_create_tx_result_created
 *       top-level create tx: res->created = oracle value (nonces 0, 0x0100).
 *   check6_eip3541_and_7702_designator
 *       0xEF-prefixed code is refused (create tx and nested CREATE); a
 *       pre-state 7702 designator (0xef0100 || 20-byte target) is followed
 *       with the target RIGHT-ALIGNED into 32 bytes (12 zero bytes || 20),
 *       through a CALL and as a top-level tx target; a decoy at
 *       (non-zero high || same 20 bytes) never runs.
 *   check7_change_set_deterministic
 *       the same transaction sequence on two fresh states yields
 *       byte-identical serialized change sets.
 *
 * Standalone harness (like tests/test_u256.c): reports via fprintf;
 * exit 0 = every check passed, 1 = a check failed, 2 = engine fault/OOM.
 */
#include "evm.h"
#include "evm_membackend.h"
#include "addr32_vectors.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* ── opcodes used (execution-specs@a87891f7 prague/vm/instructions) ──── */
#define OP_STOP          0x00
#define OP_ADDRESS       0x30
#define OP_BALANCE       0x31
#define OP_ORIGIN        0x32
#define OP_CALLER        0x33
#define OP_EXTCODESIZE   0x3b
#define OP_EXTCODECOPY   0x3c
#define OP_RETURNDATASIZE 0x3d
#define OP_EXTCODEHASH   0x3f
#define OP_COINBASE      0x41
#define OP_MLOAD         0x51
#define OP_MSTORE        0x52
#define OP_MSTORE8       0x53
#define OP_SSTORE        0x55
#define OP_GAS           0x5a
#define OP_PUSH1         0x60
#define OP_CREATE        0xf0
#define OP_CALL          0xf1
#define OP_CALLCODE      0xf2
#define OP_RETURN        0xf3
#define OP_DELEGATECALL  0xf4
#define OP_CREATE2       0xf5
#define OP_STATICCALL    0xfa
#define OP_SELFDESTRUCT  0xff

/* ecrecover vector "valid_signature_1":
 * execution-specs@a87891f7 tests/frontier/precompiles/test_ecrecover.py:58-73
 * (msg_hash, v, r, s -> output). */
static const char *ECREC_HASH =
    "18c547e4f7b0f325ad1e56f57e26c745b09a3e503d86e00e5255ff7f715d3d1c";
static const char *ECREC_V =
    "000000000000000000000000000000000000000000000000000000000000001c";
static const char *ECREC_R =
    "73b1693892219d736caba55bdb67216e485557ea6b6af75f37096c9aa6a5a75f";
static const char *ECREC_S =
    "eeb940b1d03b21e36b0e47e79769f095fe2ab855bd91e3a38756b7d75a9c4549";
static const char *ECREC_OUT =
    "000000000000000000000000a94f5374fce5edbc8e2a8697c15331677e6ebf0b";

/* ── tiny assembler ──────────────────────────────────────────────────── */

typedef struct {
    uint8_t b[2048];
    size_t  n;
    int     overflow;
} asm_t;

static void a_byte(asm_t *a, uint8_t v)
{
    if (a->n >= sizeof(a->b)) {
        a->overflow = 1;
        return;
    }
    a->b[a->n++] = v;
}

/* PUSH<len> v[0..len) (1 <= len <= 32) */
static void a_push(asm_t *a, const uint8_t *v, size_t len)
{
    a_byte(a, (uint8_t)(OP_PUSH1 + len - 1));
    for (size_t i = 0; i < len; i++) a_byte(a, v[i]);
}

static void a_push1(asm_t *a, uint8_t v)
{
    a_push(a, &v, 1);
}

static void a_push32(asm_t *a, const uint8_t v[32])
{
    a_push(a, v, 32);
}

/* <value on stack> -> storage[slot] */
static void a_store(asm_t *a, uint8_t slot)
{
    a_push1(a, slot);
    a_byte(a, OP_SSTORE);
}

/* CALL / CALLCODE (with value) or DELEGATECALL / STATICCALL (without),
 * forwarding all available gas; leaves the success flag on the stack. */
static void a_call(asm_t *a, uint8_t op, const uint8_t addr[32], uint8_t value,
                   uint8_t in_off, uint8_t in_size,
                   uint8_t out_off, uint8_t out_size)
{
    a_push1(a, out_size);
    a_push1(a, out_off);
    a_push1(a, in_size);
    a_push1(a, in_off);
    if (op == OP_CALL || op == OP_CALLCODE) a_push1(a, value);
    a_push32(a, addr);
    a_byte(a, OP_GAS);
    a_byte(a, op);
}

/* init code (<= 32 bytes) right-aligned into memory word 0; returns its
 * memory offset (32 - len). */
static uint8_t a_mstore_code(asm_t *a, const uint8_t *code, size_t len)
{
    a_push(a, code, len);
    a_push1(a, 0);
    a_byte(a, OP_MSTORE);
    return (uint8_t)(32 - len);
}

/* ── small helpers ──────────────────────────────────────────────────── */

static int hexval(char c)
{
    if (c >= '0' && c <= '9') return c - '0';
    if (c >= 'a' && c <= 'f') return c - 'a' + 10;
    return -1;
}

/* 64 lowercase hex digits -> 32 bytes (no engine code) */
static void hex32(uint8_t out[32], const char *s)
{
    for (int i = 0; i < 32; i++)
        out[i] = (uint8_t)(hexval(s[2 * i]) * 16 + hexval(s[2 * i + 1]));
}

static void word_u64(uint8_t out[32], uint64_t v)
{
    memset(out, 0, 32);
    for (int i = 0; i < 8; i++) out[31 - i] = (uint8_t)(v >> (8 * i));
}

static evm_addr mkaddr(const uint8_t b[32])
{
    evm_addr a;
    memcpy(a.b, b, 32);
    return a;
}

static const uint8_t ZERO32[32];

/* ── check bookkeeping ─────────────────────────────────────────────── */

static unsigned g_fail_checks;
static unsigned g_check_fail;      /* failures inside the current check */
static const char *g_check;

static void check_begin(const char *name)
{
    g_check = name;
    g_check_fail = 0;
}

static void expect(int cond, const char *what)
{
    if (!cond) {
        fprintf(stderr, "  [FAIL] %s: %s\n", g_check, what);
        g_check_fail++;
    }
}

static void expect_word(const uint8_t got[32], const uint8_t want[32],
                        const char *what)
{
    if (memcmp(got, want, 32) != 0) {
        fprintf(stderr, "  [FAIL] %s: %s\n    got  ", g_check, what);
        for (int i = 0; i < 32; i++) fprintf(stderr, "%02x", got[i]);
        fprintf(stderr, "\n    want ");
        for (int i = 0; i < 32; i++) fprintf(stderr, "%02x", want[i]);
        fprintf(stderr, "\n");
        g_check_fail++;
    }
}

static void check_end(void)
{
    fprintf(stderr, "%s: %s\n", g_check, g_check_fail ? "FAIL" : "PASS");
    if (g_check_fail) g_fail_checks++;
}

/* A fault (-2) or OOM aborts the whole run: there is no outcome to judge. */
static void fatal(const char *what)
{
    fprintf(stderr, "FATAL (%s): %s\n", g_check ? g_check : "setup", what);
    exit(2);
}

/* ── captured change set ───────────────────────────────────────────── */

typedef struct {
    evm_addr    addr;
    int         deleted;
    uint64_t    nonce;
    uint8_t     balance[32];
    int         code_changed;
    uint8_t    *code;               /* copied inside the callback */
    size_t      code_len;
    evm_bytes32 code_hash;
    int         storage_cleared;
} acc_rec;

typedef struct {
    evm_addr    addr;
    evm_bytes32 key;
    evm_bytes32 val;
} slot_rec;

typedef struct {
    acc_rec  *acc;
    size_t    na, cap_a;
    slot_rec *sl;
    size_t    ns, cap_s;
    uint8_t  *ser;                  /* canonical serialization (check 7) */
    size_t    ser_len, ser_cap;
} changes_t;

static void ser_put(changes_t *c, const void *p, size_t n)
{
    if (c->ser_len + n > c->ser_cap) {
        size_t nc = c->ser_cap ? c->ser_cap * 2 : 4096;
        while (nc < c->ser_len + n) nc *= 2;
        uint8_t *x = realloc(c->ser, nc);
        if (!x) fatal("oom (serialization)");
        c->ser = x;
        c->ser_cap = nc;
    }
    if (n) memcpy(c->ser + c->ser_len, p, n);
    c->ser_len += n;
}

static void ser_u64(changes_t *c, uint64_t v)
{
    uint8_t b[8];
    for (int i = 0; i < 8; i++) b[i] = (uint8_t)(v >> (56 - 8 * i));
    ser_put(c, b, 8);
}

static int cb_account(void *ctx, const evm_account_change_t *ch)
{
    changes_t *c = ctx;
    if (c->na == c->cap_a) {
        size_t nc = c->cap_a ? c->cap_a * 2 : 32;
        acc_rec *x = realloc(c->acc, nc * sizeof(*x));
        if (!x) fatal("oom (account records)");
        c->acc = x;
        c->cap_a = nc;
    }
    acc_rec *r = &c->acc[c->na++];
    memset(r, 0, sizeof(*r));
    r->addr = ch->addr;
    r->deleted = ch->deleted;
    r->nonce = ch->nonce;
    evm_u256_to_be(r->balance, &ch->balance);
    r->code_changed = ch->code_changed;
    if (ch->code_changed && ch->code_len) {
        r->code = malloc(ch->code_len);
        if (!r->code) fatal("oom (code copy)");
        memcpy(r->code, ch->code, ch->code_len);
        r->code_len = ch->code_len;
    }
    r->code_hash = ch->code_hash;
    r->storage_cleared = ch->storage_cleared;

    uint8_t tag = 'A';
    ser_put(c, &tag, 1);
    ser_put(c, r->addr.b, 32);
    ser_u64(c, (uint64_t)r->deleted);
    ser_u64(c, r->nonce);
    ser_put(c, r->balance, 32);
    ser_u64(c, (uint64_t)r->code_changed);
    ser_u64(c, (uint64_t)r->code_len);
    ser_put(c, r->code, r->code_len);
    ser_put(c, r->code_hash.b, 32);
    ser_u64(c, (uint64_t)r->storage_cleared);
    return 0;
}

static int cb_storage(void *ctx, const evm_addr *addr, const evm_bytes32 *key,
                      const evm_bytes32 *value)
{
    changes_t *c = ctx;
    if (c->ns == c->cap_s) {
        size_t nc = c->cap_s ? c->cap_s * 2 : 64;
        slot_rec *x = realloc(c->sl, nc * sizeof(*x));
        if (!x) fatal("oom (slot records)");
        c->sl = x;
        c->cap_s = nc;
    }
    slot_rec *s = &c->sl[c->ns++];
    s->addr = *addr;
    s->key = *key;
    s->val = *value;

    uint8_t tag = 'S';
    ser_put(c, &tag, 1);
    ser_put(c, addr->b, 32);
    ser_put(c, key->b, 32);
    ser_put(c, value->b, 32);
    return 0;
}

static void changes_free(changes_t *c)
{
    for (size_t i = 0; i < c->na; i++) free(c->acc[i].code);
    free(c->acc);
    free(c->sl);
    free(c->ser);
    memset(c, 0, sizeof(*c));
}

static void collect(const evm_state_t *st, changes_t *c)
{
    memset(c, 0, sizeof(*c));
    evm_change_visitor_t v;
    v.account = cb_account;
    v.storage = cb_storage;
    v.ctx = c;
    if (evm_state_visit_changes(st, &v) != 0) fatal("visit_changes");
}

/* ── post-state view: change set over the pre-state ─────────────────── */

typedef struct {
    const evm_membackend *pre;
    const changes_t      *cs;
} post_t;

static const acc_rec *post_rec(const post_t *p, const uint8_t a[32])
{
    for (size_t i = 0; i < p->cs->na; i++)
        if (memcmp(p->cs->acc[i].addr.b, a, 32) == 0) return &p->cs->acc[i];
    return NULL;
}

static const evm_mem_account *pre_acc(const post_t *p, const uint8_t a[32])
{
    evm_addr x = mkaddr(a);
    return evm_membackend_find(p->pre, &x);
}

/* 1 = the account exists after the transaction(s) */
static int post_exists(const post_t *p, const uint8_t a[32])
{
    const acc_rec *r = post_rec(p, a);
    if (r) return !r->deleted;
    return pre_acc(p, a) != NULL;
}

static void post_balance(const post_t *p, const uint8_t a[32], uint8_t out[32])
{
    const acc_rec *r = post_rec(p, a);
    if (r) {
        if (r->deleted) memset(out, 0, 32);
        else memcpy(out, r->balance, 32);
        return;
    }
    const evm_mem_account *m = pre_acc(p, a);
    if (m) memcpy(out, m->balance, 32);
    else memset(out, 0, 32);
}

static uint64_t post_nonce(const post_t *p, const uint8_t a[32])
{
    const acc_rec *r = post_rec(p, a);
    if (r) return r->deleted ? 0 : r->nonce;
    const evm_mem_account *m = pre_acc(p, a);
    return m ? m->nonce : 0;
}

static void post_code(const post_t *p, const uint8_t a[32],
                      const uint8_t **code, size_t *len)
{
    const acc_rec *r = post_rec(p, a);
    *code = NULL;
    *len = 0;
    if (r && r->deleted) return;
    if (r && r->code_changed) {
        *code = r->code;
        *len = r->code_len;
        return;
    }
    const evm_mem_account *m = pre_acc(p, a);
    if (m) {
        *code = m->code;
        *len = m->code_len;
    }
}

static void post_slot(const post_t *p, const uint8_t a[32], uint64_t key,
                      uint8_t out[32])
{
    uint8_t k[32];
    word_u64(k, key);
    for (size_t i = 0; i < p->cs->ns; i++)
        if (memcmp(p->cs->sl[i].addr.b, a, 32) == 0 &&
            memcmp(p->cs->sl[i].key.b, k, 32) == 0) {
            memcpy(out, p->cs->sl[i].val.b, 32);
            return;
        }
    const acc_rec *r = post_rec(p, a);
    if (r && (r->deleted || r->storage_cleared)) {
        memset(out, 0, 32);
        return;
    }
    const evm_mem_account *m = pre_acc(p, a);
    evm_bytes32 kk;
    memcpy(kk.b, k, 32);
    const evm_bytes32 *v = m ? evm_mem_account_find_slot(m, &kk) : NULL;
    if (v) memcpy(out, v->b, 32);
    else memset(out, 0, 32);
}

static void expect_slot(const post_t *p, const uint8_t a[32], uint64_t key,
                        const uint8_t want[32], const char *what)
{
    uint8_t got[32];
    post_slot(p, a, key, got);
    expect_word(got, want, what);
}

static void expect_slot_u64(const post_t *p, const uint8_t a[32], uint64_t key,
                            uint64_t want, const char *what)
{
    uint8_t w[32];
    word_u64(w, want);
    expect_slot(p, a, key, w, what);
}

static void expect_balance_u64(const post_t *p, const uint8_t a[32],
                               uint64_t want, const char *what)
{
    uint8_t got[32], w[32];
    post_balance(p, a, got);
    word_u64(w, want);
    expect_word(got, w, what);
}

static void expect_code(const post_t *p, const uint8_t a[32],
                        const uint8_t *want, size_t want_len, const char *what)
{
    const uint8_t *code;
    size_t len;
    post_code(p, a, &code, &len);
    expect(len == want_len && (len == 0 || memcmp(code, want, len) == 0), what);
}

/* ── the pre-state ──────────────────────────────────────────────────── */

/* pre-state balances (wei) */
#define BAL_SENDER      1000000000000000000ull   /* 1e18 */
#define BAL_DRIVER      1000ull
#define BAL_X_HI        0x1111ull
#define BAL_X_LO        0x2222ull
#define BAL_SD          0x777ull
#define BAL_S_LO        0x55ull

/* check 8's contract (high 12 bytes non-zero, like every account here) */
static const uint8_t ADDR32_BLOBFEE[32] = {
    0xb1, 0x0b, 0xfe, 0xe0, 0xb1, 0x0b, 0xfe, 0xe0, 0xb1, 0x0b, 0xfe, 0xe0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x4a, 0x4a };

static void add_acc(evm_membackend *mb, const uint8_t a[32], uint64_t nonce,
                    uint64_t balance, const uint8_t *code, size_t code_len)
{
    uint8_t bal[32];
    word_u64(bal, balance);
    evm_addr x = mkaddr(a);
    if (evm_membackend_add_account(mb, &x, nonce, bal, code, code_len,
                                   NULL, NULL) != 0)
        fatal("membackend_add_account");
}

static void add_asm(evm_membackend *mb, const uint8_t a[32], uint64_t nonce,
                    uint64_t balance, const asm_t *code)
{
    if (code->overflow) fatal("assembler overflow");
    add_acc(mb, a, nonce, balance, code->b, code->n);
}

/* code: PUSH1 v PUSH1 slot SSTORE STOP, then `pad` extra STOPs */
static void code_store(asm_t *a, uint8_t v, uint8_t slot, unsigned pad)
{
    memset(a, 0, sizeof(*a));
    a_push1(a, v);
    a_store(a, slot);
    a_byte(a, OP_STOP);
    for (unsigned i = 0; i < pad; i++) a_byte(a, OP_STOP);
}

/* code: MSTORE(0, v); RETURN(0, 32) */
static void code_return_word(asm_t *a, uint8_t v)
{
    memset(a, 0, sizeof(*a));
    a_push1(a, v);
    a_push1(a, 0);
    a_byte(a, OP_MSTORE);
    a_push1(a, 32);
    a_push1(a, 0);
    a_byte(a, OP_RETURN);
}

static void build_pre(evm_membackend *mb)
{
    asm_t a;
    evm_membackend_init(mb);

    add_acc(mb, ADDR32_SENDER, 3, BAL_SENDER, NULL, 0);
    add_acc(mb, ADDR32_CREATOR0, ADDR32_NONCE_CREATOR0, BAL_SENDER, NULL, 0);
    add_acc(mb, ADDR32_CREATOR1, ADDR32_NONCE_CREATOR1, BAL_SENDER, NULL, 0);
    add_acc(mb, ADDR32_CREATOR_EF, ADDR32_NONCE_CREATOR_EF, BAL_SENDER, NULL, 0);

    /* check 1 */
    memset(&a, 0, sizeof(a));
    a_byte(&a, OP_ADDRESS);  a_store(&a, 0);
    a_byte(&a, OP_CALLER);   a_store(&a, 1);
    a_byte(&a, OP_ORIGIN);   a_store(&a, 2);
    a_byte(&a, OP_COINBASE); a_store(&a, 3);
    a_byte(&a, OP_STOP);
    add_asm(mb, ADDR32_ENV_INNER, 1, 0, &a);

    memset(&a, 0, sizeof(a));
    a_call(&a, OP_CALL, ADDR32_ENV_INNER, 0, 0, 0, 0, 0);
    a_store(&a, 0);
    a_byte(&a, OP_ADDRESS); a_store(&a, 1);
    a_byte(&a, OP_CALLER);  a_store(&a, 2);
    a_byte(&a, OP_STOP);
    add_asm(mb, ADDR32_ENV_OUTER, 1, 0, &a);

    /* check 8: BLOBBASEFEE PUSH1 0 SSTORE STOP */
    memset(&a, 0, sizeof(a));
    a_byte(&a, 0x4a);        a_store(&a, 0);
    a_byte(&a, OP_STOP);
    add_asm(mb, ADDR32_BLOBFEE, 1, 0, &a);

    /* check 2: twins (different code lengths so EXTCODESIZE differs) */
    code_store(&a, 0xA1, 0x00, 0);  add_asm(mb, ADDR32_X_HI, 1, BAL_X_HI, &a);
    code_store(&a, 0xB2, 0x00, 2);  add_asm(mb, ADDR32_X_LO, 1, BAL_X_LO, &a);
    code_return_word(&a, 0xA2);     add_asm(mb, ADDR32_Y_HI, 1, 0, &a);
    code_return_word(&a, 0xB3);     add_asm(mb, ADDR32_Y_LO, 1, 0, &a);
    code_store(&a, 0xA3, 0x71, 0);  add_asm(mb, ADDR32_Z_HI, 1, 0, &a);
    code_store(&a, 0xB4, 0x73, 0);  add_asm(mb, ADDR32_Z_LO, 1, 0, &a);
    code_store(&a, 0xA4, 0x81, 0);  add_asm(mb, ADDR32_W_HI, 1, 0, &a);
    code_store(&a, 0xB5, 0x83, 0);  add_asm(mb, ADDR32_W_LO, 1, 0, &a);
    memset(&a, 0, sizeof(a));
    a_push32(&a, ADDR32_S_HI);
    a_byte(&a, OP_SELFDESTRUCT);
    add_asm(mb, ADDR32_SD, 1, BAL_SD, &a);
    add_acc(mb, ADDR32_S_LO, 0, BAL_S_LO, NULL, 0);
    /* X_PROJ, S_PROJ, S_HI: deliberately absent */

    memset(&a, 0, sizeof(a));
    a_push32(&a, ADDR32_X_HI);   a_byte(&a, OP_BALANCE);     a_store(&a, 0x10);
    a_push32(&a, ADDR32_X_LO);   a_byte(&a, OP_BALANCE);     a_store(&a, 0x11);
    a_push32(&a, ADDR32_X_PROJ); a_byte(&a, OP_BALANCE);     a_store(&a, 0x12);
    a_push32(&a, ADDR32_X_HI);   a_byte(&a, OP_EXTCODESIZE); a_store(&a, 0x20);
    a_push32(&a, ADDR32_X_LO);   a_byte(&a, OP_EXTCODESIZE); a_store(&a, 0x21);
    a_push32(&a, ADDR32_X_PROJ); a_byte(&a, OP_EXTCODESIZE); a_store(&a, 0x22);
    a_push32(&a, ADDR32_X_HI);   a_byte(&a, OP_EXTCODEHASH); a_store(&a, 0x30);
    a_push32(&a, ADDR32_X_LO);   a_byte(&a, OP_EXTCODEHASH); a_store(&a, 0x31);
    a_push32(&a, ADDR32_X_PROJ); a_byte(&a, OP_EXTCODEHASH); a_store(&a, 0x32);
    /* EXTCODECOPY(addr, mem 0, src 0, 32) ; MLOAD 0 */
    a_push1(&a, 32); a_push1(&a, 0); a_push1(&a, 0);
    a_push32(&a, ADDR32_X_HI); a_byte(&a, OP_EXTCODECOPY);
    a_push1(&a, 0); a_byte(&a, OP_MLOAD); a_store(&a, 0x40);
    a_push1(&a, 32); a_push1(&a, 0); a_push1(&a, 0);
    a_push32(&a, ADDR32_X_LO); a_byte(&a, OP_EXTCODECOPY);
    a_push1(&a, 0); a_byte(&a, OP_MLOAD); a_store(&a, 0x41);
    /* CALL with value: storage and balance land on the right twin */
    a_call(&a, OP_CALL, ADDR32_X_HI, 1, 0, 0, 0, 0); a_store(&a, 0x50);
    a_call(&a, OP_CALL, ADDR32_X_LO, 2, 0, 0, 0, 0); a_store(&a, 0x51);
    /* STATICCALL: returned word identifies the code that ran */
    a_call(&a, OP_STATICCALL, ADDR32_Y_HI, 0, 0, 0, 0, 32); a_store(&a, 0x60);
    a_push1(&a, 0); a_byte(&a, OP_MLOAD); a_store(&a, 0x61);
    a_call(&a, OP_STATICCALL, ADDR32_Y_LO, 0, 0, 0, 0, 32); a_store(&a, 0x62);
    a_push1(&a, 0); a_byte(&a, OP_MLOAD); a_store(&a, 0x63);
    /* DELEGATECALL / CALLCODE: the twin's code writes OUR storage */
    a_call(&a, OP_DELEGATECALL, ADDR32_Z_HI, 0, 0, 0, 0, 0); a_store(&a, 0x70);
    a_call(&a, OP_DELEGATECALL, ADDR32_Z_LO, 0, 0, 0, 0, 0); a_store(&a, 0x72);
    a_call(&a, OP_CALLCODE, ADDR32_W_HI, 0, 0, 0, 0, 0);     a_store(&a, 0x80);
    a_call(&a, OP_CALLCODE, ADDR32_W_LO, 0, 0, 0, 0, 0);     a_store(&a, 0x82);
    /* SELFDESTRUCT beneficiary */
    a_call(&a, OP_CALL, ADDR32_SD, 0, 0, 0, 0, 0);           a_store(&a, 0x90);
    a_byte(&a, OP_STOP);
    add_asm(mb, ADDR32_TWIN_DRIVER, 1, BAL_DRIVER, &a);

    /* check 3: FACTORY — CREATE (nonce 0x7f), CREATE (0x80), CREATE2 */
    memset(&a, 0, sizeof(a));
    {
        uint8_t off = a_mstore_code(&a, ADDR32_INITCODE, sizeof(ADDR32_INITCODE));
        uint8_t len = (uint8_t)sizeof(ADDR32_INITCODE);
        a_push1(&a, len); a_push1(&a, off); a_push1(&a, 0);
        a_byte(&a, OP_CREATE); a_store(&a, 0);
        a_push1(&a, len); a_push1(&a, off); a_push1(&a, 0);
        a_byte(&a, OP_CREATE); a_store(&a, 1);
        a_push32(&a, ADDR32_SALT);
        a_push1(&a, len); a_push1(&a, off); a_push1(&a, 0);
        a_byte(&a, OP_CREATE2); a_store(&a, 2);
        a_byte(&a, OP_STOP);
    }
    add_asm(mb, ADDR32_FACTORY, ADDR32_NONCE_FACTORY, 0, &a);

    /* check 4: PC_DRIVER */
    memset(&a, 0, sizeof(a));
    {
        uint8_t w[32];
        hex32(w, ECREC_HASH); a_push32(&a, w); a_push1(&a, 0);  a_byte(&a, OP_MSTORE);
        hex32(w, ECREC_V);    a_push32(&a, w); a_push1(&a, 32); a_byte(&a, OP_MSTORE);
        hex32(w, ECREC_R);    a_push32(&a, w); a_push1(&a, 64); a_byte(&a, OP_MSTORE);
        hex32(w, ECREC_S);    a_push32(&a, w); a_push1(&a, 96); a_byte(&a, OP_MSTORE);
        uint8_t pc01[32] = {0}, pc04[32] = {0};
        pc01[31] = 0x01;
        pc04[31] = 0x04;
        /* real ecrecover: out -> mem[128..160) */
        a_call(&a, OP_STATICCALL, pc01, 0, 0, 128, 128, 32); a_store(&a, 0);
        a_byte(&a, OP_RETURNDATASIZE);                       a_store(&a, 1);
        a_push1(&a, 128); a_byte(&a, OP_MLOAD);              a_store(&a, 2);
        /* fake: same input, out -> mem[160..192) */
        a_call(&a, OP_STATICCALL, ADDR32_FAKE01, 0, 0, 128, 160, 32);
        a_store(&a, 3);
        a_byte(&a, OP_RETURNDATASIZE);                       a_store(&a, 4);
        a_push1(&a, 160); a_byte(&a, OP_MLOAD);              a_store(&a, 5);
        /* the fake is an ordinary account: it can receive value */
        a_call(&a, OP_CALL, ADDR32_FAKE01, 1, 0, 0, 0, 0);   a_store(&a, 6);
        /* identity: 5 input bytes */
        a_call(&a, OP_STATICCALL, pc04, 0, 0, 5, 0, 0);      a_store(&a, 9);
        a_byte(&a, OP_RETURNDATASIZE);                       a_store(&a, 7);
        a_call(&a, OP_STATICCALL, ADDR32_FAKE04, 0, 0, 5, 0, 0);
        a_store(&a, 10);
        a_byte(&a, OP_RETURNDATASIZE);                       a_store(&a, 8);
        a_byte(&a, OP_STOP);
    }
    add_asm(mb, ADDR32_PC_DRIVER, 1, BAL_DRIVER, &a);

    /* check 6: nested CREATE of 0xEF code */
    memset(&a, 0, sizeof(a));
    {
        uint8_t off = a_mstore_code(&a, ADDR32_INITCODE_EF,
                                    sizeof(ADDR32_INITCODE_EF));
        a_push1(&a, (uint8_t)sizeof(ADDR32_INITCODE_EF));
        a_push1(&a, off);
        a_push1(&a, 0);
        a_byte(&a, OP_CREATE); a_store(&a, 0);
        a_byte(&a, OP_STOP);
    }
    add_asm(mb, ADDR32_EF_FACTORY, ADDR32_NONCE_EF_FACTORY, 0, &a);

    /* check 6: 7702 designator 0xef0100 || DEL_TARGET[12..32) */
    {
        uint8_t des[23];
        des[0] = 0xef;
        des[1] = 0x01;
        des[2] = 0x00;
        memcpy(des + 3, ADDR32_DEL_TARGET + 12, 20);
        add_acc(mb, ADDR32_DELEGATED, 0, 0, des, sizeof(des));
    }
    memset(&a, 0, sizeof(a));
    a_byte(&a, OP_ADDRESS); a_store(&a, 1);
    a_push1(&a, 0xE7);      a_store(&a, 0);
    a_byte(&a, OP_STOP);
    add_asm(mb, ADDR32_DEL_TARGET, 1, 0, &a);
    memset(&a, 0, sizeof(a));
    a_push1(&a, 0xDE);      a_store(&a, 0);
    a_push1(&a, 0xDE);      a_store(&a, 2);
    a_byte(&a, OP_STOP);
    add_asm(mb, ADDR32_DEL_DECOY, 1, 0, &a);
    memset(&a, 0, sizeof(a));
    a_call(&a, OP_CALL, ADDR32_DELEGATED, 0, 0, 0, 0, 0); a_store(&a, 0);
    a_byte(&a, OP_STOP);
    add_asm(mb, ADDR32_DEL_DRIVER, 1, 0, &a);

    if (evm_membackend_finalize(mb) != 0) fatal("membackend_finalize");
}

/* ── running transactions ──────────────────────────────────────────── */

/* A Nodus-style 32-byte chain id with non-zero high bytes (evm.h: never
 * truncated). */
static void chain_id(evm_u256 *out)
{
    uint8_t b[32];
    for (int i = 0; i < 32; i++) b[i] = (uint8_t)(0xA0 + i);
    evm_u256_from_be(out, b);
}

static void make_cfg(evm_config_t *cfg)
{
    memset(cfg, 0, sizeof(*cfg));
    cfg->fork = EVM_FORK_PRAGUE;
    cfg->addr_bytes = 32;
    chain_id(&cfg->chain_id);
    /* precompile set is configuration (evm.h precompile_mask, red-team
     * round 1 fix 7): this file pins the Prague set */
    cfg->precompile_mask = EVM_PRECOMPILES_PRAGUE;
}

static void make_env(evm_block_env_t *env)
{
    memset(env, 0, sizeof(*env));
    memcpy(env->coinbase.b, ADDR32_COINBASE, 32);
    env->number = 100;
    env->timestamp = 1000;
    env->gas_limit = 30000000;
    evm_u256_from_u64(&env->base_fee, 7);
}

typedef struct {
    evm_backend_t   be;
    evm_config_t    cfg;
    evm_block_env_t env;
    evm_state_t    *st;
} run_t;

static void run_open(run_t *r, const evm_membackend *mb)
{
    make_cfg(&r->cfg);
    make_env(&r->env);
    evm_membackend_bind(mb, &r->be);
    r->st = evm_state_new(&r->cfg, &r->be);
    if (!r->st) fatal("evm_state_new");
}

static void run_close(run_t *r)
{
    evm_state_free(r->st);
    r->st = NULL;
}

/* legacy (type 0) tx with the configured chain id; returns evm_tx_apply's
 * return value; a fault (-2) is fatal. */
static int run_tx(run_t *r, const uint8_t from[32], uint64_t nonce,
                  const uint8_t *to, const uint8_t *data, size_t data_len,
                  evm_tx_result_t *res)
{
    evm_tx_t tx;
    memset(&tx, 0, sizeof(tx));
    tx.type = 0;
    memcpy(tx.sender.b, from, 32);
    if (to) memcpy(tx.to.b, to, 32);
    else tx.is_create = 1;
    tx.nonce = nonce;
    tx.gas_limit = 5000000;
    evm_u256_from_u64(&tx.gas_price, 10);
    tx.data = data;
    tx.data_len = data_len;
    tx.has_chain_id = 1;
    chain_id(&tx.chain_id);
    int rc = evm_tx_apply(r->st, &r->env, &tx, res);
    if (rc == -2) fatal("evm_tx_apply fault");
    return rc;
}

/* one call tx from SENDER (nonce 3) on a fresh state; change set into cs */
static int run_single_call(const evm_membackend *mb, const uint8_t to[32],
                           changes_t *cs, evm_exec_status_t *status)
{
    run_t r;
    evm_tx_result_t res;
    run_open(&r, mb);
    int rc = run_tx(&r, ADDR32_SENDER, 3, to, NULL, 0, &res);
    *status = res.status;
    if (rc == 0) collect(r.st, cs);
    else memset(cs, 0, sizeof(*cs));
    evm_tx_result_free(&res);
    run_close(&r);
    return rc;
}

/* ── the checks ─────────────────────────────────────────────────────── */

static void check1(const evm_membackend *mb)
{
    check_begin("check1_env_opcodes_push_full_word");
    changes_t cs;
    evm_exec_status_t status;
    int rc = run_single_call(mb, ADDR32_ENV_OUTER, &cs, &status);
    expect(rc == 0, "tx applied");
    expect(status == EVM_EXEC_SUCCESS, "tx succeeded");
    post_t p = { mb, &cs };
    expect_slot_u64(&p, ADDR32_ENV_OUTER, 0, 1, "outer CALL to inner succeeded");
    expect_slot(&p, ADDR32_ENV_INNER, 0, ADDR32_ENV_INNER, "inner ADDRESS");
    expect_slot(&p, ADDR32_ENV_INNER, 1, ADDR32_ENV_OUTER,
                "inner CALLER = outer contract");
    expect_slot(&p, ADDR32_ENV_INNER, 2, ADDR32_SENDER, "inner ORIGIN = sender");
    expect_slot(&p, ADDR32_ENV_INNER, 3, ADDR32_COINBASE, "inner COINBASE");
    expect_slot(&p, ADDR32_ENV_OUTER, 1, ADDR32_ENV_OUTER, "outer ADDRESS");
    expect_slot(&p, ADDR32_ENV_OUTER, 2, ADDR32_SENDER,
                "outer CALLER = sender (top level)");
    changes_free(&cs);
    check_end();
}

static void check2(const evm_membackend *mb)
{
    check_begin("check2_stack_address_uses_full_word");
    changes_t cs;
    evm_exec_status_t status;
    int rc = run_single_call(mb, ADDR32_TWIN_DRIVER, &cs, &status);
    expect(rc == 0, "tx applied");
    expect(status == EVM_EXEC_SUCCESS, "tx succeeded");
    post_t p = { mb, &cs };
    const uint8_t *D = ADDR32_TWIN_DRIVER;
    evm_addr xhi = mkaddr(ADDR32_X_HI), xlo = mkaddr(ADDR32_X_LO);
    const evm_mem_account *mhi = evm_membackend_find(mb, &xhi);
    const evm_mem_account *mlo = evm_membackend_find(mb, &xlo);
    if (!mhi || !mlo) fatal("twin pre-state missing");

    /* BALANCE */
    expect_slot_u64(&p, D, 0x10, BAL_X_HI, "BALANCE(X_HI)");
    expect_slot_u64(&p, D, 0x11, BAL_X_LO, "BALANCE(X_LO)");
    expect_slot_u64(&p, D, 0x12, 0, "BALANCE(20-byte projection) = 0");
    /* EXTCODESIZE */
    expect_slot_u64(&p, D, 0x20, mhi->code_len, "EXTCODESIZE(X_HI)");
    expect_slot_u64(&p, D, 0x21, mlo->code_len, "EXTCODESIZE(X_LO)");
    expect_slot_u64(&p, D, 0x22, 0, "EXTCODESIZE(projection) = 0");
    expect(mhi->code_len != mlo->code_len, "fixture: twin code sizes differ");
    /* EXTCODEHASH */
    expect_slot(&p, D, 0x30, mhi->code_hash.b, "EXTCODEHASH(X_HI)");
    expect_slot(&p, D, 0x31, mlo->code_hash.b, "EXTCODEHASH(X_LO)");
    expect_slot(&p, D, 0x32, ZERO32, "EXTCODEHASH(absent projection) = 0");
    /* EXTCODECOPY: first 32 bytes, zero padded */
    {
        uint8_t w[32] = {0};
        memcpy(w, mhi->code, mhi->code_len);
        expect_slot(&p, D, 0x40, w, "EXTCODECOPY(X_HI)");
        memset(w, 0, 32);
        memcpy(w, mlo->code, mlo->code_len);
        expect_slot(&p, D, 0x41, w, "EXTCODECOPY(X_LO)");
    }
    /* CALL with value */
    expect_slot_u64(&p, D, 0x50, 1, "CALL X_HI succeeded");
    expect_slot_u64(&p, D, 0x51, 1, "CALL X_LO succeeded");
    expect_slot_u64(&p, ADDR32_X_HI, 0, 0xA1, "X_HI code wrote X_HI storage");
    expect_slot_u64(&p, ADDR32_X_LO, 0, 0xB2, "X_LO code wrote X_LO storage");
    expect_balance_u64(&p, ADDR32_X_HI, BAL_X_HI + 1, "X_HI balance += 1");
    expect_balance_u64(&p, ADDR32_X_LO, BAL_X_LO + 2, "X_LO balance += 2");
    expect(!post_exists(&p, ADDR32_X_PROJ), "20-byte projection not created");
    expect_slot_u64(&p, ADDR32_X_PROJ, 0, 0, "projection storage untouched");
    expect_balance_u64(&p, D, BAL_DRIVER - 3, "driver paid 1 + 2");
    /* STATICCALL */
    expect_slot_u64(&p, D, 0x60, 1, "STATICCALL Y_HI succeeded");
    expect_slot_u64(&p, D, 0x61, 0xA2, "STATICCALL Y_HI ran Y_HI code");
    expect_slot_u64(&p, D, 0x62, 1, "STATICCALL Y_LO succeeded");
    expect_slot_u64(&p, D, 0x63, 0xB3, "STATICCALL Y_LO ran Y_LO code");
    /* DELEGATECALL */
    expect_slot_u64(&p, D, 0x70, 1, "DELEGATECALL Z_HI succeeded");
    expect_slot_u64(&p, D, 0x71, 0xA3, "DELEGATECALL Z_HI ran Z_HI code");
    expect_slot_u64(&p, D, 0x72, 1, "DELEGATECALL Z_LO succeeded");
    expect_slot_u64(&p, D, 0x73, 0xB4, "DELEGATECALL Z_LO ran Z_LO code");
    expect_slot_u64(&p, ADDR32_Z_HI, 0x71, 0, "Z_HI own storage untouched");
    expect_slot_u64(&p, ADDR32_Z_LO, 0x73, 0, "Z_LO own storage untouched");
    /* CALLCODE */
    expect_slot_u64(&p, D, 0x80, 1, "CALLCODE W_HI succeeded");
    expect_slot_u64(&p, D, 0x81, 0xA4, "CALLCODE W_HI ran W_HI code");
    expect_slot_u64(&p, D, 0x82, 1, "CALLCODE W_LO succeeded");
    expect_slot_u64(&p, D, 0x83, 0xB5, "CALLCODE W_LO ran W_LO code");
    expect_slot_u64(&p, ADDR32_W_HI, 0x81, 0, "W_HI own storage untouched");
    expect_slot_u64(&p, ADDR32_W_LO, 0x83, 0, "W_LO own storage untouched");
    /* SELFDESTRUCT (pre-existing contract: EIP-6780 keeps it, moves balance) */
    expect_slot_u64(&p, D, 0x90, 1, "CALL SD succeeded");
    expect_balance_u64(&p, ADDR32_S_HI, BAL_SD, "beneficiary S_HI got SD balance");
    expect_balance_u64(&p, ADDR32_S_LO, BAL_S_LO, "twin S_LO unchanged");
    expect_balance_u64(&p, ADDR32_S_PROJ, 0, "projection S_PROJ got nothing");
    expect(!post_exists(&p, ADDR32_S_PROJ), "projection S_PROJ not created");
    expect_balance_u64(&p, ADDR32_SD, 0, "SD balance moved out");
    expect(post_exists(&p, ADDR32_SD), "SD not deleted (not created this tx)");
    changes_free(&cs);
    check_end();
}

static void check3(const evm_membackend *mb)
{
    check_begin("check3_create_create2_full_hash");
    changes_t cs;
    evm_exec_status_t status;
    int rc = run_single_call(mb, ADDR32_FACTORY, &cs, &status);
    expect(rc == 0, "tx applied");
    expect(status == EVM_EXEC_SUCCESS, "tx succeeded");
    post_t p = { mb, &cs };
    static const uint8_t runtime[1] = { 0x2a };
    expect_slot(&p, ADDR32_FACTORY, 0, ADDR32_EXP_CREATE_FACTORY_N7F,
                "CREATE at nonce 0x7f pushed the oracle address");
    expect_slot(&p, ADDR32_FACTORY, 1, ADDR32_EXP_CREATE_FACTORY_N80,
                "CREATE at nonce 0x80 pushed the oracle address");
    expect_slot(&p, ADDR32_FACTORY, 2, ADDR32_EXP_CREATE2_FACTORY,
                "CREATE2 pushed the oracle address");
    expect_code(&p, ADDR32_EXP_CREATE_FACTORY_N7F, runtime, 1,
                "code deployed at the CREATE(0x7f) address");
    expect_code(&p, ADDR32_EXP_CREATE_FACTORY_N80, runtime, 1,
                "code deployed at the CREATE(0x80) address");
    expect_code(&p, ADDR32_EXP_CREATE2_FACTORY, runtime, 1,
                "code deployed at the CREATE2 address");
    expect(post_nonce(&p, ADDR32_EXP_CREATE_FACTORY_N7F) == 1, "created nonce 1 (a)");
    expect(post_nonce(&p, ADDR32_EXP_CREATE_FACTORY_N80) == 1, "created nonce 1 (b)");
    expect(post_nonce(&p, ADDR32_EXP_CREATE2_FACTORY) == 1, "created nonce 1 (c)");
    expect(post_nonce(&p, ADDR32_FACTORY) == ADDR32_NONCE_FACTORY + 3,
           "factory nonce advanced by 3");
    changes_free(&cs);
    check_end();
}

static void check4(const evm_membackend *mb)
{
    check_begin("check4_precompile_match_full_word");
    changes_t cs;
    evm_exec_status_t status;
    int rc = run_single_call(mb, ADDR32_PC_DRIVER, &cs, &status);
    expect(rc == 0, "tx applied");
    expect(status == EVM_EXEC_SUCCESS, "tx succeeded");
    post_t p = { mb, &cs };
    const uint8_t *D = ADDR32_PC_DRIVER;
    uint8_t want[32];
    hex32(want, ECREC_OUT);
    expect_slot_u64(&p, D, 0, 1, "STATICCALL 0x00..01 succeeded");
    expect_slot_u64(&p, D, 1, 32, "0x00..01 returned 32 bytes (ecrecover)");
    expect_slot(&p, D, 2, want,
                "ecrecover output = 12 zero bytes || 20-byte address");
    expect_slot_u64(&p, D, 3, 1, "STATICCALL fake 0xff..01 succeeded");
    expect_slot_u64(&p, D, 4, 0, "fake 0xff..01 returned nothing (empty account)");
    expect_slot_u64(&p, D, 5, 0, "fake 0xff..01 wrote no output");
    expect_slot_u64(&p, D, 6, 1, "CALL with value to fake 0xff..01 succeeded");
    expect_balance_u64(&p, ADDR32_FAKE01, 1, "fake 0xff..01 holds the value");
    expect(post_exists(&p, ADDR32_FAKE01), "fake 0xff..01 is now an account");
    {
        uint8_t pc01[32] = {0};
        pc01[31] = 0x01;
        expect_balance_u64(&p, pc01, 0, "real 0x00..01 received nothing");
    }
    expect_slot_u64(&p, D, 9, 1, "STATICCALL 0x00..04 succeeded");
    expect_slot_u64(&p, D, 7, 5, "0x00..04 returned 5 bytes (identity)");
    expect_slot_u64(&p, D, 10, 1, "STATICCALL fake 0xff..04 succeeded");
    expect_slot_u64(&p, D, 8, 0, "fake 0xff..04 returned nothing");
    changes_free(&cs);
    check_end();
}

static void check5(const evm_membackend *mb)
{
    check_begin("check5_create_tx_result_created");
    static const uint8_t runtime[1] = { 0x2a };
    const struct {
        const uint8_t *from;
        uint64_t       nonce;
        const uint8_t *want;
        const char    *what;
    } cases[2] = {
        { ADDR32_CREATOR0, ADDR32_NONCE_CREATOR0, ADDR32_EXP_TXCREATE_CREATOR0,
          "create tx at nonce 0" },
        { ADDR32_CREATOR1, ADDR32_NONCE_CREATOR1, ADDR32_EXP_TXCREATE_CREATOR1,
          "create tx at nonce 0x0100" },
    };
    for (int i = 0; i < 2; i++) {
        run_t r;
        evm_tx_result_t res;
        changes_t cs;
        run_open(&r, mb);
        int rc = run_tx(&r, cases[i].from, cases[i].nonce, NULL, ADDR32_INITCODE,
                        sizeof(ADDR32_INITCODE), &res);
        expect(rc == 0, cases[i].what);
        expect(res.status == EVM_EXEC_SUCCESS, cases[i].what);
        expect_word(res.created.b, cases[i].want, cases[i].what);
        collect(r.st, &cs);
        post_t p = { mb, &cs };
        expect_code(&p, cases[i].want, runtime, 1,
                    "runtime code at res->created");
        changes_free(&cs);
        evm_tx_result_free(&res);
        run_close(&r);
    }
    check_end();
}

/* 7702 assertions shared by the CALL path and the top-level path */
static void expect_delegation_followed(const post_t *p)
{
    expect_slot_u64(p, ADDR32_DELEGATED, 0, 0xE7,
                    "DEL_TARGET (12 zero bytes || 20) ran in DELEGATED");
    expect_slot(p, ADDR32_DELEGATED, 1, ADDR32_DELEGATED,
                "ADDRESS inside delegated code = DELEGATED (32 bytes)");
    expect_slot_u64(p, ADDR32_DELEGATED, 2, 0,
                    "decoy (non-zero high || same 20) did not run");
    expect_slot_u64(p, ADDR32_DEL_DECOY, 0, 0, "decoy storage untouched");
    expect_slot_u64(p, ADDR32_DEL_TARGET, 0, 0, "target's own storage untouched");
}

static void check6(const evm_membackend *mb)
{
    check_begin("check6_eip3541_and_7702_designator");

    /* EIP-3541, top-level create tx */
    {
        run_t r;
        evm_tx_result_t res;
        changes_t cs;
        run_open(&r, mb);
        int rc = run_tx(&r, ADDR32_CREATOR_EF, ADDR32_NONCE_CREATOR_EF, NULL,
                        ADDR32_INITCODE_EF, sizeof(ADDR32_INITCODE_EF), &res);
        expect(rc == 0, "0xEF create tx applied (execution failure, not refusal)");
        expect(res.status == EVM_EXEC_INVALID_CODE_PREFIX,
               "0xEF create tx -> EVM_EXEC_INVALID_CODE_PREFIX");
        expect_word(res.created.b, ADDR32_EXP_TXCREATE_CREATOR_EF,
                    "0xEF create tx: res->created is the oracle address");
        collect(r.st, &cs);
        post_t p = { mb, &cs };
        expect_code(&p, ADDR32_EXP_TXCREATE_CREATOR_EF, NULL, 0,
                    "no code at the refused create-tx address");
        expect(post_nonce(&p, ADDR32_CREATOR_EF) == ADDR32_NONCE_CREATOR_EF + 1,
               "sender nonce still advanced");
        changes_free(&cs);
        evm_tx_result_free(&res);
        run_close(&r);
    }
    /* EIP-3541, nested CREATE */
    {
        changes_t cs;
        evm_exec_status_t status;
        int rc = run_single_call(mb, ADDR32_EF_FACTORY, &cs, &status);
        expect(rc == 0, "EF_FACTORY tx applied");
        expect(status == EVM_EXEC_SUCCESS, "EF_FACTORY tx succeeded");
        post_t p = { mb, &cs };
        expect_slot_u64(&p, ADDR32_EF_FACTORY, 0, 0, "nested CREATE of 0xEF pushed 0");
        expect_code(&p, ADDR32_EXP_CREATE_EF_FACTORY_N1, NULL, 0,
                    "no code at the refused nested-CREATE address");
        expect(post_nonce(&p, ADDR32_EF_FACTORY) == ADDR32_NONCE_EF_FACTORY + 1,
               "EF_FACTORY nonce advanced");
        changes_free(&cs);
    }
    /* 7702 designator in pre-state, reached by CALL (access_delegation) */
    {
        changes_t cs;
        evm_exec_status_t status;
        int rc = run_single_call(mb, ADDR32_DEL_DRIVER, &cs, &status);
        expect(rc == 0, "DEL_DRIVER tx applied");
        expect(status == EVM_EXEC_SUCCESS, "DEL_DRIVER tx succeeded");
        post_t p = { mb, &cs };
        expect_slot_u64(&p, ADDR32_DEL_DRIVER, 0, 1, "CALL DELEGATED succeeded");
        expect_delegation_followed(&p);
        changes_free(&cs);
    }
    /* 7702 designator as the top-level tx target */
    {
        changes_t cs;
        evm_exec_status_t status;
        int rc = run_single_call(mb, ADDR32_DELEGATED, &cs, &status);
        expect(rc == 0, "tx to DELEGATED applied");
        expect(status == EVM_EXEC_SUCCESS, "tx to DELEGATED succeeded");
        post_t p = { mb, &cs };
        expect_delegation_followed(&p);
        changes_free(&cs);
    }
    check_end();
}

/* The whole call sequence in one overlay (a block), serialized. */
static void run_sequence(const evm_membackend *mb, changes_t *cs, int *ok)
{
    const uint8_t *targets[] = {
        ADDR32_ENV_OUTER, ADDR32_TWIN_DRIVER, ADDR32_FACTORY,
        ADDR32_PC_DRIVER, ADDR32_EF_FACTORY, ADDR32_DEL_DRIVER,
    };
    run_t r;
    run_open(&r, mb);
    *ok = 1;
    for (size_t i = 0; i < sizeof(targets) / sizeof(targets[0]); i++) {
        evm_tx_result_t res;
        int rc = run_tx(&r, ADDR32_SENDER, 3 + i, targets[i], NULL, 0, &res);
        if (rc != 0 || res.status != EVM_EXEC_SUCCESS) *ok = 0;
        evm_tx_result_free(&res);
    }
    /* plus a create tx from another sender */
    {
        evm_tx_result_t res;
        int rc = run_tx(&r, ADDR32_CREATOR1, ADDR32_NONCE_CREATOR1, NULL,
                        ADDR32_INITCODE, sizeof(ADDR32_INITCODE), &res);
        if (rc != 0 || res.status != EVM_EXEC_SUCCESS) *ok = 0;
        evm_tx_result_free(&res);
    }
    collect(r.st, cs);
    run_close(&r);
}

static void check7(void)
{
    check_begin("check7_change_set_deterministic");
    evm_membackend mb1, mb2;
    changes_t a, b;
    int ok_a, ok_b;
    /* two independently built pre-states, two fresh overlays */
    build_pre(&mb1);
    run_sequence(&mb1, &a, &ok_a);
    build_pre(&mb2);
    run_sequence(&mb2, &b, &ok_b);
    expect(ok_a && ok_b, "every tx of the sequence applied and succeeded");
    expect(a.ser_len > 0, "change set is not empty");
    expect(a.na > 0 && a.ns > 0, "accounts and slots were reported");
    expect(a.ser_len == b.ser_len, "serialized lengths equal");
    expect(a.ser_len == b.ser_len && memcmp(a.ser, b.ser, a.ser_len) == 0,
           "serialized change sets byte-identical");
    /* evm.h: accounts strictly ascending by address */
    for (size_t i = 1; i < a.na; i++)
        if (memcmp(a.acc[i - 1].addr.b, a.acc[i].addr.b, 32) >= 0) {
            expect(0, "accounts reported in strictly ascending address order");
            break;
        }
    changes_free(&a);
    changes_free(&b);
    evm_membackend_free(&mb1);
    evm_membackend_free(&mb2);
    check_end();
}

/* check 8 — BLOBBASEFEE = taylor_exponential(1, excess, 5007716) with the
 * final `// denominator` (execution-specs@a87891f7 ethereum/utils/numeric.py
 * :200-214, prague/vm/gas.py:448-467). Expected values computed with that
 * Python function: excess 0 -> 1, 10 000 000 -> 7, 200 000 000 ->
 * 221315816840568244. Regression for red-team finding Astra#1 (the final
 * division was missing; the official state tests did not catch it because
 * their BLOBBASEFEE cases ride type-3 transactions, which are excluded). */
static void check8(const evm_membackend *mb)
{
    static const struct { uint64_t excess, fee; } v[] = {
        { 0, 1 }, { 10000000ull, 7 }, { 200000000ull, 221315816840568244ull } };
    check_begin("check8_blobbasefee_reference_values");
    for (size_t i = 0; i < sizeof(v) / sizeof(v[0]); i++) {
        run_t r;
        evm_tx_result_t res;
        changes_t cs;
        run_open(&r, mb);
        r.env.excess_blob_gas = v[i].excess;
        int rc = run_tx(&r, ADDR32_SENDER, 3, ADDR32_BLOBFEE, NULL, 0, &res);
        expect(rc == 0 && res.status == EVM_EXEC_SUCCESS, "BLOBBASEFEE tx ok");
        collect(r.st, &cs);
        post_t p = { mb, &cs };
        expect_slot_u64(&p, ADDR32_BLOBFEE, 0, v[i].fee, "BLOBBASEFEE value");
        changes_free(&cs);
        evm_tx_result_free(&res);
        run_close(&r);
    }
    check_end();
}

int main(void)
{
    evm_membackend mb;
    build_pre(&mb);
    check1(&mb);
    check2(&mb);
    check3(&mb);
    check4(&mb);
    check5(&mb);
    check6(&mb);
    check8(&mb);
    evm_membackend_free(&mb);
    check7();
    if (g_fail_checks) {
        fprintf(stderr, "test_addr32: %u check(s) FAILED\n", g_fail_checks);
        return 1;
    }
    fprintf(stderr, "test_addr32: all 8 checks passed\n");
    return 0;
}
