/**
 * @file test_u256.c
 * @brief Checks evm_u256.c against the Python big-int oracle vectors
 *        (tests/u256_vectors.h, generated by tests/u256_oracle.py).
 *
 * For every vector:
 *   - the operation is run into a fresh result, and again with the result
 *     aliasing each operand in turn (r == a, r == b, and r == n for the
 *     ternary ops), and every result must equal the oracle;
 *   - ADD / SUB also check the returned carry / borrow;
 *   - the conversion helpers are checked on operand a: from_be / to_be
 *     against an independent hex -> bytes decode, from_be_var on the
 *     minimal-length big-endian encoding (and on lengths 0 and 32),
 *     to_u64 / bitlen / is_zero / cmp / scmp against the oracle.
 * Plus fixed checks of from_be_var's len > 32 refusal (r untouched).
 *
 * Standalone harness (shared/evm builds without shared/crypto): reports via
 * fprintf like the shared/crypto/zk standalone tests; exit 0 = all passed.
 */
#include "evm_u256.h"
#include "u256_vectors.h"

#include <stdio.h>
#include <string.h>

static unsigned long g_fail;

static int hexval(char c)
{
    if (c >= '0' && c <= '9')
        return c - '0';
    if (c >= 'a' && c <= 'f')
        return c - 'a' + 10;
    return -1;
}

/* Minimal lowercase hex (<= 64 digits) -> limbs, without using evm_u256.c. */
static int parse_limbs(evm_u256 *r, const char *s)
{
    size_t len = strlen(s);
    if (len == 0 || len > 64)
        return -1;
    r->w[0] = r->w[1] = r->w[2] = r->w[3] = 0;
    for (size_t k = 0; k < len; k++) {
        int v = hexval(s[len - 1 - k]);      /* k = nibble index from LSB */
        if (v < 0)
            return -1;
        r->w[k / 16] |= (uint64_t)v << ((k % 16) * 4);
    }
    return 0;
}

/* Minimal hex -> 32 big-endian bytes, by a separate route (byte-wise). */
static int parse_bytes(uint8_t out[32], const char *s)
{
    size_t len = strlen(s);
    if (len == 0 || len > 64)
        return -1;
    memset(out, 0, 32);
    for (size_t k = 0; k < len; k++) {
        int v = hexval(s[len - 1 - k]);
        if (v < 0)
            return -1;
        size_t byte = 31 - k / 2;
        out[byte] |= (uint8_t)((k % 2) ? (v << 4) : v);
    }
    return 0;
}

static int eq(const evm_u256 *a, const evm_u256 *b)
{
    return a->w[0] == b->w[0] && a->w[1] == b->w[1] &&
           a->w[2] == b->w[2] && a->w[3] == b->w[3];
}

static void fail(size_t idx, const u256_vector *v, const char *what)
{
    g_fail++;
    if (g_fail <= 50)
        fprintf(stderr, "FAIL #%zu %s(a=%s b=%s c=%s) expected %s: %s\n",
                idx, U256_OP_NAMES[v->op], v->a, v->b, v->c, v->x, what);
}

typedef void (*bin_fn)(evm_u256 *, const evm_u256 *, const evm_u256 *);
typedef void (*ter_fn)(evm_u256 *, const evm_u256 *, const evm_u256 *,
                       const evm_u256 *);

static bin_fn binary_fn(int op)
{
    switch (op) {
    case U256_OP_MUL:        return evm_u256_mul;
    case U256_OP_DIV:        return evm_u256_div;
    case U256_OP_MOD:        return evm_u256_mod;
    case U256_OP_SDIV:       return evm_u256_sdiv;
    case U256_OP_SMOD:       return evm_u256_smod;
    case U256_OP_EXP:        return evm_u256_exp;
    case U256_OP_SIGNEXTEND: return evm_u256_signextend;
    case U256_OP_AND:        return evm_u256_and;
    case U256_OP_OR:         return evm_u256_or;
    case U256_OP_XOR:        return evm_u256_xor;
    case U256_OP_BYTE:       return evm_u256_byte;
    case U256_OP_SHL:        return evm_u256_shl;
    case U256_OP_SHR:        return evm_u256_shr;
    case U256_OP_SAR:        return evm_u256_sar;
    default:                 return NULL;
    }
}

/* ADD / SUB with their carry / borrow return; same alias pattern. */
static void check_addsub(size_t idx, const u256_vector *v,
                         const evm_u256 *a, const evm_u256 *b,
                         const evm_u256 *x)
{
    int (*fn)(evm_u256 *, const evm_u256 *, const evm_u256 *) =
        (v->op == U256_OP_ADD) ? evm_u256_add : evm_u256_sub;
    int want = (strcmp(v->c, "1") == 0);
    evm_u256 r;
    int c;

    c = fn(&r, a, b);
    if (!eq(&r, x)) fail(idx, v, "result");
    if (c != want) fail(idx, v, "carry/borrow");

    r = *a;
    c = fn(&r, &r, b);
    if (!eq(&r, x)) fail(idx, v, "alias r==a");
    if (c != want) fail(idx, v, "carry/borrow alias r==a");

    r = *b;
    c = fn(&r, a, &r);
    if (!eq(&r, x)) fail(idx, v, "alias r==b");
    if (c != want) fail(idx, v, "carry/borrow alias r==b");

    r = *a;
    c = fn(&r, &r, &r);               /* a op a, only meaningful if a == b */
    if (eq(a, b)) {
        if (!eq(&r, x)) fail(idx, v, "alias r==a==b");
        if (c != want) fail(idx, v, "carry/borrow alias r==a==b");
    }
}

static void check_binary(size_t idx, const u256_vector *v,
                         const evm_u256 *a, const evm_u256 *b,
                         const evm_u256 *x)
{
    bin_fn fn = binary_fn(v->op);
    evm_u256 r;
    if (!fn) {
        fail(idx, v, "no binary function for op");
        return;
    }
    fn(&r, a, b);
    if (!eq(&r, x)) fail(idx, v, "result");
    r = *a;
    fn(&r, &r, b);
    if (!eq(&r, x)) fail(idx, v, "alias r==a");
    r = *b;
    fn(&r, a, &r);
    if (!eq(&r, x)) fail(idx, v, "alias r==b");
    if (eq(a, b)) {
        r = *a;
        fn(&r, &r, &r);
        if (!eq(&r, x)) fail(idx, v, "alias r==a==b");
    }
}

static void check_ternary(size_t idx, const u256_vector *v,
                          const evm_u256 *a, const evm_u256 *b,
                          const evm_u256 *n, const evm_u256 *x)
{
    ter_fn fn = (v->op == U256_OP_ADDMOD) ? evm_u256_addmod : evm_u256_mulmod;
    evm_u256 r;
    fn(&r, a, b, n);
    if (!eq(&r, x)) fail(idx, v, "result");
    r = *a;
    fn(&r, &r, b, n);
    if (!eq(&r, x)) fail(idx, v, "alias r==a");
    r = *b;
    fn(&r, a, &r, n);
    if (!eq(&r, x)) fail(idx, v, "alias r==b");
    r = *n;
    fn(&r, a, b, &r);
    if (!eq(&r, x)) fail(idx, v, "alias r==n");
}

static int expected_sign(const evm_u256 *x)
{
    /* CMP / SCMP expected is (-1/0/1) mod 2^256. */
    if (x->w[0] == 0 && x->w[1] == 0 && x->w[2] == 0 && x->w[3] == 0)
        return 0;
    if (x->w[0] == 1 && x->w[1] == 0 && x->w[2] == 0 && x->w[3] == 0)
        return 1;
    return -1;
}

/* Conversion helpers on operand a (the hex string v->a). */
static void check_conversions(size_t idx, const u256_vector *v,
                              const evm_u256 *a)
{
    uint8_t be[32], out[32];
    evm_u256 r;
    if (parse_bytes(be, v->a) != 0) {
        fail(idx, v, "bad hex in a");
        return;
    }
    evm_u256_from_be(&r, be);
    if (!eq(&r, a)) fail(idx, v, "from_be");
    evm_u256_to_be(out, a);
    if (memcmp(out, be, 32) != 0) fail(idx, v, "to_be");

    size_t lead = 0;
    while (lead < 32 && be[lead] == 0)
        lead++;
    evm_u256_from_u64(&r, 0xDEADBEEFull);
    if (evm_u256_from_be_var(&r, be + lead, 32 - lead) != 0 || !eq(&r, a))
        fail(idx, v, "from_be_var minimal");
    if (evm_u256_from_be_var(&r, be, 32) != 0 || !eq(&r, a))
        fail(idx, v, "from_be_var 32");
}

int main(void)
{
    size_t checked = 0;

    for (size_t i = 0; i < U256_VECTOR_COUNT; i++) {
        const u256_vector *v = &U256_VECTORS[i];
        evm_u256 a, b, c, x;
        if (parse_limbs(&a, v->a) != 0 || parse_limbs(&x, v->x) != 0) {
            fail(i, v, "bad hex");
            continue;
        }
        check_conversions(i, v, &a);

        switch (v->op) {
        case U256_OP_ADD:
        case U256_OP_SUB:
            if (parse_limbs(&b, v->b) != 0) { fail(i, v, "bad hex b"); break; }
            check_addsub(i, v, &a, &b, &x);
            break;
        case U256_OP_ADDMOD:
        case U256_OP_MULMOD:
            if (parse_limbs(&b, v->b) != 0 || parse_limbs(&c, v->c) != 0) {
                fail(i, v, "bad hex b/c");
                break;
            }
            check_ternary(i, v, &a, &b, &c, &x);
            break;
        case U256_OP_CMP:
        case U256_OP_SCMP: {
            if (parse_limbs(&b, v->b) != 0) { fail(i, v, "bad hex b"); break; }
            int want = expected_sign(&x);
            int got = (v->op == U256_OP_CMP) ? evm_u256_cmp(&a, &b)
                                             : evm_u256_scmp(&a, &b);
            if (got != want) fail(i, v, "compare");
            break;
        }
        case U256_OP_NOT: {
            evm_u256 r;
            evm_u256_not(&r, &a);
            if (!eq(&r, &x)) fail(i, v, "result");
            r = a;
            evm_u256_not(&r, &r);
            if (!eq(&r, &x)) fail(i, v, "alias r==a");
            break;
        }
        case U256_OP_BITLEN:
            if ((uint64_t)evm_u256_bitlen(&a) != x.w[0] || x.w[1] || x.w[2] || x.w[3])
                fail(i, v, "bitlen");
            break;
        case U256_OP_ISZERO:
            if ((uint64_t)evm_u256_is_zero(&a) != x.w[0])
                fail(i, v, "is_zero");
            break;
        case U256_OP_TOU64: {
            uint64_t out = 0xA5A5A5A5A5A5A5A5ull;
            int want = (strcmp(v->c, "1") == 0);
            int got = evm_u256_to_u64(&a, &out);
            if (got != want) fail(i, v, "to_u64 fits");
            if (want && out != x.w[0]) fail(i, v, "to_u64 value");
            if (!want && out != 0xA5A5A5A5A5A5A5A5ull) fail(i, v, "to_u64 wrote on refusal");
            break;
        }
        default:
            if (parse_limbs(&b, v->b) != 0) { fail(i, v, "bad hex b"); break; }
            check_binary(i, v, &a, &b, &x);
            break;
        }
        checked++;
    }

    /* from_be_var: len > 32 is refused and r is untouched; len 0 -> zero. */
    {
        uint8_t buf[40];
        evm_u256 r, keep;
        memset(buf, 0x11, sizeof(buf));
        evm_u256_from_u64(&r, 0x1234u);
        keep = r;
        if (evm_u256_from_be_var(&r, buf, 33) != -1 || !eq(&r, &keep)) {
            g_fail++;
            fprintf(stderr, "FAIL from_be_var len 33\n");
        }
        if (evm_u256_from_be_var(&r, buf, 40) != -1 || !eq(&r, &keep)) {
            g_fail++;
            fprintf(stderr, "FAIL from_be_var len 40\n");
        }
        if (evm_u256_from_be_var(&r, NULL, 0) != 0 || !evm_u256_is_zero(&r)) {
            g_fail++;
            fprintf(stderr, "FAIL from_be_var len 0\n");
        }
    }

#if defined(EVM_U256_PORTABLE)
    const char *build = " (portable build)";
#else
    const char *build = "";
#endif
    fprintf(stderr, "test_u256: %zu vectors checked, %lu failures%s\n",
            checked, g_fail, build);
    return g_fail ? 1 : 0;
}
